### ISSUE TITLE
Lambda expressions inference

### ISSUE THREAD

**Issue by ghost** [dotnet/csharplang#1660] opened 2018-06-23 14:12 UTC
In VB.NET I can Write:
```Dim x = Function(n As Integer) n + 1```
VB will infer x to be Func(of Integer, Integer)

But I can't do the same in C#:
```var x = (int n ) => n + 1;```
C# says it can't infer lambda expressions. Why?.. VB.NET Can, so it is doable.

**Comment by svick** [comment] 2018-06-23 14:33
Duplicate of https://github.com/dotnet/csharplang/issues/150.

**Comment by YairHalberstadt** [comment] 2020-10-16 10:29
Closing as duplicate of #150

**Closed by YairHalberstadt** 2020-10-16 10:29 UTC
