### ISSUE TITLE
[Proposal] Allow defining local aliases for types

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/csharplang#3306] opened 2020-03-25 01:50 UTC
I came across this code:
```C#
public List<Expression<Func<T, object>>> Includes { get; } = new List<Expression<Func<T, object>>>();
```

And I wondered: Can't I simplify this to:
```C#
using Expr = Expression<Func<T, object>>

public List<Expr> Includes { get; } = new List< Expr>();
```

This seems readable.
But unfortunately it is not possible, since T exists only inside the class scope, and `using` exists only in file/namespace scope!

 So, I wish if C# allows `using` type aliases inside classes. This is a must in today's projects that contain very complex generics and lambdas that make our heads spin.

**Comment by Joe4evr** [comment] 2020-03-25 02:00
Duplicate of #2488, #1170, #410 and #259.

**Comment by VBAndCs** [comment] 2020-03-25 02:10
Seems a popular demand :)

**Comment by VBAndCs** [comment] 2020-03-25 02:14
Too many votes for those proposals, yet none is a champion!

**Comment by theunrepentantgeek** [comment] 2020-03-25 02:29
Development isn't a democracy - votes on issues merely show what's popular, not what's _good_.

The LDM decides on what goes into the next version of the language - and they take into account a far wider range of inputs than just this repo.

Someone pointed out (I think it was @CyrusNajmabadi, but I'm not 100% sure) that the feedback in this repo is less than the _statistical noise_ in feedback through other channels. Fortunately, the LDM takes a special interest in what's said here because many of the contributors take the time to carefully think through issues instead of just banging on their own drum.

**Comment by YairHalberstadt** [comment] 2020-11-24 10:55
Closing as dupliucate between #2488, #1170, #410 and #259.

**Closed by YairHalberstadt** 2020-11-24 10:55 UTC
