### ISSUE TITLE
Namespaces from Project Folder Path

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3355] opened 2020-04-11 14:11 UTC
It would be great if I had a class like so:
````
using System;
//The class below is not contained in a namespace
[Namespace(fromproject:true, fromfolder: true)]
public class MyClass { }
````

and my project was organizes like so:
````
+MyProject.csproj
+--+Data
    +--MyClass.cs
````

That the class would be automatically moved into the namespace ````MyProject.Data````

**Comment by svick** [comment] 2020-04-11 14:40
This is mostly a duplicate of https://github.com/dotnet/csharplang/issues/2908.

**Comment by YairHalberstadt** [comment] 2020-11-24 11:07
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/2908

**Closed by YairHalberstadt** 2020-11-24 11:07 UTC
