### ISSUE TITLE
Proposal - Add new keyword fullnameof

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#1609] opened 2018-06-06 21:10 UTC
There are cases where we might have numerous methods all with the same name but scattered across different classes (e.g. MVC Controllers). In these cases the existing `nameof `keyword gives only the lexical spelling of the simple name and does not include namespaces.

Having `fullnameof `would address this and it would (where applicable) generate the fully qualified name of the item (e.g. a method).

**Comment by yaakov-h** [comment] 2018-06-06 21:33
Duplicate of #701.

**Comment by DavidArno** [comment] 2018-06-08 09:10
@Korporal, would you mind closing this please, since it is a direct duplicate?

**Closed** 2018-06-13 20:00 UTC
