### ISSUE TITLE
Indexers in derived class misbehavior

### ISSUE THREAD

**Issue by giladfrid009** [dotnet/csharplang#3360] opened 2020-04-15 00:46 UTC
When accessing the indexer of a class with a single value (`foo[1]`) to a class containing both single val indexer and params indexer (`this[int i]`, `this[params int[] idxs]`), the single value indexer is used, yet when a derived class implements the params indexer, and then it accessed by a single value, then the params indexer is accessed, unless the derived class contains **Directly** a **New implementation** of a single value indexer.

There is an inconsistency here and a weird requirement for the direct implementation of both indexers in order to work properly, even if the base class already implements a single value indexer.

**Here is a sample program demonstrating the issue:**
```
using System;
					
public class Program
{
	public static void Main()
	{		
		Console.WriteLine(new BaseClass()[1]);		
		Console.WriteLine(new DerClass1()[1]);	
		Console.WriteLine(new DerClass2()[1]);
	}
}

class BaseClass
{
	public string this[int i] => "base";
}

class DerClass1 : BaseClass
{
	public string this[params int[] idxs] => "der1";
}

class DerClass2 : BaseClass
{
	public new string this[int i] => base[i]; 
	public string this[params int[] idxs] => "der2";
}
```

**Output:**
```
base
der1
base
```

**Expected output:**
```
base
base
base
```

**Comment by giladfrid009** [comment] 2020-04-15 01:00
** BTW, added a similar issue in the roslyn repo `#43359` in case it's not the right place for submitting it.

**Comment by CyrusNajmabadi** [comment] 2020-04-15 01:07
i would imagine this is by design.  The walk up finds the closer applicable member and chooses it.  

in general, it's a bad idea to do something like this *unless* you ensure that both observe the same externally.  i.e. calling the params version with 1 item should behave the same as just accessing the single item overload.  Otherwise, things will simply be very confusing to consumers of this API, and you'll also end up with the behavior you see here.

**Comment by giladfrid009** [comment] 2020-04-15 01:18
Another point to consider, perhaps there is a similar situation with methods, where method in base class accepts 1 arg, yet it derived class it accepts params. This behavior might consist in this case either.

**Comment by HaloFour** [comment] 2020-04-15 01:39
Unless this is a regression I'd say that even if this isn't correct based on the spec that it probably couldn't be changed due to the potential for breaking changes.  I think Cyrus is right, though.  The compiler will look back one level in the inheritance tree for candidates and, if any are found, it will not look further back.

**Comment by 333fred** [comment] 2020-04-15 01:59
I'll defer to @gafter to see if he can come up with an explanation. Reading the spec (https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#better-function-member, https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#method-invocations), it says nothing about scoping being considered, other than that derived members hide base members, as appropriate. However, I did test this on the native compiler and it outputs the same results, so regardless of whether this is a spec violation or not we cannot change behavior here.

**Comment by CyrusNajmabadi** [comment] 2020-04-15 02:03
@333fred It's:

> and methods in a base class are not candidates if any method in a derived class is applicable (Method invocations).

https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#overload-resolution

**Comment by 333fred** [comment] 2020-04-15 02:04
Ah, missed that line. Thanks! @giladfrid009, does this answer your question?

**Comment by CyrusNajmabadi** [comment] 2020-04-15 02:04
> Another point to consider, this behavior is happening with methods either.
When a base class contains a method that accepts 1 arg T, and the deriving class has a method with same name but with params T[], the same behavior is happening.

Yes, i believe that would be expected as per https://github.com/dotnet/csharplang/issues/3360#issuecomment-613772489

It's part and parcel of how the language has worked for  >20 years now :)

**Comment by CyrusNajmabadi** [comment] 2020-04-15 07:28
Closing out.  The behavior is spec'ed and has been part and parcel of the language longer than some team members have been alive :)

**Closed by CyrusNajmabadi** 2020-04-15 07:28 UTC
Labels: Discussion

**Comment by 333fred** [comment] 2020-04-15 15:13
> longer than some team members have been alive

Hey now, I'm older than C#. It'll be another couple of years before we start hiring full timers younger than it @CyrusNajmabadi.
