### ISSUE TITLE
Add a ?( operator to null-check method calls

### ISSUE THREAD

**Issue by ekolis** [dotnet/csharplang#3436] opened 2020-05-07 16:36 UTC
If I have a variable which might be null I can do this:

```
var x = y?,ID ?? 0;
```

Or an array/collection:

```
var x = dict?["foo"];
```

But for some reason if I want to call a method I have to do this:

```
foo.DoStuff?.Invoke(narf);
```

rather than just

```
foo?.DoStuff(narf);
```

It would be really nice to add the latter syntax to make code more readable/writable! :)

**Comment by bbarry** [comment] 2020-05-07 16:46
foo.DoStuff?.Invoke(narf);

means that DoStuff could be null on foo. For example:

    class Foo {
      Action<Narf>? DoStuff { get; set; }
    }

There is no way for a normal method to be null on a class.

**Comment by jnm2** [comment] 2020-05-07 17:00
@ekolis `foo?.DoStuff(narf);` is already legal syntax which is sugar for:

```cs
var temp = foo;
if (temp != null) temp.DoStuff(narf);`
```

**Comment by jnm2** [comment] 2020-05-07 17:05
One problem with `foo.DoStuff?(narf)` is ``foo.DoStuff ? (narf) : (etc)`. The IDE has to understand what you're doing while typing incomplete code and behave well for things like intellisense and parsing the rest of the method.

**Comment by Joe4evr** [comment] 2020-05-07 18:33
Also a duplicate of #3257.

**Comment by YairHalberstadt** [comment] 2020-11-29 08:23
Closing as duplicate of https://github.com/dotnet/csharplang/issues/3257

**Closed by YairHalberstadt** 2020-11-29 08:23 UTC
