### ISSUE TITLE
Proposal: Allow local readonly variables

### ISSUE THREAD

**Issue by leandromoh** [dotnet/csharplang#3258] opened 2020-03-09 19:03 UTC
Looks a nice idea to have `readonly` variables as well readonly members. Currently we can create local `const` variables, but you can't make it `const` if the value won't be a compile-time constant, or if it's an instance field. 

we already have
- arguments as readonly references (`in` parameter modifier)
- `readonly` members
- `readonly` properties/fields
- local `const` variables

so looks interesting to local variables as well:

```c#
readonly int x = ComputeX();
```

**Comment by svick** [comment] 2020-03-09 19:14
This is a duplicate of https://github.com/dotnet/csharplang/issues/188.

**Comment by leandromoh** [comment] 2020-03-09 19:17
> This is a duplicate of #188.

@svick thanks! any news about that feature?

**Comment by 333fred** [comment] 2020-03-09 19:18
It's championed, for some future point release of C#. Closing this as a duplicate.

**Closed by 333fred** 2020-03-09 19:18 UTC

**Comment by CodingBoson** [comment] 2025-06-19 02:44
This feature would be really game changing.

Hope it gets implemented soon (Or never 😢)
