### ISSUE TITLE
Partial parameter detection on generic extension method

### ISSUE THREAD

**Issue by IgorMenshikov** [dotnet/csharplang#2821] opened 2019-09-24 08:28 UTC
I have a generic interface IRow`<T>` that represent a collection of some T values with ability to find a value. There are few implementations of this interface. I need to implement a function to convert a value to some another class. I wanted to implement that via an extension method like:

``` C#
    public class FieldValue<T, V>
    {
    }

    public interface IRow<T>
    {
        T Find(string id);
    }


    public static class IRowExtensions
    {
        public static FieldValue<T, V> Find<V, T>(this IRow<T> row, string id)
            where V : class
        {
            var v = row.Find(id);
            return (v == null ? null : new FieldValue<T, V>());
        }
    }

    public class Row<T> : IRow<T>
    {
        public T Find(string id) => default;
    }
```

I do not want always pass both generic parameters to the extension method. Would like to have a code like that:

``` C#
var row = new Row<string>();
var partial = row.Find<string>("test"); // hope the compiler can understand that the second parameter is string as well
```

But compiler does not want automatically detect the second generic parameter even it can be done from "row" variable.

I expected C# 8.0 interface method implementation would help but some code works with a concrete IRow implementation and casting to IRow does not make the code look good because of a complex generic parameter.

Is there a way something implement what I wanted or is that something you plan to do?

**Comment by yaakov-h** [comment] 2019-09-24 08:34
See #1349.

**Comment by YairHalberstadt** [comment] 2020-11-05 11:54
Closing as duplicate of #1349.

**Closed by YairHalberstadt** 2020-11-05 11:54 UTC
