### ISSUE TITLE
Proposal: Specifying Attributes for expression-bodied property getter method via [method: ...] 

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/csharplang#1853] opened 2018-09-13 01:20 UTC
C# 7.3 added `[field: ...]` for specifying attributes on an automatic backing field.

In a similar vein, it would be nice to be able to do the same for a Property's expression-bodied getter method. Instead of what's currently required...

	public ulong MyProp
	{
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => 1234UL;
	}

...the following would be syntactically allowed, effecting the same result:

	[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
	public ulong MyProp => 1234UL;

Thank you for your consideration.

**Comment by theunrepentantgeek** [comment] 2018-09-13 01:32
Duplicate of #887

**Closed** 2019-01-11 00:17 UTC
