### ISSUE TITLE
multiple exception types with the same handler

### ISSUE THREAD

**Issue by chmely** [dotnet/csharplang#1312] opened 2018-02-07 12:34 UTC
It would be nice to be able to specify one catch clause for multiple exception types, e.g.

try {...}
catch (InvalidCastException [ex1], FormatException [ex2])
{
  // common handler for both
}
catch (Exception ex)
{
  // generic handler
}

**Comment by ufcpp** [comment] 2018-02-07 13:16
https://github.com/dotnet/csharplang/issues/164

**Comment by ufcpp** [comment] 2018-02-07 13:19
https://github.com/dotnet/csharplang/issues/399

or 

```cs
try {...}
catch (Exception ex) when (ex is InvalidCastException || ex is FormatException)
{
    // common handler for both
}
catch (Exception ex)
{
    // generic handler
}
```

**Comment by jnm2** [comment] 2018-02-08 13:10
This is also an exact duplicate of https://github.com/dotnet/csharplang/issues/519 and is similar to https://github.com/dotnet/csharplang/issues/235.

**Comment by YairHalberstadt** [comment] 2020-10-13 09:17
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/519

**Closed by YairHalberstadt** 2020-10-13 09:17 UTC
