### ISSUE TITLE
Generic parameter inference at generic class level

### ISSUE THREAD

**Issue by navikale** [dotnet/csharplang#3465] opened 2020-05-16 15:31 UTC
Many times I have came across situation where I thought it would been nice to have generic parameter inference where my code can look little cleaner, I know there have been many issues already opened and closed given the reason its breaking change behavior implementing in Roslyn. Those issues are all about asking feature at method level. But I feel it can still be implemented at class level without any breaking changes something like this

```
public class Database<I>
        where I: IRepository<_>
{
        public I<T> Table<T>()
            where T: class
        {

        }
}
```

**Comment by svick** [comment] 2020-05-16 15:54
I think this is a duplicate of https://github.com/dotnet/csharplang/issues/3208 (which is still open).

**Comment by YairHalberstadt** [comment] 2020-11-29 08:50
Closing as this looks like HKTs actually, which are championed at https://github.com/dotnet/csharplang/issues/339

**Closed by YairHalberstadt** 2020-11-29 08:50 UTC
