### ISSUE TITLE
“Using” declaration / RAII

### ISSUE THREAD

**Issue by be5invis** [dotnet/csharplang#599] opened 2017-05-19 05:26 UTC
Mirroring dotnet/roslyn#5881

```c#
void foo() {
    using var conn = new SqlConnection("...");
    using var cmd = conn.CreateCommand();

    connection.Open();

    using var reader = cmd.ExecuteReader();

    while (reader.Read()) {
        // ...
    }
}
```

In combination with #188 
```c#
void foo() {
    using let conn = new SqlConnection("...");
    using let cmd = conn.CreateCommand();

    connection.Open();

    using let reader = cmd.ExecuteReader();

    while (reader.Read()) {
        // ...
    }
}
```

Syntax being: `using` *Local Variable Declaration* `;`

**Comment by svick** [comment] 2017-05-19 11:18
This looks like duplicate of https://github.com/dotnet/csharplang/issues/114.

**Closed** 2017-05-31 19:49 UTC
