### ISSUE TITLE
Static local variables

### ISSUE THREAD

**Issue by dark2201** [dotnet/csharplang#2344] opened 2019-03-14 14:55 UTC
Instead of:

```
class sample {
    static readonly Regex _regex = new Regex("[-.]", RegexOptions.Compiled);

    string RemoveDashesAndDots(string s)
    {
       return _regex.Replace(s);
    }
}
```

this:

```
class sample {
    string RemoveDashesAndDots(string s)
    {
       static readonly var regex = new Regex("[-.]", RegexOptions.Compiled);
       return regex.Replace(s);
    }
}
```

**Comment by YairHalberstadt** [comment] 2019-03-14 15:05
#832

**Comment by gafter** [comment] 2019-03-14 20:26
Closing as duplicate of #832

**Closed** 2019-03-14 20:26 UTC
