### ISSUE TITLE
Proposal: Implicit conversion to interface

### ISSUE THREAD

**Issue by darrenoakey** [dotnet/csharplang#3739] opened 2020-07-28 10:51 UTC
This is a bit different from many other requests, because clearly someone has decided that implicit conversion to an interface is a bad idea, as there's a specific error when you try to do it...

but lets just say... I try to do it _a lot_, and I wish that decision would be reversed.  

Especially - for instance, when you wrap stuff.   For instance, I'm often wrapping collections - you don't really want a list< string > floating around when it could be a UserList... it's cleaner, the intention is more obvious, and you inevitably find all sorts of user list specific helper functionality you can hang off it.    But each wrapper has to end up implementing the interface, which in some cases is a lot of work, or in other cases is a bit more "white box" than you really want - for instance, with enumerable, I really want to say  "here... this is the enumerable" - rather than actually having to cough up the enumerator itself... If I'm wrapping X - and X implements interface Y - and I want my wrapper to delegate that concept across to X - why should I have to know _anything_ about Y??

I'd much rather be able to say

```c#
    public class UserList
    {
        private readonly string[] _underlying;
       
            ...

        public static implicit operator IEnumerable<string>(UserList values)
        {
            return values._underyling;
        }
    }
```

the restriction preventing you from doing it seems completely artificial.

**Comment by darrenoakey** [comment] 2020-07-28 11:02
One really interesting implementation of this is that doing that actually _implements_ the interface - so the above would compile to something like:

```c#
public class UserList_Generated: IEnumerable<string>
    {
        private readonly string[] _underlying;

        private IEnumerable<string> ImplicitOperator => _underlying;

        public IEnumerator<string> GetEnumerator()
        {
            return ImplicitOperator.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return ImplicitOperator.GetEnumerator();
        }
    }
```

which would be awesome - because then if you could be implicitly converted to an interface, you'd also say yes if someone asked if you is that interface.

**Comment by svick** [comment] 2020-07-28 11:07
Is implicit conversion actually what you want, considering it means the class does not actually implement the interface, so it can't be used e.g. in extension methods like LINQ?

> One really interesting implementation of this is that doing that actually implements the interface

That sounds more useful, though I think conflating this with implicit conversions would be very confusing. And asking for that separately has already been proposed at https://github.com/dotnet/csharplang/issues/234 (where I also explain how you can achieve something similar today using some boilerplate code: https://github.com/dotnet/csharplang/issues/234#issuecomment-287891654).

**Comment by PathogenDavid** [comment] 2020-07-28 12:12
This is something I've found myself wanting every once and a while for similar reasons.

That being said, it's a duplicate of #3464 (although the initial discussion was for conversions in the other direction.)

As noted in that issue, [here's the relevant part of the spec  (along with the justification)](https://github.com/dotnet/csharplang/blob/0c25406d8a99064bb85d934bb32ffcf547753acc/spec/classes.md#conversion-operators):

> User-defined conversions are not allowed to convert from or to _interface_types_. In particular, this restriction ensures that no user-defined transformations occur when converting to an _interface_type_, and that a conversion to an _interface_type_ succeeds only if the object being converted actually implements the specified _interface_type_.

(Not saying this shouldn't be revisited, but I think it's valuable to understand the reasoning behind the restriction.)

**Comment by PathogenDavid** [comment] 2020-07-28 12:14
> something similar today using some boilerplate code: [#234 (comment)](https://github.com/dotnet/csharplang/issues/234#issuecomment-287891654)

This seems like a prime candidate for C#9 source generators.

**Comment by 333fred** [comment] 2020-07-28 14:21
Closing as a duplicate.

**Closed by 333fred** 2020-07-28 14:21 UTC
