### ISSUE TITLE
[Proposal] Auto-fluent interface for void-return methods

### ISSUE THREAD

**Issue by Remleo** [dotnet/csharplang#781] opened 2017-08-01 11:39 UTC
Hi all!

Suppose we have Entity:
```c#
public class Entity
{
    public void One() { ... }
    public void Two() { ... }
}
```

If need to call both methods, than
```c#
var entity = new Entity();
entity.One();
entity.Two();
```

I propose adding syntactic sugar to make possible call void-return mehtods in chain:
```c#
new Entity().One().Two();
```

I think the Compiler can automatically transform the chain `entity.One().Two()` to `entity.One(); entity.Two();`.

In lambda expressions:
```c#
...Configure(entity => entity.One().Two());

// instead of
...Configure(entity => {
     entity.One();
     entity.Two();
});
```

More complex case:
```c#
    public class BaseBuilder
    {
        public BaseBuilder AddRule()
        {
            return this;
        }
    }

    public class CustomBuilder : BaseBuilder
    {
        public CustomBuilder AddCustomRule()
        {
            return this;
        }
    }
```
Using:
```c#
((CustomBuilder) ((CustomBuilder) new CustomBuidler().AddRule()).AddCustomRule().AddRule()).AddCustomRule();
```
We must convert explicitly  to `CustomBuilder` to call `AddCustomRule()`  after each `AddRule()`.

With auto-fluent syntax sugar it makes it much more easier:
```c#
    public class BaseBuilder
    {
        public void AddRule()
        {
        }
    }

    public class CustomBuilder : BaseBuilder
    {
        public void AddCustomRule()
        {
        }
    }
```
```c#
// Pretty chaining
new CustomBuidler().AddRule().AddCustomRule().AddRule().AddCustomRule();
```

And more usefull usage in extension-methods:
```c#
    // Interfaces
    public interface IBaseBuilder
    {
        List<string> Rules { get; }
    }
    public interface ICustomBuilder : IBaseBuilder
    {
        List<string> CustomRules { get; }
    }

    // Implementations
    public class BaseBuilder : IBaseBuilder
    {
        public List<string> Rules { get; } = new List<string>();
    }

    public class CustomBuilder : BaseBuilder, ICustomBuilder
    {
        
        public List<string> CustomRules { get; } = new List<string>();
    }

    // Extension methods
    public static class BuilderExtensions
    {
        public static IBaseBuilder AddFooRule(this IBaseBuilder builder)
        {
            builder.Rules.Add("Foo");
            return builder;
        }

        public static IBaseBuilder AddBarRule(this IBaseBuilder builder)
        {
            builder.Rules.Add("Bar");
            return builder;
        }

        public static ICustomBuilder AddCustomFooRule(this ICustomBuilder builder)
        {
            builder.CustomRules.Add("Bar");
            return builder;
        }
    }
```

Instead of this:
```c#
((ICustomBuilder)((ICustomBuilder) ((ICustomBuilder) new CustomBuilder().AddFooRule()).AddCustomFooRule().AddBarRule())
                .AddCustomFooRule().AddFooRule()).AddCustomFooRule();
```
much more pretty syntax:
```c#
new CustomBuilder().AddFooRule().AddCustomFooRule().AddBarRule()
                .AddCustomFooRule().AddFooRule().AddCustomFooRule();
```

if make extension-methods void-return:
```c#
    public static class BuilderExtensions
    {
        public static void AddFooRule(this IBaseBuilder builder)
        {
            builder.Rules.Add("Foo");
        }

        public static voidAddBarRule(this IBaseBuilder builder)
        {
            builder.Rules.Add("Bar");
        }

        public static void AddCustomFooRule(this ICustomBuilder builder)
        {
            builder.CustomRules.Add("Bar");
        }
    }
```

Thanks!

**Comment by MgSam** [comment] 2017-08-01 13:22
You're proposing to change silently the meaning of `void`. I prefer void to mean exactly what it currently means. If you want a fluent pattern, return `this` at the end of your methods instead of void.

I suspect a feature you may be interested in is [covariant return types](https://github.com/dotnet/csharplang/issues/49). This would allow you to specify more specific types in subclasses.

**Comment by alrz** [comment] 2017-08-01 13:32
Note that fluent methods don't always return `this`, depending on the context you might want a different builder, so this seems to fail to cover the very use case it aim to address.

**Comment by jnm2** [comment] 2017-08-01 13:59
Dupe of https://github.com/dotnet/csharplang/issues/577

**Comment by jnm2** [comment] 2017-08-01 14:00
Related: https://github.com/dotnet/csharplang/issues/311

**Comment by Remleo** [comment] 2017-08-04 07:04
#16961 and #8947

**Comment by Remleo** [comment] 2017-08-04 07:06
https://github.com/dotnet/roslyn/issues/16961
and
https://github.com/dotnet/roslyn/issues/8947

**Closed** 2020-09-08 21:42 UTC
Labels: Discussion, Feature Request, Move to Discussion
