### ISSUE TITLE
Proposal: Custom operators in C#

### ISSUE THREAD

**Issue by kanisimoff** [dotnet/csharplang#3249] opened 2020-03-05 07:53 UTC
I suggest adding to the ability to create custom operator by analogy with c ++

``` cpp
#include <iostream>

// generic LHSlt holder
template<typename LHS, typename OP>
struct LHSlt {
    LHS lhs_;
};

// declare myop as an operator-like construct
enum { myop };

// parse 'lhs <myop' into LHSlt
template<typename LHS>
LHSlt<LHS, decltype(myop)> operator<(const LHS& lhs, decltype(myop))
{
    return { lhs };
}

// declare (int <myop> int) -> int
int operator>(LHSlt<int, decltype(myop)> lhsof, int rhs)
{
    int& lhs = lhsof.lhs_;
    // here comes your actual implementation
    return (lhs + rhs) * (lhs - rhs);
}

// strictly optional
#define MYOP <myop>

int main() {
    std::cout << (5 <myop> 2) << ' ' << (5 MYOP 2);
}
```

**Comment by svick** [comment] 2020-03-05 08:40
Related discussions: https://github.com/dotnet/csharplang/issues/594, https://github.com/dotnet/csharplang/issues/175.

Also, that C++ code is horrible abuse and doesn't really clarify what are you actually proposing.

**Comment by HaloFour** [comment] 2020-03-05 12:29
C# operator overloading was designed specifically to avoid the kind of syntax that you're proposing.  Even the bit shift operators were intentionally limited to accept integers as the second operand to prevent them from being used for something like a stream operator.

**Comment by kanisimoff** [comment] 2020-03-05 20:30
To work with mathematical objects, it is much easier to use a new operator than a method. Suppose I need to perform actions with a matrix. 
``` csharp
var a = new Matrix();
var res = a * a^(-1); // a matirx multiply on inverse a matrix
```
It is more convenient than
``` csharp
var a = new Matrix();
var res = a * a.Inverse(); // a matirx multiply on inverse a matrix as method
```
In numerical methods, where expressions can be very long, operators take precedence over methods. The code becomes more understandable.

**Comment by HaloFour** [comment] 2020-03-05 20:35
@kanisimoff 

C# doesn't have an exponentiation operator for numbers either.  There are proposals requesting that, and if that were to be added to the language it may be a candidate for being overloadable.

**Comment by kanisimoff** [comment] 2020-03-05 20:41
> @kanisimoff
> 
> C# doesn't have an exponentiation operator for numbers either. There are proposals requesting that, and if that were to be added to the language it may be a candidate for being overloadable.

Of course not. That is why I’m talking about defining your own operators. If you do not like the implementation from C++, you could use the option from F#. In F# it looks like this
``` fsharp
let (+.) x s = [for y in s -> x + y]
let s = 1 +. [2;3;4]
```

**Comment by HaloFour** [comment] 2020-03-05 20:43
@kanisimoff 

I'd say that runs counter to the design decision that C# support limited operator overloading to avoid becoming the incomprehensible ASCII mess that can be C++.

**Comment by kanisimoff** [comment] 2020-03-05 20:54
@HaloFour, 
I agree that with rash use, this will be a problem. But in any language there is a certain compromise between readability and flexibility. The same math, which is essentially a language, despite its expressiveness, may look like a bunch of obscure characters. However, much more clearly if described using formulas and operators than with words.

**Comment by eyalsk** [comment] 2020-03-05 21:20
@kanisimoff 

if anything infix functions would have been better imo but that ship has sailed and even this is debatable.

> But in any language there is a certain compromise between readability and flexibility.

Only it doesn't really provide any "flexibility" you just use an operator over a function name that is specific to your domain so now the reader have to stop and figure what all these operators are when reading the code that makes the code harder to follow and harder to understand thus reduces the readability quite a bit and this depends on the amount of operators the (ab)user decides to introduce to the code.

**Comment by CyrusNajmabadi** [comment] 2020-03-05 21:25
> But in any language there is a certain compromise between readability and flexibility

Absolutely!  The question is where C# lands in that spectrum.  For many decades it has landed in the camp of not offering this flexibility, even if there are domains that would benefit from it.  The request is totally reasonable.  However, barring a large shift in the attitudes from teh designers, i would put it at very unlikely to happen.

**Comment by kanisimoff** [comment] 2020-03-06 08:05
@eyalsk, 
> Only it doesn't really provide any "flexibility" you just use an operator over a function name that is specific to your domain so now the reader have to stop and figure what all these operators are when reading the code that makes the code harder to follow and harder to understand thus reduces the readability quite a bit and this depends on the amount of operators the (ab)user decides to introduce to the code.

However, when overloading the operators, we have the same problems, i.e. we must find out the behavior of the overloaded operator in relation to the class. When we define own operator, to avoid ambiguity, the operator should probably be defined in the type and most likely as a static. Thus, the logic of the operator would be tied to the logic of the class.

**Comment by eyalsk** [comment] 2020-03-06 09:41
@kanisimoff Yes, we have the same problem but we also have guidelines.

* Operator overloads **allow framework types** to appear as if they were built-in language primitives.

* Although allowed and useful in some situations, operator overloads should be used **cautiously**.

* ✔️ CONSIDER providing methods with friendly names that correspond to each overloaded operator.
    
  Many languages do not support operator overloading. For this reason, it is recommended that types that overload operators include a secondary method with an **appropriate domain-specific name** that provides equivalent functionality.

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads

**Comment by kanisimoff** [comment] 2020-03-06 11:00
@eyalsk, 
> * Operator overloads **allow framework types** to appear as if they were built-in language primitives.
> * Although allowed and useful in some situations, operator overloads should be used **cautiously**.
> 
> https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads

Ok, we can indicate similar requirements for custom operators. 
I think that operator overloading is being demonized because its uses in other languages has led to excesses, many people who dislike operator overloading can trace it back to some personal experiences where they once had to deal with code that was clearly abusing this feature. This is unfortunate, but I still think that new operators are much more convenient for working with mathematical libraries than methods.
It would be enough for me if this opportunity were implemented in the form of a library that would be used in a limited context (for example, only for numeric types), and would not carry the load for the rest of the language. True, I can not imagine how this can be implemented.

**Comment by kanisimoff** [comment] 2020-03-06 11:12
In principle, we can introduce a custom operator, for example, using the method described below.

``` csharp
public class TestClass
    {
        private static void ArithmeticExample()
        {
            Func<int, int, int> _sum = (a, b) => a + b;
            Func<int, int, int> _mult = (a, b) => a * b;
            var sum = _sum.Infixize();
            var mult = _mult.Infixize();
            
            Console.WriteLine(1 | sum | (2 | mult | 4) | sum | 8); //17
        }
    }

    public static class InfixExtensions
    {
        public static InfixOperator<T1, T2, RT> Infixize<T1, T2, RT>(this Func<T1, T2, RT> f)
        {
            return new InfixOperator<T1, T2, RT>(f);
        }
    }
    /// <summary>
    /// TODO: Curryable Infix Operator
    /// </summary>
    /// <typeparam name="T1">Left operand type</typeparam>
    /// <typeparam name="T2">Right operand type</typeparam>
    /// <typeparam name="RT">Return type</typeparam>
    public class InfixOperator<T1, T2, RT>
    {
        Func<T1, T2, RT> function;
        T1 leftvalue;
        public InfixOperator(Func<T1, T2, RT> f)
        {
            this.function = f;
        }
        public InfixOperator(T1 lv, Func<T1, T2, RT> f)
        {
            this.function = f;
            this.leftvalue = lv;
        }
        public static RT operator |(InfixOperator<T1, T2, RT> a, T2 b)
        {
            return a.function(a.leftvalue, b);
        }
        public static InfixOperator<T1, T2, RT> operator |(T1 a, InfixOperator<T1, T2, RT> b)
        {
            return new InfixOperator<T1, T2, RT>(a, b.function);
        }
    }
```
But imho this code is less readable than it could be.

**Comment by CyrusNajmabadi** [comment] 2020-11-19 15:28
Closing this out as this was a core and conscious decision that was part of the C# design.  in other words, the inability to not allow custom operators was not an accident, or a case of thinking that this could be done later.  It was an intentional restriction due to the belief that this functionality does more harm than good.

**Closed by CyrusNajmabadi** 2020-11-19 15:28 UTC
