### ISSUE TITLE
Proposal: fixed buffers for "unmanaged" structs

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#1494] opened 2018-05-04 07:45 UTC
Currently, declaring fixed buffers on structs is limited to a set of primitives and when you try to use it for custom blittables, you get the following compilation error: 

> error CS1663: Fixed size buffer type must be one of the following: bool, byte, short, int, long, char, sbyte, ushort, uint, ulong, float or double

The idea is to allow the following:

```
public unsafe struct TestA
{
    private fixed TestB _myFixedArray[100];
}

public struct TestB
{
  ... no reference-type fields here ...    
}
```

(Maybe one way to enforce such support is by requiring  to make explicit the type of struct layout)

This is related to ...:
https://github.com/dotnet/csharplang/blob/38370edf77e23da6c459bfbdf7c36dacd14eea7f/proposals/fixed-sized-buffers.md

... but would not imply modifications to allow the use of fixed buffers on safe contexts.

**Comment by ygc369** [comment] 2018-05-05 00:29
Like this idea.

**Comment by tannergooding** [comment] 2018-05-05 03:32
The Fixed Sized Buffer proposal you linked is already championed and covers this.

The work to support all 'unmanaged' types (effectively what you are proposing) and the work to support all types is very similar and should probably be done all at once (IMO).

In both cases, the existing backing structures generated is not sufficient to handle arbitrary types. That is, the current mechanism creates a single field struct that is explicitly sized. However, in many cases, the size of the struct cannot be determined until runtime (as it may differ between platforms, architectures, or even runtimes).

The mechanism discussed in the championed proposal is one of the ways that these inconsistencies can be handled. That is, the backing struct would not be explicitly sized and would, instead, explicitly list a field per element and would have a packing of 0.

**Comment by jnm2** [comment] 2018-05-05 15:10
> Porposal

As Cyrus likes to say, “for all intensive porpoises…”

**Comment by jnm2** [comment] 2018-05-07 18:34
Lol, I thought there was [something familiar about my comment](https://github.com/dotnet/csharplang/issues/1436#issuecomment-378927311)... 😳

**Comment by jnm2** [comment] 2018-05-07 18:36
Lol, I thought there was [something familiar about my comment](https://github.com/dotnet/csharplang/issues/1436#issuecomment-378927311)... 😳

Something appears to have started happening here:

![image](https://user-images.githubusercontent.com/8040367/39718356-0ab5db42-5204-11e8-8069-d44aa274f0ec.png)

**Comment by jnm2** [comment] 2018-05-07 20:27
No problem, sorry for making a big deal of it 😁

**Comment by Ultrahead** [comment] 2020-04-26 01:18
Any news about the champion that covers this proposal?

**Comment by YairHalberstadt** [comment] 2020-10-14 15:06
Closing as duplicate of championed issue https://github.com/dotnet/csharplang/issues/1314

**Closed by YairHalberstadt** 2020-10-14 15:06 UTC
