### ISSUE TITLE
Proposal: Deconstruct Tuples to param list

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/csharplang#2550] opened 2019-05-20 11:54 UTC
Suppose we have:
```C#
  void Foo(int x, string y, DateTime z)
  {
            
  }
```

I am thinking of doing this:
```C#
var a = (1, "test");
Foo(a, DateTime.Now);
//Instead of
Foo(a.Item1, a.Item2 ,DateTime.Now);


var b = (1, "test", DateTime.Now);
Foo(b);
//Instead of
Foo(b.Item1, b.Item2 ,b.Item3);
```

**Comment by YairHalberstadt** [comment] 2019-05-20 12:03
I have a couple of questions:

1. Would this work for any deconstructable type or just tuples?

2. How would this interact with overload resolution. What would the rules be? How could this be efficiently implemented in the compiler?

3. How would you resolve this ambiguity:

```csharp
public void Foo((int, int) a, int b, int c);
public void Foo(int a, int b, (int, int) c);

...
var a = (0, 1);
var b = (2, 3);

Foo(a, b); // what method does this call?
```

**Comment by VBAndCs** [comment] 2019-05-20 12:11
Interesting questions:
1. I like use it with any deconstructable type.
2. passing values to direct parameters have precedence over deconstructions
3. Left most direct params have precedence. So, first overload wins.

**Comment by jnm2** [comment] 2019-05-20 12:12
The usual term for this is 'splatting.'

I believe this is a duplicate of #1654. An alternative I also like is #1648.

**Comment by jcouv** [comment] 2020-05-01 20:50
Closing as duplicate of #1654 to organize things a bit

**Closed by jcouv** 2020-05-01 20:50 UTC
