### ISSUE TITLE
Proposal: Composite Implementation Routing

### ISSUE THREAD

**Issue by Sologix** [dotnet/csharplang#2017] opened 2018-11-20 10:48 UTC
Composition is a powerful tool in object oriented design, but I'm somewhat bothered by having to reroute the interface members to implementation members, which are usually one-on-one calls. 

I'm thinking about a C# language proposal to alleviate this burden and I'm posting here to discuss as to whether this might be a good idea.

The code is as follows: 

NAME: COMPOSITE IMPLEMENTATION ROUTING

```
public interface IComposite1
{
  void Method1();
}

public interface IComposite2
{
  void Method2();
}

public Composite2Impl : IComposite2
{
  
}

CURRENT:

public class MyCompositeClass : IComposite1, IComposite2
{
  private IComposite1 _composite1;
  private Composite2Impl _composite2;

  public MyCompositeClass(IComposite1 composite1)
  {
    _composite1 = composite1;
    _composite2 = new Composite2Impl();
  }
  
  private void Method1()
  {
    _composite1.Method1();
  }
  
  private void Method2()
  {
    _composite2.Method2();
  }
}

PROPOSED: 

public class MyCompositeClass : IComposite1(_composite1), IComposite2(_composite2)
{
  protected IComposite1 _composite1;
  private Composite2Impl _composite2;
  
  public MyCompositeClass(IComposite1 composite1)
  {
    _composite1 = composite1;
    _composite2 = new Composite2Impl();
  }
}

public class MyInheritedCompositeClass : MyCompositeClass
{
  public override Method1()
  {
    
  }
}


```

**Comment by Joe4evr** [comment] 2018-11-20 21:57
Looks like mostly a duplicate of #900, just with a slightly different syntax.

**Comment by yaakov-h** [comment] 2018-11-21 07:11
Looks more like a duplicate of #234 (with different syntax) to me.

**Closed** 2020-10-19 11:33 UTC
