### ISSUE TITLE
[Proposal]: Method Assignment Operator (.=)

### ISSUE THREAD

**Issue by gstrasd** [dotnet/csharplang#4253] opened 2020-12-20 23:57 UTC
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

I'd like the ability to assign the result of a method to the original object that invoked it. In other words...

Instead of:
var foo = "  biz bang  ";
foo = foo.Trim();

Do this:
var foo = "  biz bang  ";
foo.=Trim();

## Motivation
[motivation]: #motivation

The motivation is simply for brevity. The null coalescing assignment operator was just added. It seems logical to have this as well. 

## Detailed design
[design]: #detailed-design

Further detail isn't really needed. It should be obvious.

## Drawbacks
[drawbacks]: #drawbacks

It could be used in a way that could confusingly reassign the type, but that already exists.
var foo = "hello";
foo .= Count;

## Alternatives
[alternatives]: #alternatives

NA

## Unresolved questions
[unresolved]: #unresolved-questions

NA

## Design meetings

NA

**Comment by HaloFour** [comment] 2020-12-21 00:08
See: https://github.com/dotnet/csharplang/discussions/4245

**Comment by theunrepentantgeek** [comment] 2020-12-21 02:36
> It could be used in a way that could confusingly reassign the type, but that already exists.
> var foo = "hello";
> foo .= Count;

No, it couldn't - the variable `foo` is strongly typed as a **string**. The second line will fail to compile because `Count` is not a **string**.

**Comment by 333fred** [comment] 2024-12-06 23:40
Closing as a duplicate of https://github.com/dotnet/csharplang/discussions/4245.

**Closed by 333fred** 2024-12-06 23:40 UTC
