### ISSUE TITLE
Shortcut for foreach... yield return

### ISSUE THREAD

**Issue by ekolis** [dotnet/csharplang#3421] opened 2020-05-03 18:38 UTC
A lot of the time I'll wind up writing code like this:

```
public IEnumerable<Thing> Things
{
	get
	{
		yield return MyThing;
		foreach (var thing in MyOtherThings)
			yield return thing;
	}
}
```

This seems wasteful and unintuitive, to have to `foreach` the collection just to `yield return` each item individually. I'm not sure what would be a better way to write this, but there has got to be one! Just throwing some ideas out there:

```
yield return MyOtherThings; // could be ambiguous if typeof(Thing) is a subclass of Thing, e.g. typeof(Thing) == typeof(object)
yield MyOtherThings; // is the lack of return sufficient to denote it?
yield returnAll MyOtherThings; // do we really need to add a new keyword?
yield return foreach MyOtherThings; // wordy
yield foreach MyOtherThings; // maybe this would work?

**Comment by CyrusNajmabadi** [comment] 2020-05-03 18:42
Dupe of https://github.com/dotnet/csharplang/issues/378

**Closed by CyrusNajmabadi** 2020-05-03 18:42 UTC
