### ISSUE TITLE
Async Contructors

### ISSUE THREAD

**Issue by bilal-fazlani** [dotnet/csharplang#934] opened 2017-09-24 07:17 UTC
I am proposing something like this: 

```c#
public class MyClass
{
  public async Task<MyClass>()
  {
    await doSomeAsyncSetupWork();
  }
}

class Program
{
  public static async Task main(string[] args)
  {
    MyClass myClass = await new MyClass();
  }
}
```

Without this feature, it would have to be something like this.

Workaround 1:

```c#
public class MyClass
{
  public MyClass()
  {
    doSomeAsyncSetupWork().Wait();
  }
}

class Program
{
  public static async Task main(string[] args)
  {
    MyClass myClass = new MyClass();
  }
}
```

Or Workaround 2:

```c#
public class MyClass
{
  public MyClass()
  {
  }

  public async Task Setup()
  {
    await doSomeAsyncSetupWork();
  }
}

class Program
{
  public static async Task main(string[] args)
  {
    MyClass myClass = new MyClass();
    await myClass.Setup();
  }
}
```

Both of these workarounds have some problem. The former obviously because of it's blocking behaviour. 

The issue with latter is, I even though Setup() in a mandatory requirement for object to exist and function correctly, I still have to call it explicitly whenever I create instance of object, otherwise, the the object is incomplete and won't function and throw runtime exceptions.

**Comment by benaadams** [comment] 2017-09-24 07:27
Workaround 3:

```csharp
public class MyClass
{
    private Task _initalization;
    
    public MyClass()
    {
        _initalization = doSomeAsyncSetupWork(); 
    }
    
    public async Task WhenInitalizedAsync()
    {
      await _initalization;
    }
}

class Program
{
  public static async Task main(string[] args)
  {
    MyClass myClass = new MyClass();
    await myClass.WhenInitalizedAsync();
  }
}
```

Workaround 4:

```csharp
public class MyClass
{
    private Task _initalization;
    
    private MyClass()
    {
        _initalization = doSomeAsyncSetupWork(); 
    }
    
    public async static Task<MyClass> CreateAsync()
    {
        MyClass myClass = MyClass();
        await myClass._initalization;
        return myClass;
    }
}

class Program
{
  public static async Task main(string[] args)
  {
    MyClass myClass = await MyClass.CreateAsync();
  }
}
```

**Comment by yaakov-h** [comment] 2017-09-24 08:39
Duplicate of #419, though with different requested syntax.

**Closed** 2020-09-08 21:50 UTC
Labels: Discussion, Feature Request, Move to Discussion
