### ISSUE TITLE
Proposal: Bring parameter names into nameof scope for attributes on methods and return values

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#3073] opened 2020-01-06 01:27 UTC
Easiest to show via a simple example:

```c#
// Currently have to do this:

[return: NotNullIfNotNull("source")]
public static string? GetString(object? source) => source?.ToString();

// Want to do this:

[return: NotNullIfNotNull(nameof(source))]
public static string? Resolve(object? source) => source?.ToString();
```

**Comment by 333fred** [comment] 2020-01-06 01:30
Closing as a duplicate of https://github.com/dotnet/csharplang/issues/373.

**Closed by 333fred** 2020-01-06 01:30 UTC
