### ISSUE TITLE
request: non-nullable type constraint

### ISSUE THREAD

**Issue by Spongman** [dotnet/csharplang#2146] opened 2019-01-15 20:25 UTC
```c#
void Foo<T>(T? foo) // error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.
{
}
```

but there's no way to specify that `T` is non-nullable. i can specify `struct` or `class`, but i can't specify `either`.

the nullability check is forcing me to duplicate the definition of this method. like Java would :(

**Comment by YairHalberstadt** [comment] 2019-01-15 20:33
I believe there were plans to allow `where T : object` to mean a non-nullable type

**Comment by 333fred** [comment] 2019-01-15 22:08
@YairHalberstadt is correct. It seems to be working fine on sharplab for me: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWACgBiAOwFcAbBiYBufOGlty7AZkIAmfAGEAPABUAfPgDuAC0TsJ+EPgD2wAFZwAxjHwBvSvlOEB2ACz4AsgAoAlEZNmAvpVdA. Also see the feature doc here: https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#type-parameters.

@Spongman, if there are no other questions, could you please close this issue?

**Comment by YairHalberstadt** [comment] 2019-01-15 22:11
Ah. I was on the NRT branch of sharplab. I should have checked master first 🤣

**Comment by Spongman** [comment] 2019-01-15 22:13
doesn't work for me:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWACgBiAOwFcAbBiYBufOGlty7AZkIAmfADF8Ab0r5phACyiA9goA8AFQB8AClUB+fADMlASnwB6UxwQIFCfAGEAygA4AbIIDsIfAEF89JtzsMACeAA7soRAIEGBw8LZgdLD4wOwA1jQKAO40+DAKKewQ+ABuEAx0QWHsNn4KNAC0/sys7Ahw+oicAMZV4QB09vVQAJYoiPgQKCgjNADmk/gA5NiCS0jLsAh03TDr+LUh4fjdwzDRszD9UjIAkFkAFl34qvheCsAAVnC7N9KSFBk+AAvpRgUA==

**Comment by 333fred** [comment] 2019-01-15 22:51
Copying the relevant code over:
```C#
using System;
#nullable enable
public class F {
    void Foo<T>(T? foo) // error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.
    	where T : object
    {
    }
}
```

At least currently, this is intended behavior, as we cannot determine whether `T` is a `class` or a `struct`. @cston and @MadsTorgersen for more discussion on this.

**Comment by Spongman** [comment] 2019-01-15 22:53
> we cannot determine whether T is a class or a struct
then why does this constraint work when used on a class definition, as in your sharplab example?

**Comment by 333fred** [comment] 2019-01-15 22:54
@Spongman, it might be helpful if we had a more complete scenario here. What are you trying to do that you can't just have an unconstrained `T` for? For example:

```C#
#nullable enable
class C<T>
{
	void M(T t) => t.ToString(); // warning CS8602: Possible dereference of a null reference.
}
```

> then why does this constraint work when used on a class definition, as in your sharplab example?

It's not that the constraint doesn't work on a method, it's that with that constraint you can't create a variable of type `T?`.

**Comment by DavidArno** [comment] 2019-02-15 13:19
@333fred,

A simple, complete scenario for you:
```cs
public class Foo<T>
{
    public T? Prop { get; set; }
}
```
This gives a warning on `T?` as I can't constrain the class to work only with classes or structs. But if I remove the `?` it gives a warning that `Prop` is uninitialized, 

I simply want `Prop` to be allowed to be *defaultable*. The inability to do this makes NRTs incompatible with generics in any scenario where I simply want a default of `T`.

I'm even wondering whether `T?` should mean "defaultable", not "nullable" in a generic context unless constrained to structs or classes.

**Comment by AlexanderTaeschner** [comment] 2019-02-28 18:15
@333fred an actual example would be:
```csharp
    #nullable enable
    public class TwoDimensionalLookupTable<TKeys, TValue>
        where TValue : object
    {
        // ...
        public bool TryGetValue(TKeys key1, TKeys key2, out TValue? value) // error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.
        {
            if (!_internalDictionary.TryGetValue(key1, out var key2Dictionary))
            {
                value = default;
                return false;
            }
            // ...
        }
    }
```

**Comment by lmmarsano** [comment] 2019-03-22 01:39
@333fred A library I'm writing to convert between nullable types and non-nullable Option/Maybe types runs into this problem.
Though converting nullable types to Maybe is possible with nearly duplicate extension methods, a single function with constraint `T: object` would be preferable.
```c#
public static Maybe<T> ToMaybe<T>(this T? @this) where T: class
=> @this is T value
 ? (Maybe<T>)value
 : Nothing.Value;

public static Maybe<T> ToMaybe<T>(this T? @this) where T: struct
=> @this is T value
 ? (Maybe<T>)value
 : Nothing.Value;
```
[lmmarsano/alias:source/Functional/Extension.cs](/lmmarsano/alias/blob/db4e7772d7afefe53bb38be65b1cf05f77ef11db/source/Functional/Extension.cs#L29-L50)
Converting to nullable types raises difficult errors.
```c#
#nullable enable
public abstract class Maybe<T> where T: object {
	public abstract T? ToNullable(); //error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.
}
```
[sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABAZgtNgQgGMYKmATBQCyEAJ7A4AHgAqAPgoB3ABaJKMkBQD2wAFZxeFAN6MAkK3bBOPPjID8FGVoByREmTgAKAJQBuRgC+QA=)
The only workaround I know is to employ the null-forgiving operator `!` with non-nullable types, which defeats the purpose of nullable type-checking.

**Comment by gafter** [comment] 2019-03-22 02:55
We are working on a `[MaybeNull]` attribute you could put on the `ToNullable()` method that would make this work.  But it isn't ready yet.

**Comment by yaakov-h** [comment] 2019-03-22 03:38
Why does it require a separate attribute to `[Nullable]`?

**Comment by YairHalberstadt** [comment] 2020-10-21 07:26
Closing in favor of https://github.com/dotnet/csharplang/issues/2194 which explains the suggested language change more clearly.

**Closed by YairHalberstadt** 2020-10-21 07:26 UTC
