### ISSUE TITLE
Update keyword use as an initializer

### ISSUE THREAD

**Issue by srburton** [dotnet/csharplang#2063] opened 2018-12-11 18:06 UTC
**Model**
```
public class People {
   public string Name {get; set;}
   public string LastName {get; set;}
}
```

**Suggestion**
```
public class Program{

  public void Main(){
     
     var people = new People()
     {
         Name = "sr"
     };

    // Continue ....
    
     update people{
       Name = "renato"
       LastName = "burton"
     };
  
  }
}
```

**Actual**

```
public class Program{

  public void Main(){
     
     var people = new People()
     {
         Name = "sr"
     };

    // Continue ....
    
      people.Name = "Renato";
      people.LastName = "burton";
     
  }
```

**Comment by srburton** [comment] 2018-12-11 18:14
**Other Exemple**

**Models**
```
public class ModelA{
   public string Name {get; set;}
   public string LastName {get; set;}
}

public class ModelB{
   public string Name {get; set;}
   public string LastName {get; set;}
}
```

**Suggestion**
```
public class Program{
   
  readonly ModelB _modelB = new ModelB();

  public void Main(ModelA modelA){
     
      update  _modelB{
        Name = modelA.Name,
        LastName = modelA.LastName
      }
     
  }
```
**Actual**

public class Program{
   
  readonly ModelB _modelB = new ModelB();

  public void Main(ModelA modelA){
     
//repetitive monolith
        _modelB.Name = modelA.Name,
        _modelB.LastName = modelA.LastName
 //repetitive monolith

  }

**Comment by cpplearner** [comment] 2018-12-11 18:23
Duplicate of #1449?

**Comment by yaakov-h** [comment] 2018-12-12 00:14
Technically not a duplicate if it proposes a different keyword, but the concept is the same.

**Comment by willard720** [comment] 2018-12-12 02:10
I have no idea what you're trying to get at. Could you actually explain your proposal?

**Comment by TheUnlocked** [comment] 2018-12-13 21:38
@willard720 
I believe the idea is to set multiple properties in a single statement using a similar syntax to what you can do with `new`.

I like this idea, but I don't think we need a new keyword for it.

**Comment by srburton** [comment] 2018-12-17 12:10
@TheUnlocked  Correct, we don't need a new key word we can use an existing one. But the update is not the linq? It already exists;

**Comment by YairHalberstadt** [comment] 2020-10-20 11:30
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/1534

**Closed by YairHalberstadt** 2020-10-20 11:30 UTC
