### ISSUE TITLE
[Proposal] Extend readonly members to classes and interfaces

### ISSUE THREAD

**Issue by leandromoh** [dotnet/csharplang#3531] opened 2020-06-04 00:46 UTC
We already have [readonly members](https://github.com/dotnet/csharplang/issues/1710), introduced in C# 8, but it works just on structs. 

Can we have extend this feature for classes and interfaces take benefits too?

**Comment by HaloFour** [comment] 2020-06-04 01:09
The benefit of `readonly` members on structs is to inform the compiler that it doesn't have to make a defensive copy when calling those members when the struct is in a memory location that should not be modified, like a `readonly` field or `in` parameter.  That situation doesn't exist for reference types.

**Comment by huoyaoyuan** [comment] 2020-06-04 05:11
If we have some concept of **readonly instance** of reference type in the future, extending readonly members will be useful then.

**Comment by Joe4evr** [comment] 2020-06-04 10:53
Duplicate of #3055. Specifically read [this post](https://github.com/dotnet/csharplang/issues/3055#issuecomment-571227415) on why this is very likely not happening.

**Comment by leandromoh** [comment] 2020-06-04 15:16
@HaloFour the benefit that I did not know that for structs the target was for compiler. What I have in mind was help developers write/read methods without side-effects.

**Closed** 2020-06-04 16:06 UTC
