### ISSUE TITLE
allow ref var with initial value

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1077] opened 2017-11-03 22:33 UTC
allow to use ref var with initial or default value.

```
if (!map.AddOrFind(ref var kvp = (item, slot).AsPair(), false);
{
    // ...
}
```

equivalent to

```
var kvp = (item, slot).AsPair();
if (!map.AddOrFind(ref kvp, false))
{
   // ...
}
```

AsPair is extension method to convert tuple to key value pair.

```
public static KeyValuePair<TKey, TValue> AsPair<TKey, TValue>(this (TKey key, TValue value) tuple)
{
    return new KeyValuePair<TKey, TValue>(tuple.key, tuple.value);
}
```

---

edited with real example of what I had, AddOrFind method exist [here](https://github.com/qwertie/ecsharp/blob/master/Core/Loyc.Collections/Sets/MMap.cs)

--- 

**some considerations:** 

 - should this syntax be allowed too?

```
Call(ref var x, y); // x assigns to default(T), var is inferred from method signature if there are no ambiguous overloads.
```

**Comment by jnm2** [comment] 2017-11-04 18:19
I feel like this is a duplicate but on my phone.

**Comment by jnm2** [comment] 2017-11-04 18:20
Duplicate of https://github.com/dotnet/csharplang/issues/854

**Closed** 2020-09-08 23:47 UTC
Labels: Discussion, Feature Request, Move to Discussion
