### ISSUE TITLE
Propose: Add "where" support for enum in generic type defintions

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#329] opened 2017-03-24 15:49 UTC
Currently there's no way to restrict a generic type argument to be an enum. One "workaround" is to restrict the type to a struct perhaps adding IComparable etc to the "where" clause.

So this is a proposal to add this feature to C#.

This was inspired by this related issue:

https://github.com/dotnet/roslyn/issues/18126

This has come up numerous time in certain kinds of designs, it isn't a frequent issue but does arise and does seem like a gap in the language.

Thx

**Comment by HaloFour** [comment] 2017-03-24 15:51
Dupe of #104.

**Comment by playsomethingsaxman** [comment] 2017-03-24 21:23
#104 just disappeared, so...

Generic constraints make extremely good sense with enum inheritance. Example from the future:

```
public enum WindowMessage
{
    WM_NULL = 0,
}

public enum ListViewMessage : WindowMessage
{
    LVM_FIRST = 0x1000,
    LVM_EDITLABELW = (LVM_FIRST + 118),
}

public static IntPtr SendMessage<TMessage>(
    HWND hwnd,
    TMessage Msg = WindowMessage.WM_NULL,
    UIntPtr wParam = default(UIntPtr),
    IntPtr lParam = default(IntPtr))
    where TMessage : WindowMessage
{
    // [....]
}
```

**Closed** 2020-09-08 19:46 UTC
Labels: Discussion, Feature Request, Move to Discussion
