### ISSUE TITLE
Make ternary expressions with an explicit null and another type return a nullable

### ISSUE THREAD

**Issue by realbart** [dotnet/csharplang#2853] opened 2019-10-03 09:10 UTC
Expressions like `true ? 1 : null` currently throw an exception: 

`error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'int' and '<null>'`

Therefore, the codebase I inherited contains many instances of:
```
Housenumber = int.TryParse(organization.HouseNumber, out var parsed) ? parsed : default(int?)
```
or
```
Housenumber = int.TryParse(organization.HouseNumber, out var parsed) ? (int?)parsed : null
```
or
```
Housenumber = int.TryParse(organization.HouseNumber, out var parsed) ? parsed : (int?)null
```

I'd like to be able to write:
```
Housenumber = int.TryParse(organization.HouseNumber, out var parsed) ? parsed : null
```

**Comment by yaakov-h** [comment] 2019-10-03 10:09
Duplicate of #33 / #2460 / #2823

**Closed** 2019-10-03 21:42 UTC
