### ISSUE TITLE
[Proposal] Generic aliases

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/csharplang#3309] opened 2020-03-25 13:52 UTC
Allow defining generic aliases:
Currently, we can't mark an alias as generic:
```C#
using Expr<T> = Expression<Func<T, object>>;
```

So, Expr<T> can be used in generic classes like this:
```C#
class Foo<T>
{
   public List<Expr<T>> Includes { get; } 
       = new List<Expr<T>>( );
}
```

Which is a little longer than #3306 but still readable, with the benefit that it is usable in all classes in the file.

**Comment by YairHalberstadt** [comment] 2020-03-25 14:04
@VBAndCs 

For future reference, adding a link to your issue on every single related issue is generally considered spam.

**Comment by YairHalberstadt** [comment] 2020-03-25 14:06
Also this is a duplicate of https://github.com/dotnet/csharplang/issues/1239.
Please close and move discussion to there.

**Comment by CyrusNajmabadi** [comment] 2020-03-25 15:11
Dupe. Closing out.

**Closed by CyrusNajmabadi** 2020-03-25 15:11 UTC

**Comment by CyrusNajmabadi** [comment] 2020-03-25 15:13
> For future reference, adding a link to your issue on every single related issue is generally considered spam.

Indeed. Please avoid that in the future @VBAndCs. Thanks!

**Comment by VBAndCs** [comment] 2020-03-25 15:27
OK.
Hope you accept #1239.
