### ISSUE TITLE
Auto-Implemented Property Accessor-Targeted Attributes

### ISSUE THREAD

**Issue by jcouv** [dotnet/csharplang#1355] opened 2018-03-06 06:48 UTC
@IlyaGrebnov commented on [Mon Mar 05 2018](https://github.com/dotnet/roslyn/issues/25236)

Unable to apply MethodImpl attribute to Expression-bodied Property Get. Tested with latest version of VS 2017.15.6.0.

Note, program is for illustration purpose only and have no real value.

    class Program
    {
        public int Working1
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get { return 1; }
        }

        public int Working2
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get;
        } = 3;

        public int Working3
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get => 2;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public int NotWorking1 => 2;

        static void Main(string[] args)
        {
        }
    }

Expected Behavior: Program compiles.

Actual Behavior: Error CS0592 Attribute 'MethodImpl' is not valid on this declaration type. It is only valid on 'constructor, method' declarations.

**Comment by jcouv** [comment] 2018-03-06 06:50
Relates to [Auto-Implemented Property Field-Targeted Attributes ](https://github.com/dotnet/csharplang/issues/42)

**Comment by svick** [comment] 2018-03-06 08:14
How exactly would this work?

Are you saying there should be a rule like "If an attribute that cannot be applied to a property is applied to a property with a single accessor, the attribute behaves as if it was applied to the accessor"?

Or do you want code using attribute target like `[method: MethodImpl(MethodImplOptions.NoInlining)] public int NotWorking1 => 2;` to work? (Which would be consistent with https://github.com/dotnet/csharplang/issues/42.)

**Comment by Joe4evr** [comment] 2018-03-06 08:31
While I struggle to think up use-cases, I would prefer the `method:` target syntax be used, both for clarity and the aforementioned consistency.

Though this would beg the question, how would it behave when both accessors are defined? E.g.
```cs
[method: MethodImpl(MethodImplOptions.NoInlining)]
public int Prop { get; set; }
```
Error? Apply an instance to both accessor methods?

**Comment by jnm2** [comment] 2018-03-06 13:24
I prefer being explicit:

```cs
[get: MethodImpl(MethodImplOptions.NoInlining)]
[set: MethodImpl(MethodImplOptions.NoInlining)]
public int Prop { get; set; }
```

**Comment by HaloFour** [comment] 2018-03-06 13:38
I agree, the `method` attribute target should be required, even if the attribute cannot be applied to properties.  And I think that this syntax should only be added specifically to the case of readonly expression-bodied properties that lack a `get` accessor as in all other cases you can already target an attribute specifically on the accessor methods.

**Comment by IlyaGrebnov** [comment] 2018-03-06 18:56
For my point of view adding method attribute (get: or set: or method:) is not intuitive. 

There is no ambiguity as expression bodied property only have one method (getter or setter). Why not make it work with just [MethodImpl(MethodImplOptions.NoInlining)]?

**Comment by HaloFour** [comment] 2018-03-06 19:23
@IlyaGrebnov 

> There is no ambiguity as expression bodied property only have one method (getter or setter). Why not make it work with just [MethodImpl(MethodImplOptions.NoInlining)]?

The ambiguity is with whether the attribute applies to an accessor method or to the property itself.  As a developer you'd have to know that `MethodImplAttribute` doesn't allow targeting properties.  For attributes that do allow targeting either methods or properties the existing syntax would only apply the attribute to the property, so the `method:` target syntax is necessary in order to allow the developer to explicitly apply the attribute to the accessor method anyway.

**Comment by jnm2** [comment] 2018-03-06 19:28
If it was possible to target the method without the target if it fails to match the property, that would mean adding AttributeTargets.Property your AttributeUsage would be a breaking change if it initially happened to include AttributeTargets.Method.

**Comment by IlyaGrebnov** [comment] 2018-03-06 19:29
This make sense. Thanks for clarification.

**Comment by CyrusNajmabadi** [comment] 2018-03-07 06:38
```c#
[method: MethodImpl(MethodImplOptions.NoInlining)]
public int Prop { get; set; }
```

If you have a get/set already declared in source, then i see no reason why you'd need attribute on the *property* that referred to them.  You would simply put the attributes on the accessors themselves.

I'm of the opinion that the point of expression-bodied getters is to be brief for the common case.  The moment you need to do more complex stuff, then you should jsut write a full property.  So placing attributes on properties that apply to accessors shouldn't be done.  Instead, just allow attributes for accessors and have the user write those instead.

**Comment by Joe4evr** [comment] 2018-03-07 12:19
Sounds fair.

**Comment by glenn-slayden** [comment] 2019-03-29 01:51
related: https://github.com/dotnet/csharplang/issues/887

**Comment by YairHalberstadt** [comment] 2020-10-13 11:28
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/887

**Closed by YairHalberstadt** 2020-10-13 11:28 UTC
