### ISSUE TITLE
Structs and Nullable

### ISSUE THREAD

**Issue by merthsoft** [dotnet/csharplang#3222] opened 2020-02-20 22:00 UTC
I've noticed if you have the nullable annotations enabled, and declare the following class:

```csharp
public class A
{
    public string Value { get; }
}
```
You will see the following warning:
> Non-nullable property 'Value' is uninitialized. Consider declaring the property as nullable.

However, if this is a struct, you do not run into this warning. Additionally, in the world of the struct or the class, you can do the following with no warning:
```csharp
Console.WriteLine(new A().Value.Length);
```
`new A().Value.Length` will always throw an exception here.

If you fix the warning in the class by introducing a constructor:
```csharp
public class A
{
    public string Value { get; }

    public A(string value)
    {
        Value = value;
    }
}
```
Things behave and you can't `new A()`. However, if it's a struct, you can still get away with accessing members of the Value property after doing `new A()` without warning, because parameter-less constructors always exist on structs (which seems an odd choice for readonly structs). It's possible if you have an `A` instance that you set the value manually, so not all calls to `A.Value.Length` after a `new A()` would cause the null reference. However, if it's a readonly struct, all calls to `A.Value.Length` will cause a null ref exception.

I would expect some of these cases to generate warnings similar to if it were just:
```csharp
public class A
{
    public string Value { get; }
}
```

Edit:
Also, VS reports to me that `Value` is not null:
![image](https://user-images.githubusercontent.com/1743796/74982656-879b6f80-5402-11ea-8028-dd95a6caddd9.png)
But it is always null.

**Comment by ufcpp** [comment] 2020-02-21 01:01
dup of https://github.com/dotnet/csharplang/issues/3030

**Comment by YairHalberstadt** [comment] 2020-11-19 10:10
CLosing as duplicate of #3030

**Closed by YairHalberstadt** 2020-11-19 10:10 UTC
