### ISSUE TITLE
Using all syntax

### ISSUE THREAD

**Issue by CreatorVilius** [dotnet/csharplang#3812] opened 2020-08-20 08:44 UTC
What about allowing to import/use all of namespaces? E.g., let's say we have this in `C.cs`
```cs
namespace A.B {
    public class C {
        // ...
    }
}
```
And this in `E.cs`
```cs
namespace A.D {
    public class E {
        // ...
    }
}
```
Now, we can use
```cs
using A.B;
using A.D;
```
to get both C and E types. However, what about doing
```cs
using A.*;
```
instead?

**Comment by Flutterish** [comment] 2020-08-20 08:54
This sounds fine until you create a namespace in `A` that makees your code do something unexpected. If anything this could be an IDE feature to add all current child namespaces.

**Comment by khm1600** [comment] 2020-08-20 09:43
#2653

**Comment by PathogenDavid** [comment] 2020-08-20 09:51
@khm1600 you beat me to it!

--------

Duplicate of https://github.com/dotnet/csharplang/issues/2653

Similar/related proposals:

| | |
|-----|-----|
Allow importing every namespace in referenced assemblies | https://github.com/dotnet/csharplang/issues/1708
Proposals for more compact using directive syntax | https://github.com/dotnet/csharplang/issues/3590 https://github.com/dotnet/csharplang/issues/1696
Allow automatic importing when there's no conflicting types | https://github.com/dotnet/csharplang/issues/3477
Project-wide using directives | https://github.com/dotnet/csharplang/issues/3428 (C# 10.0 candidate) https://github.com/dotnet/csharplang/issues/1777

**Comment by 333fred** [comment] 2020-08-20 15:10
Closing as a duplicate.

**Closed by 333fred** 2020-08-20 15:10 UTC
