### ISSUE TITLE
[Proposal] Allow local methods use Attribute

### ISSUE THREAD

**Issue by ahdung** [dotnet/csharplang#2740] opened 2019-08-24 06:01 UTC
I hope can do this:
```c#
private static void PlaySystemSound(string soundAlias)
{
    PlaySound(soundAlias, IntPtr.Zero, 0x10000 /*SND_ALIAS*/| 0x1 /*SND_ASYNC*/);

    [DllImport("winmm.dll", CharSet = CharSet.Auto)]
    static extern bool PlaySound([MarshalAs(UnmanagedType.LPWStr)] string soundName, IntPtr hmod, int soundFlags);
}
```

**Comment by svick** [comment] 2019-08-24 06:49
This is a duplicate of https://github.com/dotnet/csharplang/issues/1888.

**Comment by RikkiGibson** [comment] 2019-12-06 22:06
Closing as a duplicate

**Closed by RikkiGibson** 2019-12-06 22:06 UTC
