### ISSUE TITLE
Define Sets: Non numeric Enums

### ISSUE THREAD

**Issue by ghost** [dotnet/csharplang#2237] opened 2019-02-16 21:14 UTC
I and others sent many proposals asking for string enusm, date enums, and even tuple enums. This is a popular request but the answer is always "CLR can't do it"!.. So, please make it do it!
I suggest do define a new type (named "set" for example) that can be defined as:

public set SetName: SetType
{
     elem1 = value1,
     elem2 = value2,
     elem3 = value3
}

SetType can any numeric type, char, string, datetime or a valueTupe.
Variables defined from the 'SetName' type must refuse to accept any value that is not defined within the set, and the compiler rises an error (enums can accept numbers that are nor defined in the enum!). value1 should be the default value of the set, or we can use a <default> attr before one of the itmes to make it the default value. We can use the `default' keyword to inithialize the set.

Ex:
```
public set Win: string
{
      Win7 = "Windows 7",
      WS2016 = "Windows Server 2016",
      XP = "Windows XP"
}
```

```
if (GetOPName( ) == (string)Win.XP)
{
   // Note: it will be better to convert Win.XP to string implicitly.
}

Win w7 = default;
w7 = "anty win"; // ERROR
```

**Comment by HaloFour** [comment] 2019-02-16 21:20
https://github.com/dotnet/csharplang/issues/113

**Comment by Thaina** [comment] 2019-02-18 07:37
#144

**Comment by TonyValenti** [comment] 2019-02-18 08:47
You can already do something pretty close to this.  For example, take a look at System.Drawing.Colors or System.Windows.Media.Brushes.

**Comment by MohammadHamdyGhanem** [comment] 2019-02-18 09:54
@TonyValenti
I use that, but I can't find a way to make intellisense offer auto complete from the helper structure, nor to force the type to refuse any other value other than those of the helper structure.

**Comment by TonyValenti** [comment] 2019-02-18 10:12
@MohammadHamdyGhanem -
1.  I'm not sure about the intellisence option but you might look at how WPF does it.
2.  To refuse other values, I make the constructor internal and do something like this (this keeps other assemblies from extending it but doesn't protect you against yourself.  Not perfect but not a bad compromise!):
````

public abstract class MockEnum {

  public string Value {get; private set;}

  internal MockEnum(string Value){
    this.Value = Value;
  }

}

public static class MockEnums {
  public MockEnum Red {get; private set;} = new MockEnum("Red");
  public MockEnum Green {get; private set;} = new MockEnum("Green");
  public MockEnum Blue {get; private set;} = new MockEnum("Blue");
}

````

**Comment by MohammadHamdyGhanem** [comment] 2019-02-18 10:43
Yes, I did something like that here:
https://github.com/MohammadHamdyGhanem/Verex/blob/master/Verex/CharClasses/Escapes.cs
And I merge the type and the helper so the type itself has the predefined values.

**Comment by YairHalberstadt** [comment] 2020-10-22 09:09
Closing as duplicate of #113

**Closed by YairHalberstadt** 2020-10-22 09:09 UTC
