### ISSUE TITLE
[Proposal] where expression

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/csharplang#3701] opened 2020-07-17 03:00 UTC
It is recommended to add a WHERE expression. The purpose of the new expression is to allow an expression in the constraint operator to be evaluated as a value.Like the usual operator (+-*/%)

```csharp
public class Foo {
    public static T add<T> (T a, T b) where [T + T] {
        return a + b;
    }
}
public class Foo1 {
    public static T opera<T> (T a, T b) where [T + T], [T - T], [T * T, [T / T], [T % T] {
        return a + b;
    }
}



Foo.add (1, 2); // compile success
Foo.add (1.2, 2.6); // compile success
Foo.add (new object (), new object ()); // compile failure

public class Bar {
    public int val = 5;
    public static Bar operator + (Bar a, Bar b) {
        return new Bar { val = a.val + b.val };
    }
}
Foo.add (new Bar (), new Bar ()); // compile success

public class Bar1 {
    public int val = 5;
    public static Bar1 operator - (Bar1 a, Bar1 b) {
        return new Bar1 { val = a.val - b.val };
    }
}
Foo1.opera (new Bar1 (), new Bar1 ()); // compile success
Foo.add (new Bar1 (), new Bar1 ()); // compile failure
```

Existing problem: There is no constraint that can directly make T type do mathematical operation, so it must be cast to dynamic, but cast or method directly accept dynamic type, which may make the type that cannot do mathematical operation can also be passed as a parameter, unable to check the code statically

the proposal can fix this problem

**Comment by yaakov-h** [comment] 2020-07-17 03:30
Seems like something better solved by Shapes (#164).

**Comment by juliusfriedman** [comment] 2020-07-17 03:31
How about a little something different here cause I sorta like this...

```c#
public class Foo {
    public static T add<T> (T a, T b) where T : [virtual] operator(+, -, *, /, %)
        return a + b;
    }
}
public class Foo1 {
    public static T opera<T> (T a, T b) where  [virtual] operator(+, -, *, /, %)
        return a + b;
    }
}
```

**Comment by juliusfriedman** [comment] 2020-07-17 03:32
> Seems like something better solved by Shapes (#164).

Or Roles right?

**Comment by fawdlstty** [comment] 2020-07-17 03:42
> where T : [virtual] operator(+, -, *, /, %)
@juliusfriedman how to recognition `i++` or `++i`？

**Comment by 333fred** [comment] 2020-07-17 04:08
https://github.com/dotnet/csharplang/issues/1711 is the current issue for static interface members and roles, which is what we're looking at for this space. This issue itself is mostly a duplicate of https://github.com/dotnet/csharplang/issues/3333, so I'm going to close it out and direct discussion to one of those two.

**Closed by 333fred** 2020-07-17 04:08 UTC
