### ISSUE TITLE
out variables and using

### ISSUE THREAD

**Issue by jimsnab** [dotnet/csharplang#3798] opened 2020-08-15 21:37 UTC
Can using be added to out?

```
public void MyMethod(string path)
{
    _CreateImage(using out var image);
    image.Save(path, ImageFormat.PNG);
}

void _CreateImage(out Image image)
{
    image = new Image();  // IDisposable
    ... code to draw the image ...
}
```

**Comment by jnm2** [comment] 2020-08-15 21:59
Duplicate of #3544

**Comment by jnm2** [comment] 2020-08-15 22:02
This is very close to the alternative proposal in #3544, only this is the one we all liked, `using out var`, rather than `dispose out var` or implicitly `out var` which got a lot of downvotes.

**Comment by mpolicki** [comment] 2020-08-16 01:43
Actually, the alternative proposal in #3544 was to "Introduce a mechanism for the programmer to signal that an `IDisposable` `out` parameter discard should be disposed of", and a `dispose` keyword was merely an example of how that could be done. Also `dispose out var` was not suggested, but `dispose out _` which would signal that the programmer wants to discard the value and call `Dispose` on it.
I wonder if everyone just skimmed that proposal.

**Comment by theunrepentantgeek** [comment] 2020-08-16 06:52
I don't believe a new issue is needed simply to suggest an alternative syntax for an existing feature suggestion. All that's achieved is to split discussion across two (or more) related issues, making it harder to follow.

**Closed** 2020-12-08 14:00 UTC
