### ISSUE TITLE
Feature Request: 'Safe Invocation' operator [Discussion] [Proposal]

### ISSUE THREAD

**Issue by tangelov** [dotnet/csharplang#2200] opened 2019-02-06 13:48 UTC
Hi guys,

I propose an extension to the 'Safe Navigation' `?` operator. If the nested expression does not have a value the parent expression would evaluate to `null` without calling the method e.g:

Given we have a method signature `int DoStuffAndGetValue(int arg)`

The new syntax would be used like so `var a = DoStuffAndGetValue(parent?.child.child?)`

Such an operator would avoid the need of assigning a variable with `parent?.child.child?` or repeating the code with a ternary operator. It looks like a natural extension of the 'Safe Navigation' operator to me.

Regards,
Teodor

**Comment by HaloFour** [comment] 2019-02-06 13:55
Here's a relevant discussion on this subject that happened on the Roslyn repo:

https://github.com/dotnet/roslyn/issues/5961

**Comment by jnm2** [comment] 2019-02-06 22:35
Duplicate of https://github.com/dotnet/csharplang/issues/842, very close to https://github.com/dotnet/csharplang/issues/433.

**Comment by YairHalberstadt** [comment] 2020-10-21 12:23
Closing as duplicate of #843 and https://github.com/dotnet/csharplang/discussions/433

**Closed by YairHalberstadt** 2020-10-21 12:23 UTC
