### ISSUE TITLE
Allow "implements" keyword for interface implementation

### ISSUE THREAD

**Issue by liamlim** [dotnet/csharplang#3618] opened 2020-06-26 12:19 UTC
I am proposing change of C# syntax which would allow `implements` keyword for an interface method implementation. 

**Reasoning:**
Why do I propose this change? We have many interface definitions during a development phase and methods get added and removed from and into interfaces. Every such change needs careful lookup for all interface implementations and fixing it up so we don't get dead code. Right now we don't get any alert after removing a method or changing it's signature which is not ideal solution because we should be alerted about method implementations. We need to find all interface implementations and find a method which is no longer valid (it's not that easy) and then check if everything is still valid.

**Proposed code**
```
interface IA 
{
  void f_1();
  void f_2();
}

class A : IA
{
  public implements void f_1() => ... // 1
  public void f_2() => ...
}

class B : IA 
{
  public void f_1() => ...
  public void f_2() => ...
}
```

If we decide to refactor code in this code sample and remove method f_1 from an interface IA then we get exactly one compile time error (line 1) because we opted in for an error if someone removes a method from an interface which we implement. On the other hand if we decide to remove method f_2 from interface IA then we don't get any compile time error because we haven't used implements keyword for either of it's implementations.

Note that we don't have to check all implementations of an interface IA. We get an error exactly on places which we want to fix (typically remove method and move it to other place in a code).

**Drawbacks**
Methods should not be removed from an interface once we publish it. We all agree with that because we cannot just change contract which our customers use. This feature is solely about development phase before we publish an interface and refactor it over and over again until we are happy with our definition. I am pretty sure that proposed change would boost development phase and make developers code more and less trying to find correct place to fix something.
  The only drawback I can see is an implementation cost of Roslyn team. Once this feature is in a language no one has to use it if they don't want so there is no drawback in my opinion.

**Comment by HaloFour** [comment] 2020-06-26 12:26
This could be done with an analyzer and a custom attribute:

```cs
public class C : I {
    [Implements(typeof(I))]
    public void M() { }
}
```

If the analyzer detects a method marked as implementing a specific interface and either the class doesn't implement the interface or the method doesn't implicitly override an interface member it can emit an error diagnostic.

**Comment by 333fred** [comment] 2020-06-26 15:11
Closing as a duplicate of https://github.com/dotnet/csharplang/issues/3510, with a different keyword. Feel free to suggest a different keyword in that issue.

**Closed by 333fred** 2020-06-26 15:11 UTC
