### ISSUE TITLE
[Proposal]: Extend standalone discard to support using declarations

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/csharplang#4170] opened 2020-11-24 01:43 UTC
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

As a modern C# developer, I'd like to leverage the [standalone discard](https://docs.microsoft.com/dotnet/csharp/discards#a-standalone-discard) syntax in conjunction with `using` declarations. This would allow the following:

```csharp
using _ = SomeDisposable();
```

## Motivation
[motivation]: #motivation

When working with implementations of the `IDisposable` interface, where you want to ensure that it's disposed of, but do **_not_** need actually need a reference to the object itself - you can use the following syntax:

```csharp
using (SomethingDisposable())
{
}
```

Sometimes you may even write this differently, depending on your style preferences:

```csharp
using (IDisposable _ = SomethingDisposable())
{
}
```

In the preceding two examples, the `_` is not actually a discard, but rather the variable named `_`.

Or with `using` declarations:

```csharp
using IDisposable _ = SomethingDisposable();
```

Sometimes when writing modern C#, it is nice to leverage true discard functionality. It would be great if the standalone discard syntax was extended to support `using` declarations.

For example, we could write this:

```csharp
using _ = SomethingDisposable();
```

## Detailed design
[design]: #detailed-design

[Example sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoE7ABgAIBJAEQEsoAHAeygmABs5KB9SgLyUAdnADulBszYduACgCUAbhIkA9GsoBVYQGMWYMHGEx1min0Ejxkxq3Zc4ilaWJ5b0h90ogaU+7JwJADeJJThlNgAzJEALB72TgphEaHEEZQAviSZQA=)

```csharp
using System;

using IDisposable _ = new Disposable();

// Uncomment
// using _ = new Disposable();

class Disposable : IDisposable
{
    public void Dispose()
    {
    }
}
```

## Drawbacks
[drawbacks]: #drawbacks

Nothing comes to mind.

## Alternatives
[alternatives]: #alternatives

Nothing comes to mind.

## Unresolved questions
[unresolved]: #unresolved-questions

From what I could tell, this doesn't currently exist.

**Comment by jnm2** [comment] 2020-11-24 01:50
Duplicate of https://github.com/dotnet/csharplang/issues/2235 which is currently being championed.

**Closed by jnm2** 2020-11-24 01:50 UTC
