### ISSUE TITLE
Optional type information on local constants.

### ISSUE THREAD

**Issue by davor-skontra** [dotnet/csharplang#2713] opened 2019-08-06 11:24 UTC
At the moment it is possible to prefix a **local** variable with var and the type information is inferred from the assignment:

For example:

```csharp
private void SomeMethod() {
    var foo = 1;
}
```

However when declaring local constants it is necessary to also write a type. Like here 

```csharp
private void SomeMethod() {
   const float baz = 2f;

   var foo = 1;
}
```

This feels a bit inconsistent. Maybe `const baz = 2f;` should be allowed for local constants, that way we could write

```csharp
private void SomeMethod() {
    const baz = 2f;

    var foo = 1;
}
```

This would be both more constant and convenient. Additionally it would encourage using immutable values when possible.

**Comment by ufcpp** [comment] 2019-08-06 11:52
https://github.com/dotnet/csharplang/issues/106

**Comment by Richiban** [comment] 2019-08-06 16:08
See also https://github.com/dotnet/csharplang/issues/188 which would allow `readonly` locals (with a shorthand for `readonly var`) that would be applicable in all cases, not just constants.

**Comment by DavidArno** [comment] 2019-08-07 08:48
And further, as per the discussion in #188, using `let` to be another way of expressing `readonly var` allows us to then say:
```cs
private void SomeMethod() 
{
   let baz = 2f; // readonly, ie constant
   let bar = new C(); // readonly, ie constant
   var foo = 1; // mutable
}
```
thus we get a consistent way of expressing local "constants" for all types, not just those allowed with the `const` keyword.

**Comment by johnkellyoxford** [comment] 2019-08-09 08:05
Personally I don't see the value in this. Constant locals must be of type `bool, byte, sbyte, ushort, short, uint, int, ulong, long, float, double, decimal, char, string`. None of these are particularly long or complex keywords, and const modifier isn't used anywhere near as regularly as non const locals, so saving ~5 chars doesn't seem worth it

**Comment by HekiShavik** [comment] 2019-10-30 08:58
But @john-h-k take a look at enums then:

`const TravellerBase.TravellerType typeFilter = TravellerBase.TravellerType.Adult | TravellerBase.TravellerType.Youth;`

versus

`const typeFilter = TravellerBase.TravellerType.Adult | TravellerBase.TravellerType.Youth;`

It's definitely worth it in my oppinion.

**Comment by YairHalberstadt** [comment] 2020-11-03 10:22
Closing as duplicate of #106

**Closed by YairHalberstadt** 2020-11-03 10:22 UTC
