### ISSUE TITLE
Add nullability check operator (using "bang" operator)

### ISSUE THREAD

**Issue by neoaisac** [dotnet/csharplang#3779] opened 2020-08-06 06:54 UTC
Instead of:
```
if (variable == null) throw new ArgumentNullException(nameof(variable));
```

Write:
```
variable!;
```

**Comment by 333fred** [comment] 2020-08-06 06:57
Duplicate of https://github.com/dotnet/csharplang/issues/2145. Closing out.

**Closed by 333fred** 2020-08-06 06:57 UTC
