### ISSUE TITLE
[Proposal] (Un)checked arithmethic operators

### ISSUE THREAD

**Issue by JustNrik** [dotnet/csharplang#2709] opened 2019-08-02 03:07 UTC
Currently, if we wanted to define a struct that behaves like a sort of primitive type, let's say... `Int24`, we are currently unable to define how arithmethic with them behave on (un)checked context.

Example:

```cs
public readonly struct UInt24 
{
    public const uint MaxValue = 0xFFFFFF;
    private readonly uint _value;
    public UInt24(uint value) { ... }
    // This method must throw an exception if overflow
    public static UInt24 checked operator +(UInt24 left, UInt24 right)
    {
        var value = left._value + right._value;
        if (value > MaxValue)
            throw new OverflowException();
        return new UInt24(value);
    }
    // If a (un)checked operator is defined, the other must be defined as well 
    // just like how == and != works
    public static UInt24 unchecked operator +(UInt24 left, UInt24 right)
    {
        return new UInt24((left._value + right._value) % (MaxValue + 1));
    }
}
```

**Comment by ufcpp** [comment] 2019-08-02 04:29
https://github.com/dotnet/csharplang/issues/686

**Comment by YairHalberstadt** [comment] 2020-11-02 08:58
Closing as duplicate of #686

**Closed by YairHalberstadt** 2020-11-02 08:58 UTC
