### ISSUE TITLE
Creating global aliases/Type abbreviations: using global Directive

### ISSUE THREAD

**Issue by bugproof** [dotnet/csharplang#2488] opened 2019-05-06 08:25 UTC
There's no suitable alternative for `typedef` from C++. My proposition is to add `using global` directive that will allow defining global aliases:

so instead of writing this:

```csharp
public class MyAliasForGenericType : GenericType<object>
{
// constructors...
...
}
```

we could write this:

```csharp
using global MyAliasForGenericType = GenericType<object>;
using global MyNumber = int;
```
(we could define this in file like Aliases.cs or just below the type we're creating an alias for)

The problem with the first approach is that we can't implicitly convert from `GenericType<object>` to `MyAliasForGenericType`.

Today aliases can be used but only in the scope of the file, they're defined in. With `using global` it would be available everywhere. It would be great when access modifier could be set for an alias e.g. `internal`, or some attribute that controls the visibility.

```csharp
internal using global MyAliasForGenericType = GenericType<object>;
```

or

```csharp
using global internal MyAliasForGenericType = GenericType<object>;
```

or maybe something like

```csharp
internal MyAliasForGenericType = GenericType<object>;
internal MyNumber = int;
```

similar to how F# does it https://fsharpforfunandprofit.com/posts/type-abbreviations/

**Comment by svick** [comment] 2019-05-06 09:07
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/1170, https://github.com/dotnet/csharplang/issues/410 and https://github.com/dotnet/csharplang/issues/259.

**Comment by VBAndCs** [comment] 2020-03-25 13:55
This will be more powerful if also allows generic aliases #3309.

**Comment by YairHalberstadt** [comment] 2020-10-26 12:55
Closing as duplicate of #1170, #410 and #259.

**Closed by YairHalberstadt** 2020-10-26 12:55 UTC
