### ISSUE TITLE
Explicit access to auto implemented property's backing field

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#2011] opened 2018-11-16 17:27 UTC
With an auto implemented property the anonymous backing field is inaccessible but it would be neat if we could get at this.

Consider a class (more or less a POCO)

```
public class Grade : SomeBase
{
   public Grade (string source):base(source) 
   {

   }
   public int UserID {get; private set;}
   public string Name {get; private set;}
   public int Age {get; private set;} 
}
```

The pattern in this case that the base class contains a constructor that contains logic to analyze the `source `and then use reflection to populate the properties of the derived class (not all details are here in this example).

The base exposes a bool property `Valid `set to true if all fields are parsed fine or false if one or more fields could not be parsed/populated.

It would therefore be neat if we could write this derived class like this:

```
public class Grade : SomeBase
{
   public Grade (string source):base(source) 
   {

   }
   public int UserID {get { if (!Valid) throw new InvalidOperationException(<whatever>); return field  }; private set;}
   public string Name {get; private set;}
   public int Age {get; private set;} 
}
```

In which `field `is a new keyword representing the backing field for the property. Don't dwell on the example here, but on the feature itself.

Thoughts?

**Comment by svick** [comment] 2018-11-16 17:31
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/140.

**Comment by jnm2** [comment] 2018-11-16 19:38
@MadsTorgersen The points made in the comment at https://github.com/dotnet/csharplang/issues/140#issuecomment-368590469 have not had acknowledgement from any LDT member. Meanwhile, issues asking for backing field sugar are always among the most frequent requests and folks' appetite for it seems to be snowballing.

Would you please take this proposal to a meeting, or let us know what you need from us before doing so?
We would be grateful!

**Comment by jnm2** [comment] 2020-04-04 12:58
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md

**Comment by YairHalberstadt** [comment] 2020-10-19 11:22
Closing as duplicate of #140.

**Closed by YairHalberstadt** 2020-10-19 11:22 UTC
