### ISSUE TITLE
[Proposal]: using aliases for function pointers

### ISSUE THREAD

**Issue by facebamm** [dotnet/csharplang#4285] opened 2020-12-30 11:43 UTC
* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

```csharp
using T = delegate*<int, int, int, void>;
```

## Motivation
[motivation]: #motivation

Language consistency. Without this syntax, you cannot give function pointer names either and the cast from any pointer into a function pointer can make your code hard to read, which is a big downside.

**Comment by 333fred** [comment] 2020-12-30 20:31
I'm going to close this as a duplicate of https://github.com/dotnet/csharplang/issues/1239. That issue is about letting both generic type parameters and language keywords be used in using aliases, and I would expect that to cover function pointers as well.

**Closed by 333fred** 2020-12-30 20:31 UTC

**Comment by CyrusNajmabadi** [comment] 2020-12-30 21:08
Yes.  I'll test this to make sure this works.

**Comment by facebamm** [comment] 2020-12-30 21:24
Does it work?
