### ISSUE TITLE
Proposal: Friendship

### ISSUE THREAD

**Issue by realSmushyTaco** [dotnet/csharplang#3437] opened 2020-05-08 08:14 UTC
I think the friend keyword (Like C++ implements it) perfectly fits in to OOP. Some people say it's breaking the rules but that's just wrong and here's why:

You can achieve the exact same thing with nested classes the only difference is nested classes are a more messy less readable implementation that takes a little longer to set up while using friendship is a clean easy to read and use implementation that's quick to set up and uses less lines of code. So how is it breaking the rules of OOP when you can do the exact same thing with nested classes which is OOP?

From what I've seen people say it isn't a language feature because of the reason that it isn't OOP but from what I've seen that's just flat out incorrect so why not add friendship as a language feature?

**Comment by svick** [comment] 2020-05-08 08:35
This is a duplicate of https://github.com/dotnet/csharplang/issues/2073.

**Closed** 2020-05-08 08:43 UTC
