### ISSUE TITLE
Disambiguate static class selection by method overload resolution

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#2963] opened 2019-11-15 13:37 UTC
I don't think the example below needs to be an error. As a bonus, it's a relatively easy way to allow "static extension method/property" like behavior, though I don't want to group this directly into that proposal because I think this should be allowed regardless of whether "extension everything" happens or not as it's a slightly different issue...this is all about removing an unnecessary ambiguity. Apparently F# already does exactly this.

```c#
using NS1;
using NS2;

namespace NS1
{
    public static class StaticClass
    {
        public static int SomeNumber { get; }
        public static void Method(int x) { }
    }
}

namespace NS2
{
    public static class StaticClass
    {
        public static string SomeString { get; }
        public static void Method(string x) { }
    }
}

namespace App
{
    class Program
    {
        void Main()
        {
            StaticClass.Method(3); // Error: `StaticClass` is an ambigious reference
            string value = StaticClass.SomeString; // Error: `StaticClass` is an ambigious reference
        }
    }
}
```

I think the compiler can be smart enough to check valid overloads on both static classes and disambiguate which one should be used based on overload selection when possible. Likewise, if you access a property then the class should be selected based on the existence of that property.

**Comment by YairHalberstadt** [comment] 2020-11-11 09:56
Closing as duplicate of https://github.com/dotnet/csharplang/issues/1988

**Closed by YairHalberstadt** 2020-11-11 09:56 UTC
