### ISSUE TITLE
available readonly keyword beyond constructor calls

### ISSUE THREAD

**Issue by Shpendicus** [dotnet/csharplang#3806] opened 2020-08-18 16:50 UTC
## Background and Motivation

The Idea is to enable the safety and explicit expression this keyword already gives to types beyond constructor initialization. 
As known, alot of Frameworks have a _not-constructor-based-Initialization_ API which will doesnt allow the benefit of a readonly field to be declared in such functions.

## Risks

I would like to hear from you ppl and what you think about :)
Best regard

**Comment by svick** [comment] 2020-08-18 19:06
The formatting problems make this issue really hard to understand, but I *think* this is pretty much a duplicate of https://github.com/dotnet/csharplang/issues/348 and https://github.com/dotnet/csharplang/issues/1296.

**Comment by HaloFour** [comment] 2020-08-18 19:06
This proposal seems to read like it's requesting `init` properties?  The text of the proposal is incredibly hard to read and is really poorly formatted.

**Comment by spydacarnage** [comment] 2020-08-18 19:26
It's either that, or the ability to write to readonly variables in blocks
of code called by the constructor (init methods, maybe)?

**Comment by Shpendicus** [comment] 2020-08-23 17:58
Sry for this late answer, i am not at home this week (and b4) so couldnt write something.,.

The Idea is just, to make the readonly keyword as it is right now, ALSO available for using it in NON-constructor based init Methods, because right now you ONLY can assign values it in constructors or directly in its variable declaration but I want to make this possible:

`
public readonly int myReadOnlyField;

public void API_InitCall()
{
    myReadOnlyField = ComputeSomeShitHere(....)   +  someRandomValue;  //just as example..
}
`
This would allow to use the full power of readonly BEYOND constructors since many API's/Engines/Framworks use  "NON-CONSTRUCTOR-BASED-INITIALIZATION" so making use of readonly there would be awesome. And ofc, when you wanna reassign
"myReadOnlyField " 3 methods later somewhere it wont work and the compiler throws error. Thats the idea ,

**Comment by HaloFour** [comment] 2020-08-23 18:46
This should be covered by `init` methods which are likely to make it into C# 10.0 towards the end of next year:

https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-15.md#init-methods

**Closed** 2020-08-24 23:23 UTC

**Comment by Shpendicus** [comment] 2020-08-25 10:54
> This should be covered by `init` methods which are likely to make it into C# 10.0 towards the end of next year:
> 
> https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-15.md#init-methods

But tbf, could be implemented in C#9.0 actually, why they wait so long?

**Comment by HaloFour** [comment] 2020-08-25 12:03
@Shpendicus 

> But tbf, could be implemented in C#9.0 actually, why they wait so long?

Can't be implemented without a design, and that design has not happened yet.  The notes point out the issues that such a design would have to address.  With C# 9.0 relatively around the corner and records being a part of that release it was more important to nail down the concerns of `init` properties, but they did intentionally leave the door open to explore `init` methods.  Time is a premium and language design is a long and arduous process.
