### ISSUE TITLE
Proposal: local fields & properties

### ISSUE THREAD

**Issue by LegoCylon** [dotnet/csharplang#2993] opened 2019-11-28 01:14 UTC
Local functions have helped to limit the leaking of implementation details into the enclosing type. 

I think there's a corollary case to be made for fields & properties which would be initialized just once per instance and are only visible within the body of the declaring function. Ideally these should be capable of being static & non-static like other fields & properties.

Static example:
```csharp
public static class MathUtils {

    public static uint MemoizedSum (uint i) {

        // partial indicates that this is a local field, in this case it is also static
        partial static readonly List<uint> s_sums = new List<uint>();

        if (s_sums.Count <= i) {
            s_sums.Add(i + i > 0 ? MemoizedSum(i - 1) : 0);
        }

        return s_sums[i];

    }

}
```

Non-static example:
```csharp
public class Smallest {

    public float Evaluate (float value) {

        //  partial indicates that this is a local property
        partial float Result { get; set; } = float.MaxValue;

        Result = Result < distance ? Result : distance;

        return Result;
    }

}
```

Closing thoughts:
- There could be some confusion about using partial in this manner, particularly if the type itself isn't required to be designated as partial (I think there's pros and cons to that). I'm not beholden to partial; it just seemed like the closest choice without requiring a new keyword.
- When used for memoizing as above, there's no intrinsic ability to reset the field or property contents (i.e. if you wanted to clear the field in MathUtils.MemoizedSum or reset the property in Smallest.Evaluate), but this is solvable by using sentinel values or additional (likely defaulted) parameters indicating whether a reset should happen.
- In terms of implementation, I think this could be implemented as syntactic sugar for standard fields & properties so long as the local fields & properties are given unpronounceable names.

**Comment by Joe4evr** [comment] 2019-11-28 01:22
Duplicate of #832.

**Comment by LegoCylon** [comment] 2019-11-28 01:24
There's certainly some overlap with #832, but I wouldn't consider it a duplicate since it covers non-static fields & properties.

**Comment by HaloFour** [comment] 2019-11-28 02:01
> I think there's a corollary case to be made for fields & properties which would be initialized just once per instance and are only visible within the body of the declaring function.

Fields maybe, but properties?  That seems like it would be a curiosity at best.  Your example wouldn't be any different if you had used a field instead.

**Comment by LegoCylon** [comment] 2019-11-28 02:21
> Fields maybe, but properties? That seems like it would be a curiosity at best. Your example wouldn't be any different if you had used a field instead.

Agreed, I just didn't see a reason to exclude them.

**Closed** 2019-12-02 00:42 UTC
