### ISSUE TITLE
[Propousal] Enhancement for == operator or Explicit reference equality

### ISSUE THREAD

**Issue by redradist** [dotnet/csharplang#3602] opened 2020-06-22 21:41 UTC
Sometimes reading `C#` code is difficult due to context ...

Consider the following scratch code example:
```csharp
...
    if (name == defaultName) 
...
```

Without knowledge of type `name` and `defaultName` it is not obvious what would be comparison by reference (class) or by value (struct) ...

I like how the same is made in `Python`:
```python
...
    if name == defaultName: # User defined operator ==
...
```
I know exactly that it is user defined `==` operator

and in `Python` checking by reference is done:
```python
...
    if name is defaultName: # Checking by reference
...
```
Similar in `Kotlin`:
```kotlin
...
    if (name == defaultName) // User defined operator ==
...
```
```kotlin
...
    if (name === defaultName) // Checking by reference
...
```
All modern languages have different operator for checking be reference because it improves readability ;)

Maybe it is time to add feature `explicit reference equality` ?
```csharp
...
    if (name == defaultName) // Compiles only if there is user-defined == operator
...
```
```csharp
...
    if (name is defaultName) // Checking by reference equality only if this types are `class`
...
```

It would make code more readable and prevent unpredictable behavior ;)

**Comment by HaloFour** [comment] 2020-06-22 21:50
I don't understand what you're proposing here.  You seem to imply that `==` and `is` would mean the same thing?  How does that help you understand whether or not `==` is invoking an overloaded operator?

**Comment by PathogenDavid** [comment] 2020-06-22 21:51
> ```cs
> ...
>     if (name is defaultName) // User-defined == operator
> ...
> ```

Pretty sure the comment here is a typo.

**Comment by redradist** [comment] 2020-06-22 21:55
> 
> 
> I don't understand what you're proposing here. You seem to imply that `==` and `is` would mean the same thing? How does that help you understand whether or not you are invoking an overloaded operator?

I am proposing to add some flag like for `nullable` reference types that will:
```csharp
...
    if (name == defaultName) // Compiles only if there is user-defined == operator
...
```
and if user what reference equality:
```csharp
...
    if (name is defaultName) // Checking by reference equality only if this types are `class`
...
```

**Comment by redradist** [comment] 2020-06-22 21:57
> 
> 
> > ```cs
> > ...
> >     if (name is defaultName) // User-defined == operator
> > ...
> > ```
> 
> Pretty sure the comment here is a typo.

Yeah, you are right ;)
Fixed

**Comment by HaloFour** [comment] 2020-06-22 21:57
@redradist 

You're proposing both a new dialect and a **massive** breaking change to the language.  I don't think it's exaggerating to state that there's no chance that will be considered.

**Comment by redradist** [comment] 2020-06-22 22:00
@HaloFour 
> 
> 
> @redradist
> 
> You're proposing both a new dialect and a **massive** breaking change to the language. I don't think it's exaggerating to state that there's no chance that this will be considered.

Only if user set the special flag, but it this flag is very helpful due to improved readability and therefore better code quality and maintainability

**Comment by HaloFour** [comment] 2020-06-22 22:03
@redradist 

> Only if user set the special flag

The language team has stated that they are not interested in creating dialects within the C# language.  The benefit to doing so is insanely high.  NRTs are the only feature to have met that threshold, and even that feature went to very great lengths to ensure that absolutely no code would change semantically as a result.  You're suggesting this because you have a stylistic preference and the result is breaking literally all code ever written in C# in the last 20 years.  It'll never happen.

**Comment by redradist** [comment] 2020-06-22 22:10
> 
> 
> @redradist
> 
> > Only if user set the special flag
> 
> The language team has stated that they are not interested in creating dialects within the C# language. The benefit to doing so has to be insanely high to justify it. NRTs are the only feature to have met that threshold, and even that feature went to very great lengths to ensure that absolutely no code would change semantically as a result. You're suggesting this because you have a stylistic preference and the result is breaking literally all code ever written in C# in the last 20 years. It'll never happen.

Again it will not break the all code !!
Only if user have set special flag ...

You've already created dialect with `nullable` reference type !? And only do to that it was proven by `Kotlin` that is deserve to be implemented and I respect it !!
`Kotlin` also has different operator for `user-defined` equality and `reference-equality` https://kotlinlang.org/docs/reference/equality.html
What you need proofs that this feature will be helpful ?

How language will evolve without breaking some other old paradigms or extending with dialect old behavior ?

**Comment by HaloFour** [comment] 2020-06-22 22:12
@redradist 

> Only if user have set special flag ...

Which creates a dialect, a no-no.

> You've already created dialect with `nullable` reference type !

Yes, but NRTs were considered important enough to warrant it.  Yet still, that flag doesn't change the behavior of **any** existing code, at all.

> How language will evolve without breaking some other old paradigms or extending with dialect old behavior ?

**Comment by redradist** [comment] 2020-06-22 22:16
> 
> It'll evolve in ways that don't break the language for the millions of people who use it.

It depends on what you are thinking `break the language` ...
Sometimes it is not possible to evolve the language without breaking something, even `Rust` break language with additions and it is cool, language follows the time ...

**Comment by PathogenDavid** [comment] 2020-06-22 22:18
I think it's much more viable to propose that `is` (or some other new syntax) means reference equality and you can use an analyzer to restrict `==` how you want.

**Comment by HaloFour** [comment] 2020-06-22 22:18
@redradist 

> Sometimes it is not possible to evolve the language without breaking something

Sure, if the impact is relatively small and the benefit is significant enough to justify it.  That is no where near the case here.

**Comment by redradist** [comment] 2020-06-22 22:23
> 
> 
> I think it's much more viable to propose that `is` (or some other new syntax) means reference equality and you can use an analyzer to restrict `==` how you want.

I like this idea, I think it would be cool !!

There are not many options:
1) `is`
2) `===` and `!==`

Seems like `2)` introduce also negation operator ;)

**Comment by yaakov-h** [comment] 2020-06-22 22:23
>  it is not obvious what would be compassion by reference (class) or by value (struct)

Assuming that "compassion" means "comparison", classes with overridden operators can also compare by value.

If you want to explicitly call out your reference comparisons, use `ReferenceEquals(a, b)`.

**Comment by HaloFour** [comment] 2020-06-22 22:24
@PathogenDavid 

That seems like a more reasonable approach.  I don't see `is` being reused here as the RHS resolves to a type even when there is an identifier in scope.

**Comment by HaloFour** [comment] 2020-06-22 22:25
Also, https://github.com/dotnet/csharplang/issues/540

**Comment by redradist** [comment] 2020-06-22 22:30
> 
> 
> Also, #540

This proposal is cool, but status is unknown ... seems like it stucks ... (

**Comment by jnm2** [comment] 2020-06-22 22:38
The breaking change of disallowing `==` can be removed and replaced with a custom analyzer that provides errors or warnings.

I have had the thought on a few occasions that an `is` operator as a shortcut for ReferenceEquals would be nice. It's rare.

**Comment by redradist** [comment] 2020-06-22 22:41
> 
> 
> The breaking change of disallowing `==` can be removed from the proposal and replaced with a custom opt-in analyzer that provides errors or warnings when `==` is used in a way you don't like. This would be equivalent to an opt-in flag.
> 
> I have had the thought on a few occasions that an `is` operator as a shortcut for ReferenceEquals would be nice. It's rare.

It is already discussed above ;)
And seems like we found compromise ;) I hope )))

**Comment by CyrusNajmabadi** [comment] 2020-06-22 23:57
> I am proposing to add some flag like for nullable reference types that will:

This is doable simply by writing an analzyer for your code to find and flag this.  No language change necessary.

**Comment by CyrusNajmabadi** [comment] 2020-06-23 00:00
Closing out as this is a request to create a new dialect of C# that would make existing *widely used* code illegal.  That would violate our back compat guarantees and would effectively never happen.  A good rule of thumb:

If your proposal is about introducing a rule/flag that makes a lot of existing code illegal because you don't like it, then the appropriate answer to that need is: write an analyzer to find and flag the pattern you do not like.

This is easy to write, easy to customize to exactly your needs (including potential exceptions you may end up finding).  And, best of all, can already be done today :)

**Closed by CyrusNajmabadi** 2020-06-23 00:00 UTC

**Comment by redradist** [comment] 2020-06-23 08:10
@CyrusNajmabadi 
> 
> 
> Closing out as this is a request to create a new dialect of C# that would make existing _widely used_ code illegal. That would violate our back compat guarantees and would effectively never happen. A good rule of thumb:
> 
> If your proposal is about introducing a rule/flag that makes a lot of existing code illegal because you don't like it, then the appropriate answer to that need is: write an analyzer to find and flag the pattern you do not like.
> 
> This is easy to write, easy to customize to exactly your needs (including potential exceptions you may end up finding). And, best of all, can already be done today :)

Why ? In comments above I agree that it would be also nice to have analyzer that will suggest the new syntax for `reference equality` like `is` or `===`

**Comment by HaloFour** [comment] 2020-06-23 11:55
@redradist 

The suggestion was you use an analyzer in your own projects to make it illegal to use `==` for reference equality.  You can then use `Object.ReferenceEquals` in its place.  Given how infrequent it is to explicitly want reference equality I don't imagine `===` or `is` will gain much traction as shorthand for it.

**Comment by PathogenDavid** [comment] 2020-06-23 16:05
Also #540 exists for that aspect, there's not much benefit of having two issues for the same feature.

**Comment by CyrusNajmabadi** [comment] 2020-06-23 17:41
> Why ?

Because there is no language change requested here anymore.

> In comments above I agree that it would be also nice to have analyzer

Right.  So that's entirely outside the purview of the language (or language repo).

**Comment by jnm2** [comment] 2020-06-23 21:37
@CyrusNajmabadi Isn't there still a request here for the `is` operator to be expanded to allow object instances on both sides?

**Comment by HaloFour** [comment] 2020-06-23 21:52
@jnm2 

Then it would be a dupe of #540.
