### ISSUE TITLE
[Proposal]: Multiple patterns - one computation branch

### ISSUE THREAD

**Issue by igor-tkachev** [dotnet/csharplang#7324] opened 2023-07-06 00:25 UTC
# Multiple patterns - one computation branch

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Allows for specifying a single computation branch for multiple patterns that include variable declarations.

```c#
switch (ex)
{
    case Multiply(Constant(0) e, _)             :            // 0 * e => 0
    case Multiply(_,             Constant(0) e) :            // e * 0 => 0
    case Multiply(Constant(1),   var e)         : return e;  // 1 * e => e
}
```

## Motivation
[motivation]: #motivation

The switch/case statement and pattern matching expression already support multiple patterns for a single computation branch, but only if the pattern does not include any variable declarations.

## Detailed design
[design]: #detailed-design

This should be allowed only if the number of variables and their types match.

```c#
switch (a)
{
    case B(C c, var e) :
    case D(E e, var c):
        Console.WriteLine($"{c} - {e}");
        break;
}
```
In this example, both variables `e` should have the same type, just like the variables `c`.

If necessary, the pattern can declare additional variables as follows:

```c#
switch (a)
{
    case B(C c, var e) :
    case D(E e) with C c = default :
    _ with C c = default, E e = default :
        Console.WriteLine($"{c} - {e}");
        break;
}
```
The same should be supported by pattern matching expression:

```c#
Console.WriteLine(a switch
{
    B(C c, var e)               =>
    D(E e) with var c = new C() => $"{c} - {e}"
});
```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved questions
[unresolved]: #unresolved-questions

**Comment by 333fred** [comment] 2023-07-06 00:55
Duplicate of https://github.com/dotnet/csharplang/issues/4018.

**Closed by 333fred** 2023-07-06 00:55 UTC
