### ISSUE TITLE
Allow parameters for the generic new() constraint

### ISSUE THREAD

**Issue by msedi** [dotnet/csharplang#1626] opened 2018-06-13 21:15 UTC
Currently we can only constrain the generic argument in class with the new() "classifier". 

```
public T Create<T>() where T : class, new()
{
  return new T();
}
```

The only problem is that in a lot of situations I need arguments on the class so I have to go with the Activator

```
public T Create<T>(params object[] obj) where T : class, new()
{
  return (T)Activator.CreateInstance(typeof(T), obj));
}
```

which cannot be checked at compile time. So if I want to force that a class to have at least a necessary constructor I can currently not enforce it. So I would suggest to extend the new() with a parameter list.

Example:
```
public T Create<T>(int a, int b) where T : class, new(int,int)
{
  return new T(a,b);
}
```

**Comment by Joe4evr** [comment] 2018-06-13 21:19
Duplicate of #769, #1574.

**Closed** 2018-06-13 21:45 UTC
