### ISSUE TITLE
Sum types

### ISSUE THREAD

**Issue by hez2010** [dotnet/csharplang#2469] opened 2019-04-26 01:40 UTC
Is there any way to write sum types (aka. Enum class, tagged union) in C#?
```haskell
data Weekday = Monday | Tuesday | .....
```

**Comment by HaloFour** [comment] 2019-04-26 01:49
There are proposals to add that to the language:

https://github.com/dotnet/csharplang/issues/113

**Comment by gulshan** [comment] 2019-04-30 03:46
Also see #399 for union types, not tagged union though.

**Comment by YairHalberstadt** [comment] 2020-10-26 11:33
Closing as duplicate of https://github.com/dotnet/csharplang/issues/113 / https://github.com/dotnet/csharplang/discussions/399

**Closed by YairHalberstadt** 2020-10-26 11:33 UTC
