### ISSUE TITLE
C# 9.0 proposal – 'with' statement for changing context

### ISSUE THREAD

**Issue by vova-lantsov-dev** [dotnet/csharplang#2580] opened 2019-06-03 22:12 UTC
Changing working context using
`with (variable) { ... }`
syntax

Instead of
```c#
class Foo
{
  void Bar()
  {
    // Do some work before

    var s = new StringBuilder();
    s.Append('1');
    s.Append('2');
    s.Append('3');
    s.Append('4');
    string result = s.ToString();

    // Do some work after
  }
}
```

I suggest to use
```c#
class Foo
{
  void Bar()
  {
    // Do some work before

    Console.WriteLine(this);
    // prints 'Foo'

    var s = new StringBuilder();
    string text;
    with (s)
    {
      Console.WriteLine(this);
      // prints 'System.Text.StringBuilder'

      Console.WriteLine(parent);
      // prints 'Foo'

      Append('1');
      Append('2');
      Append('3');
      Append('4');
      text = ToString();
    }

    Console.WriteLine(this);
    // prints 'Foo'
  }
}
```

Rules:
* `with` statement cannot contain another `with` statement
* `parent` keyword is used for accessing the parent (real) context
* `with` statement can be used for inline declaration
`with (var s = new StringBuilder())`
* we can still use variable name
```c#
with (s)
{
  s.Append('1');
}
```
* suddenly :) internal and private members are still hidden inside `with` statement if needed

Also some ideas:
1. `with` expression
```c#
string text = with (s)
{
  Append('1');
  Append('2');
  ToString();
  // return value of last call is used for assignment
};
```
or
```c#
string text = with (s)
{
  Append('1');
  Append('2');
  return ToString();
};
```

I think that first is better because it won't conflict with returning from parent method. The base concept for me is that `with` statement should work like `using` statement (it means that `return;` call will return from parent method), but assignment should work like `switch expression` does.
2. Reduce nesting (usage without brackets)
```c#
with s;
Append('1');
Append('2');
string text = ToString();
unwith;
```

**Comment by dm-CaT** [comment] 2019-06-03 22:22
From an example provided looks like call-chaining alternative.

```
var sb = new StringBuilder();
var text = sb
  .Append("Hello")
  .Append(" ")
  .Append("World")
  .ToString();
```

**Comment by vova-lantsov-dev** [comment] 2019-06-03 22:32
@dm-CaT you're right, but sometimes call-chaining is not available (for ex, when return type is not equal to initial type or when there are a lot of conditions between calls).

Thing I described above is already a part of Kotlin programming language.

**Comment by salarcode** [comment] 2019-06-04 00:13
Please don't awaken VB6

**Comment by TonyValenti** [comment] 2019-06-04 02:22
Here's a nice few extension methods that make With:
````
        public static T With<T>(this T o, params object[] pattern) => o;

        public static T With<T>(this T o, params Action<T>[] x) {
            foreach (var item in x) {
                item(o);
            }

            return o;
        }

        public static T With<T, U>(this T o, U u, params Action<U>[] x) {
            foreach (var item in x) {
                item(u);
            }

            return o;
        }
````

**Comment by vova-lantsov-dev** [comment] 2019-06-04 03:41
@TonyValenti completely not the same, isn't it?

**Comment by ufcpp** [comment] 2019-06-04 04:47
dup of https://github.com/dotnet/csharplang/issues/1534

**Comment by vova-lantsov-dev** [comment] 2019-06-04 05:41
@ufcpp my suggestion is a bit different because it's about context changing, not only shorthand spelling

**Comment by vova-lantsov-dev** [comment] 2019-06-04 07:58
One more sample

```c#
var message = new HttpRequestMessage();
with (message)
{
  Header.Add();
  Headers.Add();

  Content = ...
}
var resp = await http.SendAsync(message);
```

**Comment by MihaZupan** [comment] 2019-06-04 08:23
Out of all the suggestions, I like the "extended" object initializer best. I think everyone can see themselves using it.

**Comment by Joe4evr** [comment] 2019-06-04 08:33
> 
> 
> One more sample
> 
> ```cs
> var message = new HttpRequestMessage();
> with (message)
> {
>   Headers.Add();
>   Headers.Add();
> 
>   Content = ...
> }
> var resp = await http.SendAsync(message);
> ```

If you're `new`ing up right there, there's no need for any additional syntax:
```cs
var message = new HttpRequestMessage
{
    Headers = 
    {
        { "Key", "Value" }
    },
    Content = //...
};
var resp = await http.SendAsync(message);
```

**Comment by vova-lantsov-dev** [comment] 2019-06-04 10:42
@Joe4evr ok, let me add some conditions, and now atomic initialization cannot be used. I don't argue that this code can't be written in another way. But this is a good syntax sugar.

```c#
var message = new HttpRequestMessage();
with (message)
{
  if (authRequired)
    Headers.Add("Authorize", token);
  foreach (var (key, value) in earlierResponse)
    Headers.Add(key, value);

  Content = ...
}
var resp = await http.SendAsync(message);
```

**Comment by Korporal** [comment] 2019-06-04 14:58
> Changing working context using
> `with (variable) { ... }`
> syntax
> 
> Instead of
> 
> ```cs
> class Foo
> {
>   void Bar()
>   {
>     // Do some work before
> 
>     var s = new StringBuilder();
>     s.Append('1');
>     s.Append('2');
>     s.Append('3');
>     s.Append('4');
>     string result = s.ToString();
> 
>     // Do some work after
>   }
> }
> ```
> 
> I suggest to use
> 
> ```cs
> class Foo
> {
>   void Bar()
>   {
>     // Do some work before
> 
>     Console.WriteLine(this);
>     // prints 'Foo'
> 
>     var s = new StringBuilder();
>     string text;
>     with (s)
>     {
>       Console.WriteLine(this);
>       // prints 'System.Text.StringBuilder'
> 
>       Console.WriteLine(parent);
>       // prints 'Foo'
> 
>       Append('1');
>       Append('2');
>       Append('3');
>       Append('4');
>       text = ToString();
>     }
> 
>     Console.WriteLine(this);
>     // prints 'Foo'
>   }
> }
> ```
> 
> Rules:
> 
> * `with` statement cannot contain another `with` statement
> * `parent` keyword is used for accessing the parent (real) context
> * `with` statement can be used for inline declaration
>   `with (var s = new StringBuilder())`
> * we can still use variable name
> 
> ```cs
> with (s)
> {
>   s.Append('1');
> }
> ```
> 
> * suddenly :) internal and private members are still hidden inside `with` statement if needed
> 
> Also some ideas:
> 
> 1. `with` expression
> 
> ```cs
> string text = with (s)
> {
>   Append('1');
>   Append('2');
>   ToString();
>   // return value of last call is used for assignment
> };
> ```
> 
> or
> 
> ```cs
> string text = with (s)
> {
>   Append('1');
>   Append('2');
>   return ToString();
> };
> ```
> 
> I think that first is better because it won't conflict with returning from parent method. The base concept for me is that `with` statement should work like `using` statement (it means that `return;` call will return from parent method), but assignment should work like `switch expression` does.
> 2. Reduce nesting (usage without brackets)
> 
> ```cs
> with s;
> Append('1');
> Append('2');
> string text = ToString();
> unwith;
> ```

What if you were working with _two_ objects here, s1 and s2? You could only use "with" for one of these. If you even considered "with (s1, s2)" you'd be in trouble because in the enclosed block it would be impossible to disambiguate if the objects had any members with the same names.

**Comment by HaloFour** [comment] 2019-06-04 15:15
Javascript-style `with` is considered one of it's "Bad Parts" due to the ambiguity it creates in the language.  For example:

```cs
    with (s)
    {
      Console.WriteLine(this);
      // prints 'System.Text.StringBuilder'

      Console.WriteLine(parent);
      // prints 'Foo'

      Append('1');
      Append('2');
      Append('3');
      Append('4');
      text = ToString();
    }
```

What if `s` has a member called `Console`?  This makes the language significantly harder to read and reason about.  There are better versions of `with` out there, including the syntax adopted by VB.NET.  But even then I don't think that the feature is worth it.  You can already collapse the expression to a temporary variable with a short and simple name.

**Comment by vova-lantsov-dev** [comment] 2019-06-04 15:17
@Korporal you must not use it everywhere. If it doesn't solve your needs – just use something else instead.

**Comment by vova-lantsov-dev** [comment] 2019-06-04 15:27
@HaloFour I saw the next snippet of code in a similar issue:

```c#
with (s)
{
  .Console // property
  .Method1()
  Console.Write() // class
}
```

Looks like a simple trick for preventing the conflicts.

**Comment by vova-lantsov-dev** [comment] 2019-06-04 15:45
And, telling more, code above allows us to combine both parent and selected contexts. Now we can use:

```c#
class Foo
{
  public string Field;
}

class Bar
{
  string Field;

  void DoSmth()
  {
    // Some code before

    var foo = new Foo();

    with (foo)
    {
      Console.WriteLine(Field);
      // field of Bar class

      Console.WriteLine(.Field);
      // field of Foo class

      Field = "1";
      .Field = "2";
    }

    // Some code after
  }
}
```

**Comment by msedi** [comment] 2019-06-04 21:37
Pascal already had the `with` keyword, obviously some already thought about this a long time ago. Since some originators of C# where involved in Pascal it would be nice to hear their thoughts of why they didn't used it in C#.

In my example I also have a lot of parameters in need to prefix with the class name, especially in "copy constrcutors" or cloning, it would help a lot, but I agree that there might be things you have to think about. As an example here's some cloning where I'm not quite sure what should/will happen.


```
public class MyObject
{
  public int Value1;
  public int Value1;
}
...
public MyObject Clone()
{
  MyObject ClonedObject = new MyObject();

  with(this)
  {
    with (MyObject)
    {
      // Not clear here
      // Original Code:
      // MyObject.Value1 = this.Value1;
      // MyObject.Value2 = this.Value2;
      Value1 = Value1;
      Value2 = Value2;
    }
  }
}
```

Nevertheless, I would agree if there would be a better shorthand if you have an object already created and during the lifetime of the object you need to adjust many parameters, so the` {}` syntax would be nice if it would also work without `new`ing the object. Following looks a bit odd to me, so I would agree that the `with` keyword would make it more obvious.

MyObject obj = new MyObject();
...
obj 
{
  Value1 = 10;
  Value2 = 20;
}

**Comment by HaloFour** [comment] 2019-06-04 22:41
@msedi 

This was answered in a 2004 article from the "Ask a C# Designer" series, which unfortunately I've not been able to find.  This [post](https://devblogs.microsoft.com/csharpfaq/why-doesnt-c-have-vb-nets-with-operator/) by Jon Skeet is about as close as I could find.  From what I can recall the reason boils down to "why?" rather than "why not?", and it doesn't help that the syntax doesn't fit within existing C heritage for what that's worth.

Of course articles from 15 years ago aren't necessary relevant to today and C# currently has numerous features which were not accepted at that time, such as default parameters and static using.

**Comment by HaloFour** [comment] 2019-06-05 01:58
@msedi 

Found an archive of the page in question: http://web.archive.org/web/20051030105444/http://www.gotdotnet.com/team/csharp/learn/columns/ask.aspx

**Comment by msedi** [comment] 2019-06-05 19:42
@HaloFour: Thanks for the article. In the end I agree that the impact of having a `with `statement is not of such high relevance than for example having a `Range`.

For me, I have to deal a lot with structures with a large amount of parameter (approx. 200) per class it would be great to have a bit of assistance in not having to write

`ObjTarget.Property = ObjSource.Property`

on and on again for cloning, serialization and deserialization. For me, the syntax:

```
MyObject obj = new MyObject();
...
obj 
{
  Value1 = 10;
  Value2 = 20;
}

```
would be nice, but I have no good suggestion what would be the best style.

**Comment by Korporal** [comment] 2019-06-05 19:56
@msedi - This is probably not suitable for C# but it may be worth mentioning it. Some languages support a feature called "by name assignment". At that time there were no classes but conventional structures and these were often associated with file records and so on.

Here's what it would look like:

```cs
namespace ConsoleApp8
{
    class Program
    {
        static void Main(string[] args)
        {
            Source source = new Source();
            Target target = new Target();

            target = source by name;
        }
    }

    public class Source
    {
        public string Name;
        public TimeSpan Age;
        public int BookCount;
    }

    public class Target
    {
        public string Name;
        public TimeSpan Age;
    }
}

```
Only members who's names match will be assigned. As I say this is rooted in older languages and there were no reference copying really, everything was value based copies.

Also refactoring such code could easily lead to bugs and so on so the idea isn't immediately portable to C# but it might spawn some better ideas...

**Comment by Korporal** [comment] 2019-06-05 20:10
> @HaloFour: Thanks for the article. In the end I agree that the impact of having a `with `statement is not of such high relevance than for example having a `Range`.
> 
> For me, I have to deal a lot with structures with a large amount of parameter (approx. 200) per class it would be great to have a bit of assistance in not having to write
> 
> `ObjTarget.Property = ObjSource.Property`
> 
> on and on again for cloning, serialization and deserialization. For me, the syntax:
> 
> ```
> MyObject obj = new MyObject();
> ...
> obj 
> {
>   Value1 = 10;
>   Value2 = 20;
> }
> ```
> 
> would be nice, but I have no good suggestion what would be the best style.

@msedi 

What about analyzing the field assignment scenarios in more detail? If there is a common subset of fields that are always copied as a group, you could do several things.

Here's one (crude example but you get the idea)

```cs
using System;

namespace ConsoleApp8
{
    class Program
    {
        static void Main(string[] args)
        {
            Source source = new Source();
            Target target = new Target();

            target.SetFromSource(source);
        }
    }

    public class Source
    {
        public string Name;
        public TimeSpan Age;
        public int BookCount;
    }

    public class Target
    {
        public void SetFromSource (Source source)
        {
            this.Name = source.Name;
            this.Age = source.Age;
        }
        public string Name;
        public TimeSpan Age;
    }
}

```

Or if the things being copied happen to be value types, then you can do this (or at least leverage this ability)

```cs
using System;

namespace ConsoleApp8
{
    class Program
    {
        static void Main(string[] args)
        {
            Source source = new Source();
            Target target = new Target();

            target.common = source.common;
        }
    }

    public struct CommonFields
    {
        public string Name;
        public TimeSpan Age;
    }
    public struct Source
    {
        public CommonFields common;
        public int BookCount;
    }

    public struct Target
    {
        public CommonFields common;
    }
}

```

**Comment by msedi** [comment] 2019-06-06 21:00
@Korporal: In the end your suggested solution is that what I do, except that my types are immutable for the user of the structure, so having a public method `SetFromSource` does not work in my case.

Honestly, I'm not having big problems with my current implementation, but if the discussion is open here, I'm glad if things can be made easier.

**Comment by garyng** [comment] 2019-06-07 15:31
Dart has something called the _[cascade notation](https://dart.dev/guides/language/language-tour#cascade-notation-)_:

> ```dart
> querySelector('#confirm') // Get an object.
>  ..text = 'Confirm' // Use its members.
>  ..classes.add('important')
>  ..onClick.listen((e) => window.alert('Confirmed!'));
> ```
> [...] is equivalent to:
> ```dart
> var button = querySelector('#confirm');
> button.text = 'Confirm';
> button.classes.add('important');
> button.onClick.listen((e) => window.alert('Confirmed!'));
> ```

IMHO this is probably cleaner/less ambiguous than the `with` statement...

**Comment by WrongBit** [comment] 2019-06-25 10:07
I completely support "with" operator, but disagree with syntax inside - it MUST include dots before fields to make sure it doesn't intersect with other members (from outer scope). Maybe even "with" (totally misused by C# team) can be skipped in favor of Perl-like hieroglyphs :)
````
var a = new ClassA(params) <#
    .path = "123";
    SomeFunc(); // it's from outer scope!
    .OurFunc();// OK, it's from "a"
#>
````
Same with just existing object:
````
a <#
    .path = "123";
    .f1 = SomeFunc(); // SomeFunc() is from outer scope! That's why w/o dot
    .OurFunc();// OK, it's from "a"
#>
````

**Comment by MihaZupan** [comment] 2019-06-25 10:40
That looks too ugly IMO @WrongBit

**Comment by WrongBit** [comment] 2019-06-25 21:13
@MihaZupan If you look at any math formulae, they don't impress too. So what? I offer <# #>, you can offer better parents, maybe « and » :) Who care? Important is to implement AT LAST (after 15 years of nose inspection) operator "with".

**Comment by YairHalberstadt** [comment] 2020-10-28 08:46
CLosing as duplicate of #1534

**Closed by YairHalberstadt** 2020-10-28 08:46 UTC
