### ISSUE TITLE
Proposal: add byte type-literal b

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1482] opened 2018-04-25 15:22 UTC
Proposal: add byte type-literal b
C# has the 0B binary literal:
`var x = 0B1010;`
X will be integer.
It also will be useful if we use b as a type symbol for byte type like this:
```
var b = 12b;
var c = new[]{1b, 2b, 3b};
```
so C# can infer that b is a byte, and c is a byte array.
And as I proposed before in #1360, I hope to initialize the array like this:
`var c = {1b, 2b, 3b};
`

**Comment by svick** [comment] 2018-04-25 15:27
Pretty much a duplicate of https://github.com/dotnet/csharplang/issues/1058.

**Comment by MohammadHamdyGhanem** [comment] 2018-04-25 15:37
@svick 
Thanks. Is there a way to fine tune the search to look in the titles only?

**Comment by bondsbw** [comment] 2018-04-25 15:46
@MohammadHamdyGhanem Honestly I find Github search to just be frustrating.

What tends to work better is doing the search in Google and adding this term:

```
site:github.com/dotnet/csharplang
```

**Comment by MohammadHamdyGhanem** [comment] 2018-04-25 17:48
@bondsbw 
I agree, but I notice you find similar issues quicly, and I want to know is there some feature to do so.
I am told to use in:title qualifier in search box.

**Comment by jnm2** [comment] 2018-04-25 17:53
@bondsbw Isn't that `inurl:github.com/dotnet/csharplang`?

**Comment by bondsbw** [comment] 2018-04-25 19:18
@jnm2 ¯\_(ツ)_/¯

Seems to work.

**Closed** 2019-03-04 16:24 UTC
