### ISSUE TITLE
NuGet package for Range and Index

### ISSUE THREAD

**Issue by lostmsu** [dotnet/csharplang#3126] opened 2020-01-25 20:30 UTC
So C# 8 is released, and .NET Framework support EoL is 2029, so I am targeting .NET Standard 2.0 for most old and new libraries alike. Which also means I can't really use ranges or the new indexing because

> error CS0518: Predefined type 'System.Range' is not defined or imported

In the previous conversation about that topic it was mentioned, that `System.ValueTuple` NuGet support put an undue burden on the team and bloated the dependency list of many packages.

Well, I love the System.ValueTuple package. And I can assure you to a great length, that I would love Range and Index even more, because it is rarely that extreme performance is needed, but every day I'd take clean code over a mess of method calls with off-by-one errors.

So I urge you to reconsider the lack of a similar package. At the very least, put the types themselves there (which, BTW, would be 100% compatible with further additions, if you wish to add extra members supporting them to the rest of the framework). At least it would be possible to implement indexing for our own collections.

Previous issue for the reference (it deviated too far from the topic): https://github.com/dotnet/csharplang/issues/2148

**Comment by sharwell** [comment] 2020-01-25 21:56
[Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces) already provides similar functionality for a different feature new for C# 8.

**Comment by huoyaoyuan** [comment] 2020-01-30 10:42
Pattern-based index and range expressions are added near the ship time of C# 8. Without this feature, out-of-band package cannot be actually used, since existing types have no member accepting them. But with this feature, it can be easily used.

**Comment by lostmsu** [comment] 2020-01-31 20:45
@huoyaoyuan it is fine, that I can't use it on core types. Problem is: without a package I can't implement indexers with them in my types in a .NET Standard 2.0 assembly.

**Comment by lostmsu** [comment] 2020-02-11 22:39
@jkotas should this issue be in dotnet/runtime instead? I'd love `Microsoft.Bcl.Ranges`

**Comment by jkotas** [comment] 2020-02-11 23:45
This is duplicate of https://github.com/dotnet/runtime/issues/28285

**Comment by 333fred** [comment] 2020-02-12 01:45
Closing as a duplicate.

**Closed by 333fred** 2020-02-12 01:45 UTC
