### ISSUE TITLE
[Suggestion] Simply List<T> init

### ISSUE THREAD

**Issue by surfsky** [dotnet/csharplang#3493] opened 2020-05-26 05:12 UTC
```
string[] array = ["a", "B", "c"];
List<string> list = ["a", "b", "c"];  // is ok
```

**Comment by yaakov-h** [comment] 2020-05-26 05:15
This seems like a duplicate of #1399.

**Comment by 333fred** [comment] 2020-05-26 06:50
Closing as a duplicate.

**Closed by 333fred** 2020-05-26 06:50 UTC
