### ISSUE TITLE
My thoughts on the primary constructor

### ISSUE THREAD

**Issue by windows-live** [dotnet/csharplang#7187] opened 2023-05-11 04:22 UTC
I would like to express a few personal thoughts that I hope will provide another source of inspiration for the controversial primary constructor
My English is very poor and my expression is not clear.  Please understand

`public class Employee(string firstName, string lastName, string email, decimal salary)
{    
	public string FirstName { get; set; } = firstName;
	public string LastName { get; set; } = lastName;
	public string Email { get; set; } = email;
	public decimal Salary { get; set; } = salary;

	/*
	The syntax of the function body of the primary constructor is suggested to write in this way, inspired by the destructor, the destructor is turned over to write, which not only ensures the elegant syntax but also realizes the problem of the function body of the primary constructor
	The "~" symbol represents: (string firstName, string lastName, string email, decimal salary)
	Simply put, the "~" symbol represents the primary constructor
	*/
	public Employee~
	{
		/*
		This area is the body area of the primary constructor
		The arguments passed into the primary constructor are freely accessible here,
		because the ~ symbol stands for: PrimaryConstructor ====>>> (string firstName, string lastName, string email, decimal salary)
		*/
		
		//"~" is equivalent to: (string firstName, string lastName, string email, decimal salary)
	}
	
	//Destructor, the destructor with "~" in prefix, and adjusted "~" to suffix as the primary constructor. Remove parentheses
	public ~Employee()
	{
		
	}
	
	
	/*
	Multiple constructors with the same signature (same type 、 same number of arguments) are defined below for syntactic purposes.   Do not misunderstand
	*/
	
	
	/*
	When this constructor is called to create an object, the primary constructor must be included
	"with" translates to take something with you, The "~" after "with" represents the primary constructor
	*/
     public Employee(HttpClient http_client, string first_name, string last_name) with ~
     {
        FirstName = firstName;	//Here you can either use first_name directly or use the firstName passed in by the primary constructor
								
        LastName = lastName;	//Here you can either use last_name directly or use the lastName passed in by the primary constructor
								
        Email = email;	//This can only use the email passed in by the primary constructor
						
        Salary = salary;//This can only use the salary passed in by the primary constructor

     }
	 /*
	 When creating an Employee instance, this is called, with the "~" after the "with" represents the primary constructor, and the "=" represents the assignment
	 var emp_3 = new Employee(my_httpclient, "冯", "feng") with ~= ("冯", "先生", "56820168@qq.com", 15000);
	 */
	 
	 
	
	 /*
	 When this constructor is called to create an object, it can be created with or without the primary constructor, because it has been assigned a default value
	 */
	 public Employee(HttpClient http_client, string first_name, string last_name) with ~= ("冯", "先生", "56820168@qq.com", 9000)
     {
        FirstName = firstName;	//first_name or firstName all right
		/* 
		We can use either first_name directly or the firstName passed in by the main constructor.  If the firstName of the main constructor is also named first_name, then we can override the first_name of the main constructor by applying the nearest principle.  Or you can use the main constructor first according to the principle of the main constructor first.  There are only two ways to choose, and the estimation is ultimately the principle of choosing the nearest application
		*/
						
        LastName = lastName; //last_name or lastName all right
        /*
		We can use either last_name directly or the lastName passed in by the main constructor.  If the lastName of the main constructor is also named last_name, then we can override the last_name of the main constructor by applying the nearest principle.  Or you can use the main constructor first according to the principle of the main constructor first.  There are only two ways to choose, and the estimation is ultimately the principle of choosing the nearest application
		*/
		
		Email = email;	//This can only use the email passed in by the primary constructor
						
        Salary = salary;//This can only use the salary passed in by the primary constructor
						
		
		Console.WriteLine($"姓: {FirstName}, 名: {LastName}");//output: 姓:冯, 名:先生
     }
	 /*
	 When creating an Employee instance, the "~" after "with" represents the primary constructor and "=" represents the assignment
	 var emp_3 = new Employee(http_client, "冯", "feng");
	 var emp_3 = new Employee(my_httpclient, "冯", "feng") with ~= ("冯", "先生", "56820168@qq.com", 15000);
	 */
	 
	 
	 /*
	 One of the cases in which the parameterless constructor is called to create an object must include the primary constructor
	 The "~" after "with" represents the primary constructor
	 */
     public Employee() with ~
     {
        FirstName = firstName;	//The firstName passed in by the primary constructor
								
        LastName = lastName;	//The lastName passed in by the primary constructor
								
        Email = email;	//The email passed in by the primary constructor
						
        Salary = salary;//The salary passed in by the primary constructor
						
						
		/*
		If the constructor of the parent class needs to be called, then the following "~" represents the primary constructor of the parent class and assigns the value to the primary constructor of the parent class using the same syntax
		*/
		base() with ~= (firstName, lastName, email, salary);
		
		/*
		The by clause directly tells the compiler that it is calling the primary constructor of the parent class, "~" represents the primary constructor, and "by ~" directly tells the compiler that this is the primary constructor
		*/
		base(firstName, lastName, email, salary) by ~;
     }

	 
	 /*
	 When the no-argument constructor is called to create an object, it can be created with or without the primary constructor, because the primary constructor is preassigned a default value
	 "~" represents the primary constructor and "=" represents the assignment, Simply put, with the primary constructor and assign a value to the primary constructor
	 */
     public Employee() with ~= ("冯", "小姐", "56820168@qq.com", 9000)
     {
        FirstName = firstName;	//The firstName passed in by the primary constructor
								
        LastName = lastName;	//The lastName passed in by the primary constructor
								
        Email = email;	//The email passed in by the primary constructor
						
        Salary = salary;//The salary passed in by the primary constructor
						
		
		/*
		If the constructor of the parent class needs to be called, then the following "~" represents the primary constructor of the parent class and assigns the value to the primary constructor of the parent class using the same syntax
		*/
		base() with ~= ("冯", "先生", "56820168@qq.com", 9500);
		
		/*
		The by clause directly tells the compiler that it is calling the primary constructor of the parent class, "~" represents the primary constructor, and "by ~" directly tells the compiler that this is the primary constructor
		*/
		base(firstName, lastName, email, salary) by ~;
     }
	 
	/*
	There can only be one parameterless constructor, The constructor of the same signature can only have one , Here is to demonstrate the syntax, so write multiple
	*/
	
	
	 /*
	 mark:AAA //Make a mark here
	 Any of several constructors that take only one argument and must be called with the primary Constructor when creating an object
	 The "~" after "with" represents the primary constructor
	 */
     public Employee(decimal my_salary) with ~
     {
        FirstName = firstName;	//The firstName passed in by the primary constructor
								
        LastName = lastName;	//The lastName passed in by the primary constructor
								
        Email = email;	//The email passed in by the primary constructor
						
        Salary = my_salary; //my_salary or salary all right
		/*
		Here we can use either my_salary or the salary passed in by the primary constructor. If the salary of the primary constructor is also named my_salary, then we can override the salary of the Primary constructor by applying the nearest principle.     Alternatively, it is possible to use the primary constructor first according to the primary constructor first principle, Only one of the two methods can be chosen, and estimation is ultimately the principle of choosing the nearest application
		*/
		
		Console.WriteLine($"主构造的Salary：{Salary}，这个单参构造的Salary：{my_salary}");//output: 主构造的Salary：999999，这个单参构造的Salary：77777
     }

	 /*
	 mark:BBB //Make a mark here
	 Another case of a constructor with only one argument, When this constructor is called to create an object, it can be created with or without the primary constructor, because the primary constructor is preassigned a default value
     "~" represents the primary constructor and "=" represents the assignment, Simply put, with the primary constructor and assign a value to the primary constructor
	 */
	 public Employee(decimal my_salary) with ~= ("冯", "先生", "56820168@qq.com", 10000)
     {
        FirstName = firstName;	//The firstName passed in by the primary constructor
								
        LastName = lastName;	//The lastName passed in by the primary constructor
								
        Email = email;	//The email passed in by the primary constructor
						
        Salary = salary; //my_salary or salary all right
		/*
		Here we can use either my_salary or the salary passed in by the primary constructor.     If the salary of the primary constructor is also named my_salary, then we can override the salary of the Primary constructor by applying the nearest principle.     Alternatively, it is possible to use the primary constructor first according to the primary constructor first principle, Only one of the two methods can be chosen, and estimation is ultimately the principle of choosing the nearest application
		*/
		
		Console.WriteLine($"主构造的Salary：{Salary}，这个单参构造的Salary：{my_salary}");//output: 主构造的Salary：999999，这个单参构造的Salary：77777
     }

}
`
`/*
Call a constructor with only one argument, corresponding to the constructor labeled mark:AAA or mark:BBB, and pass in an argument that overrides the default value given when defined, mark:AAA and mark:BBB are duplicative, and this is just for syntax purposes so I'm duplicative
The "~" represents the PrimaryConstructor and the "=" represents the assignment, Simply put, with the PrimaryConstructor and assign a value to the PrimaryConstructor
*/
var emp_1 = new Employee(77777) with ~= ("冯", "先生", "56820168@qq.com", 999999);

/*
Call a constructor with only one argument, corresponding to the constructor marked mark:BBB.  Since the constructor marked mark:BBB assigns default values to the PrimaryConstructor, it can be omitted when called
*/
var emp_1 = new Employee(77777);

/*
Call the parameterless constructor, and the arguments passed in the call override the default values given when defined
"~" represents the primary constructor and "=" represents the assignment, Simply put, with the PrimaryConstructor and assign a value to the primary constructor
*/
var emp_0 = new Employee() with ~= ("冯", "小姐", "56820168@qq.com", 888888);

/*
Call a parameterless constructor,  when give default value  assigned to the main constructor when defined, it can be omitted when called
You do not need to include the primary constructor, If the primary constructor is included, the default value at the time of definition is overridden
*/
var emp_0 = new Employee();

var http_client = new HttpClient(){ BaseAddress = new Uri("xxxxxxx") });

/*
Calls the three-argument constructor, passing in arguments that override the default values given when defined
"~" represents the primary constructor and "=" represents the assignment, Simply put, with the PrimaryConstructor and assign a value to the PrimaryConstructor
*/
var emp_3 = new Employee(http_client, "冯", "feng") with ~= ("冯", "先生", "56820168@qq.com", 15000);

/*
Call a three-argument constructor. In the same way that a default value is assigned to the primary constructor when defined, it can be omitted when called, You do not need to include the primary constructor, which overrides the default value when defined
*/
var emp_3 = new Employee(http_client, "冯", "feng");

/*
The primary constructor is called here
The primary constructor is called here.  Note that just because there is no with clause does not mean it must be the primary constructor, because the secondary constructor can also be called without the with clause.
When the secondary constructor is defined with a default value assigned to the primary constructor, it can also be called without the with clause, so it does not mean that the absence of a with is the primary constructor.
*/
var emp_primary = new Employee("冯", "先生", "56820168@qq.com", 75000);

/*
Proposed addition of "by" syntax,
"~" symbol represents the primary constructor, The "by" clause tells the compiler directly: this is the primary constructor
So it's like telling the compiler directly: this is the primary constructor
*/
var emp_primary = new Employee("冯", "先生", "56820168@qq.com", 75000) by ~;

/*
The proposed addition of the "default" syntax means that you artificially tell the compiler to use the default value directly.  I gave the primary constructor a default value when defining it, so you can use the default value directly
*/
var emp_0 = new Employee() with ~= default; 
//Be equivalent to ====>>> var emp_0 = new Employee(); 
//The advantage is that it is obvious at a glance that the main constructor is involved, since the new syntax is used

var emp_1 = new Employee(77777) with ~= default; 
//Be equivalent to ====>>> var emp_1 = new Employee(77777); //Same as above

var emp_3 = new Employee(http_client, "冯", "feng") with ~= default;
//Be equivalent to ====>>> var emp_3 = new Employee(http_client, "冯", "feng");

/*
We never underestimate the "default" syntax, with this "default" syntax, then you can make all the classes containing the primary constructor all unified use of "new .... with ...." or "new .... by ...." syntax,
In this way, it is clear at a glance that any object that uses the new syntax "new" has a primary constructor, and any object that uses the old syntax "new" has no primary constructor

It is suggested that classes that have a primary constructor use the new syntax to create instances, and classes that do not have a primary constructor use the original syntax to create instances, so that the new and old are clear at a glance
*/
`

**Comment by 333fred** [comment] 2023-05-11 06:27
Closing as a duplicate of the two other locations you've posted this in. @windows-live, we appreciate your passion, but reposting this so many times is unnecessary. Please leave feedback for the feedback discussion you've already posted in. Thanks!

**Closed** 2023-05-11 06:27 UTC
