### ISSUE TITLE
 Default Generic Type

### ISSUE THREAD

**Issue by sameerkapps** [dotnet/csharplang#2177] opened 2019-01-27 20:01 UTC
**Problem:**
A generic class can have the same generic type used multiple times. Allow setting default generic type to reduce redundant code and making it easier to read.
**Current:**
```
public class Node<T>
{
	public T Data
	{
		get;
		set;
	}
}
```
Use:
```
	Node<int> node1 = new Node<int>() { Data = 1};
	Node<int> node2 = new Node<int>() { Data = 2};
	Node<string> nodeStr = new Node<string>() { Data = "test" };
```
**Proposed:** note: **<T = int>** in the declaration
```
public class Node<T = int>
{
	public T Data
	{
		get;
		set;
	}
}
```
Use:
```
    // empty <> reduces the redundant code and distinguishes from non-generic class Node
    Node<> node1 = new Node<>() { Data = 1};
    Node<> node2 = new Node<>() { Data = 2};
    Node<string> nodeStr = new Node<string>() { Data = "test" };

```

**Comment by anadale** [comment] 2019-01-27 20:42
Why just don’t inherit from generic type and specify required generic argument?

`public class IntNode : Node<int> { ... }`

**Comment by CyrusNajmabadi** [comment] 2019-01-27 21:00
Or, more simply: `using IntNode = Node<int>;`

**Comment by svick** [comment] 2019-01-27 22:33
@CyrusNajmabadi You have to repeat that in every file where you want to use the type like this, and I think that makes it less appealing by quite a lot.

@sameerkapps I would prefer to reserve the `Node<>` syntax for partial type inference (https://github.com/dotnet/csharplang/issues/1349), at least for now. I think that feature would be more useful than this one and it's not clear yet what syntax it would use.

**Comment by CyrusNajmabadi** [comment] 2019-01-27 22:35
> @CyrusNajmabadi You have to repeat that in every file where you want to use the type like this, and I think that makes it less appealing by quite a lot.

Why?  It's a single line.  You write it once, and you can use it as many times as you want in that file.  Seems totally workable.

**Comment by sameerkapps** [comment] 2019-01-27 23:03
@anadale 
As per the coding conventions, you would create a new file for IntNode class. It is an overhead.

@CyrusNajmabadi 
As @svick suggests, this will have to be repeated in each file. That is a maintenance issue. Also, more than one developer may choose to name it differently e.g. IntNode in one file. IntegerNode in another file.

**Comment by CyrusNajmabadi** [comment] 2019-01-27 23:13
> That is a maintenance issue

And?  That's been fine for years.  Why is it now an issue needing addressing?

> Also, more than one developer may choose to name it differently e.g. IntNode in one file. IntegerNode in another file.

That doesn't seem like a problem.  Much less of an issue than the rare need for a generic type to have to specify a default because it's so common that it is instantiated with that value.

**Comment by theunrepentantgeek** [comment] 2019-01-28 00:02
@svick wrote:

>  I would prefer to reserve the `Node<>` syntax for partial type inference (#1349)

But that syntax is already used - allowing you to reference the _open_ generic type e.g. `typeof(Node<>)`.

`#include std_backward_compatibility_rules`

**Comment by yaakov-h** [comment] 2019-01-28 00:15
> As per the coding conventions, you would create a new file for IntNode class.

This is a self-imposed limitation, not a limitation of the language. Self-imposed limitations can be changed far more easily.

**Comment by svick** [comment] 2019-01-28 01:04
@theunrepentantgeek That syntax currently only works in `typeof`. I think either partial type inference or the feature proposed here could use the same syntax outside of `typeof` with no breaking changes.

**Comment by theunrepentantgeek** [comment] 2019-01-28 01:36
> the feature proposed here could use the same syntax outside of typeof with no breaking changes.

So, what would `typeof(Node<>)` return?

Would it be the _open_ generic type, from which all closed generic types derive?

Or would it be the _closed_ generic type with the default type value specified?

It can't be both.

If `typeof(Node<>)` returns the open type, then what's the syntax for **typeof** to obtain the closed type with the default type specified? And why does this differ from the syntax used to declare a member/local/parameter/etc?

If `typeof(Node<>)` returns the closed type, then what's the syntax for **typeof** to obtain the open type with no default? And wouldn't it be inconsistent for **typeof** to return a closed type for `typeof(Node<>)` but an open type for `typeof(Foo<>)`?

**Comment by willard720** [comment] 2019-02-09 01:36
My biggest gripe with this is I don't know what `Node<>`'s type is. The proposed solutions of using inheritance, or, even better, using name aliases (which were created for such a purpose), we can use `IntNode` instead and that shows what the type is.

Of course `Node<>` is much shorter than `StringIntDictionaryNode` but you should have autocomplete to help write that anyways, and readibilty is more important regardless.

**Comment by YairHalberstadt** [comment] 2020-10-21 07:59
Closing as duplicate of #278

**Closed by YairHalberstadt** 2020-10-21 07:59 UTC
