### ISSUE TITLE
Non-nullable members initialized by consumer

### ISSUE THREAD

**Issue by pablocar80** [dotnet/csharplang#3020] opened 2019-12-12 20:33 UTC
If we have a class like the following:

```csharp
class Person
{
  public string Name { get; set; }
  public Address Address { get; set; }
  [...]
}
```

These fields will yield the warning CS8618 "non-nullable property xxx is uninitialized". The only way to keep these fields required, is (a) to assign them values in the constructor, or (b) initialize with dummy values in the lines that declares them:

```csharp
class Person
{
  public string Name { get; set; } = string.Empty;  // dummy value
  public Address Address { get; set; }

  public Person(Address address)
  {
     Address = address;   // assign in constructor
  }
}
```

But doing so has some problems:
- dummy values, such as the empty string, defeat the original purpose of controlling that the programmer forgot to pass a value
- a class can have many fields, and adding a bunch of parameters to a constructor makes the code awfully less readable
- classes decorated with `DataContract` are required to have a parameterless constructor, and thus in practice cannot use the non-nullable constraint for their fields

Thus, it would be much more interesting if the "required" behavior of these fields was such that any caller creating an instance is required to pass a value, as in the following code:

```csharp
// compiles without errors or warnings
var myPerson = new Person
{
  Name = "Pablo",
  Address = new Address(...)
}

// yields a warning that the member `Address` is required yet uninitialized
var anotherPerson = new Person
{
  Name = "John"
}
```

**Comment by pablocar80** [comment] 2019-12-12 20:51
Much related to this, classes decorated with `DataContract` are required to have a parameterless constructor. This means that in practice, all reference members in a DataContract class will have to be nullable, even if in theory they shouldn't be.

The ideal behavior for DataContract classes would be to allow them to have non-nullable fields. These could be filled in during deserialization process (by the same mechanism described above, of passing member values when newing). Then the deserialization would fail if missing any of the required members.

**Comment by pablocar80** [comment] 2019-12-13 00:03
It also would be great if we could use the non-nullable constraint in `DataContract` classes. The way it should work is that deserialization fails if a non-nullable reference is missing a value.

**Comment by YairHalberstadt** [comment] 2019-12-13 04:05
Duplicate of https://github.com/dotnet/csharplang/issues/2328

**Comment by svick** [comment] 2019-12-13 11:47
One workaround is to force initialize the properties to `null`:

```c#
class Person
{
  public string Name { get; set; } = null!;
  public Address Address { get; set; } = null!;
}
```

**Comment by spydacarnage** [comment] 2019-12-13 11:57
To get the CS8618 error, the OP must be running in a NRT-aware context, so
that won't compile - they would need to be defined as string? and Address?

**Comment by pablocar80** [comment] 2019-12-13 13:47
@svick @spydacarnage that seems to work. As @svick said, it's at the cost of effectively preventing any null values on those members

**Comment by YairHalberstadt** [comment] 2020-11-15 12:13
Closing as championed at https://github.com/dotnet/csharplang/issues/3630

**Closed by YairHalberstadt** 2020-11-15 12:13 UTC
