### ISSUE TITLE
Named generic arguments

### ISSUE THREAD

**Issue by KnorxThieus** [dotnet/csharplang#1363] opened 2018-03-07 11:31 UTC
We can specify named arguments to methods now, like:

```
// Declaration:
void Method(int first, int second, int third);

// Call:
Method(first: 12, second: 42, third: 0);
// Call in custom order:
Method(second: 42, first: 12, third: 0);
```

I miss the same functionality for generic arguments. Expected syntax:

```
// Declaration:
class GenericClass<TFirst, TSecond, TThird>;

// Instanciation:
GenericClass<TFirst: bool, TSecond: int, TThird: string> myObject1;
// Instanciation in any order:
GenericClass<TSecond: int, TFirst: bool, TThird: string> myObject2;

// Derivation:
class ClosedClass1 : GenericClass<TFirst: bool, TSecond: int, TThird: string>
{
    /*...*/
}
// Derivation in custom order:
class ClosedClass2 : GenericClass<TSecond: int, TFirst: bool, TThird: string>
{
    /*...*/
}
```

This would help making generic arguments more intuitive and providing them a new attractivity next to free-to-name `ValueTuples`.

Real word examples:

- ```var customerNames = new Dictionary<TKey: int, TValue: string>();```
- ```class MyConverter : Converter<TInput: int, TOutput: string> { ... }```
- ```Func<double, double, TOut: int>```

**Edit:** To get conscious of another advantage of named generic arguments, remember what for named method arguments have been designed: On the one hand, for selecting relevant parameters from a set of optional ones, on the other hand for re-notating the meaning of a parameter of a "all-world-type" like boolean. Isn't this a problem we have got with generic parameters in particular, because most of generic parameters are not constrained and "all-world-types" in every way?

**Comment by svick** [comment] 2018-03-07 11:43
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/280.

**Comment by KnorxThieus** [comment] 2018-03-07 11:45
I'm sorry, I did not find this issue. Shall I close this thread?

**Comment by Joe4evr** [comment] 2018-03-07 12:21
Please do.

**Closed** 2018-03-07 12:54 UTC
