### ISSUE TITLE
Allow typescript-like notation of delegates.

### ISSUE THREAD

**Issue by wrkettlitz** [dotnet/csharplang#3456] opened 2020-05-13 13:28 UTC
Delegate alternative notation
Proposed

Summary
This proposal addresses an issue with delegates where the delegates either hides what it expects as arguments or hides away, in another place of code, what it does.

Motivation
Sometimes it is unclear what a delegate expects as arguments, especially if this is a named delegate.
``` C#
// Most delegates are either of type Action or Func.
// The problem with both of the is that it is sometimes unclear what the arguments represent.

Func<string, bool> // What is string supposed to be here? A person's name? A password?

// The problem with named delegates is that you have to look at it's definition for it to understand.

delegate void BindingPropertyChangedDelegate // huh? What is this? What does this expect?

public delegate void BindingPropertyChangedDelegate(BindableObject bindable, object oldValue, object newValue); // Oh, that is what is expected from me!

// Wouldn't it be nice if we could get the best of both worlds? A quick and easy way to see what a delegate expects and returns and what it's arguments are supposed to represent.
```

Detailed design
``` Typescript
// In typescript: 
    forEachArrayItem(itemHandler: (item : T => void)): void;
```
Here it is clear what types are expected and what those arguments are supposed to represent. This is because now both the types and the argument names are indicated,
Can't C# have something similar?

Drawbacks
People who are used to Action and Func might need to get used to this.

**Comment by HaloFour** [comment] 2020-05-13 13:36
That notation would have to be converted to a delegate at some point since that's what the CLR and the ecosystem understands.  Delegates are nominal types in the CLR and you can't cast from one to the other even if the signature is identical.  At best you have to have one delegate call the `Invoke` method of the other delegate which adds overhead to each call.

IMO the `Action`/`Func` delegates should only be used in cases where the purpose of the arguments are obvious by their position and type.  Consider them the tuples of the delegate world.  If you need a more complicated signature, named parameters and separate documentation I would suggest writing a custom delegate type.

**Comment by svick** [comment] 2020-05-13 16:16
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/269.

**Comment by 333fred** [comment] 2020-05-13 22:20
This does seem like a duplicate, closing out. If you think that there's something different that you wanted to discuss in this issue, ping me and I can reopen.

**Closed by 333fred** 2020-05-13 22:20 UTC
