### ISSUE TITLE
Use continue/break with the ?? Operator in a foreach loop

### ISSUE THREAD

**Issue by BattleRush** [dotnet/csharplang#531] opened 2017-05-03 21:28 UTC
Example
![image](https://cloud.githubusercontent.com/assets/11750584/25682195/8dc0a974-3057-11e7-8cba-a328ab1944be.png)

could also be used for `break`

Similar to
![image](https://cloud.githubusercontent.com/assets/11750584/25682178/7ed75872-3057-11e7-92f0-daa534ee134c.png)

To avoid in this case to do a null check, it would be better to just either continue to the next element or break the loop.

**Comment by HaloFour** [comment] 2017-05-03 21:41
Dupe of #176

**Comment by BattleRush** [comment] 2017-05-26 18:49
Closed due to being duplicate

**Closed** 2017-05-26 18:49 UTC
