### ISSUE TITLE
Omit Type for Generic Initialization

### ISSUE THREAD

**Issue by GrayOsmose** [dotnet/csharplang#1386] opened 2018-03-16 13:46 UTC
We can initialize generics with initial data, but we still have to specify type of the generic. It would be nice to omit type defenition in that case.

Currently following statements are legal.

```C#
int[] array = { 1, 2, 3 };
var array = new[] { 1, 2, 3 };
var list = new List<int> { 1, 2, 3 };
var dictionary = new Dictionary<string, string> { ["key"] = "value" };
```
With syntax proposed in this topic you'd be able to write:

``` C#
var list = new List { 1, 2, 3 };           // List<int>
var dictionary = new Dictionary { ["key"] = "value" }; // Dictionary<string,string>
```

It is simmilar to how type `omit` works for `Generic Methods`.

```C#
...
public static T GetData<T>(T data) => data;
...

// type is omited in this case
var data = GetData(1);
```

**Comment by jnm2** [comment] 2018-03-16 13:52
Duplicate of: https://github.com/dotnet/csharplang/issues/1349, https://github.com/dotnet/csharplang/issues/1348

**Comment by svick** [comment] 2018-03-16 13:53
This is a duplicate of https://github.com/dotnet/csharplang/issues/281.

@jnm2 I don't think those issues are exactly the same thing.

**Comment by jnm2** [comment] 2018-03-16 13:54
@svick True.

**Comment by jnm2** [comment] 2018-03-16 13:55
See also: #1103, #1018, #997, #1348, https://github.com/dotnet/csharplang/issues/997#issuecomment-336421033

**Comment by GrayOsmose** [comment] 2018-03-16 14:16
Thanks, will read them.

**Closed** 2018-03-19 07:00 UTC
