### ISSUE TITLE
Static constructor for structs doesn't behave according to the specs

### ISSUE THREAD

**Issue by vladd** [dotnet/csharplang#1948] opened 2018-10-22 09:37 UTC
Consider [the following code](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEAMABLgIwDcAsAFDW4BMxJA7NQN7WGeMBsxALIQCyEAJaYAFAEpCAXgB8hACZwAZhHQAbGOIBCAewBeACz0blkgHQAxKZSoBfatVgYAxjEL7jp5Ww5dSXi8TMzgpWQVSAE5xACIAZRgIGBFXQlc9TBd0dz0EWMk7LmIAZn5CG2lWQkcHIA==):

```csharp
using System;

class Program
{
    static void Main() => default(Bozholde).F();
}

struct Bozholde
{
    static Bozholde() => Console.WriteLine("Static constructor");
    public void F() { }
}
```

This code outputs `Static constructor` before calling `F`. Tested online on sharplab.io, as well as with the fresh Visual Studio 2017 on .NET Fx 4.7.1 and .NET Core 2.0.

However [the spec](https://github.com/dotnet/csharplang/blob/master/spec/structs.md#static-constructors) doesn't list calling an instance method as a valid reason for triggering the static constructor:

> The execution of a static constructor for a struct type is triggered by the first of the following events to occur within an application domain:
>
> *  A static member of the struct type is referenced.
> *  An explicitly declared constructor of the struct type is called.
 
I believe, the bug is in the specification and must be corrected. [If not, it's a bug in compiler and must be moved to the appropriate repository.]

**Comment by svick** [comment] 2018-10-22 12:35
I think you are right that this is a bug in the C# spec. [The CLI spec says](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf#%5B%7B%22num%22%3A991%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C87%2C654%2C0%5D) (note that types with static constructor are not marked BeforeFieldInit by the C# compiler):

> If not marked BeforeFieldInit then that type’s initializer method is executed at (i.e., is triggered by):
>
> a. first access to any static field of that type, or  
> b. first invocation of any static method of that type, or 
> c. **first invocation of any instance or virtual method of that type if it is a value type** or 
> d. first invocation of any constructor for that type

**Comment by vladd** [comment] 2018-10-22 13:16
@svick: Nice find, thank you!

**Comment by gafter** [comment] 2018-10-22 20:42
I've reported this to ECMA so the next version of the spec can be updated.

**Comment by TPFInferno** [comment] 2018-10-23 11:50
First time posting so excuse my ignorance but doesn't that code comply with the spec?

Default(T) is syntatic sugar for **structs** in that it just calls the default constructor. So when you call default for a **struct**, you are explicitly invoking the constructor for the struct.

**Comment by HaloFour** [comment] 2018-10-23 12:13
@TPFInferno 

> Default(T) is syntactic sugar for **structs** in that it just calls the default constructor.

`default(T)` doesn't call a constructor, it zeroes out the memory location.  Even if the struct had a default parameterless constructor, which C# doesn't allow but other languages can, `default(T)` would not invoke that constructor.  You'd have to explicit invoke it via `new T()`.

**Comment by TPFInferno** [comment] 2018-10-23 12:28
> @TPFInferno
> 
> > Default(T) is syntactic sugar for **structs** in that it just calls the default constructor.
> 
> `default(T)` doesn't call a constructor, it zeroes out the memory location. Even if the struct had a default parameterless constructor, which C# doesn't allow but other languages can, `default(T)` would not invoke that constructor. You'd have to explicit invoke it via `new T()`.

Is that so?  Thank you for clearing that up for me! :)

**Comment by vladd** [comment] 2018-10-23 12:58
@TPFInferno The spec makes a [special exception](https://github.com/dotnet/csharplang/blob/master/spec/structs.md#static-constructors) for struct default constructor:

> The creation of default values ([Default values](The creation of default values (Default values) of struct types does not trigger the static constructor.)) of struct types does not trigger the static constructor.

**Comment by BillWagner** [comment] 2021-04-30 18:19
Closing as a duplicate of dotnet/csharpstandard#152

**Closed by BillWagner** 2021-04-30 18:19 UTC
Labels: Spec
