### ISSUE TITLE
[Proposal]: iteration-else

### ISSUE THREAD

**Issue by pedro-gilmora** [dotnet/csharplang#4386] opened 2021-02-03 21:27 UTC
# Iteration statements should be detected

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

## Motivation
[motivation]: #motivation

Sometimes it's annoying the fact that if the iteration has zero incursion and we have to ask the collection to take actions in case there was no iteration. I'm not a languaje design expert but I think this feature could be useful and non-obstrusive for backward compatibility. Should be not intended for do..while statement Ex:
```cs
if (enumerable.Any ()) {
     // while, for, foreach
} else {
     // actions if no iterations
}
```
And other variants 

## Detailed design
[design]: #detailed-design

```cs
while(condition){ //for; foreach; while
    //iteration job
}
else {
  //if no iteration, execution goes here
  throw new EmptyEnumerableException("collection must contain at least 1 element");
}
```

**Comment by 333fred** [comment] 2021-02-03 22:18
Duplicate of https://github.com/dotnet/csharplang/discussions/4387.

**Closed by 333fred** 2021-02-03 22:18 UTC
