### ISSUE TITLE
Use an ! operator to assert that a variable is not null.

### ISSUE THREAD

**Issue by ekolis** [dotnet/csharplang#3096] opened 2020-01-13 17:11 UTC
This would be useful to simplify conversion of nullable types to non-nullable types:

```
int? answer = 42;
int magic = answer!; // equivalent to answer.Value or (int)answer
```

**Comment by 333fred** [comment] 2020-01-13 19:01
We considered something like this for the initial version of C# 8: https://github.com/dotnet/csharplang/issues/1865. We decided against this, and at this point this would be a breaking change.

**Comment by ronnygunawan** [comment] 2020-01-14 18:07
Breaking change can be avoided by introducing a new `!!` operator.

```cs
string? s = null;
string t = s!!; // throws NullReferenceException
```

**Comment by 333fred** [comment] 2020-01-14 20:04
@ronnygunawan yes, but note that your example uses reference types and the issue is about nullable value types.

**Comment by ekolis** [comment] 2020-01-14 23:27
@333fred I was actually talking about both reference types and nullable value types; sorry if I wasn't clear!

**Comment by ronnygunawan** [comment] 2020-01-15 03:58
For nullable value type:

```cs
int? i = null;
int j = i!!; // equivalent to i!.Value, throws InvalidOperationException: Nullable object must have a value.
```

**Comment by MatisseHack** [comment] 2020-04-17 20:40
This feature would make using nullables so much cleaner and easier. I run into issues whenever I'm dealing with deserialized data. The models' types are all nullable and I end up having to litter my code with explicit null checks. I've taken to adding the following two extension methods to all my projects to make it slightly cleaner:

```csharp
public static T GetValue<T>(this T? possibleNull, [CallerLineNumber] int sourceLineNumber = 0) where T : class =>
    possibleNull ?? throw new NullReferenceException($"Value is null on line {sourceLineNumber}");

public static T GetValue<T>(this T? possibleNull, [CallerLineNumber] int sourceLineNumber = 0) where T : struct =>
    possibleNull ?? throw new NullReferenceException($"Value is null on line {sourceLineNumber}");
```

The new `CallerArgumentExpression` [proposal](https://github.com/dotnet/csharplang/issues/287) would improve the exception message, but this is better than nothing. I would love to have a language feature to do this assertion more concisely!

**Comment by YairHalberstadt** [comment] 2020-11-17 11:43
Closing as the feature as suggested here is a breaking change

**Closed by YairHalberstadt** 2020-11-17 11:43 UTC
