### ISSUE TITLE
Explicit but encapsulated backing fields

### ISSUE THREAD

**Issue by mbarbac** [dotnet/csharplang#3042] opened 2019-12-20 11:09 UTC
Quite often I have getter and setter logic for a type property that need an explicit field. Even if it is a private one there is always the risk that someone touching the code access that field instead of using the property. Why cannot those fields be encapsulated such as follows:

class MyType {
    ...
    public string MyProperty {
        string _myrestrictedstring;
        get { ... whatever logic is needed ... }
        set { ... whatever logic is needed ... }
    }
    ...
}

The point here is that the '_myrestrictedstring' field won't be accesible beyond the 'scope' set by the property brackets.

Thanks.

**Comment by quinmars** [comment] 2019-12-20 14:05
This is a duplicate of #133.

**Comment by YairHalberstadt** [comment] 2020-11-16 08:57
Closing as duplicate of https://github.com/dotnet/csharplang/issues/133

**Closed by YairHalberstadt** 2020-11-16 08:57 UTC
