### ISSUE TITLE
Nullable Dictionary.TryGetValue and out var

### ISSUE THREAD

**Issue by szmcdull** [dotnet/csharplang#2890] opened 2019-10-17 03:01 UTC
![image](https://user-images.githubusercontent.com/2098590/66974246-16068a00-f0cd-11e9-9076-ba1e6c32f7b3.png)

Compiler complains about unassigned field in the true block instead of the false one.

**Comment by yaakov-h** [comment] 2019-10-17 05:57
Duplicate of #916.

**Closed** 2020-11-09 09:48 UTC
