### ISSUE TITLE
[Suggestions] Some suggestions for csharp lang

### ISSUE THREAD

**Issue by surfsky** [dotnet/csharplang#3492] opened 2020-05-26 04:08 UTC
# 1. Simply List&lt;T&gt; init:

``` csharp
string[] array = ["a", "B", "c"];
List<string> list = ["a", "b", "c"];  // is ok
```

# 2. Backward if/when expression

``` csharp
n = 0 if (b == true);   // n = 0 when (b == true);
```
means
``` csharp
if (b == true)
   n = 0;
```

# 3.  Exception-Ignore expression

``` csharp
int n = ParseInt("21test") !! 0;
```
means
``` csharp
int n;
try
{
    n = ParseInt(21test");
}
catch
{
    n = 0;
}
```
# 4. Generic limit to number

``` csharp
bool Add(this T t1, T t2) where  T : number
```
limit t type to short, int, long, double,  float, decimal, nshort, nint, nlong.

# 5. Allow Ignoring new keyword, and allow use : to replace =, more like dart and json

``` csharp
var t = Rectangle(Width: 10, Height: 20);
```

# 6. Simplify ```# region``` 

- Delete the endregion line
- You can free drag and sort code region in vs(code)

eg.
``` csharp
# region 1
....
# region 2
....
# region 3
```
or rename to part
``` csharp
# part 1
...
# part 2
...
# part 3
``` 

# 7.Expression expression

This code create a Expression object:
``` csharp
var exp = expression(Persion.Name);
or
var exp = expressof(Person.Name);
```

# 8. Variant alias and readable switch expression

``` csharp
int longvariantname = 10;
var stage = switch(longvariantname as t)   // alias
 {
        (t < 0) =>  LiftStage.Prenatal,
        (t < 2) =>  LifeStage.Infant,
        (t < 4) =>  LifeStage.Toddler,
        _       =>  LifeStage.LateAdult,
 };
```
or rename to 'map'
``` csharp
var stage = map(t)
 {
        (t < 0) =>  LiftStage.Prenatal,
        (t < 2) =>  LifeStage.Infant,
        (t < 4) =>  LifeStage.Toddler,
        _       =>  LifeStage.LateAdult,
 };
```

# 9. Multiline string """ expression

use dart syntax
``` csharp
var txt = """
    any multi line text" with ' and "
    any multi line text" with ' and "
    any multi line text" with ' and "
    """;
```

**Comment by YairHalberstadt** [comment] 2020-05-26 04:46
Hi @surfsky 

Thanks for your suggestions.

Generally proposals require more work put in: they should try and address some of:

1. What issue are they trying to solve
2. What are current workarounds
3. What are the suggested syntax and semantics
4. How will code gen work
5. What are any outstanding issues/disadvantages with the suggested design
6. Is the suggested design backwards compatible

Also it's very difficult to discuss multiple suggestions at once. Please open an issue per suggestion.

Finally I believe many of these are duplicates. Off hand I think I've already seen all but the last 3?

**Comment by surfsky** [comment] 2020-05-26 05:02
OK, I will split these suggestions. 
But I really feel that it is very difficult  to find the old issues in github. And old issues has not  adopt or deny tag.

**Comment by theunrepentantgeek** [comment] 2020-05-26 05:04
Just so you know, usual practice in this repo is to keep each issue to a single language proposal so that discussions don't get mixed up.

Many of your suggestions have already been made, and discussed in other issues. Generally simple changes like this flounder because, even though they may be nice ideas, they don't provide enough benefit to justify the enormous investment required. [Every proposal starts at -100 points](https://docs.microsoft.com/en-us/archive/blogs/ericgu/minus-100-points).

#### Simply List<T> init:

Target typed **new** is coming in C# 9.0 and simplifies code in a different way:

List<string> list = new {"a", "b", "c"};

#### Backward if/when expression

#2352 suggests adding trailing **if** and **unless** keywords

#### Generic limit to number

Has been suggested a large number of times, and would likely be handled by either the *Shapes and Extensions* (#164) or *Roles, extension interfaces and static interface members* (#1711) issues

#### Allow Ignoring new keyword

For better or worse, omitting the **new** keyword would make the language ambiguous. See #350

The remainder of this suggestion is already legal syntax for named parameters.

#### Simplify Region

This would be a breaking change, given that regions can already be nested.

#### Variant alias and readable switch expression

This is very similar to the **switch** expression syntax that was released in C# 8. That syntax is likely to be [enhanced in C# 9](https://devblogs.microsoft.com/dotnet/welcome-to-c-9-0/?utm_source=csharpdigest&utm_medium=email&utm_campaign=312#improved-pattern-matching) with range conditions:

``` csharp
var stage = longvariantname switch
{
    Thing t when t <0  => LiftStage.Prenatal,
    Thing t when t < 2 => LifeStage.Infant,
    Thing t when t < 4 => LifeStage.Toddler,
    _ =>  LifeStage.LateAdult,
};
```

**Comment by theunrepentantgeek** [comment] 2020-05-26 05:08
> But I really feel that it is very difficult to find the old issues in GitHub. 
> And old issues has not adopt or deny tag.

Very few issues have been outright denied. #1581 (Making semicolon optional) is one rare example.

If you can't find the older issue and inadvertently create a duplicate of an older idea, someone will likely point that out (with issue numbers) pretty quickly and ask you to close the issue. Don't worry about it.

**Comment by surfsky** [comment] 2020-05-26 05:24
OK, thanks much :-)

**Comment by 333fred** [comment] 2020-05-26 06:47
Closing this as the individual proposals have been split out.

**Closed by 333fred** 2020-05-26 06:47 UTC

**Comment by theunrepentantgeek** [comment] 2020-05-27 01:51
@surfsky I fear that I wasn't clear enough with my earlier comment. I wrote:

> If you can't find the older issue and inadvertently create a duplicate of an older idea, someone will likely point that out (with issue numbers) pretty quickly and ask you to close the issue.

Please **do** take the time to check for duplicates before raising issues.

If you know that an issue would be a duplicate, please **do not** open the duplicate issue. This includes situations where *someone has already identified the duplicate to you*.
