### ISSUE TITLE
Proposal: Guardian/Return if syntactic sugar

### ISSUE THREAD

**Issue by Shaviro** [dotnet/csharplang#3242] opened 2020-03-02 12:36 UTC
So, I'm currently doing a lof of parser work where it's basically always a case of return x if y.

```csharp
public static bool Parse(ref src Lexer, ref SomeType someType)
{
    if(!src.ExpectName("Version")) 
        return false;

    if(!src.ReadNumber(out someType.version))
        return false;

    if(!src.ExpectTokenChar('{'))
        return false;

    ....

    return true;
}
```

...and in other cases you will typically have a lot of guardian code near the top of a method

```csharp
public void PerformSomeTask(string name, int value, SomeEnum something)
{
    if(something == SomeEnum.IrrelevantForSomeReason)
        return;

    if(value == 0)
        return;

    if(string.IsNullOrWhiteSpace(name)) 
        return;

    ….
}
```

While this in many cases is perfectly fine, some situations leave you with a whole lot of boilerplate. You could of course compact it to a series of oneliners like

```csharp
if(!src.ExpectName("Version")) return false;
```
But it is still somewhat cluttered.
If one could instead write the following pattern

```csharp
<- (boolean expression) (value);
```

which unrolls to

```csharp
if( (boolean expression) )
    return (value);
```
where if the value is omitted it will default to the return type's default value.
This would result in the following code for the previous example

```csharp
public static bool Parse(ref src Lexer, ref SomeType someType)
{
    <- !src.ExpectName("Version");
    <- !src.ReadNumber(out someType.version);
    <- !src.ExpectTokenChar('{');

    ....

    return true;
}
```

If you need a different return value one can be supplied after the boolean expression.

```csharp
public Vector3 GetLocalUp(float angle)
{
    // If the angle is negligible, just return the default Up vector.
    <- (MathF.Abs(angle) < 0.0001f) Vector3.UnitY;
    ....
}
```

It would arguable be even more succinct than a switch case in some shorter mapping scenarios

```csharp
public VkFilter ToVk(Filter filter)
{
    <- (filter == Filter.Near) VkFilter.Nearest;
    <- (filter == Filter.Cubic) VkFilter.CubicImg;
    <- (filter == Filter.Linear) VkFilter.Linear;
    throw new NotSupportedException("Unsupported Filter type");
}
```

Where the expression switch case would be
```csharp
public VkFilter ToVk(Filter filter)
{
    return filter switch
    {
        Filter.Near => VkFilter.Nearest,
        Filter.Cubic => VkFilter.CubicImg,
        Filter.Linear => VkFilter.Linear,
         _ => throw new NotSupportedException("Unsupported Filter type")
    };
}
```

Just like 'var', the various null operators or the ability to omit {} for single commands, this feature is purely syntactic sugar that exists to increase readability.

**Comment by Joe4evr** [comment] 2020-03-02 14:34
#138, #325, #1368, #2966.

**Comment by YairHalberstadt** [comment] 2020-11-19 10:16
Closing as duplicate of #138, #325, #1368, #2966

**Closed by YairHalberstadt** 2020-11-19 10:16 UTC
