### ISSUE TITLE
[Proposal] Default types for generics

### ISSUE THREAD

**Issue by JustNrik** [dotnet/csharplang#2837] opened 2019-09-28 16:56 UTC
Some months ago, this was suggested #2484 back in that time I really didn't fine any valid use-case and the example provided back then wasn't useful enough to understand how this proposal could actually be useful, today, messing around with WPF commands I found a valid use-case to make this proposal.

### The problem

Some times, when we have a generic class or method, there are situations where we don't actually need the generic argument. But we still must provide a generic type even if we ain't gonna use it.

Example:

```cs
public abstract class Command : ICommand
{
    public event EventHandler CanExecuteChanged;

    public abstract bool CanExecute(object parameter);
    public abstract void Execute(object parameter);

    public void RaiseCanExecute()
        => CanExecuteChanged?.Invoke(this, EventArgs.Empty);

    public static Command<Window> Create(Action<Window> action) 
        => new Command<Window>(null, _ => true, action);

    public static Command<TWindow> Create<TWindow>(TWindow window, Action<TWindow> action) 
        where TWindow : Window
        => new Command<TWindow>(window, _ => true, action);

    public static Command<TWindow> Create<TWindow>(TWindow window, Func<TWindow, bool> condition, Action<TWindow> action) 
        where TWindow : Window
        => new Command<TWindow>(window, condition, action);
}

public class Command<TWindow> : Command where TWindow : Window
{
    protected readonly Action<TWindow> _action;
    protected readonly Func<TWindow, bool> _condition;
    protected readonly TWindow _window;

    internal Command(TWindow window, Func<TWindow, bool> condition, Action<TWindow> action)
    {
        _action = action;
        _condition = condition;
        _window = window;
    }

    public override bool CanExecute(object _)
        => _condition.Invoke(_window);

    public override void Execute(object _)
        => _action.Invoke(_window);
}
```

There's a bunch of code and 2 classes just to avoid giving a generic argument when I don't need it. If this proposal was possible, all this mess would be done this way:

```cs
public class Command<TWindow = Window> : ICommand where TWindow : Window
{
    protected readonly Action<TWindow> _action;
    protected readonly Func<TWindow, bool> _condition;
    protected readonly TWindow _window;

    private Command(TWindow window, Func<TWindow, bool> condition, Action<TWindow> action)
    {
        _action = action;
        _condition = condition;
        _window = window;
    }

    public override bool CanExecute(object _)
        => _condition.Invoke(_window);

    public override void Execute(object _)
        => _action.Invoke(_window);

    public void RaiseCanExecute()
        => CanExecuteChanged?.Invoke(this, EventArgs.Empty);

    public static Command<TWindow> Create(Action<TWindow> action) 
        => new Command<TWindow>(null, _ => true, action);

    public static Command<TWindow> Create(TWindow window, Action<TWindow> action) 
        => new Command<TWindow>(window, _ => true, action);

    public static Command<TWindow> Create(TWindow window, Func<TWindow, bool> condition, Action<TWindow> action) 
        => new Command<TWindow>(window, condition, action);
}
```

now it would be possible to do

```cs
public class ViewModel
{
    public ICommand Exit { get; }
    public ViewModel(MainWindow window)
    {
        Exit = Command.Create(_ => Application.Current.Shutdow(0)); // creates a Command<Window>
    }
}
```

instead of 

```cs
public class ViewModel
{
    public ICommand Exit { get; }
    public ViewModel(MainWindow window)
    {
        Exit = Command<Window>.Create(_ => Application.Current.Shutdow(0));
        // Or
        Exit = Command.Create<Window>(_ => Application.Current.Shutdow(0));
    }
}
```

Inb4 "if you don't need the generic argument on some cases, why not just create a non-generic class and a generic one and make both to implement ICommand?"

it's because it's more typing. My suggestion is that basically, the codegen for default type for generic is that this would generate 2 classes under the hood, a non-generic one using the default type and the generic one which is the one we make. In this case, we have all the functionality of 2 classes (non generic and generic one) by just typing `<T = DefaultType>`

Of course, a feature like this would require some restrictions, like not being able to make the non-generic class explicitly to avoid ambiguity and such.

**Comment by Joe4evr** [comment] 2019-09-28 17:51
You know it's not conducive to open duplicate issues, right?

**Comment by MgSam** [comment] 2019-09-30 03:40
https://github.com/dotnet/csharplang/issues/278 looks to be the original among the chain of duplicates

**Comment by YairHalberstadt** [comment] 2020-11-08 09:50
Closing as duplicate of #278. Feel free to add your example there.

**Closed by YairHalberstadt** 2020-11-08 09:51 UTC
