### ISSUE TITLE
Generic Names

### ISSUE THREAD

**Issue by Flutterish** [dotnet/csharplang#3703] opened 2020-07-17 14:08 UTC
Just like in tuples, it would be nice to have a generic item name.
```cs
public class ValueContainer<T:Tname> {
    public T Tname;
    public ValueContainer ( T Tname = default ) {
        this.Tname = Tname;
    }
}
```
```
var A = new ValueContainer<double:Angle>( Angle: Math.PI );
var sin = Math.Sin( A.Angle );
var cos = Math.Cos( A.Tname ); // also valid when name is unspecified
```

**Comment by jnm2** [comment] 2020-07-17 14:18
The first example is a duplicate of https://github.com/dotnet/csharplang/issues/280.

**Comment by jnm2** [comment] 2020-07-17 14:27
This is a duplicate of https://github.com/dotnet/csharplang/issues/1883.

(corrected)

**Comment by 333fred** [comment] 2020-07-17 15:17
Closing as a duplicate.

**Closed by 333fred** 2020-07-17 15:17 UTC
