### ISSUE TITLE
Request for more advanced 'new Constraint'

### ISSUE THREAD

**Issue by flo4004** [dotnet/csharplang#1330] opened 2018-02-20 13:10 UTC
Please add the possibility to "request" specific arguments for `new()` like `public void Foo<T>() where T : Bar, new(float f1, int i1, string str)`

**Comment by jnm2** [comment] 2018-02-20 13:12
This is a duplicate of https://github.com/dotnet/csharplang/issues/769.

**Comment by gafter** [comment] 2018-02-20 16:02
This feature would become available as a side-effect of #110, which is under consideration by the LDM.

**Closed by gafter** 2018-02-20 16:02 UTC
