### ISSUE TITLE
Allow Expression Trees with async/await

### ISSUE THREAD

**Issue by jmaine** [dotnet/csharplang#1505] opened 2018-05-09 03:43 UTC
Example:
`Expression<Func<Func<Task<int>> Task<bool>>> lambda = async f => await f() < 5;  `

'Await' here will be translated to System.Linq.Expressions.AwaitExpression without creating a state machine when c# compiler runs.

lambda.compile() would be responsible translating the expression tree with AwaitExpression into the needed state machines that make the newly compiled async/await method work.

**Comment by Joe4evr** [comment] 2018-05-09 08:30
Related/duplicate of #158.

**Closed** 2020-10-15 12:21 UTC
