### ISSUE TITLE
Can't infer type arguments when passing argument of a generic delegate type with an out parameter.

### ISSUE THREAD

**Issue by gdar91** [dotnet/csharplang#2927] opened 2019-11-02 13:31 UTC
Trying to implement `IEnumerable<>.Choose extension` function, similar to F#'s.
This function is a combination of `Where` and `Select`. For each element, it decides whether the element should be in a result collection and in which shape.

```
public delegate bool Chooser<TElement, TProjection>(TElement element, out TProjection projection);


public static IEnumerable<TProjection> Choose<TElement, TProjection>(
    this IEnumerable<TElement> source,
    Chooser<TElement, TProjection> chooser
)
{
    foreach (var item in source)
    {
        if (chooser(item, out var projection))
        {
            yield return projection;
        }
    }
}
```
As a second argument, it takes a chooser, which is a delegate type, taking the current element and returning a boolean, indicating if it should be included in a result set and the projected result element itself as an out parameter, very much like `bool int.TryParse(string s, out int result)` but with generic arguments.

The problem is, the Choose extension method can't infer the type parameter of the out variable.
```
new[] { "one", "2", "three", "4", "5" }.Choose(int.TryParse);
```
In the example above, it's obvious that the type should be an `int` but I still get an error with this message: "The type arguments for method * cannot be inferred from the usage. Try specifying the type arguments explicitly."
It works if you specify them explicitly:
```
new[] { "one", "2", "three", "4", "5" }.Choose<string, int>(int.TryParse);
// or
new[] { "one", "2", "three", "4", "5" }.Choose((string s, out int i) => int.TryParse(s, out i));
// or even
new[] { "one", "2", "three", "4", "5" }.Choose((Chooser<string, int>) int.TryParse);
```

I think it's a technical flaw in the type inference system.

Platform: .NET Core 3.0
C# Version: 8.0

**Comment by HaloFour** [comment] 2019-11-02 13:52
> I think it's a technical flaw in the type inference system.

It would only be a technical flaw if the language specification stated that the compiler should be able to infer the generic type arguements in these scenarios.  It likely doesn't.  I'm not saying it shouldn't, I'd like to see more type inference.

This is the right repo to request changes to the language spec, tho.

**Comment by alrz** [comment] 2019-11-03 06:06
Duplicate of https://github.com/dotnet/csharplang/issues/129. It was champion for four days.

**Closed** 2019-11-05 13:40 UTC
