### ISSUE TITLE
Proposal: Functions can return "this" instead of void

### ISSUE THREAD

**Issue by Terry1511512** [dotnet/csharplang#1472] opened 2018-04-23 00:43 UTC
I would like to propose that a function can return "this" instead of void making function chaining a little neater.

public class A() 
{
public this F1(){}
public this F2(){}
public this F3(){}
}

var A1 = new A();

A1.F1().F2().F3();

**Comment by jnm2** [comment] 2018-04-23 01:02
See https://github.com/dotnet/csharplang/issues/252, https://github.com/dotnet/csharplang/issues/902.

**Comment by DavidArno** [comment] 2018-04-23 07:17
```cs
public class A()
{
    public A F1() => this;
    public A F2() => this;
    public A F3() => this;
}

var a1 = new A();

a1.F1().F2().F3();
```
There you go; it now compiles. :wink:

**Comment by sharwell** [comment] 2018-04-23 13:31
Duplicate of #902

**Comment by YairHalberstadt** [comment] 2020-10-14 14:21
Closing as duplicate of #902

**Closed by YairHalberstadt** 2020-10-14 14:21 UTC
