### ISSUE TITLE
Proposal: Scope enum to argument position

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/csharplang#543] opened 2017-05-04 20:30 UTC
Let's use `Directory.Delete` as an example
```c#
Directory.Delete(@"C:\Temp", true); // not obvious what true means when reading it.
```
Naming the argument makes it clear but is not mandatory

```c#
Directory.Delete(@"C:\Temp", recursive: true);
```

An alternative is using an enum:
```c#
public enum DeleteMode
{
    TopLevel,
    Recursive
}

Directory.Delete(@"C:\Temp", DeleteMode.Recursive); // A bit clumsy with Enum.Member
```

This is the proposal:

```c#
public enum DeleteMode
{
    TopLevel,
    Recursive
}

// Like if there was a `using static DeleteMode;` but only scoped to the argument position.
Directory.Delete(@"C:\Temp", Recursive);
```

**Comment by svick** [comment] 2017-05-04 21:06
This is a duplicate of https://github.com/dotnet/csharplang/issues/354.

**Comment by JohanLarsson** [comment] 2017-05-04 21:08
Oh, very much a duplicate, sry about that.

**Comment by YairHalberstadt** [comment] 2020-10-13 05:42
Closing as duplicate

**Closed by YairHalberstadt** 2020-10-13 05:42 UTC
