### ISSUE TITLE
Idea: fullnameof()

### ISSUE THREAD

**Issue by janniksam** [dotnet/csharplang#2154] opened 2019-01-18 09:50 UTC
I like the nameof() functionality that was implemented a few versions ago.

I would love to have a similar functionality for full namespace:

An example:
[ServiceInterface(Name = nameof(IServiceInterface), ConfigurationName = "Foo.Bar.Test.IServiceInterface")]
public interface IAsyncServiceInterface : IServiceInterface

Could look like this:
[ServiceInterface(Name = nameof(IServiceInterface), ConfigurationName = namespaceof(IServiceInterface))]
public interface IAsyncServiceInterface : IServiceInterface

What you guys think about it?

**Comment by Unknown6656** [comment] 2019-01-18 10:07
The namespace of a type `abc.def.ghi` is usually `abc.def` (leaving aside the possiblity of nested types). To retrieve this string, one usually uses `typeof(....).Namespace` or `.....GetType().Namespace`.

To retrieve the fully qualified type name, one uses `typeof(....).FullName` or `.....GetType().FullName`.
This -- as far as I understood your aim correctly -- is the string you are interested in.

What exactly are you proposing? A compile-time constant resolution of the Properties `Type.Namespace` and `Type.FullName`?
What are real-world applications of this feature? (considering that compile-time "constant" instances of `System.Type` are allowed to be passed to attributes)

**Comment by svick** [comment] 2019-01-18 13:15
If you actually want the full name of the type, not just the namespace, then I think this is a duplicate of https://github.com/dotnet/csharplang/issues/701.

**Comment by alrz** [comment] 2019-01-18 13:21
>one usually uses typeof(....).Namespace

I think there was a proposal to make those compile-time constants so you can use it in attributes (or any const context).

**Comment by svick** [comment] 2019-01-18 13:45
@alrz I think you're talking about https://github.com/dotnet/roslyn/issues/10972.

**Comment by jnm2** [comment] 2020-05-13 13:03
@janniksam Could you close this one please since you've linked to the original?

**Comment by 333fred** [comment] 2020-05-13 15:21
Closing as a duplicate.

**Closed by 333fred** 2020-05-13 15:21 UTC

**Comment by jnm2** [comment] 2024-10-11 21:14
This would be addressed by a proposal to make `typeof(IServiceInterface).Namespace` a constant, usable in the sample you gave. https://github.com/dotnet/csharplang/issues/8505
