### ISSUE TITLE
Update Blocks

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#1879] opened 2018-09-22 10:27 UTC
I really like how C# lets you set properties after calling new():
````
var p = new Person(){
  Name ="Bob Smith",
  Age = 21,
};
````
It is also unfortunate that you can't use a similar syntax once the object is created.  It would be great if I could do something similar to the following:
````
var p = GetPerson(){
  DateOfBirth = DateTimeOffset.Parse(NewDateOfBirth"  
  Updated_At = DateTimeOffset.UtcNow,
};
````

I also hate how with lots of objects, I have to define a temporary variable in order to set child properties:
````
var Document = new RadFlowDocument();
var Editor = new RadFlowDocumentEditor(Document);
var Line = Editor.InsertLine("Conflict Check Summary");
Line.Paragraph.Alignment = Alignment.Center;
Line.Paragraph.FontSize = 28;
Line.Paragraph.FontFamily = "Calibri Light";
````
As a solution to both of these challenges, I suggest Update Blocks.  They would look something like this:
````
var Document = new RadFlowDocument();
var Editor = new RadFlowDocumentEditor(Document);
var Line = Editor.InsertLine("Conflict Check Summary").{
  Paragraph.{
    Alignment = Alignment.Center;
    FontSize = 28;
    FontFamily = "Calibri Light";
  }
};
````

**Comment by TonyValenti** [comment] 2018-09-22 14:45
I really like the language extensions proposed in #803.  It would be 1% nicer if they were actually part of the language but those extensions get me 99% of the way there and I'm quite happy with them.

**Comment by YairHalberstadt** [comment] 2020-10-18 13:39
Closing as duplicate of #803 and https://github.com/dotnet/csharplang/discussions/1534 among others

**Closed by YairHalberstadt** 2020-10-18 13:39 UTC
