### ISSUE TITLE
[Proposal] ? can also be used when setting values.

### ISSUE THREAD

**Issue by Yinimi** [dotnet/csharplang#1896] opened 2018-09-28 21:20 UTC
This operator can already be used when calling methods like this:

`myObj?.Update();`

It would be awesome if I could also use this when setting values:
**Edit: a better example**

When stopping my car the turboloaders state can be set to inactive.

If it's an old car that doesn't have a turboloader just ignore the command.
`myCar.TurboLoader?.State = TurboLoaderState.Inactive;`

By using the operator the coder would clarify he knows it can be null.
And you would not need those `!= null` if's.

**Comment by theunrepentantgeek** [comment] 2018-09-28 22:51
In isolation, this _almost_ looks like a good idea.

I had to stop and think hard about the semantics of this - I'm guessing that the only possibility would be to bypass the assignment.

Intuitively, the code becomes this
```
null = TurbloLoaderState.Inactive;
```
which looks very odd indeed; I'm pretty sure there's nowhere existing in C# where **null** is treated as an lvalue.

Also, I can't remember the last time I wrote code like this:
```
if (thing != null)
{
    thing.ImportantProperty = someValue;
}
```

There has always been something else within the body of the **if** - some other related activity that also needs to be predicated on the presence of the value.

**Comment by svick** [comment] 2018-09-28 23:42
This is a duplicate of https://github.com/dotnet/csharplang/issues/1106.

**Comment by willard720** [comment] 2018-09-29 06:55
I could use this regularly as well, thing is though, is that it it would have to be shorthand for an if statement, which isn't bad on itself, the bad thing is though, is what @theunrepentantgeek pointed out about about `null` not being an lvalue. 

The way C# works is that assignment evaluates as the value that was assigned, so if I did `WriteLine(X = 5);` that will print `5`, and `Y = X = 5` sets `Y` to be `5`. 

What would be printed if I did, `WriteLine(Foo?.X = 5);`? Surely not 5, but it can't be `null` either, because `null` wasn't assigned. Nothing was assigned, and to print `null` would be kind've lying. Even more troublesome would be `Y = Foo?.X = 5`. Again, what would `Y` be? Normally it would be whatever `Foo?.X = 5` evaluated as, but it didn't evaulate to 5, or to `null`. So there's actually no appropriate value. The only way to do that would be to have any statement that includes an `Foo?.Bar = X` to be skipped when `Bar` is `null`. 

This can lead to other issues. Like this, for example:

```csharp
while (Foo?.X > 10)
{
    if (X > 5) X = null;
}
```

This `while` loop breaks when `X` is 5, not 10. And sure, this example is easy to spot, but it might end up being much harder to spot a mistake like this, where `X` is set a few method calls deep. Either that, or this entire while loop is skipped, or maybe it keeps running until it hits a NRF, or this doesn't compile. 

Basically, it's kind've like an implicit flow control. The flow control of the application is being changed by something that *looks* like just regular assignment, which I *really really* don't like. All other flow controls start with a keyword and is then wrapped with parens, an assignment. When you see `lvalue = rvalue` you don't think that it could change the flow. 

Another idea is to only allow it to work when it's return value isn't being used. That would prevent these errors, but it would be very weird and aggervating to have this form of assignment only work in one place, when normal assignment works in so many more places, so no matter what, you're breaking expectations that people are used to. 

And trust me, I've wanted this *so* many times. It just really doesn't make sense. 

I tried thinking of a way to write an extension method, but I don't think there is one. Unless there is someway to use reflection to do, `myCar.TurboLoader.Set("State", Inactive);` but that would probably not be good for performance anyways.

**Comment by jnm2** [comment] 2018-09-29 13:57
`foo?.Property = obj` is not that different in spirit to `foo?.Event += handler` which I'd also use regularly. 

Another way to look at it is that `foo?.Property = obj` is logically `foo?.set_Property(obj)`—something we could already do if there was a way to address the property setter directly.

**Comment by YairHalberstadt** [comment] 2018-09-29 19:55
This sort of works as an extension method:
```csharp
 public static void DoIfNotNull<T>(this T object, Action<T> action)
 {
     if (object != null)
         action(object);
 }
...
foo.DoIfNotNull(f => f.property = 5);
```
That said, something neater would be nice. However I'm with @willard720 on this: The syntax doesn't really work.

Alternatively, being able to pass a property setter to a method would also make writing an extension method significantly easier.

**Comment by willard720** [comment] 2018-09-30 08:41
@YairHalberstadt If we could do ref properties, then it could be something like

```csharp
public static void Set(this object obj, ref T property, T value)
{
    if (obj != null) property = value;
}
...
foo?.Set(ref X, 42);    // Even though the ? is not needed, I feel it explicitly expresses the
                        // intent and understanding that this line might not be executed, 
                        // but that's fine and won't break anything, so I feel better using it
```

@jnm2 
> `foo?.Property = obj` is not that different in spirit to `foo?.Event += handler` which I'd also use regularly

You're right, which is why the event one also shouldn't be in it because it still doesn't make sense. I'd much rather have a ref property and make an extension method on `object`. It being a `void` method means we can't use it in any of those places I already mentioned, and it's not breaking any preexisting constructs to add, besides just giving ref properties, which some people want anyways. 

And I'm sure likewise could be written to add/remove events via extension methods as well.

**Comment by YairHalberstadt** [comment] 2018-09-30 11:59
@willard720

I have created an issue suggesting a way to do something similar to passing a property by reference. https://github.com/dotnet/csharplang/issues/1901.

Please let me know what you (and anyone else here) thinks.

**Comment by jnm2** [comment] 2018-09-30 13:31
@willard720 In UI code this type of pattern is common:

```c#
public object DataSource
{
    set
    {
        if (dataSource == value) return'

        if (dataSource is IBindingList originalBindingList)
            originalBindingList.ListChanged -= OnListChanged;

        dataSource = value;
        
        if (dataSource is IBindingList newBindingList)
            newBindingList.ListChanged += OnListChanged;
    }
}
```

It happens frequently and there is not really a way to misunderstand `?.ListChanged += OnListChanged` so I'm rooting for it along with `?.FieldOrProp = value` which is also not really possible to misunderstand.

**Comment by YairHalberstadt** [comment] 2020-10-13 08:57
Closing as duplicate of https://github.com/dotnet/csharplang/issues/1106

**Closed by YairHalberstadt** 2020-10-13 08:57 UTC
