### ISSUE TITLE
VB-style With block

### ISSUE THREAD

**Issue by mdawson67** [dotnet/csharplang#2355] opened 2019-03-19 14:49 UTC
VB-style With block to perform multiple operations on a class without having create fluent code.  Similar in though to an initializer, but allows for non-initialization operations.

```
class Person
{
	public string Name;
	public bool Tired;
	public void WakeUp() {}
	public void GoToWork() {}
	public void GoHome() {}
}

// regular code:
var person = new Person();
// do some non-fluent things
person.Name = "Some Name";
person.WakeUp();
person.GoToWork();
if (person.Tired)
	person.GoHome();

// With code, accessor (.) on object
var person = new Person();
// do some non-fluent things 
person.
{
	Name = "Some Name";
	WakeUp();
	GoToWork();
	if (Tired)
		GoHome();
}

// alternate With code, accessor (.) on members
var person = new Person();
// do some non-fluent things 
person
{
	.Name = "Some Name";
	.WakeUp();
	.GoToWork();
	if (.Tired)
		.GoHome();
}
```

For brevity, have the accessor on the object so that intellisense can also offer a With block, and provide intellisense inside the block.

**Comment by Unknown6656** [comment] 2019-03-19 14:59
please do place your code inside an code-block to increase the readability of your proposal, as follows:
````
```csharp
    <your code goes here>
```
````

**Comment by HaloFour** [comment] 2019-03-19 15:02
You can use code fences to make the sample easier to read: https://help.github.com/en/articles/creating-and-highlighting-code-blocks

We've had a number of requests for this feature on the repo.  My opinion is always that `with` blocks are unnecessary as they don't provide any advantages to an assignment over a tersely-named temporary variable.

Your second example creates a situation where the LHS could resolve to either a member on the target or to some other identifier in scope.

**Comment by mdawson67** [comment] 2019-03-19 16:12
Thanks for the formatting tips...this is my first post and didn't think of that.  I could not find other posts on this feature or else I would have chimed in on one of those.

> Your second example creates a situation where the LHS could resolve to either a member on the target or to some other identifier in scope.

Good point.

**Comment by yaakov-h** [comment] 2019-03-19 19:41
Near-duplicate of #803.

**Comment by JustNrik** [comment] 2019-03-21 02:17
My suggested use cases:

```cs
var person = new Person(someArgs);

with (person)
{
    .DoStuff();
    .SomeProperty = someValue;
    // etc...
}

// another use
// can be used with hard cast but will throw if fail regardless (?)

with (person as Student)?
{
    // do stuff as Student, nothing if soft cast fails
    // without the ? it will enter the scope, but if it's null then you risk NullReferenceException normally.
}

// another use
// only applicable to settable properties and fields

with (Console.ForegroundColor = ConsoleColor.Blue) // Saves the current color somewhere
{ // in this scope ForegroundColor is blue
	
} // Foreground color goes back to whatever it was before
// Can use commas to set multiple properties, they will back to whatever they were before at the end of the scope
```

**Comment by RobotAL76** [comment] 2019-03-22 20:52
@mdawson67 @JustNrik 

Currently it is possible simulate `with` block functionality by effective extension methods and even got some benefits which not supported by classical initialization blocks

```c#
/* null safe initialization */

GetPerson().To(out var p)?.With
(
    p.Age = 32,
    p.Name = "Any Name"
);
```
```c#
/* method calls and outing of variables */

new Person().To(out var p).With
(
    p.Age = 32,
    p.Name = "Any Name",
    p.ToString().To(out var description)
);

Console.WriteLine(p.Age);
Console.WriteLine(p.Name);
Console.WriteLine(description);
```
<details>
<summary>
Example of an implementation
</summary>

```c#
/* The Language Extensions */
public static class LE
{
    	/* type casting */
	public static object ChangeType<T>(this object o) =>
		o is null || typeof(T).IsValueType || o is IConvertible ? Convert.ChangeType(o, typeof(T), null) : o;
    
    	public static T To<T>(this T o) => o;
	public static T To<T>(this object o) => (T)o.ChangeType<T>();
	public static ref T To<T>(this T o, out T x) { x = o; return ref x; }
	public static ref T To<T>(this object o, out T x) { x = (T)o.ChangeType<T>(); return ref x; }
	public static ref T? To<T>(this object o, out T? x) where T : struct { x = (T?)o; return ref x; }
	
	public static T With<T>(this T o) => o;
	public static T With<T, A>(this T o, A a) => o;
	public static T With<T, A, B>(this T o, A a, B b) => o;
	public static T With<T, A, B, C>(this T o, A a, B b, C c) => o;
	public static T With<T, A, B, C, D>(this T o, A a, B b, C c, D d) => o;
	/* etc */
}
```

</details>

**Comment by mdawson67** [comment] 2019-03-22 21:33
> with (person) {...}

I prefer this construct over my original suggestion.  It feels much like using(obj) and lock(obj)

**Comment by spixy** [comment] 2019-05-14 21:04
@JustNrik 

- `with (person as Student)?` can be just written as `if (person is Student student)`

- use can use undo with `using`: https://gist.github.com/spixy/e51937de63d1a6fde7d01a7043e93d8f

**Comment by JustNrik** [comment] 2019-05-15 00:00
> 
> 
> @JustNrik
> 
>     * `with (person as Student)?` can be just written as `if (person is Student student)`
> 
>     * use can use undo with `using`: https://gist.github.com/spixy/e51937de63d1a6fde7d01a7043e93d8f

The second is really nice!

The first one has nothing to do with my suggestion. It's not just pattern matching but also following the suggested `with` feature, `if (parse is Student student)` literally defeats the whole purpose of using `with` in the first place.

**Comment by YairHalberstadt** [comment] 2020-10-23 13:01
Closing as duplicate of https://github.com/dotnet/csharplang/issues/803 and https://github.com/dotnet/csharplang/discussions/1534 among others

**Closed by YairHalberstadt** 2020-10-23 13:01 UTC
