### ISSUE TITLE
Proposal: Emit expression tree's on type members

### ISSUE THREAD

**Issue by koenbeuk** [dotnet/csharplang#1442] opened 2018-04-06 06:23 UTC
Consider this example:
```  
class Student
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string FullName => FirstName + " " + LastName;
}

var query = students.Where(x => x.FullName == "Jon Doe"); // this will fail when the provider (e.g.  EF core) needs insights into the computation of FullName
```

Instead we'll have to pass in an Expression like
```students.Where(x => (x.FirstName + " " + x.LastName) == "Jon Doe")```

Assuming that this expression is used often, we can define the expression once and then reuse it however this is not trivial, e.g.:

```
    class Student
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        // Can only be used in select clauses only (limited subset)
        public Expression<Func<Student, string>> FullNameExpression { get; } = student => student.FirstName + " " + student.LastName;
        // Can only be used in where clauses only
        public static Expression<Func<Student, bool>> CreateFullNameEqualsExpression(string fullName) => (Student student) => student.FirstName + " " + student.LastName == fullName;
        // only used for local evaluation
        public string FullName => FullNameExpression.Compile().Invoke(this);
    }
```

The compiler already has ability to turn a regular lambda into an expression tree. What we also want is to have the compiler emit an Expression tree for an arrow function on demand, e.g. this could be done with the use of an attribute.

```
class Student
{
    public string FirstName { get; set; }
    public string LastName { get; set; }  
    [LazyEvaluate] // Name just being a placeholder...
    public string FullName => FirstName + " " + LastName;
}
```
Where the compiler will store the Expression tree on the LazyEvaluate attribute as well as compiles the actual property so that local evaluation does not change.

This would allow queries like the following:
```
var r1 = students.Where(x => x.FullName == "Jon Doe")  // FullName can be used in a where clause
                .Select(x => new { Student = x, FullName = x.FullName }) // FullName can be used in a select clause, either directly or as part of a larger model
                .FirstOrDefault();

r1.Student.FirstName = "Joe";
Console.WriteLine(r1.FullName); // Prints: "Jon Doe"; FullName is precomputed and stored as a property on r1
Console.WriteLine(r1.Student.FullName); // Prints: "Joe Doe"; FullName is being computed on the fly.
```
A provider would evaluate each MemberAccess expression and if the member type has an LazyEvaluate attribute, it would find the actual expression in there.

This would also allow for further improvements, e.g. exposing an expression tree for (static) methods that optionally takes parameters.

Thoughts?

**Comment by YairHalberstadt** [comment] 2020-10-14 09:28
Closing as duplicate of #161

**Closed by YairHalberstadt** 2020-10-14 09:28 UTC
