### ISSUE TITLE
Allow "using type aliases" inside generic classes and allow generic aliases

### ISSUE THREAD

**Issue by mikernet** [dotnet/csharplang#2123] opened 2019-01-08 06:16 UTC
Currently "using type aliases" have to have known generic type parameters because they can't be inside a class. A propose that you allow them to be placed inside types so the generic parameters can be used to create aliases for generic types:

```c#
// Before:

public class WeakValueDictionary<TKey, TValue> : IEnumerable<KeyValuePair<TKey, TValue>> where TValue : class
{
    private Dictionary<TKey, WeakReference<TValue>> _lookup = new Dictionary<TKey, WeakReference<TValue>>();
    // ... 
}

// After:

public class WeakValueDictionary<TKey, TValue> : IEnumerable<KeyValuePair<TKey, TValue>> where TValue : class
{
    using Lookup = System.Collections.Generic.Dictionary<TKey, WeakReference<TValue>>;
    private Lookup _lookup = new Lookup();
    // ... 
}
```

Also somewhat related, allow generic using definitions so you could do something like this:

```c#
using WeakLookup<TKey, TValue> = System.Collections.Generic.Dictionary<TKey, WeakReference<TValue>>;

public class WeakValueDictionary<TKey, TValue> : IEnumerable<KeyValuePair<TKey, TValue>> where TValue : class
{
    private WeakLookup<TKey, TValue> _lookup = new WeakLookup<TKey, TValue>();
    // ... 
}

**Comment by svick** [comment] 2019-01-08 13:03
I think the second part of this proposal is a duplicate of https://github.com/dotnet/csharplang/issues/1239.

**Comment by alrz** [comment] 2019-01-08 15:32
First part would be #218.

**Comment by mikernet** [comment] 2019-01-08 15:35
@alrz Partly yeah, the main motivation I intended here was to be able to use the type's generic type parameters in the using statement which seems like a separate feature.

**Comment by YairHalberstadt** [comment] 2020-10-21 07:16
Closing as duplicates of #1239 and #218 respectively

**Closed by YairHalberstadt** 2020-10-21 07:16 UTC
