### ISSUE TITLE
Proposal: Allow Type Parameters on Generic Types

### ISSUE THREAD

**Issue by Frank0101** [dotnet/csharplang#3521] opened 2020-05-31 01:10 UTC
Hello everyone,
This proposal would allow using interfaces to describe common behaviours for generic classes. For instance let's take the following 2 classes:

```c#
    public class MyMonad1<T>
    {
        private readonly T _value;

        public MyMonad1(T value)
        {
            _value = value;
        }
        
        public MyMonad1<T2> Map<T2>(Func<T, T2> func) => 
            new MyMonad1<T2>(func(_value));
    }
    
    public class MyMonad2<T>
    {
        private readonly T _value;

        public MyMonad2(T value)
        {
            _value = value;
        }
        
        public MyMonad2<T2> Map<T2>(Func<T, T2> func) => 
            new MyMonad2<T2>(func(_value));
    }
```

Would be nice to extract the Map() method into an interface IMonad, written in the following way:

```c#
    public interface IMonad<TMonad, T>
    {
        TMonad<T2> Map<T2>(Func<T, T2> func);
    }
```

or

```c#
    public interface IMonad<TMonad<T>>
    {
        TMonad<T2> Map<T2>(Func<T, T2> func);
    }
```

But unfortunately this is not possible.

Another consequence of this problem is the Select() methods coming from Linq. In that case the workaround is to always return IEnumerable<T>, which however causes the loss of the original type, hence forcing to re-convert the result. For instance:

```c#
var list = new List<int>();
var selectResult = list.Select(v => v.ToString()); // Here would be nice to have a List, but that would require the interface IEnumerable to be written in the way I'm suggesting. Given it's not possible I get an IEnumerable..
var mappedList = selectResult.ToList(); // ..And therefore here I'm forced to re-convert the value to a List
```

**Comment by HaloFour** [comment] 2020-05-31 01:18
https://github.com/dotnet/csharplang/issues/339

**Comment by 333fred** [comment] 2020-05-31 06:34
Closing as a duplicate of the existing HKT issue.

**Closed by 333fred** 2020-05-31 06:34 UTC
