### ISSUE TITLE
Proposal: Default types for generics

### ISSUE THREAD

**Issue by Erlite** [dotnet/csharplang#2484] opened 2019-05-03 20:51 UTC
### Background
I've written a `QueryResult` class today. Pretty simple, it just contains a constructor, two properties and two helper methods:

```cs
public class QueryResult
{
 public bool IsSuccessful { get; }
 
 public string Message { get;}

 public QueryResult(bool success, string message)
 {
     IsSuccessful = success;
     Message = message;
 }
 
 public static QueryResult FromSuccess(string message = "No message specified.")
 {
     return new QueryResult(true, message);
 }

 public static QueryResult FromError(string message = "No message specified.")
 {
     return new QueryResult(false, message);
 }
}
```
Then, a little later, I've decided that I wanted a third property: `Result`. 
Using a generic is the best way to proceed here. However, I've soon realized that I'd need to create a second class and copy/paste everything in while adding the generic property.

### Proposal
Allow generics to have a default value. Example:

```cs
public class QueryResult<T = object>
{
    public bool IsSuccessful { get; }
    
    public string Message { get; }

    public T Result { get; }
}
```
If the user instantiates a `QueryResult` without passing in the type of the generic, `Result` would be of type `object`. This would allow developers to include generics optionally in their classes without having to create another class/file and rewrite everything. The class would behave as if the user instantiated a `QueryResult<object>`.

Other possibility for the syntax:
```cs
public class QueryResult<T> where T : default(object) {}
```

**Comment by HaloFour** [comment] 2019-05-03 20:58
I think this would introduce a lot of ambiguity to the language.  The compiler and the CLR differentiate types by their generic arity, `QueryResult`, `QueryResult<T>` and `QueryResult<T1, T2>` all being completely different types.

In the case above you don't have to (and likely wouldn't want to) have two completely disparate classes.  You could have `QueryResult<T>` extend from `QueryResult` adding in the `T Result` property.  And you could add `static` helper methods to `QueryResult` to create a `QueryResult<T>` when passing a result value.  This is similar to how `Task` and `Task<T>` are defined.

**Comment by JustNrik** [comment] 2019-05-03 20:59
Looks like improper abstraction
Have you tried this?
```cs
interface IQueryResult 
{ 
    bool IsSuccessful { get; }
    string Message { get; }
}
interface IQueryResult<T> : IResult 
{
    T Value { get; } 
}
 ```
Expose IQueryResult if you don't want T Value property

**Comment by theunrepentantgeek** [comment] 2019-05-03 23:42
Adding a default for the generic type parameter makes things easier for *creation* of a new `QueryResult<T>`, but not for *consumption*.

I've taken a different approach to solving the same problem, one that works well with the current language. I use a combination of factory methods and implicit casts to allow code like this:

```
public QueryResult<IList<Person>> FindVeryImportantPeople()
{
    try
    {
        IList<Person> results = _repository.FindVips();
        return results; // implicit cast
    }
    catch (Exception ex)
    {
        return Error(ex.Message); // using static factory method as well
    }
}
```

The class `QueryResult<T>` includes two implicit casts:

*  from `T` to `QueryResult<T>`, returns a result with `IsSuccessful` set **true**.
*  from `Error` to `QueryResult<T>`, returns a result with  `IsSuccessful` set **false**.

(Credit to my colleague Pete (@pebomber) for the technique; it makes code quite clean to read.)

**Comment by svick** [comment] 2019-05-04 07:27
This is a duplicate of https://github.com/dotnet/csharplang/issues/2177.

**Comment by FiniteReality** [comment] 2019-05-04 13:41
In the case of a "result"-like type, wouldn't it be better to just have a base interface, e.g. IResult, and then do pattern matching on the type to get the correct value out of it? e.g.:
```cs
IResult MyMethod()
{
    return x > 5 ? Ok("Some value") : Error("Oh no, an error!");
}

switch (MyMethod())
{
    case OkResult ok:
        // handle OkResult
        break;
    case ErrorResult notOk:
        // handle ErrorResult
        break;
}
```

While a "default" type for generics would be nice in some cases, it adds overhead and also makes certain cases more ambiguous. In your case, you'd have to do a null check on the Result type to make sure it was actually set, and that, in my opinion, is likely to cause more errors than it is going to solve.

**Comment by SilentSin** [comment] 2019-05-11 10:33
You can already do this by just having a non-generic class with the same name inherit from the generic one (or vice-versa, depending on your goals):

```
public class QueryResult<T>
{
    public bool IsSuccessful { get; }
    
    public string Message { get; }

    public T Result { get; }
}

public class QueryResult : QueryResult<object> { }
```

The only difference is that the base type obviously can't be `sealed`.

**Comment by YairHalberstadt** [comment] 2020-10-26 12:53
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/278

**Closed by YairHalberstadt** 2020-10-26 12:53 UTC
