### ISSUE TITLE
Variable Delcarations in Initializers

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#1632] opened 2018-06-14 15:35 UTC
It would be great if I could do the following:
````
var Org = new Company(){
  Name = "Microsoft",
  Employees = {
    new Employee(){Name = "John Smith"}
    , var Nadella = new Employee(){Name = "Satya Nadella"}
  },
  CEO = Nadella
}

````

**Comment by svick** [comment] 2018-06-14 16:05
I think this would be solved by declaration expressions: https://github.com/dotnet/csharplang/issues/595.

**Comment by DavidArno** [comment] 2018-06-15 08:02
Declaration expressions are championed in #973.

Probably best to therefore close this and direct requests for declaration expressions to be supported in object initializers.

**Comment by jcouv** [comment] 2018-07-07 02:53
Declaration expressions are supported in object initializers as of [7.3](https://github.com/dotnet/csharplang/blob/master/Language-Version-History.md#c-73-visual-studio-2017-version-157), which can be used to solve this problem.
I'll go ahead and close this issue. Thanks

**Closed by jcouv** 2018-07-07 02:53 UTC

**Comment by svick** [comment] 2018-07-07 14:39
@jcouv 

Are you saying that if I want to write the code in the initial post in C# 7.3, I should use something like the following code?

```c#
public static T Set<T>(this T input, out T output)
{
    output = input;
    return input;
}

…

var org = new Company {
  Name = "Microsoft",
  Employees = {
    new Employee { Name = "John Smith" },
    new Employee { Name = "Satya Nadella" }.Set(out var nadella)
  },
  CEO = nadella
};

**Comment by jnm2** [comment] 2019-02-06 15:14
Duplicate of https://github.com/dotnet/csharplang/issues/973.
