### ISSUE TITLE
Allow subclasses to add setters to readonly inherited properties

### ISSUE THREAD

**Issue by ekolis** [dotnet/csharplang#2288] opened 2019-03-02 19:40 UTC
Let's say I have a class:

```
public abstract class Person
{
    public virtual int AgeOfMajority => 18;
}
```

and then I want to do this:

```
public class Martian : Person
{
    public override int AgeOfMajority {get; set;}
}
```

I can't do this because Person doesn't have a setter to override. This should be allowed IMO.

**Comment by JustNrik** [comment] 2019-03-03 02:42
`new` keyword is a thing, though.

**Comment by khm1600** [comment] 2019-03-03 04:53
#1568

**Comment by Unknown6656** [comment] 2019-03-03 09:49
> `new` keyword is a thing, though.

would this code work?
```csharp
public class A {
    public virtual int i => 18;
}

public class B : A {
    public new int i => 42;
}

static public void Main() {
    A a = new B();
        
    System.Console.WriteLine(a.i);
}
```

**Comment by jho1965us** [comment] 2019-03-04 10:35
Workaround:

    public class A {
        public virtual int i => 18;
    }

    public abstract class BBase : A {
        public override int i => GetI();
        protected abstract int GetI();
    }
        
    public class B : BBase  {
        public new int i { get; set; }
        protected sealed override int GetI() => i;
    }

    static public void Main() {
        B b = new B();
        b.i = 42;
        A a = b;
        
        System.Console.WriteLine(a.i);
    }

**Comment by willard720** [comment] 2019-03-04 18:50
Just use getter/setter methods at this point, and add a public setting in the child class.

**Comment by datvm** [comment] 2019-03-10 13:14
I have the same proposal, but something like this:

```
        public bool CanRead
        {
            override get => this.canReadField;
            set => this.canReadField = value;
        }
```

This way we explicitly say that we only override the getter, and add the setter.

**Comment by YairHalberstadt** [comment] 2020-10-22 11:46
Closing as duplicate of https://github.com/dotnet/csharplang/issues/1568

**Closed by YairHalberstadt** 2020-10-22 11:46 UTC
