### ISSUE TITLE
Generic Type List

### ISSUE THREAD

**Issue by ghost** [dotnet/csharplang#1388] opened 2018-03-16 20:46 UTC
Generic Type List
# Suggestion:
I suggest to add a new constraint syntax that allow us to supply a list of types that can be used with the generic class, like this:
```
class foo<T>  where T: {int, float, byte}
{
        void DoSomething(T x, T y)
         {
                 T z = x + y;
          }
 }
```

This code should compile with no errors. The compiler have a list with the possible types that can be assigned to T. The compiler should test the foo<T> for all thsese types, i.e. foo<int>, foo<float> , foo<byte>.
if the code of the foo class is ok in all these cases, then it should compile correctly (i.e doesn't complain about the x + y operation) .

# Benefit:
This will solve some problems when there is no common interface to use as a constraint. for more details: https://github.com/dotnet/corefx/issues/27167

# Implementation:
C# can compile the type list as an attribute:

```
public class TypeListAttribute : Attribute
{
    public Type[] Types;
    public TypeListAttribute(params Type[] types)
    {
        Types = types;
    }
} 
```

```
[TypeList(typeof(int), typeof(float), typeof(byte))]
class foo<T>  
{
        void DoSomething(T x, T y)
         {
                 T z = x + y;
          }
 }
```
Then C# uses the TypeListAttribute.Types[] to validate the generic class.

**Comment by CyrusNajmabadi** [comment] 2018-03-16 20:50
How is this code actually compiled down to IL?  Specifically, what does hte compiler do with:

```c#
T z = x + y;
```

?

**Comment by CyrusNajmabadi** [comment] 2018-03-16 20:50
How is this code actually compiled down to IL?  Specifically, what does hte compiler do with:

```c#
T z = x + y;
```

?

**Comment by CyrusNajmabadi** [comment] 2018-03-16 20:53
Isn't thsi subsumed by Shapes/Extensions: https://github.com/dotnet/csharplang/issues/164

You would simply say: i have this shape:

```c#
shape SAddable<T> {
    public static T operator +(T t1, T t2);
}

//...
         void DoSomething<T>(T x, T y) where T : SAddable<T> {
                 T z = x + y;
          }

extension FloatAddable of float : SAddable<float> {
   public static float operator +(float f1, float f2) => f1 + f2;
}

// ...

DoSomething(1.0, 2.0)
```

**Comment by MohammadHamdyGhanem** [comment] 2018-03-16 21:00
@CyrusNajmabadi 
> How is this code actually compiled down to IL? Specifically, what does hte compiler do with:
T z = x + y; ?

I'm not expert with IL, but I think the proplem is at C# compiler, which refuses to do unknown operator. We convince it that we know the types, and it should validate the code against them. In IL the code should work. If there are details I don't konw about how IL work, please tell me.

**Comment by MohammadHamdyGhanem** [comment] 2018-03-16 21:03
My solution is sheaper, shorter, and easier than  Shapes/Extensions. Why do we need to re-define the shape, while we will only deal with a short list of types that are already in shape. and the compiler can see that?

**Comment by JonasZ95** [comment] 2018-03-16 21:09
@MohammadHamdyGhanem The problem is If you want good performance you need to implement the each function for each type in your list. Shapes will solve your problem in a very clean and extendable way. 

Your solution would require the compiler to look at each time and see which methods/propertys/fields It does have and generate some intersection. This could lead to some very weird interactions and will be kinda complex as soon generics and where clauses are involved.

Also I think It's safe to assume that there will be alot of already implemented Shapes for common types.

**Comment by CyrusNajmabadi** [comment] 2018-03-16 21:11
> Why do we need to re-define the shape,

You would only need to redefine the shape if you wanted different behavior.  For example, you might want an 'addable' thing that didn't add in a normal way (not sure why you'd want this, but maybe you have a use case).

**Comment by MohammadHamdyGhanem** [comment] 2018-03-16 21:22
It was about the genral Enum class at first. I suggested many other ways to solve this, but this here is the best.
I don't mind to use shapes when needed. But if there is a shorter solution in some situation, so it will be nice to consider it as well.

**Comment by MohammadHamdyGhanem** [comment] 2018-03-16 21:28
@JonasZ95 
> Your solution would require the compiler to look at each type and see which methods/propertys/fields It does have and generate some intersection. This could lead to some very weird interactions and will be kinda complex as soon generics and where clauses are involved.

1- This is all at design time, so it will not affect the runtime performance.
2- But no need for that at first place. The compiler can resolve the T for all the types in the list, and validate the code for foo<int<. foo<f;oat> and foo<byte>. If all these posibale pathes pass, the the code is ok. No reflection  and no intersection are needed.

**Comment by CyrusNajmabadi** [comment] 2018-03-16 21:46
>  so it will not affect the runtime performance.

At runtime how does this work?  What if T happens to a long?  What if it is a an int?  How does the add actually happen?

**Comment by JonasZ95** [comment] 2018-03-16 21:52
@MohammadHamdyGhanem 

> 2- But no need for that at first place. The compiler can resolve the T for all the types in the list, and validate the code for foo<int<. foo<f;oat> and foo. If all these posibale pathes pass, the the code is ok. No reflection and no intersection are needed.

So you get absolutely no auto complete information and need to 'compile' the class for each type to validate It? This can increase the compile time by a significant amount and does alot of necessary things just to validate that those types work. This is very complex and I cann't iterate about all corner cases now but this probably turns out to be impossible.

Also how does this deal with multiple type parameters? Imagine 3 type parameters with each 3 possible types how is this express and do you really want to test 27 different combinations by testing each one? This gets even worse there more you throw into this.

**Comment by MohammadHamdyGhanem** [comment] 2018-03-16 22:25
> At runtime how does this work? What if T happens to a long? What if it is a an int? How does the add actually happen?

The same as when yo add two longs. Numeric classes don't hvae arithmitic methods or operators. The Compiler knows how to do this once it knows the type of each operand. Why should I care about this? The problem is at the C# compiler level, which refuses to compile late binding code. Once you convince it that the types are known and it let the code pass, every thing else will work normally, unless you have specifice details about IL that make a this a problem.

**Comment by MohammadHamdyGhanem** [comment] 2018-03-16 22:31
@JonasZ95 
You have a point, put this is a solution to specific problem that can't involve your complicated cases. I already consedred your cases with a Shape-Like solution:
https://github.com/dotnet/csharplang/issues/1387
That will be suitable for more than one generic type parameter.

**Comment by CyrusNajmabadi** [comment] 2018-03-16 22:44
> The same as when yo add two longs. 

So if i have two ints, i'll potentially get something larger than an int?

>  Numeric classes don't hvae arithmitic methods or operators. The Compiler knows how to do this once it knows the type of each operand

Yes.  BUt here we don't know what hte type will be at runtime.  You said it could be a  long or an int.  So the compilre will not know how to add those two things together.

>Why should I care about this? 

Because you're proposing that the language do this, but you're not answering how.  If we can't figure how do implement htis, how could we deliver the feature? :)

> Once you convince it that the types are known and it let the code pass, every thing else will work normally

I don't see how.  Let's just consider a simple case:

```c#
class MyClass1 {
   public int Length { get; }
}

class MyClass2 {
   public string Length { get; }
}

void DoSomething<T>(T x) where T : { MyClass1, MyClass2 }
{
  var v = x.Length;
  Blah(v);
}

void Blah(int i) { }
void Blah(string s) { }
```

The compiler can check that the code for DoSomething works if T is a MyClass1 or if T is a MyClass2.  But then at runtime what happens?  How does it compile this?  'v' may be a int or a string.  How does it know which Blah to call?  you have hte "call" instruction, but it needs an actual description to the real method called.  In this case there are two possibilities.  How do you encode this?

**Comment by JonasZ95** [comment] 2018-03-16 23:09
@MohammadHamdyGhanem 
Actually If there's a new language feature added I don't want It to be heavily limited. Implementing this feature would either end up very complex or very powerless. Could you elaborate why Shapes aren't the solution for your problem? Shapes can be implemented in a very performant way. They avoid alot very complex problems your solution brings to the table. They also play nicely with Auto Completion.

I don't really understand why you think this will be any better than a possible Shape implementation which would work in alot of cases and would be by far more powerful. This has been proven by alot of other languages so far. Is there any reason you would even want to specify specific types instead of a shape? Also please consider this list would be hardly extendable so If you limit your class to primitive numeric types I cann't use It with my own 2d vector for example.

**Comment by MohammadHamdyGhanem** [comment] 2018-03-16 23:22
@CyrusNajmabadi 
> The compiler can check that the code for DoSomething works if T is a MyClass1 or if T is a MyClass2. But then at runtime what happens? How does it compile this? 'v' may be a int or a string. How does it know which Blah to call? you have hte "call" instruction, but it needs an actual description to the real method called. In this case there are two possibilities. How do you encode this?

I miss something here. In run-time, when the compiler resolves the generic to be a specific type, why there is still a confusion between the two overloads?  DoSomething<MyClass1> will call the Blah(int i) and DoSomething<MyClass2> will call the Blah(string s). This is what I expect the how Jit works. Doesn't it?

**Comment by CyrusNajmabadi** [comment] 2018-03-16 23:26
> This is what I expect the how Jit works. Doesn't it?

No :)

There are two problems here:

1. There is only one set of IL produced by the C# compiler for a generic method.  That IL needs to be fully resolved in terms of things like method calls.  So the IL needs to state: i want to call this *specific* 'Blah' method.  i.e. the 'Blah(int)' method or hte 'Blah(string)' method.  You can see this if you crack open the IL and look at it with any tool (like ILSpy for example).
2. When the JIT compiles generic methods down, it produces only one 'instantiation' of that method for all reference types fed into it.  So there is no way for that to work given that you couldn't have a single instantiation that somehow both called the 'Blah(int)' method or hte 'Blah(string)' method.

**Comment by MohammadHamdyGhanem** [comment] 2018-03-16 23:27
@JonasZ95 
This solution doesn't work with numerics only. You can have any list of related types, incuding DateTime, string, char (all have psrse and format for example). or any other situations.
And I don't refuse shapes. In fact my syntax can be implemnted usin shapes. In most of my propsals, I want a more compact syntax to o things, even there is another long way to do them.

**Comment by CyrusNajmabadi** [comment] 2018-03-16 23:31
> I want a more compact syntax to o things, even there is another long way to do them.

This syntax is longer:

```c#
class foo<T>  where T: {int, float, byte}
{
        void DoSomething(T x, T y)
         {
                 T z = x + y;
          }
 }
```

than:

class foo<T>  where T: SAddable<T>
{
        void DoSomething(T x, T y)
         {
                 T z = x + y;
          }
 }
```

**Comment by Richiban** [comment] 2018-03-20 11:28
I would like to point out that this feature is basically the same as ad-hoc union types https://github.com/dotnet/csharplang/issues/399.

That proposal would have you able to write:
```csharp
void Foo(int|float|byte x)
{
    Console.WriteLine(x + x);
}
```

In the above method the available operations on `x` are limited to those that are available on all the given types of `x` (i.e. the *union* of a number of types means having access to the *intersection* of the members of those types).

Would it be out of the question, in the case of an explicit union list as the OP has requested, to simply have the compiler emit the necessary overloads?

The above would simply lower to:

```csharp
void Foo(int x)
{
    Console.WriteLine(x + x);
}
void Foo(float x)
{
    Console.WriteLine(x + x);
}
void Foo(byte x)
{
    Console.WriteLine(x + x);
}
```

**Comment by MohammadHamdyGhanem** [comment] 2018-03-20 16:36
Thanks all for your response and helpful info. Any solution is OK for me. Each topic you refered to refers to more topic. It is obvious it's a public concern, so why C# team didn't adapt any of this great proposals yet?

**Comment by JonasZ95** [comment] 2018-03-20 17:48
@Richgiban

And how do you calculate this intersection? With extension methods this intersection could change depending on which dependencies you include. It's more complex than you think actually. Also functions with the same type signature and name may have very different semantics.
Imagine two collections for example:
`
void Add(T e, bool sorted);//Weird Simple Array 
void Add(T e, bool tail); //Weird Linked List
`
This could easily end in a security nightmare.

Thus would be more explicit and is already backed by ideas how to implement this.
`
void Foo<T>(T x) where T : SGroup<T>, SDisplay<T>
{
    Console.WriteLine(x + x);
}
`

**Comment by CyrusNajmabadi** [comment] 2018-03-20 18:27
> Would it be out of the question, in the case of an explicit union list as the OP has requested, to simply have the compiler emit the necessary overloads?

What if you have:

```c#
void Foo(int|float|byte x, int|float|byte y, int|float|byte z)
{
    Console.WriteLine(x + x);
}
```

How many overloads will you get?

**Comment by CyrusNajmabadi** [comment] 2018-03-20 18:27
> so why C# team didn't adapt any of this great proposals yet?

Nothing comes for free.

**Comment by Richiban** [comment] 2018-03-20 19:12
@CyrusNajmabadi 

> How many overloads will you get?

That would be 27. However, the case that the OP raised (i.e. restricting a generic parameter to one of a set number of types) would more likely see usage like this:

```csharp
void Foo<T>(T x, T y, T z) where T : {int, float, byte}
{
    // ...
}
```

which would result in three overloads.

I should say at this point that I am very much in favour of the Shapes proposal, and am very glad that it's getting the traction it is. I am also however, ever since I read about them in Ceylon and used them in Typescript, pretty interested in type unions. I'm thinking out loud here.

@JonasZ95 

> And how do you calculate this intersection? 

There's nothing really to calculate; the compiler would run through the method three times, once for each of the given types. If each pass compiles then the method as a whole compiles. This is the same reason that extension methods would work.

> Also functions with the same type signature and name may have very different semantics.

I'm not sure I agree with this argument; I remember being presented with the exact same argument against the introduction of `var` years ago:

"What if I write a statement like this:"

```csharp
var lightSwitch = Foo();

Foo.SwitchOff();
```

"but one day someone comes and changes the `GetItem` method so it actually returns a `LifeSupport` instance! My code still compiles, this is a disaster!".

I don't think that it's really our concern that someone might substitute one type for another with a semantically-different-but-identically-signatured method.

**Comment by JonasZ95** [comment] 2018-03-20 19:55
@Richiban 

> There's nothing really to calculate; the compiler would run through the method three times, once for each of the given types. If each pass compiles then the method as a whole compiles. This is the same reason that extension methods would work.

If you run through the method n times you loose auto complete support and It would get very complex. Also the compile time will get much worse. The compiler would have to generate implementations for all types all the time just to verify. With Shapes the compiler just needs to generate implementations for the types which are used.

> I'm not sure I agree with this argument; I remember being presented with the exact same argument against the introduction of var years ago

No var is completely different. You still know the type of lightSwitch. It's the return type of Foo. It should be clear what Foo returns by the naming and the documentation I can easily see in most IDEs.

With this you got multiple possibilities where you never know which type you currently you use. You have to write multiple tests for each type.  The compiler wont be able to assist because it doesn't know which specific method you use know.

With shapes you can easily get a parameter name and a documentation about this method. If you really want to loose most benefits from a statically typed language just use the dynamic type.

**Comment by MohammadHamdyGhanem** [comment] 2018-03-20 21:45
"Compile time will be worst" is overrated. Using this constraint will be rare and for only one class, if any,  all over the project. This is not expecred to exceed a few milliseconds.
Regardless, even we use shapes, it is still usefull to constraint generics to small list of types.  The compiler should   only refuse any type out of the list without any further action.
I also fined the compact syntax for overloaded methods fascinating. It imaginebit is usrd with trivial methods like Console.Writeline() which have lots of overloads that do exactly tha same thing. Oring all different types will make such classes more compact and easier to read, especially if you can define the ored list as a combined type to use more that once. The compilrt should only generste the overloads and raise errors if the common code is not suitable for one of them, with the exception window showing the syntax of this method 
I say we can come out with something useful from each proposal, to combine their power. 
Use shapes as method signatures,  type list as a more restriction for allowed types, and type unions as a compact syntax for similar logic  overloaded methods.

**Comment by CyrusNajmabadi** [comment] 2018-03-20 22:52
> Regardless, even we use shapes, it is still usefull to constrain generics to small list of types. 

Why?

**Comment by CyrusNajmabadi** [comment] 2018-03-20 22:56
>  type list as a more restriction for allowed types, and type unions as a compact syntax for similar logic overloaded methods.

I want to understand how type-unions don't blow up immediately.  Just having a few generic parameters, with a few unions blows up exponentially it seems.

> Using this constraint will be rare and for only one class

How can you know that or make that claim?  Why would people *not* use this for multiple parameters?

**Comment by JonasZ95** [comment] 2018-03-20 23:15
@MohammadHamdyGhanem 
Which one looks more compact and is easily extendable?
(SToString would be really inefficent It's probably better using something like a formatter)
```csharp
void WriteLine<T>(T v) where T : SToString<T> { 
 Console.WriteLineString(v.ToString());
}
```

vs

```csharp
void WriteLine<T>(T v) where T: {char, short, int, long, (unsigned...), float, double,...} {
  Console.WriteLineString(v.ToString());
}
```

Every proposal adds new ideas but I don't understand how this proposal can be implemented without having It heavily restricted. It's not extendable and very complex to implement. Just imagine you need a second parameter with n possible types for WriteLine then you would need n^2 different methods which all need to verify It work works because the second parameter may be used with different functions.

**Comment by theunrepentantgeek** [comment] 2018-03-24 00:35
> "Compile time will be worst" is overrated. 

Tell that to the folks working on .NET Core 2.1 - they're targeting compile time reductions of more than 10x for that release.

Also, keep in mind that the _compiler_ is running **constantly** - to provide Intellisense, syntax highlighting, unit test discovery, and so on.

> Using this constraint will be rare and for only one class, if any,  all over the project. 
> This is not expected to exceed a few milliseconds.

If it's going to be rarely used, what's the value in the C# team spending all the effort to specify, implement, test and maintain all the edge cases?

**Comment by YairHalberstadt** [comment] 2020-10-14 05:58
Closing as a duplicate of https://github.com/dotnet/csharplang/discussions/1371

**Closed by YairHalberstadt** 2020-10-14 05:58 UTC
