### ISSUE TITLE
Why does C# 8 using declarations require variable declaration?

### ISSUE THREAD

**Issue by innix** [dotnet/csharplang#3081] opened 2020-01-06 15:55 UTC
In C# 8 you can use `using` declarations like this:

```csharp
using var foo = GetDisposableFoo();
```

But sometimes a method just returns an `IDisposable` and has no use being assigned to a variable. An example of this is the `ILogger.BeginScope` method in the `Microsoft.Extensions.Logging` package. I would like to do this, but it is not allowed:

```csharp
public void Example()
{
    using logger.BeginScope("Example");

    logger.LogDebug("Hello world!");
}
```

I can work around it by assigning to a "throwaway" variable, but it feels hacky:

```csharp
public void Example()
{
    using var _ = logger.BeginScope("Example");

    logger.LogDebug("Hello world!");
}
```

Is there a reason for this restriction?

**Comment by canton7** [comment] 2020-01-06 16:04
Duplicate of https://github.com/dotnet/csharplang/issues/2593

**Comment by 333fred** [comment] 2020-01-06 16:17
Closing as duplicate.

**Closed by 333fred** 2020-01-06 16:17 UTC
