### ISSUE TITLE
[suggestion] Multiline string """ expression

### ISSUE THREAD

**Issue by surfsky** [dotnet/csharplang#3500] opened 2020-05-26 05:20 UTC
We can use """ string expresssion to simply multiline text construction, just like dart/python syntax:

``` csharp
var txt = """
    any multi line text" with ' and "
    any multi line text" with ' and "
    any multi line text" with ' and "
    """;
```

**Comment by yaakov-h** [comment] 2020-05-26 05:26
This looks like #89 but with different syntax.

**Comment by surfsky** [comment] 2020-05-26 05:33
Use """ mulitline string expression to avoid  escape character ‘  or ""

It's readable much more.

**Comment by 333fred** [comment] 2020-05-26 06:45
Closing as a duplicate of #89.

**Closed by 333fred** 2020-05-26 06:45 UTC
