### ISSUE TITLE
Consider "this" in a ref struct as fixed

### ISSUE THREAD

**Issue by ltrzesniewski** [dotnet/csharplang#1697] opened 2018-07-06 17:44 UTC
Given that a `ref struct` can only live on the stack (in other words, it cannot be moved around by the GC), it should be legal to take a pointer to the struct from a method of the struct itself.

Example:

```C#
ref struct MyStruct
{
    unsafe void Foo()
    {
        MyStruct* ptr = &this;
        SomeInteropMethod(ptr); // Example usage
    }
}
```

Currently, the compiler says this:

> error CS0212: You can only take the address of an unfixed expression inside of a fixed statement initializer

But a ref struct is necessarily fixed.

The motivation for this request is to be able to write interop code as instance methods. Currently, you need to write the above method as `static unsafe void Foo(MyStruct* item)`.

Note that `System.Runtime.CompilerServices.Unsafe` provides a `void* Unsafe.AsPointer<T>(ref T value)` method, but `ref struct` types can't be used as type arguments.

**Comment by kkokosa** [comment] 2019-02-25 21:54
It seems I've already proposed a more general question regarding all fields in #1564

**Comment by ltrzesniewski** [comment] 2019-02-25 21:57
Indeed. It seems like #1792 went for the more general approach.

**Comment by YairHalberstadt** [comment] 2020-10-18 06:36
Closing as a duplicate of championed issue https://github.com/dotnet/csharplang/issues/1792

**Closed by YairHalberstadt** 2020-10-18 06:36 UTC
