### ISSUE TITLE
Proposal: Capture returned object

### ISSUE THREAD

**Issue by RUSshy** [dotnet/csharplang#2000] opened 2018-11-13 10:49 UTC
Having a way to easily capture and edit an object without having to write lot of useless code

```c#
world.getComponent<CLocation>(id) { // call only if not null
	x = 5, y = 5
}
```

I often have to write lot of duplicate code to achieve simple stuff

```c#
var location = world.getComponent<CLocation>(id);
if(location != null)
{
	location.x = 5;
	location.y = 5;
}
```

Kotlin have something similar

```kotlin
    getComponent<CPosition>().apply {
        x = 5
        y = 5
    }
```

I can write extention methods or methods to init fields inside the ``CLocation`` class but i'm following ECS principles and DOD, so no logic in components, and it'll just bloat my classes, i'll then have to have multiple init methods for different fields wich isn't C# way to doing things

What do you think ?

**Comment by YairHalberstadt** [comment] 2018-11-13 10:56
I believe this is a duplicate of #512

**Comment by YairHalberstadt** [comment] 2018-11-13 11:02
By the way you can use optional parameters to allow users to select which value they would like to update in a method, avoiding requiring multiple methods to set the fields/properties of a class.

**Comment by RUSshy** [comment] 2018-11-13 11:05
>  you can use optional parameters to allow users to select which value they would like to update in a method

Yes but the problem again is

- Still have to create by hand these methods
- Have to update these methods if i add new/remove fields
- Probably not efficient performance wise ?

**Comment by Joe4evr** [comment] 2018-11-13 11:30
Currently, this is an option:
```cs
if (world.getComponent<CLocation>(id) is CLocation location)
{
	location.x = 5;
	location.y = 5;
}
```
And with the new pattern matching features coming soon, the type check can be elided with an empty Property Pattern: `if (world.getComponent<CLocation>(id) is {} location)`

**Comment by OyasumiLad** [comment] 2018-11-13 11:38
As far as I know those are the two closest options you currently have in the language to achieve what you want.

```csharp
public class World
{
    public bool GetComp<T>(int id, out T value)
    {
        if (!Exists<T>(id))
        {
            value = default;
            return false;
        }

        value = Get<T>(id);
        return true;
    }

    public void GetComp<T>(int id, RefAction<T> action)
    {
        if (Exists<T>(id)) action(ref Get<T>(id));
    }
}
```

You can then use it as such:
```csharp
if (world.GetComp(id, out Vector2 value))
{
    Console.WriteLine(value.X);
}

world.GetComp(id, (ref Vector2 vec) =>
{
    Console.WriteLine(value.X); 
});
```

If I recall correctly we should get static delegates at some point, which in theory should make the second version very performant.

**Comment by RUSshy** [comment] 2018-11-13 11:51
@Joe4evr i like that option, but is still a but too much typing, and there is repetition, generic type + pattern matching type

@OyasumiLad what is RefAction ?

**Comment by yaakov-h** [comment] 2018-11-13 11:54
Pattern matching in C# 8 (coming soon) as @Joe4evr posted would be the simplest and most immediate solution.

There might be some overlap here with #803 too.

**Comment by OyasumiLad** [comment] 2018-11-13 11:54
```csharp
public delegate void RefAction<T>(ref T value);
```

You can't use a regular `Action<T>` since you want to modify the returned values, obviously I wrote this under the assumption that you'd be using structs. If you're using classes the good old `Action<T>` will work fine.

**Comment by DavidArno** [comment] 2018-11-13 13:38
@RUSshy,
> @Joe4evr i like that option, but is still a but too much typing, and there is repetition, generic type + pattern matching type

As Joe points out in the rest of his answer, when C# is released, you'll be able to avoid repeating `CLocation`. And if you really are concerned over typing, you could then express it as:
```cs 
if (world.getComponent<CLocation>(id) is {} l) (l.x, l.y) = (5, 5);
```

But one should always remember that we write code once and read it many times, so sometimes a bit more typing is worth it to make reading the code a bit easier.

**Comment by dsaf** [comment] 2018-11-13 16:53
Actually is a partial duplicate of #91 not all those other things mentioned.

**Comment by theunrepentantgeek** [comment] 2018-11-13 21:35
> But one should always remember that we write code once and read it many times, so sometimes a bit more typing is worth it to make reading the code a bit easier.

I concur. 

There's a good argument to make for concise code where it's easier to _read_, but "too much typing" is seldom a useful argument.

**Comment by willard720** [comment] 2018-11-14 02:34
It would be nice to have an example syntax you wish to have

**Comment by mikernet** [comment] 2018-11-14 16:56
I always thought this would be a nice addition that mimics initializer syntax.

**Closed** 2020-09-10 20:33 UTC
