### ISSUE TITLE
Proposal: Allow using statement without curly braces

### ISSUE THREAD

**Issue by pongba** [dotnet/csharplang#1861] opened 2018-09-16 20:58 UTC
The mandatory curly braces introduced by using statement can lead to multiple level of indention that makes the code less readable. C++'s stack bound RAII is more clean and composible in this regard.

in C#
```csharp
void foo()
{
    ...
    using (var res1 = new Resource1())
    {
        ... // do something
        using (var res2 = new Resource2())
        {
            ... // do something else
            using (var res3 = new Resource3())
            {
                ... // do something else
            }
        }
    }
}
```

in C++
```cplusplus
void foo()
{
    ...
    Resource1 res1;
    ...
    Resource2 res2;
    ...
    Resource3 res3;
    ...
}
```

What if we make C# using statement capable of expressing in the same manner:

```csharp
void foo()
{
    ...
    using var res1 = new Resource1();
    ...
    using var res2 = new Resource2();
    ...
    using var res3 = new Resource3();
    ...
}
```

The scope of the reference is until "the next closing brace }", which means if you want more fine-grained scoping you can certainly do:

```csharp
void foo()
{
    ...
    using var res1 = new Resource1();
    ...
    {
        using var res2 = new Resource2();
        ...
    } // dispose res2 here
    ...
    using var res3 = new Resource3();
    ...
}
```

and

```csharp
void foo()
{
    for (int i = 0; i < ...; ++i)
    {
        using var res = new Resource();
        ...
    }
}
```

**Comment by theunrepentantgeek** [comment] 2018-09-16 21:09
The **defer** statement (#1398) would achieve the same result, but in a more flexible way - and that proposal both already has a proposal champion (@gafter himself) and is tagged as a candidate for C# 8.x.

There's also _Implicitly scoped using statement_ (#1174, also championed by @gafter) that looks like an exact duplicate of this. It's tagged as a candidate for C# 8.0.

**Closed** 2018-09-16 22:41 UTC
