### ISSUE TITLE
Define variables inside argument list

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/csharplang#1698] opened 2018-07-08 08:51 UTC
C# allows us to define variables to recieve out params in place like:
```Foo(out int x);```
I suggest to generalize this to all param types. Ex:
```
Console.WriteLine(byte b = 5);
b += 2;
```

this is a shortcut for:
```
byte b = 5;
Console.WriteLine(b);
b += 2;
```

**Comment by yaakov-h** [comment] 2018-07-08 09:54
Duplicate of #973?

**Comment by Joe4evr** [comment] 2018-07-08 15:41
@MohammadHamdyGhanem Please close if the linked issue already covers your proposal.

**Closed** 2018-07-08 15:54 UTC
