### ISSUE TITLE
Suggestion: return void and yield IEnumerable

### ISSUE THREAD

**Issue by JackTheSpades** [dotnet/csharplang#1556] opened 2018-05-23 08:19 UTC
This is honestly a really minor thing, but I run into it so frequently, that I just thought I'd at least point out my ideas.

#### 1. Be able to use `return` with void methods to support one liners.

```cs
public class Foo
{
    public void DoSomething(string someParam) { ... }
    
    public void SomethingBody()
    {
    	if(expr)
        	return DoSomething("Bar");
        //...
    }
    
    public void SomethingLambda()
    	=> DoSomething("Baz");
}
```

In the example above the expression `return DoSomething("Bar");` would fail as it is used now as void Methods do not allow something to follow the `return`. The Lambda Expression (`=>`) on the other hand does, in a way, support this.

My 'concern', if you will, is that if it wasn't for the void type, this would work just fine (e.g. if both `DoSomething` and `SomethingBody` returned an `int`).

I, in many cases, had to remove the return type of methods only to then be forced to adjust such one liners with a pair of braces.

Yes, this is a very minor thing for people like me who'd rather have things be one-liners but I honestly don't see the problem in void Methods simply executing the expression following the return and ignoring whatever it evaluates to.

E.g.
```cs
public class Foo
{    
    public void DoSomething() { ... }
    public double DoMath() { ... }

    public void SomethingBody()
    {
    	switch(param)
        {
            //returns void
            case expr1:
                return DoSomething();
            //ignore returned double value
            case expr2:
                return DoMath();
            //valid but pointless (compiler warning?)
            case expr3:
                return 3 + 4;
        }
    }
}
```

#### 2. Use `yield` in combination with `IEnumerable` values

As it stands, when writing Methods that return `IEnumerable<T>` the option to use `yield return (T)` is much appreciated. In combination with abstract or virtual Methods, it is somewhat frustrating to override.

```cs
public class Foo
{    
    public virtual IEnumerable<int> Count()
    {
    	yield return 1;
    	yield return 2;
    	yield return 3;
    }
}
public class Bar : Foo
{
    public override IEnumerable<int> Count()
    {
        foreach(int i in base.Count())
            yield return i;
    	yield return 4;
    	yield return 5;
    	yield return 6;
    }
}
```

To give just one example of dealing with other `IEnumerable<T>` Methods. It'd be nice if this could be simplified to a single expression. For example:

```cs
public class Bar : Foo
{
    public override IEnumerable<int> Count()
    {
        yield return foreach base.Count();
    	yield return 4;
    	yield return 5;
    	yield return 6;
    }
}
```

Or something of a similar nature.

**Comment by orthoxerox** [comment] 2018-05-23 09:01
Your first suggestion is a duplicate of #135.

**Comment by orthoxerox** [comment] 2018-05-23 09:02
And your second suggestion is a dupe of #378.

**Comment by jcouv** [comment] 2018-07-07 06:13
Both parts are indeed duplicates. Thanks @orthoxerox 
I'll go ahead and close this issue.

**Closed by jcouv** 2018-07-07 06:13 UTC
