### ISSUE TITLE
Q: Should static interface members without implementation be allowed?

### ISSUE THREAD

**Issue by ScottKane** [dotnet/csharplang#3829] opened 2020-08-30 23:21 UTC
Doing this could then force opt in static implementation enforcement so that the derived class must implement the static member as static.

``` C#
interface IA
{
    static void M();
}
class Derived: IA
{
    public static void M() { }
}
```

**Comment by DaZombieKiller** [comment] 2020-08-31 05:19
You're looking for https://github.com/dotnet/csharplang/issues/164.

**Comment by 333fred** [comment] 2020-08-31 05:50
I would say it's a duplicate of #110 (type classes), not necessarily shapes. We also discussed this in LDM a couple months ago: https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-06-29.md. Closing this out, please redirect discussion to one of the linked places :).

**Closed by 333fred** 2020-08-31 05:50 UTC
