### ISSUE TITLE
Proposal: Support `foreach(ref .. in ...)` for walking through value type lists and arrays

### ISSUE THREAD

**Issue by lachbaer** [dotnet/csharplang#501] opened 2017-04-25 10:49 UTC
### Problem
Assume you have a value type 'Fraction' that must be initialized properly with a non-null denominator.

You cannot create a list or array and iterate intuitively through it.
```cs
var fracArr = new Fraction[100];
foreach (var item in fracArr) item.Initialize();
```
The array items will not be initialized, because 'item' is a new copy in each iteration instead of a reference to the actual array member.

### Proposal
By changing the variable declaration to also accept a `ref`, the above problem would be solved.
```cs
var fracList = new Fraction[100];
foreach (ref var item in fracArr) item.Initialize();
```

### Benefits
It will make `foreach` more intuitively usable in such cases where the IEnumerable items are value types.

It can avoid semantic errors, because `foreach` is used on value type lists. The sole presence of `foreach(ref` and it's mention in guides, helppages, books and tutorials in the same place as the standard `foreach` make programmers aware of the problem its solution.

It eleminates the need for two different `for(...)`-loops, one for array, one for `IEnumerable`s.
### Drawbacks
Maybe the costs outweigh the benefit. I think that new interfaces 'IRefEnumarable' and 'IRefEnumerator' with 'ref T Current()' must be appended to many framework types.

### Alternatives
Stay with the current approach
For arrays:
```cs
var fracArr = new Fraction[100];
for (var iter=0; iter<fracArr.Length; ++iter) fracArr[iter] .Initialize();
```
For other IEnumerables:
```cs
var fracList= new Fraction[100].ToList();
for (var iter=0; iter<fracArr.Count; ++iter) fracArr[iter] .Initialize();
```

**Comment by svick** [comment] 2017-04-25 13:20
This is pretty much a duplicate of https://github.com/dotnet/csharplang/issues/461.

**Closed** 2017-04-28 23:19 UTC
