### ISSUE TITLE
Proposal: Keyword property access to backing field

### ISSUE THREAD

**Issue by jademinear** [dotnet/csharplang#1470] opened 2018-04-21 21:03 UTC
**Problem**

Consider the following auto-property:

```
public int MyProperty
{
    get;
    set;
}
```

MyProperty.get() returns a hidden backing store. Modifying the get() and set() methods of a property is a common practice. However, doing so requires that we declare a new backing store:

```
private int myVar;

public int MyProperty
{
    get { return myVar; }
    set { myVar = value; }
}
```

Rarely, if ever, will the backing store be directly accessed through code in a way that adds any additional functionality when the access modifier is private. How about exposing the hidden field of a property with the keyword `field` , to avoid writing unnecessary code when modifying the get() and set() of a property?

```
public int MyProperty
{
    get { return field; }
    set { field = value; }
}
```

Modified properties are declared often enough that this should warrant some quicker and cleaner alternatives, right?

**Comment by CyrusNajmabadi** [comment] 2018-04-21 21:14
> MyProperty.get() returns a hidden backing store. 

This is already legal code and may have meaning in a program already.  For example, consider a simple property that returns some object with a 'get()' method on it.

**Comment by Joe4evr** [comment] 2018-04-21 21:38
Duplicate of #140

**Closed** 2018-04-21 21:59 UTC

**Comment by jnm2** [comment] 2020-04-04 12:59
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
