### ISSUE TITLE
Discussion: break <n>

### ISSUE THREAD

**Issue by AlecsandruDuma** [dotnet/csharplang#1907] opened 2018-10-03 16:09 UTC
Hello everyone, I would like to propose allowing  break statement to have a parameter, in order to break from multiple loops.
While obviously this would be yet another break in structured programming paradigm I think overall it would be a rather beneficial one for the following reasons:
-this should be used instead of `goto` statement (which we all know it's evil), but actually it is the optimal way currently to break multiple loops (apart from return, if it applies)
-people actually don't use `goto` statement because it's evil, instead they do declare variables and make all kinds of operations (that have a resource cost) to achieve what this statement would do, usually ending up doing a second break on some condition in the upper loop, which is with nothing more structured than a single break <n> that breaks both loops.

What do you think?

Examples:
```
while(condition)
{
    switch(variable)
    {
        case 1:
        if (abort)
            break 2;
    }
}
```
or
```
for(int i=0;i<n;i++)
    for(int j=0;j<m;j++)
    {
        if (exit)
            break 2;
    }
```

**Comment by TheUnlocked** [comment] 2018-10-03 16:17
`goto` can do this already.
e.g.
```csharp
for(int i=0;i<5;i++) {
  for(int j=0;j<5;j++) {
      if (j > i)
          goto Outside;
      if (j > 2)
          throw new Exception();
  }
}
Outside:
Console.WriteLine("Finished!");
```

**Comment by TheUnlocked** [comment] 2018-10-03 16:18
`goto` is not evil in C#. `goto` is only a problem when it's improperly used to move around between different scopes and backwards in code, neither of which are possible in C#.

**Comment by willard720** [comment] 2018-10-04 02:50
That's their fault for not using `goto` where it's supposed to be used and making things more complicated than it needs to be because they're afraid of being critizied from online anons. 

That being said, I do like this, and think this is better than the Java one where you name the loops and break using their names.

**Comment by AlecsandruDuma** [comment] 2018-10-04 08:04
Thanks @HaloFour for pointing out this is actually an old debate.
From my point of view `break <n>` / `continue <n>`  have the cleanest shortest syntax and are the least confusing.
using goto <label> i think it's too relaxed(easier to do wrong with it, for instance tempts the developer to do more with it than just break the loop, such as skipping some other piece of code, or implement some weird logic), hurts refactoring  (consider copy/pasting a collapsed block of code but missing the label after), and in fact more code to write unnecessarily.
using break <label> also feels bad, because these labels would have a special treatment, they are supposed to be used before loop statements (as opposed to goto labels - after). This brings confusion. someone possibly may even be tempted to use the same label for two purposes, a break and a goto which have different meaning. I don't think putting out for use of such a tool is a great idea ...so, I'm against Java syntax.

In the end, while this feature will not be something impossible live without, every time I wrote a piece of code that needed it (I would say hundreds of times over the years for me), I paused and I felt it missing.

**Comment by DavidArno** [comment] 2018-10-04 08:53
Regarding your comments that "goto is evil", it's worth remembering that it's not the four letters, g-o-t-o that's the problem, it's the act of evaluating an expression and then branching one way or another that creates issues. So simply replacing that `if … goto` with an `if … break` solves nothing. 

I'd contend that when faced with a desire to break out of multiple loops, there's a high probability that there's an issue with the code. Applying a `break 2` sticking plaster to the code doesn't fix the underlying issue in such cases. A rethink and refactor may well be a better solution. Not always, but this scenario occurs often enough to justify making people stop and think, "do I really need a goto here?" Supplying a `break <n>` would be counter-productive in such cases as it offers a quick fix, thus discouraging looking for that better solution.

**Comment by theunrepentantgeek** [comment] 2018-10-04 09:12
> I'd contend that when faced with a desire to break out of multiple loops, there's a high probability that there's an issue with the code.

I agree with @DavidArno here. On #1597 I expressed [a similar opinion](https://github.com/dotnet/csharplang/issues/1597#issuecomment-394518030):

> ... in code reviews, I usually see nested loops as a code smell indicating a need to break out another method.

It's worth reading the entire thread of that issue to avoid rehashing the same debate over again.

**Comment by AlecsandruDuma** [comment] 2018-10-04 13:29
I agree about breaking methods wherever the case and forcing return as a better practice ....in a number of cases(maybe lots), but there will always be cases when not (processing matrices/multidimensional data; break from loop + inner `switch` statement). Same with code design, sometimes it's poor design, sometimes it's not. ...and some other times design and readability is not the point - maybe you write a quick script, do something one time asap (are we doing this a lot to justify it for an argument?).
I tried to go through the other threads,and I found many opinions and preferences but not so many compelling arguments.
One argument I see valid is that the feature may not bring enough usefulness to justify the trouble for implementing it in the language, possibly, I  am not in a position to argue with this. 
Some other assumptions I just think are wrong - for instance what was said about replacing `if ... goto` with `if ... break` solving nothing (why does even exist a `break` statement then); or some other post saying `break<number>` does not refactor well(as opposed to? labels?); or that labels are better (just because java uses them? I can argue that are worse) 
...well, I think I made my point for now, hopefully it will get some support from community and the proposal gains some traction, or not, and I will gracefully accept the defeat :)

**Comment by HaloFour** [comment] 2018-10-04 13:44
@AlecsandruDuma 

> does not refactor well(as opposed to? labels?); or that labels are better (just because java uses them? I can argue that are worse)

I do think labels are better.  Being nominal it's obvious to see where the `break`/`continue` statement would jump to.  If it's a number you have to manually walk the code backwards, taking into consideration that not every nesting level counts towards the number of times you're breaking out.  It's also not symmetrical, as `break` within a `switch` statement embedded in a loop means something very different than a `continue` statement in that same `switch` statement.  It's not obvious where `break 2;` or `continue 2;` might go.

That's not to say that I think that the Java syntax specifically is better.  I personally think that it's a little awkward to label the loop itself rather than where you're jumping to.

**Comment by AlecsandruDuma** [comment] 2018-10-04 15:56
I think break is supposed to jump execution based on context, while goto based on location. With `break` it is more important to know execution leaves the loop rather than at which line the loop ends and what follows where the execution will continue. `goto` on the other hand targets a location, and  labels are the way to go for pointing locations. This is why I would rather not use labels for break, or it will be just another `goto`.

`break<n>` is just a more powerful `break`. Shares the same paradigm, same advantages and same disadvantages. True, they both will skip scopes that are not loops ( `while(...){ if(...) { if (...) { break;} } }` ), but this is to be expected. Same as with locations, scopes also are not that important, loops are.

Regarding the `switch` statement, the harm was already done when it was decided that `break` keyword would be used for both switch and loops. break and continue refer here to different things already. Maybe a way to fix this would be if <n> in  `break <n>` will refer to number of loops it breaks not counting the switch, so `break 2;` and `continue 2;` would would count loops the same way and breaking the switch would be equivalent to `break 0;` ...it would be a shame that some bad decision in the past will block adding a good feature in the future.

**Comment by CyrusNajmabadi** [comment] 2018-10-04 16:50
```break 2;``` is this 1-based indexing, or 0-based indexing.  This seems incredibly confusing to actually figure out.  Named jumps make it totally clear what is happening.

**Comment by AlecsandruDuma** [comment] 2018-10-04 17:07
<n> should be precisely how many loops you want to break. it is a number (count) not an index.

**Comment by AlecsandruDuma** [comment] 2018-10-04 17:30
@CyrusNajmabadi 
Ok.

**Comment by BenjaminHolland** [comment] 2018-10-06 06:03
I kind of like it, but doesn't this create a semantic conflict with `yield break`? would `yield break 2` mean anything? If so, what? If not, is this semantic break worth while when other strategies like `goto label` are available?

**Comment by AlecsandruDuma** [comment] 2018-10-06 09:46
Interesting question. `yield break` is a different statement, it's something entirely different than common `break`. 
If `<n>` would have a use in a `yield break <n>` statement, at the way things are, I would say no. `yield` deals with unidimensional data - one enumeration. If there was language support to create enumerations of enumerations there might have been a place for it, but something like this is too far fetched to consider.

On the second question I will ask with another question: was introducing the existing `break` statement worth the while when `goto label` could have been used instead?

**Comment by lachbaer** [comment] 2018-10-17 14:39
It could be considered to make a distinction between `goto LABEL` and `break LABEL`.

`goto LABEL` continues with the statement following the label whereas `break LABEL` continues with statement _following_ the label.

In the following example both `goto` and `break` had the same outcome _before_ another statement was added afterwards. The statement `break LABEL_1` clearly states that **only** the for loop should be left whereas `goto LABEL_2` gives a hint that (besides whatever comes directly after the outer `for`) the code should really continue at LABEL_2.

```cs
LABEL_1:
for(int i=0;i<n;i++)
    for(int j=0;j<m;j++)
    {
        if (exit_now)
            break LABEL_1;
        if (exit_then)
            goto LABEL_2;
    }
afterwards_added_stuff();

LABEL_2:
continue_here();
```

So in my opinion there would be a use for both forms. They more clearly specify what the intention of the jump is. Of course omitting a jump completely is the best of all forms, but I believe sometimes you might just want to continue in your flow and not being stopped by intermediate refactoring.

**Comment by Thaina** [comment] 2018-12-21 10:03
I would try to make these kind of of logic into a return block. Another reason I propose #249 

```C#
=: {
    for(int i=0;i<n;i++)
    {
        for(int j=0;j<m;j++)
        {
            if (exit)
                return;
        }
    }
}
```

Currently now we could write it as delegate

```C#
new Action(() => {
    for(int i=0;i<n;i++)
    {
        for(int j=0;j<m;j++)
        {
            if (exit)
                return;
        }
    }
}).Invoke();
```

**Comment by YairHalberstadt** [comment] 2020-10-18 16:57
Closing as duplicate of #869

**Closed by YairHalberstadt** 2020-10-18 16:57 UTC
