### ISSUE TITLE
Conditional operator, same type in both branches

### ISSUE THREAD

**Issue by lukq** [dotnet/csharplang#3820] opened 2020-08-25 08:37 UTC
In:
csharplang/spec/expressions.md

Part "Conditional operator"

From the spec:

*  If `x` has type `X` and `y` has type `Y` then
   * If an implicit conversion ([Implicit conversions](conversions.md#implicit-conversions)) exists from `X` to `Y`, but not from `Y` to `X`, then `Y` is the type of the conditional expression.
   * If an implicit conversion ([Implicit conversions](conversions.md#implicit-conversions)) exists from `Y` to `X`, but not from `X` to `Y`, then `X` is the type of the conditional expression.
   * Otherwise, no expression type can be determined, and a compile-time error occurs.
*  If only one of `x` and `y` has a type, and both `x` and `y`, of are implicitly convertible to that type, then that is the type of the conditional expression.
*  Otherwise, no expression type can be determined, and a compile-time error occurs.

This does not allow the x and y parts to have the same type.

For example:

	int a=0;
	int b=a<3?2:4;

In the expression a<3?2:4, x has type int (X), y has type int (Y), there is an implicit conversion from X to Y (Identity conversion), but there is also an implicit conversion back from Y to X (Identity conversion). Therefore, only the "otherwise" case can be satisfied:

*  If...
   * Otherwise, no expression type can be determined, and a compile-time error occurs.

Is the specification incorrect? Or should it be read in other way?

**Comment by PathogenDavid** [comment] 2020-08-25 10:30
This is a duplicate of https://github.com/dotnet/csharplang/issues/358

**Comment by 333fred** [comment] 2020-08-25 15:06
Closing as a duplicate.

**Closed by 333fred** 2020-08-25 15:06 UTC
