### ISSUE TITLE
Adding the pipeline operator to C#

### ISSUE THREAD

**Issue by rxdeveloper** [dotnet/csharplang#1309] opened 2018-02-05 22:26 UTC
The Pipeline operator is going to add to Javascript, and I see it greatly enhances readability to multiple method invocation https://github.com/tc39/proposal-pipeline-operator 
How abount adding it to C#?

**Comment by HaloFour** [comment] 2018-02-05 22:40
#74 and #96 as well as probably a couple of others

**Comment by Neme12** [comment] 2018-02-05 22:59
We have extension methods for this.

**Comment by aluanhaddad** [comment] 2018-02-06 00:27
It's worth noting that while the OCaml style syntax is equally out of place in JavaScript as in C#. The former is slightly more amenable to the pipeline operator because you can trivially define curried functions and also because free functions are more common.

**Comment by jeffrey-igaw** [comment] 2018-02-06 06:49
The extension method is not a perfect match for the pipeline. We need.

**Comment by MaLiN2223** [comment] 2018-02-06 16:48
@jeffrey-igaw Why do you think extension methods are no match for pipelines? I think they do fit good in C# syntax as a "substitute". I think we could do most of the things using extensions methods with some `Func<T,TK>`   Could you provide an example?

**Comment by jeffrey-igaw** [comment] 2018-02-07 03:28
@MaLiN2223  I'm not good at English, but i fully agree with issue #74, we quite often use util classes in other library or project, when we want to call the methods with chaining, we write some extension class every each util.
It is more readable, no additional codes, no performance degradation.

and if it is possible. it also has a good effect on local functions, delegates, `Func`, `Action` that use local variable on parent scope.

```csharp
void Something()
{
    using(var context = SomeDbContext())
    {
        function Task localFunction(Entity entity) {
            // some entity codes...
           db.UseThis(entity);
        }

        // if not pipe operator
        // return localFunction(LibraryUtil.Method(entity.SomeExtendMethod()))
        return entity.SomeExtendMethod()
            |> LibraryUtil.Method
            |> localFunction
            |> Updatable.StaticFuncOrAction
    }
}
```

In fact, i do not think the pipe operator is a huge deal, but i think it's definitely helpful  when we're coding these little pieces.

**Comment by aluanhaddad** [comment] 2018-02-07 05:47
@jeffrey-igaw the pipeline operator wouldn't help with that at all. It doesn't make `void` functions return a value. I believe you're thinking of Method Cascades.

**Comment by jeffrey-igaw** [comment] 2018-02-07 06:07
@aluanhaddad Sorry i write wrong return type in this example, actually should return `Entity` or something. i want you to look this code as an example.

Yes, your right this is just method cascades with no need additional extensions methods(and i don't know FP as well, i don't want C# to be similar to more FP). more simply, Why should we add an extension method for just one call?

and like [tc39 proposal](https://github.com/tc39/proposal-pipeline-operator), if the pipeline operator is also able to use await, the code will be cleaner.
```
return somethings  |> await AsyncMethod |> A |> B |> C
```

**Comment by aluanhaddad** [comment] 2018-02-22 04:37
@jeffrey-igaw I follow you now.

Extension methods are statically dispatched so I wouldn't worry about performance but I do agree that it is verbose to define them.

Not if you have unary functions, you can write generic extension methods that chain them together.

**Comment by ufcpp** [comment] 2018-02-23 03:28
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;

static class Delegates
{
    public static Action Static = StaticMethod;
    static void StaticMethod() { }

    // faster than Static, but bit tricky
    public static Action CurriedDelegate = default(object).ExtensionsMethodWithDummyArg;
    static void ExtensionsMethodWithDummyArg(this object dummy) { }

    // I want this to be curried too, if the pipeline operator is introduced
    public static Action CurriedPipeline = default(object) |> StaticWithDummyArg;
    static void StaticWithDummyArg(object dummy) { }
}

/// <summary>
/// a result in my PC.
///           Method |     Mean |     Error |    StdDev |
/// ---------------- |---------:|----------:|----------:|
///           Static | 20.37 us | 0.0580 us | 0.0515 us |
///  CurriedDelegate | 15.26 us | 0.0530 us | 0.0496 us | // faster
/// </summary>
public class InvokeBenchmark
{
    const int N = 10000;
    [Benchmark] public void Static() => Invoke(Delegates.Static);
    [Benchmark] public void CurriedDelegate() => Invoke(Delegates.CurriedDelegate);

    private static void Invoke(Action action)
    {
        for (int i = 0; i < N; i++) action();
    }
}

class Program
{
    static void Main() => BenchmarkRunner.Run<InvokeBenchmark>();
}
```

**Comment by samuelludwig** [comment] 2019-09-25 19:08
Has there been any significant deliberation on this suggestion as time has gone on? I adore the pipe operator in Elixir and would love to have it in C# as well.

**Comment by CyrusNajmabadi** [comment] 2019-09-25 19:16
@samuelludwig No.  If/when such things happen, the issues are updated accordingly.  Thanks! :)

**Comment by greatim** [comment] 2020-03-26 04:26
> We have extension methods for this.
extension method can't handle this case:
```
void Foo(int x, class1 y, class2 z) {
    x |> y.Add |> z.handle;
}
```

**Comment by hez2010** [comment] 2020-03-26 04:59
Extension methods can only be used when the method itself being declared as an extension method. However, pipeline operator allows non-extension method to be piped.

**Comment by 1g0r** [comment] 2020-09-13 09:44
> We have extension methods for this.

With Extension methods you are forced to write additional classes methods and so forth

**Comment by YairHalberstadt** [comment] 2020-10-13 09:14
Closing as duplicate of #74 and #96

**Closed by YairHalberstadt** 2020-10-13 09:14 UTC

**Comment by winstonpuckett** [comment] 2021-04-28 04:07
Sad this is closed 😭

**Comment by theunrepentantgeek** [comment] 2021-04-28 05:09
@winstonpuckett it's closed because it's a duplicate of two existing issues, not because the idea has been rejected.

**Comment by winstonpuckett** [comment] 2021-04-28 14:11
> @winstonpuckett it's closed because it's a duplicate of two existing issues, not because the idea has been rejected. 

Oh, lol. Thank you. This was my first time responding to a github issue. Now I know to check the bottom for the comment on why it was closed.
