### ISSUE TITLE
Add index keyword in foreach loop when the collection is known to be indexable.

### ISSUE THREAD

**Issue by JustNrik** [dotnet/csharplang#3384] opened 2020-04-23 15:42 UTC
I'm aware that the compiler translates `foreach` loops into `for` loops for `Array` and `List<T>`, though, we can't access the index this way so if we needed it, we're forced to use a for loop, which in some cases it's inconsistent as most of times we just use foreach.

Suggestion, add `index` contextual keyword to point to the current index of the iteration, this variable should be readonly as that's the semantics of `foreach`.

Example:

```cs
foreach (var item in array)
{
    if (index == someNumber)
    {
        // Do stuff
    }

    // Do other stuff

    // There could be methods as well were we would require the index so we save that IndexOf call.
}
```

Possible issues: nested foreach loops that can be indexed
Work-around: indexof(item) operator? could be translated by the index directly of that element since it's known.

```cs
foreach (var x in arrayOfX)
foreach (var y in arrayOfY)
{
    // On the first iteration indexof(x) would be 0 and indexof(y) would go from 0 to arrayOfY.Length - 1)
    // This doesn't call IndexOf method since the index is already known by the compiler.
    // index and indexof just translates to whatever the current for variable is.
    Console.WriteLine($"({indexof(x)}, {indexof(y)})"); 
}
```

Why not just use a for loop? Because as I said before, most of times we use foreach, and there are situations that for consistency purposes, we want to stick with foreach even if we actually need the index, it's really ugly to have a foreach with a nested for or viceversa.

This should only work for Array and List<T>. (and maybe string and any other collection that compiler optimizes into a for loop)

**Comment by HaloFour** [comment] 2020-04-23 15:52
IMO, this is why `for` exists, and there are multiple ways to achieve this functionality today with minimal code changes, including extension methods off of `List<T>` and `T[]` that return an enumerator that includes the index.  Having new syntax strictly for a stylistic preference doesn't seem worth it, especially since it wouldn't be applicable to most enumerables.  In fact, I think it'd be highly confusing if the language didn't allow `index` in most circumstances.

**Comment by MrJul** [comment] 2020-04-23 16:13
Duplicate of #1584 (which contains several implementations of the iterator mentioned by HaloFour)

**Comment by CyrusNajmabadi** [comment] 2020-04-23 18:59
Closing out as dupe.

**Closed by CyrusNajmabadi** 2020-04-23 18:59 UTC
