### ISSUE TITLE
Null Check Before Foreach

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/csharplang#2727] opened 2019-08-18 14:29 UTC
I would like to request adding the ? null check before a foreach loop.

```
foreach(var item in myObject.MyNullableCollection?)
{

}
```

Notice the ? at the end.  I'm aware there are a few other ways to handle cases where MyNullableCollection is null, but this looks cleaner to me.

**Comment by YairHalberstadt** [comment] 2019-08-19 21:31
What should the behaviour of this be if the enumerable is null?

**Comment by devhl-labs** [comment] 2019-08-19 21:58
If it's null then it simply wouldn't do anything.  Thanks for the reply.

**Comment by svick** [comment] 2019-08-19 22:12
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/1081 with different syntax.

**Comment by devhl-labs** [comment] 2019-08-19 22:25
Indeed.  That was an interesting read.

**Comment by DavidArno** [comment] 2019-08-20 11:30
That thread contains numerous existing solution to this issue. Since things like:
```cs
if (myObject.MyNullableCollection is {} collection) 
    foreach(var item in collection)
    {
    }
```
already work, then your proposal needs to offer something more than "saves typing a few characters". And it's hard to see what that extra benefit could be. So it becomes a case of, is it worth spending large amounts of time and money adding this feature to the language, updating the spec and documentation and people having to learn about it to save a few characters? And the answer is likely very much, "no". 

So you are right to conclude it's very unlikely to happen.

**Comment by devhl-labs** [comment] 2019-08-20 12:21
With that logic we would have never added the ? operator, because you can
check if an object is null before looking at its properties.

**Comment by canton7** [comment] 2019-08-20 13:04
It's a trade-off between:

1. The amount of effort it takes to implement (for something user-visible like this, this is *never* "low")
2. The amount of typing it saves / amount that it clarifies code
3. The amount it is used

For this suggestion, 1) is probably "medium", 2) is "low", 3) is "low". The null-conditional and null-propagating operations were more like "medium" / "low" / "very high".

**Comment by HaloFour** [comment] 2019-08-20 13:40
You can define the following extension method:

```cs
public static class EnumerableExtensions {
    public static IEnumerable<T> EmptyIfNull<T>(this IEnumerable<T> source) =>
        source != null ? source : Enumerable.Empty<T>();
}
```

Then use it as follows:

```cs
foreach(var item in myObject.MyNullableCollection.EmptyIfNull())
{
    // ...
}
```

Not quite as terse, but it gets the job done.  Some people might balk at the notion of an extension method gracefully handling `null`.

**Comment by Unknown6656** [comment] 2019-08-20 20:56
One could also use the following construct:
```csharp
foreach(var item in myObject.MyNullableCollection ?? Enumerable.Empty<T>())
{
    // ...
}
```
_(replace `T` with the desired target type...)_

**Comment by VBAndCs** [comment] 2019-08-22 09:52
I would prefer C# to skip the loop if the collection is null or empty, without any more syntax!

**Comment by YairHalberstadt** [comment] 2019-08-22 09:56
@VBAndCs

That would be a breaking change. Not throwing an exception where one was previously thrown, is a breaking change.

**Comment by VBAndCs** [comment] 2019-08-22 10:14
I don't think it is a big deal. Most of old code would check for null already, so it will not be affected. other code that would catch the exception, either run the rest of the code after the loop correctly, or throw the null exception in some line, so it will behave the same. I think this should be studied.

**Comment by YairHalberstadt** [comment] 2019-08-22 10:42
@VBandCs

Exactly the same argument could be made for never throwing a NRE, and simply continuing with the next step. However the quicker you catch an invalid state the better, rather than letting nulls propogate and causing more errors and more state changes before they are caught.

If a developer wrote a foreach in the past 20 years it's with the understanding that if the enumerable was null, it would not get past that point. Changing that assumption and letting the null go further into the code before it is caught could significantly change the behaviour of running apps.

**Comment by devhl-labs** [comment] 2019-08-22 12:17
Yes there would have to be something new if a change in null handling is
made.

**Comment by devhl-labs** [comment] 2019-08-30 14:25
> You can define the following extension method:
> 
> ```cs
> public static class EnumerableExtensions {
>     public static IEnumerable<T> EmptyIfNull<T>(this IEnumerable<T> source) =>
>         source != null ? source : Enumerable.Empty<T>();
> }
> ```
> 
> Then use it as follows:
> 
> ```cs
> foreach(var item in myObject.MyNullableCollection.EmptyIfNull())
> {
>     // ...
> }
> ```
> 
> Not quite as terse, but it gets the job done. Some people might balk at the notion of an extension method gracefully handling `null`.

`public static IEnumerable<T> EmptyIfNull<T>(this IEnumerable<T>? source) => source ?? Enumerable.Empty<T>();`

This is pretty good thanks.  I added a ? and used a null coalescing operator.

**Comment by TonyValenti** [comment] 2019-11-26 13:46
@devhl-labs - This is a good idea but the problem this causes is when you have nested objects.  For example, you have you do:
````
foreach(var item in (Parent?.Child?.GrandChild?.Collection).EmptyIfNull()){

}
````

it would be so much nicer to just be able to:
````
foreach?(var item in Parent?.Child?.GrandChild?.Collection){

}
````

**Comment by YairHalberstadt** [comment] 2020-11-03 10:31
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/1081

**Closed by YairHalberstadt** 2020-11-03 10:31 UTC

**Comment by cbryantqb** [comment] 2022-06-27 23:20
You can always use `System.Linq`'s `ForEach()`, i.e., 
```
myObject?.MyNullableCollection?.ForEach(item =>
{
    // Do something with item
});
```
Or if the logic in your loop is just a single statement,
`myObject?.MyNullableCollection?.ForEach(item => /*do something with item*/);`

Either way allows you to deal with `null`s while avoiding nested bracket statements (i.e. the dreaded pyramid of doom).

**Comment by canton7** [comment] 2022-06-28 07:19
> You can always use `System.Linq`'s `ForEach()`

That's a method on `List<T>`, not a linq method. There's no linq equivalent, because that method was [regarded as a mistake](https://ericlippert.com/2009/05/18/foreach-vs-foreach/).

**Comment by cbryantqb** [comment] 2022-06-28 20:02
Sorry, my mistake @canton7 .  I forgot that `ForEach()` wasn't a part of `Linq`,  But IMO it's still a good way to handle nulls while minimizing code clutter.
