### ISSUE TITLE
Using declarations inside foreach loop.

### ISSUE THREAD

**Issue by xChernobyl** [dotnet/csharplang#3335] opened 2020-04-04 21:11 UTC
So the idea is simple - instead of having to write this

```
foreach(var disposableObj in objects) 
{
//... 
disposableObj.Dispose();
}
```

It would be pretty cool to have syntax like the following:

```
foreach(using var disposableObj in objects)
{
//...
}
```

Don't know if this something people would need often, but definitely nice to have as a language feature imo.

**Comment by theunrepentantgeek** [comment] 2020-04-05 01:26
> Don't know if this something people would need often

If it's not needed often, then the language team should be putting their efforts into features with a wider benefit. 

There's already a straightforward and idiomatic way to do what you want:

```
foreach (var disposable in objects )
using (disposable)
{
    // ...
}
```

Also, see this often quoted post [Minus 100 points](https://docs.microsoft.com/en-us/archive/blogs/ericgu/minus-100-points). Adding language features _because they're nice_ leads to language bloat and makes the language confusing for people to learn/use.

**Comment by CyrusNajmabadi** [comment] 2020-04-05 02:23
Or, put a gentler way, features have to have significant valaue in order to warrant inclusion in the language.

**Comment by canton7** [comment] 2020-04-05 09:54
Duplicate of #2541

**Comment by 333fred** [comment] 2020-04-05 16:30
Closing

**Closed by 333fred** 2020-04-05 16:30 UTC
