### ISSUE TITLE
Proposal: Null coalescing assignment operator

### ISSUE THREAD

**Issue by adnanatasos** [dotnet/csharplang#1984] opened 2018-11-04 20:46 UTC
This is a proposal for some additional syntactic sugar around the null coalescing operator ?? when performing assignments.

In scenarios where a value needs to be coalesced to itself or some default value it would be nice to have an operator that kept the original LHS assignment operation value if not null, otherwise falling back to the value specified on the RHS. 

**Example below**:

```c#
// Current
x = x ?? defaultValue;

// Proposed
x =?? defaultValue; 
```

Both approaches would be valid post the change, with the latter being more succinct and arguably having some aesthetic value.

**Comment by svick** [comment] 2018-11-04 21:00
This is a duplicate of https://github.com/dotnet/csharplang/issues/34.

**Comment by agocke** [comment] 2018-11-09 00:30
Already implemented and shipping in Preview 1

**Closed by agocke** 2018-11-09 00:30 UTC

**Comment by tkurskiev** [comment] 2019-02-13 13:16
I was just about to propose the very same thing, but with difference, why we go with =??, if we can just go like:

x ?? y;

So, if x=null, then x = y; if x!= null, x stays as it was.

**Comment by HaloFour** [comment] 2019-02-13 14:07
@tkurskiev 

`x ?? y` is already the null coalescing operator and this syntax is already legal as an expression that does not change the value of `x`.  `??=` would be the compound assignment form.

**Comment by tkurskiev** [comment] 2019-02-19 19:00
also, ??= is more appropriate, than =??

(examples:
^=
+=
*=
etc)

**Comment by adnanatasos** [comment] 2019-02-20 10:08
Yes, I agree ??= is more consistent with similar language features.

**Comment by 333fred** [comment] 2019-02-20 18:04
That's why we did `??=` 😄
