### ISSUE TITLE
Static classes should not be sealed.

### ISSUE THREAD

**Issue by ghost** [dotnet/csharplang#1631] opened 2018-06-14 14:07 UTC
For a usecase, see [this PInvoke issue](https://github.com/AArnott/pinvoke/issues/391). The current behavior of C# leads to the inability to do things like the following with static classes:

```c#
namespace Project
{
    class Program
    {
        static void Main(string[] args)
        {
            B.m();
        }
    }

    class A
    {
        public static void m()
        {

        }
    }

    class B : A
    {
        public static void n()
        {

        }
    }
}
```

**Comment by Joe4evr** [comment] 2018-06-14 14:14
`static` in the CLR is represented by `abstract sealed`: You can't intantiate it and you can't derive from it. There's no way to change this without breaking 18 years of code written for the CLR. If you need inheritance, don't make your class `static`.

**Comment by Pretasoc** [comment] 2018-06-14 14:14
In my opinion there is a good reason, why static classes are sealed. You can't instanciate an object of a static class, so a static class isn`t really an object, which means you cant inherit from it. Basically you want something like a partial class, to extend it.

**Comment by HaloFour** [comment] 2018-06-14 14:15
It doesn't make much sense for a type that cannot be instantiated to participate in a type hierarchy, not even to promote the "abusive" use of attempting to invoke static members through a derived type.

Feel free to not use the `static` modifier if this is the desired behavior that you want.

**Comment by R030t1** [comment] 2018-06-14 15:22
@Joe4evr: Why does `static` imply `abstract sealed`? Shouldn't I write `abstract sealed` if that is actually what I want?

@HaloFour: How is this abusive? How does it not make sense for a static class to participate in a type hierarchy?

Every discussion on this design choice I have found just has people repeating *what literally is* while completely failing to justify *why it is as it is*. I've provided a pretty concrete use for it. I see no reason why `static` should prevent the class from participating in a hierarchy. Sure, it is impossible to instantiate it, but you do not need to instantiate a class to use inheritance: I just provided an example.

I suppose a similar language feature would be Ruby's modules. That's a bit of a stretch but the best comparison to be made. Sometimes composition doesn't make any sense and you need to slide things in to where they already are.

An alternative would be to allow namespaces to contain members, but I suspected that would be even more unpopular.

**Comment by HaloFour** [comment] 2018-06-14 15:40
@R030t1 

Calling a static method through a derived type name is itself the abuse.  Static methods do not participate in virtual dispatch and it's not possible for the derived type to override the implementation.  The compiler is doing the work of looking up the method on base classes and then stamping that into the static method call, where that method doesn't properly exist according to the CLR.  It's a bug vector.

> `using static` works with nonstatic classes

`using static` is for importing the static members of a class.  Whether or not the class itself is static doesn't really matter.  The `static` modifier on class only exists as a guard rail to help prevent accidentally declaring instance members for a class you don't intend to instantiate.

**Comment by DavidArno** [comment] 2018-06-15 08:54
@R030t1,
> Why does `static` imply `abstract sealed`? 

Because `abstract sealed` is how static classes are represented in the CLR. They are abstract as they cannot be instantiated and they are sealed as they cannot be inherited from.

> Shouldn't I write abstract sealed if that is actually what I want?

If you want to do that, use managed C++. C# though provides `static` as a shortcut way of saying `abstract sealed`.

> why do static classes exist in the first place?

Because they make clear to the developer that the contents are all static too. It's "pit of success" stuff in that it helps prevent a future developer accidentally adding an instance member to that class.

> An alternative would be to allow namespaces to contain members, but I suspected that would be even more unpopular.

Please see #1180 for a discussion on that topic.

**Comment by R030t1** [comment] 2018-06-15 13:15
Just because the current implementation in the compiler is bugridden doesn't mean the ultimate goals of the feature are not useful.

So, to clarify, in this example:
```c#
namespace Project
{
    class A
    {
        public static void m()
        {

        }
    }

    class B : A
    {
        public static void m()
        {

        }

        public static void n()
        {

        }
    }
}
```
Calling `B.m()` actually calls `A.m()`? Why does this code even compile? If I understand what you are saying there are even bigger issues than how I want to use inheritance. Poor past decisions are not a good reason to keep making poor decisions.

**Comment by R030t1** [comment] 2018-06-15 13:15
Just because the current implementation in the compiler is bugridden doesn't mean the ultimate goals of the feature are not useful.

So, to clarify, in this example:
```c#
namespace Project
{
    class A
    {
        public static void m()
        {

        }
    }

    class B : A
    {
        public static void m()
        {

        }

        public static void n()
        {

        }
    }
}
```
Calling `B.m()` actually calls `A.m()`? Why does this code even compile? If I understand what you are saying there are even bigger issues than how I want to use inheritance. Poor past decisions are not a good reason to keep making poor decisions.

**Comment by HaloFour** [comment] 2018-06-15 13:20
@R030t1 

> Calling `B.m()` actually calls `A.m()`?

No, calling `B.m()` will call `B.m()`, but if `B.m()` didn't exist it would call `A.m()`.

> Just because the current implementation in the compiler is bugridden

> If I understand what you are saying there are even bigger issues than how I want to use inheritance. Poor past decisions are not a good reason to keep making poor decisions.

This approach is not very helpful.  You're just going to very quickly turn people off from wanting to engage you.

The compiler isn't bugridden.

Also, this has nothing to do with inheritance.  Static members aren't inherited.  They belong specifically to that type.  It's not possible to mark a static member as virtual and it's not possible to override a static member.

**Comment by R030t1** [comment] 2018-06-15 13:36
@HaloFour, @DavidArno:
>This approach is not very helpful. You're just going to very quickly turn people off from wanting to engage you.

I apologize for my tone. I do not want to turn people off. But at some point I do need to say that you are not making any sense nor are you furthering your argument. Most people are not going to like hearing that regardless of how it is phrased.

@DavidArno: You seem to be copying whatever the original developers wrote without thinking about it. You have *completely failed to justify the current behavior of the compiler.* Stop telling me what *is* and why what is *should be.* I still have no idea why static classes should be implemented the way they are, and no one here seems to have any information on the matter.

The bug report you linked is going much the same way as this conversation, though I thank you for linking it. It is good to know that some people like the feature. The comments have a useful quote:
>Likewise, it would be nice if "all it does is save a few characters" folk took the trouble to see others' views before dismissing feature requests such as this.

@HaloFour: If `B.m()` works properly then I do not understand why what I am doing is abusive. You have set up a circular situation: using a static class in the way I want is abusive because of how static classes are implemented. Obviously for it to *not* be abusive I want to change how static classes work, because to date no one has given a good reason for why they work as they do.

If I want a c;ass to be `abstract sealed` I should have to specify that myself. A `static` could simply imply a class can't be instantiated, so perhaps it could be a synonym for `abstract`?

>Also, this has nothing to do with inheritance. Static members aren't inherited. They belong specifically to that type. It's not possible to mark a static member as virtual and it's not possible to override a static member.

What does this mean? That `B.m()` would not work if it were not duplicated in `B`? I assure you it does, go and try it. The IDE does show some lint about a simpler name (`A.m`) being available. Why would I want to do the things you list?

I'm pretty sure this has everything to do with inheritance, as it is how your argument against the feature is presented ("abuse of inheritance") and what I wish static classes to be able to implement.

**Comment by DavidArno** [comment] 2018-06-15 13:36
@HaloFour,
> No, calling `B.m()` will call `B.m()`, but if `B.m()` didn't exist it would call `A.m()`.

To be fair to @R030t1, I agree that, with hindsight, this was a poor decision on the part of the C# designers. If `B.m()` didn't exist, then it would have been better for it to just not compile. Having the compiler look through the inheritance list to find if a base class defined such a static method leads to confusion and (as you mentioned in a previous comment) abuse of the feature.

But there's no point in crying over spilt milk and all that. The language is what it is. It gives the impression of inheritance, but it isn't and never will be. It's often a confusing lesson to learn, but we all learn it and move on...

**Comment by tannergooding** [comment] 2018-06-15 13:40
The issue is already "niche" but also very easy to workaround today. If you find a use case where exposing only static members, but in some form of logical hierarchy, it is not difficult to just drop the `static` keyword from your class declaration and add a `private` constructor.

I will also say that, in some cases, it makes sense to create a class that only exposes static methods and that does so as part of a logical hierarchy.

The Hardware Intrinsics APIs are looking at doing this approach in CoreCLR/CoreFX. We only expose static methods and the various classes (`Sse`, `Sse2`, `Sse3`, etc..) participate in a logical hierarchy where having a new ISA (`Sse3`) supported means that the previous ISAs (`Sse` and `Sse2`) are also supported.

I can also think of at least one other place where doing this might have made code easier to read/use (`System.Math` and `System.MathF`, which also only expose static methods, but where a new class had to be created because it would otherwise have been a breaking change).

**Comment by tannergooding** [comment] 2018-06-15 13:42
> The language is what it is. It gives the impression of inheritance

You can inherit without the ability to override, such as is the case with non-virtual instance methods. You also still have the ability to hide the method (where the compiler will warn you to add the `new` keyword).

**Comment by tannergooding** [comment] 2018-06-15 13:49
@R030t1, it was likely done the way it was because it was a convenient way to encode the data and provide the correct enforcements. `static class` means "I can only contain static members", and `abstract sealed` enforces that at the IL level (basically).

Yes it could have been done another way (such as with an attribute and actual validation), but that doesn't provide any actual enforcement (you can still "break" that by using another language or manually writing IL, etc).

At this point, it probably won't be changed as it would be considered a breaking change (it will silently break the "contracts" people have created for their APIs).

**Comment by R030t1** [comment] 2018-06-15 14:18
@tannergooding: My confusion is that `abstract sealed` seems it can be broken apart further, and removing `sealed` would allow a `static` class to be a superclass. Remember that the user types `static class`: if the object does not behave like a class, namely by not being inheritable, then why is it called a class?

To me it seems there is still something missing from your explanation. Why was `abstract` not used by itself? The best I can come up with is that someone did not want a synonym for another qualifier.

>Yes it could have been done another way (such as with an attribute and actual validation), but that doesn't provide any actual enforcement (you can still "break" that by using another language or manually writing IL, etc).

I don't understand this concern. The reason is likely related to my above comment: why is `sealed` necessary? Also, why is it necessary to defend against people writing arbitrary IL? At that point any contract the language may have given you has potentially been violated, and most language standards don't even bother to consider this situation as a possibility for that reason.

>At this point, it probably won't be changed as it would be considered a breaking change (it will silently break the "contracts" people have created for their APIs).

Existing compiled code can remain unchanged and would still interoperate with new code. Existing source could have `sealed` added to all currently static classes. I fail to see how this is a huge change.

It is still a non-additive syntactic change, so perhaps it could be held to a major version, similar to some of Python 3's changes?

**Comment by HaloFour** [comment] 2018-06-15 14:23
@R030t1 

> It is still a non-additive syntactic change, so perhaps it could be held to a major version, similar to some of Python 3's changes?

It is very much a goal of the C# team to avoid fracturing the ecosystem.

There's no reason to remove the `sealed`.  It risks breaking code that expects that `static` classes will have specific metadata in the CLR.  You can already achieve the behavior you want by removing the `static` modifier and manually making the class non-instantiatable via a private constructor.

**Comment by jnm2** [comment] 2018-06-15 17:31
@R030t1 `static` means there is a guarantee that it's impossible for there to be an object instance with that type. `sealed` alone does not guarantee this and `abstract` alone does not guarantee this.

**Comment by AustinBryan** [comment] 2018-06-16 20:54
Sounds like you don't want to use `static` classes in the first place. Just use `abstract` classes.

**Comment by sharwell** [comment] 2018-06-16 21:00
@R030t1 None of your examples use static classes, so it's difficult for me to understand what you are trying to achieve. Can you write an example showing what you would like to do (something using static classes which is not currently possible)?

**Comment by sharwell** [comment] 2018-06-16 21:55
FWIW, it sounds like this may be resolved by the ability to extend static types (specifically the addition of static methods or properties via Extension Everything). I've been pushing for this ability as part of expanding the `Assert` types common in test frameworks.

**Comment by Richiban** [comment] 2018-06-21 11:09
@R030t1 
The reason static classes cannot participate in a type hierarchy is because that would make them, well, not static.

For example, if we define a static class A

```csharp
public static class A
{
	public static void M() {}
}
```

and we then allow other types to derive from A:

```csharp
public class B : A
{
	
}
```

then that means that we can, essentially, create an instance of the 'static' class A:

```csharp
var x = (A)new B();
```

This has broken the meaning of 'static'. I shouldn't be able to use the name `A` in a type position for variables etc.

Not to mention the fact that for a class to participate in a hierarchy it must have a constructor. But, a static class (by definition) cannot have a constructor.

Sure, C# might be able to get around these facts using private inheritance, but I've got no idea how you would represent that in IL, let alone whether or not that would be a good idea.

**Comment by dzmitry-lahoda** [comment] 2019-01-21 18:18
Not sure why C# prevents me 
`MLog<Debug>.MLog()' is inaccessible due to its protection level [Microsoft.Extensions.Logging.Unity]` from doing next:

```
using System.Diagnostics;

namespace Microsoft.Extensions.Logging
{
    public class MLog<T> where T : ILogCategory
    {
       // protected works, but I not need protected. I want private and private make sence.
        private MLog()
        {
            throw new System.NotSupportedException("https://github.com/dotnet/csharplang/issues/1631");
        }

        static MLog() => Log = MLog.Factory.CreateLogger(typeof(T).Name);

        /// <summary> Gets the log.</summary>
        public static ILogger Log { get; }
    }

    /// <inheritdoc/>
    public sealed class Debug : MLog<Debug>, ILogCategory
    {
        /// <summary>
        /// Traces the specified message.
        /// </summary>
        /// <param name="message">The message.</param>
        /// <param name="args">The arguments.</param>
        [Conditional("UNITY_EDITOR")]
        public static void Trace(string message, params object[] args) => Log.LogTrace(message, args);
    }

    /// <inheritdoc/>
    public sealed class Purchase : MLog<Purchase>, ILogCategory
    {
    }

    /// <inheritdoc/>
    public class Network :  MLog<Network>, ILogCategory
    {
    }


    /// <summary>
    /// Well known categories.
    /// </summary>
    public static class MLog
    {
        private static LoggerFilterOptions loggerOptions;
        private static ILoggerConfiguration loggerConfig;

        /// <summary>
        /// Gets default logging factory.
        /// </summary>
        public static ILoggerFactory Factory { get; private set; }

        // ... factory setup methods
    }
}
```

**Comment by dzmitry-lahoda** [comment] 2019-01-21 18:41
I do not want to call instance ctor never ever and I never want to instance `Debug`, `Purchase`, or `Network` and I do not want `Purchase` to be inside my class(because I want it to be in my Purchase module-assembly, not in loggin assembly, because I want to write custom static methods like `TLog<Purchase>.Buy(new Buy(...))` or `Logging.Purchase.Buy(new Buy(...))`). 
My sealed `Purchase` never touches private instance ctor because it does not need it.  I guess `consistent and useful` would be consider-imply `Purchase` to have private ctor either. So I have non insatiable inheritance chains.

```csharp
// I guess both calls do same thing
MLog<Network>.Log.LogWarning("Disconnected from server. ");
Network.Log.LogWarning("Disconnected from server. ");
// extension method
Network.Log.Fail(serverInfo);
Network.Log.Fail(serverInfo);
```
```csharp
// ConnectionInfo is static method possibly behind Conditional to avoid code in Production
MLog<Network>.ConnectionInfo(new MyConnectionInfo(..));
Network.Log.ConnectionInfo(new MyConnectionInfo(..));
```

Short hands:
```
using static Microsoft.Extensions.Logging.Network;
using Log = Microsoft.Extensions.Logging.Network;
```


```csharp
// used to collect all categories to create GUI for filters which than stores stuff in file which calls concrete MLog to setup ILoggerFactory upon Unity game start up
  allCategories = AppDomain.CurrentDomain.GetAssemblies()
                                .SelectMany(x => x.GetTypes())
                                .Where(x => x.GetInterfaces().Contains(typeof(ILogCategory))).ToList();
```

**Comment by HaloFour** [comment] 2019-01-21 18:46
@dzmitry-lahoda 

All classes need constructors and all constructors are required to call their base constructor.  Whether or not you intend for these types to actually be creatable you must still follow those rules.  You can make the constructor `private protected` or `internal` if you never intend them to be used outside of the current assembly.

**Comment by dzmitry-lahoda** [comment] 2019-01-21 18:51
For the case of issue
```
    /// <inheritdoc/>
    public abstract class Any<T> : TLog<T>, ILogCategory where T :ILogCategory
    {
        /// <summary>
        /// Traces the specified message.
        /// </summary>
        /// <param name="message">The message.</param>
        /// <param name="args">The arguments.</param>
        [Conditional("UNITY_EDITOR")]
        public static void Trace(string message, params object[] args) => Log.LogTrace(message, args);
    }

    /// <inheritdoc/>
    public sealed class Debug : Any<Debug>, ILogCategory
    {
        [Conditional("DEBUG")]
        public static void MyDebug(string message, params object[] args) => Log.LogTrace(message, args);
    }
```

![image](https://user-images.githubusercontent.com/757125/51493289-f2284900-1dc5-11e9-84eb-61ac5bf6974d.png)

So for my case it is `consistent and useful` to have `private`, not `protected` or internal. 

And I still want some classes to be in my `TLog` assembly, like `Debug` and other default stuff (e.g. my case is `Simulation`).

I guess CLR allows to do what I want, but for some reason C# prevents me from doing so. I would rather C# to show me error if I will try in ctor(instantiate) that classes, not when I declare them.

**Comment by HaloFour** [comment] 2019-01-21 18:53
> I guess CLR allows to do what I want, but for some reason C# prevents me from doing so. 

The CLR requires that every type has a constructor and that every constructor call the base constructor, otherwise the assembly is unverifiable.

**Comment by DarthVella** [comment] 2019-01-21 20:38
@dzmitry-lahoda - Forgive me, I'm slightly lost. From what I understand of the code samples, you want a public base class that cannot be directly instantiated. Why is an abstract class not suitable for your purpose?

**Comment by dzmitry-lahoda** [comment] 2019-01-22 06:15
`abstract` gives same error. Abstract suits me, but C# prevents me from having private `ctor`. I want public static inheritable class which cannot be instantiated. I can do that in IL, why not in C#?

Mentioned Sse2 to Sse relation used `internal` for `ctor`. But I do not want to be so fine grained as `corefx` does and create library for each issue.

`peverify` is broken on my PC. It was able to verify 0 of assemblies from dozen tested. I doubt that tool is sane. I guess, I can run `cli` spec pdf file against dll somehow.

```
C:\Users\dzmitry\source\repos\ConsoleApp1\ConsoleApp2\bin\Debug\netcoreapp2.2>peverify "C:\Users\dzmitry\.nuget\packages\microsoft.netcore.app\3.0.0-preview-27122-01\ref\netcoreapp3.0\System.Runtime.Intrinsics.dll"

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[token  0x02000002] Type load failed.
[token  0x02000003] Type load failed.
[token  0x02000004] Type load failed.
[token  0x02000005] Type load failed.
[token  0x02000006] Type load failed.
[token  0x02000007] Type load failed.
[token  0x02000008] Type load failed.
[token  0x02000009] Type load failed.
```

And another angle to view from [Scala on static classes](https://docs.scala-lang.org/tour/singleton-objects.html)

**Comment by HaloFour** [comment] 2019-01-22 11:53
> I want public static inheritable class which cannot be instantiated. 

You can't have classes without constructors and you can't have inheritance without calling base constructors.  This is a rule of the CLR.

> I can do that in IL, why not in C#?

IL can do a lot of things that C# can't do.  In this particular case you are doing something considered inappropriate by IL.

> But I do not want to be so fine grained as corefx does and create library for each issue.

I don't understand why using `internal` forces you to create a library for each issue.  It forces that every type deriving from that type to be within the same assembly.  If that's not what you want, use `protected`.

What's so horribly wrong about being able to create an instance of one of these types anyway?  It's not like it breaks your code in any way.  At *worst* the developer is sitting there with an instance that they can't do anything with.  That's probably the least egregious sin that can happen when prototyping a project.

> And another angle to view from Scala on static classes

Scala doesn't have static classes, it has companion objects.  They are singleton instances of a class that happens to share a name with a normal class.  Their constructors are called.  And while they can inherit from another class, they can't inherit from another companion object.

The JVM also has the same restriction as the CLR.  Any derived class constructor must call the base class constructor.

**Closed** 2020-10-16 07:42 UTC
