### ISSUE TITLE
Expand switch and inline switch capacity

### ISSUE THREAD

**Issue by deadmann** [dotnet/csharplang#3853] opened 2020-09-05 11:15 UTC
Hello folks,

Sometime we are facing the issue of comparing many cases, but these cases are not fixed values, but variables, still that's checking an exist case against a long list of cases... 

It would be good that C# support such cases, performance wise, the compiler should check if any of cases contains variable, treat the data as variable (or create a nested if inside IL), otherwise optimize action as before.

Sample:
```C#
long.Parse(User.Identity.GetUserId()) == item.UserId) ? "Foo" : (item.SellerId==item.UserId?"Bar":(item.BuyerId==item.UserId?"Baz":"---")
```
convert to
```C#
item.UserId switch {
long.Parse(User.Identity.GetUserId()) => "Foo",
item.SellerId => "Bar",
item.BuyerId => "Baz"
_ => "---"
}
```

This will simplify reading of the code which otherwise could need lot of parentheses and nested actions... or lot of if else-if else statements.

**Comment by 333fred** [comment] 2020-09-05 15:49
Duplicate of https://github.com/dotnet/csharplang/issues/3350.

**Closed by 333fred** 2020-09-05 15:49 UTC
