### ISSUE TITLE
Proposal: extend static classes

### ISSUE THREAD

**Issue by gigajew** [dotnet/csharplang#2654] opened 2019-07-15 02:48 UTC
I'd love to see a way to extend existing static classes. Like if I would like to extend the BitConverter class to add some methods.

```c#
public static class BitConverterExtension : BitConverter {
    public static void WriteInt32(byte[] buffer, int value, int startingOffset) {
        
    }
}
```

**Comment by huoyaoyuan** [comment] 2019-07-15 07:45
**How does the term "extend" mean?**

Static class is a loosely composed unit comparing to normal classes, because you cannot create an object carrying its members. All the relationships among static class members are:
- Can consume the private ones
  - Currently no "extension" feature allows you to touch private members. That should applies to any proposals.
- Can be represented by a single `Type` object
  - Consuming members via `Type` is obviously indirect comparing to object, and it's needs very small change to collect members from `Type[]`.
- Can be consumed using same prefix
  - If you don't use prefix to clarify code sources, why not just omit it?

That's all. There's not meaningful "extend" for static classes.

**Comment by YairHalberstadt** [comment] 2020-11-01 11:04
Closing as duplicate of (among others) https://github.com/dotnet/csharplang/discussions/2505

**Closed by YairHalberstadt** 2020-11-01 11:04 UTC
