### ISSUE TITLE
Improve message NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by softlion** [dotnet/csharplang#2630] opened 2019-07-03 10:43 UTC
This message is quite common:

`NullReferenceException: Object reference not set to an instance of an object`

It should be easy and nice to display the name of the variable that is "null".  
Developpers will save time by not running the app again and not reproducing the issue again, trying to find which variable is null on the specified line.

**Comment by Joe4evr** [comment] 2019-07-03 10:51
This literally got implemented like last year, make sure you're on the latest version.

**Comment by yaakov-h** [comment] 2019-07-03 12:03
This was implemented a few years ago, but only in the debugger systems. It's not available to your own code to find the thing that was null.

Duplicate of #2365.

**Comment by softlion** [comment] 2019-07-03 21:35
it's not in Xamarin.

```
07-03 21:32:03.916 15379 15396 I mono-stdout: (MvxSetup) #1/L3:Error:InnerException was NullReferenceException: Object reference not set to an instance of an object
07-03 21:32:03.916 15379 15396 I mono-stdout: (MvxSetup) #1/L4:Error:     at App.Lib.Services.NetworkServiceBase.RestoreStreamForRange () [0x00074] in C:\app\App.Core\Lib\Services\NetworkServiceBase.cs:289
```

**Comment by CyrusNajmabadi** [comment] 2019-07-03 23:20
This is not a language request (the purpose of this repo).  If you would like an improvement with xamarin, can you file over here: https://github.com/xamarin ?

**Comment by 0xF6** [comment] 2019-07-04 01:45
1.  [enable](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-debug-and-release-configurations?view=vs-2017) debug information for normal exception stack-trace
2. This issue is not language proposal, rather improve 'runtime' request?

🤗

**Comment by YairHalberstadt** [comment] 2020-10-29 07:43
Closing as duplicate of #2365, and also as it is a request for dotnet/runtime

**Closed by YairHalberstadt** 2020-10-29 07:43 UTC
