### ISSUE TITLE
Proposal: Stream operator

### ISSUE THREAD

**Issue by hez2010** [dotnet/csharplang#1955] opened 2018-10-24 09:53 UTC
Add a forward pipe operator '|>' just like in F#. 
See #74 

--------------------
Old post:

Currently we use stream.Read() and stream.Write() to operate stream. I think we can add stream operator "->".
```c#
var test = new FileStream(...);
var buffer = new byte[256];
test -> buffer; //this will read 256 bytes from test stream to buffer, and will return a value indicated the actual read length.

new byte[] { 1, 2, 3, 4, 5 } -> test; //this will write { 1, 2, 3, 4, 5 } to test stream, and will return a value indicated the actual write length.
```

Whether to read or write depends on the type of the left parameter and the right parameter.

With stream operators, we can simplify stream operations:
```c#
var test = new FileStream(...);
var buffer = new byte[256];
while((test -> buffer) > 0)
{
    ....
}
```

Also, we can create overloads of stream operators, even if the object is not a stream.
A typical usage is image processing and video collecting.

An OpenCV example using nuget package 'OpenCVSharp3-AnyCPU':

```c#
public class VideoCapture
{
    public long operator->(object src, object dst)
    {
        if (src is VideoCapture camera && camera.Grab())
        {
            dst = camera.ReteieveMat();
            return 1;
        }

        if (src is Mat image && dst is FileStream fs)
        {
            image.Save(fs);
            return 1;
        }
        return 0;
    }
}
```

```c#
var camera = new VideoCapture();
var file = new FileStream(...);
Mat image;
while ((camera -> image) > 0)
{
    image -> file; //This will save image data to file stream.
}
```

**Comment by svick** [comment] 2018-10-24 11:06
The recommended practice is to use `async`-`await` when manipulating `Stream`s. How could you do that with this proposal?

**Comment by hez2010** [comment] 2018-10-24 11:18
@svick maybe 
```
stream async -> buffer // This will return a Task<long>
```

@YairHalberstadt 
can use other operator instead such as '~>'.

**Comment by YairHalberstadt** [comment] 2018-10-24 11:28
@hez2010. 
Can I suggest rethinking this proposal, so you come up with an operator that's more generally useful, across C#. 

F#s pipe forward (|>) operator might serve as an inspiration, along with a method `Stream.Write(Stream stream)`

**Comment by hez2010** [comment] 2018-10-24 11:30
@YairHalberstadt Thanks. Your idea is cool.

**Comment by YairHalberstadt** [comment] 2018-10-24 11:31
See https://github.com/dotnet/csharplang/issues/74

**Comment by MillKaDe** [comment] 2018-10-24 15:08
The IOStream standard library of/for C++ overloads the shift operators for input and output:
```c++
int i;
cin >> i; // read an int from console input into i
cout << "you entered: " i << endl; // write text and int i and end-of-line to console output
```
For details, see: [Wikipedia - Input/output (C++)](https://en.wikipedia.org/wiki/Input/output_(C%2B%2B))  

So, if you like input/output/stream operators, I would recommend to start with trying to port/reimplement C++ IOStreams in C#/NET ...

**Comment by HaloFour** [comment] 2018-10-24 15:17
C# intentionally restricts overloading the `>>` and `<<` operators so that they represent a bitshift and not other arbitrary operations, such as stream I/O.  The second operand is required to be an `int`.

**Comment by MillKaDe** [comment] 2018-10-24 16:59
Yes, but maybe that restriction could be removed in a future version of C# ...

For now, @hez2010 could temporarily (ab)use the relational operators `<=` and `>=` or something else instead of the shift operators to create some experimental C# version of IOStreams - without changing C# itself in advance.

If the resulting library makes sense, the shift operator restrictions might be lifted, or two completely new operators (`|>` and `|<` or `<|`) could be added just for the purpose of overloading them for stream IO.

Anyway, I think it makes sense to take a real close look how stream IO works in C++, copy the good stuff, improve the not-so-great stuff and avoid completely reinventing the wheel ..

**Comment by theunrepentantgeek** [comment] 2018-10-24 21:05
It's also worth considering the [Pipelines](https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/) library that came out of the Kestrel work - from what I can tell, it's going to make a lot of use of Streams obsolete by providing a better/smarter abstraction to work with.

Building in operators that work _only_ with Streams might therefore be a mistake. That said, a general purpose operator that can be implemented by any interested library might be quite useful.

**Comment by willard720** [comment] 2018-10-25 04:32
@MillKaDe Not likely as whatever reason they didn't allow it is likely still valid today. I'm guessing it's to do with they want `>>` to be bit shift *only* and not random things, so that would keep things simple. 

But the operator is really besides the point. They could do `>>>` or something.

**Comment by arekbal** [comment] 2018-10-25 16:32
In most of c++ world, that iostream >> overloading is considered a mistake.

**Comment by YairHalberstadt** [comment] 2020-10-19 05:59
Closing as duplicate of #74

**Closed by YairHalberstadt** 2020-10-19 05:59 UTC
