### ISSUE TITLE
Proposal: Type inference for type arguments from return type.

### ISSUE THREAD

**Issue by somerandomdev49** [dotnet/csharplang#3062] opened 2019-12-31 13:34 UTC
In situation like:
```csharp
public int Foo() { return Util.Bar<int>(thing); }
```
where `Util.Bar<int>` is
```csharp
public static T Bar<T>(int arg) { ... }
```
It is not very nice to write `Util.Bar`***`<int>`***`(thing)`. `int` may be inferred from the return type of `Foo`. So we would instead write
```csharp
public int Foo() { return Util.Bar(thing); }
```

**Comment by KalleOlaviNiemitalo** [comment] 2019-12-31 17:10
Same as #92.

#2710 additionally requests inferring `T` when `GenericType<T> Method<T>()` is called.

**Comment by jaredpar** [comment] 2020-01-03 18:53
Closing as dupe of #92. Let's keep discussion over there.

**Closed by jaredpar** 2020-01-03 18:53 UTC
