### ISSUE TITLE
Allow yield return to automatically enumerate IEnumerable of the same type

### ISSUE THREAD

**Issue by medo64** [dotnet/csharplang#1599] opened 2018-06-03 03:39 UTC
Currently yield return statement can be used to return elements from IEnumerator/IEnumerable<T> function. It would be a nice syntactic sugar if yield return could also iterate through a compatible iterator automatically without the need for the extra foreach.

For example, a common recursion pattern to enumerate through files:

    private static IEnumerable<FileInfo> GetAllFiles(string directory)
    {
        foreach (var file in Directory.GetFiles(directory))
        {
            yield return new FileInfo(file);
        }
        foreach (var subdirectory in Directory.GetDirectories(directory))
        {
            foreach (var file in GetAllFiles(subdirectory))
            {
                yield return file;
            }
        }
    }

could be simplified to:

    private static IEnumerable<FileInfo> GetAllFiles(string directory)
    {
        foreach (var file in Directory.GetFiles(directory))
        {
            yield return new FileInfo(file);
        }
        foreach (var subdirectory in Directory.GetDirectories(directory))
        {
            yield return GetAllFiles(subdirectory);
        }
    }

Since latter code is currently not supported, implementing this functionality wouldn't impact or change behavior of the currently existing code.

**Comment by ufcpp** [comment] 2018-06-03 06:04
dup of https://github.com/dotnet/csharplang/issues/378

**Comment by Unknown6656** [comment] 2018-06-03 07:11
... and #1556

**Comment by yaakov-h** [comment] 2018-06-03 07:58
Duplicate of https://github.com/dotnet/csharplang/issues/378?

Changing the meaning of `yield` in-place could still break existing code, e.g.:

```csharp
using System.Collections;

public class C {
    public IEnumerable M() {
        yield return 1;
        yield return 2;
        
        IEnumerable foo = default;
        yield return foo;
    }
}
```

**Comment by jnm2** [comment] 2018-06-03 13:16
The BCL disambiguates between operating on a collection or each element by adding the word 'range' for element operations.

**Comment by DavidArno** [comment] 2018-06-04 07:38
@yaakov-h,

Indeed, which is why the two existing proposals introduce the idea of `yield foreach`:

    public IEnumerable M() {
        yield return 1;
        yield return 2;
        
        IEnumerable foo = default;
        yield foreach foo;
    }

No broken code that way.

**Comment by yaakov-h** [comment] 2018-06-04 08:27
@DavidArno Yes, but not this one. 😉

**Comment by Thaina** [comment] 2018-06-06 06:36
@DavidArno I think we could just `yield foo` and it also not broken

**Comment by LunarWhisper** [comment] 2018-06-25 14:34
```csharp
public IEnumerable M() {
    yield return 1;
    yield return 2;
  
    yield enumerate M();
}
```

**Comment by YairHalberstadt** [comment] 2020-10-16 04:18
Closing as duplicate of #378 and #1556

**Closed by YairHalberstadt** 2020-10-16 04:18 UTC
