### ISSUE TITLE
[Suggestion] Return caller operator for easier Method Chaining

### ISSUE THREAD

**Issue by snoobvn** [dotnet/csharplang#816] opened 2017-08-12 11:24 UTC
## Problem:
Suppose we have a list and we want to remove multiple elements from the list:
```
            List<int> array = new List<int> {1,2,3,4 };
            array.Remove(1);
            array.Remove(2);
```
Since `Remove` method return a `bool` instead of the caller, we can't use Method Channing for this:
` array.Remove(1).Remove(2)`.
Of course we can make the method which discard the result and instead return the caller like this:

```
        public static List<T> FluentRemove<T>(this List<T> caller, T item) {
            caller.Remove(item);
            return caller;
        }
```
then:
```
            list.FluentRemove(1)
                .FluentRemove(2);
```

## My Proposal:
Add a operator that when used it will discard the method result and return the caller instead:
`array.!Remove(1).!Remove(2);`

**Comment by Joe4evr** [comment] 2017-08-12 11:51
Dupe of #577.

**Comment by eyalsk** [comment] 2017-08-14 00:18
@snoobvn The problem with your problem is the absence of a problem. 😄 

Seriously though, not everything needs to be chained and if you want you can always create an extension for it.

**Comment by jnm2** [comment] 2017-08-14 18:43
Should be closed so we don't duplicate the discussion as well as the question. :smile:

**Closed** 2017-08-14 19:35 UTC
