### ISSUE TITLE
Proposal: Remove new keyword from create class instance 

### ISSUE THREAD

**Issue by patrickreinan** [dotnet/csharplang#3061] opened 2019-12-29 15:14 UTC
I think would be interesting if we can create class instance without new keyword. For example:

Today:

var x = new Date(2020,01,01);

My proposal:

var x = Date(2020,01,01);

**Comment by HaloFour** [comment] 2019-12-29 15:18
Duplicate of #350

**Comment by Grauenwolf** [comment] 2019-12-30 09:41
Interesting isn't the same thing as beneficial. Making constructor calls look like local method calls is not helpful. 

Consider this very common code:

    Foo = new Foo();

Now becomes it becomes this? 

    this.Foo = Foo();

If yes, that is even longer. If no, then we just omit `new` part of the time? That'll be confusing.

**Comment by ronnygunawan** [comment] 2019-12-30 10:06
related to https://github.com/dotnet/csharplang/issues/2846

**Comment by patrickreinan** [comment] 2019-12-30 10:43
> Interesting isn't the same thing as beneficial. Making constructor calls look like local method calls is not helpful.
> 
> Consider this very common code:
> 
> ```
> Foo = new Foo();
> ```
> 
> Now becomes it becomes this?
> 
> ```
> this.Foo = Foo();
> ```
> 
> If yes, that is even longer. If no, then we just omit `new` part of the time? That'll be confusing.

I agree with you. Perhaps that will be confusing.

**Comment by jaredpar** [comment] 2020-01-03 18:53
Closing as dupe of #350. Lets keep discussion over there.

**Closed by jaredpar** 2020-01-03 18:53 UTC
