### ISSUE TITLE
Suggestion: allow use of non-default constructors in generics

### ISSUE THREAD

**Issue by msauper** [dotnet/csharplang#3244] opened 2020-03-02 19:02 UTC
Have you considered allowing a constructor prototype to be defined in the where clause of a generic.  This would further constrain the type to have a constructor of the given format.

T GetFoo< T >(int i) where T : new(int i)  // or just new(int)
{
  return new T(5);
}

**Comment by GrabYourPitchforks** [comment] 2020-03-02 19:23
(Not speaking for the language team, just speaking as a partial owner of the _System.Reflection_ namespace.)

This would require runtime support if we wanted to make it efficient. I have some ideas for how we could plumb this through the runtime and reflection APIs in a high-performance fashion, so _in theory_ this should be doable. But I'm having trouble seeing how this would be viable if targeting a runtime that doesn't natively expose these efficient APIs.

**Comment by Unknown6656** [comment] 2020-03-02 19:31
@GrabYourPitchforks Is there a possibility that this could be made available in .NET5?
I heard the rumours that .NET5 will be partially re-written from the ground-up. However, I'm not sure whether that concerns the libraries or the runtime. I'm furthermore unsure, how much of a breaking change this proposal will be for the runtime  :-/

**Comment by Joe4evr** [comment] 2020-03-02 20:57
Duplicate of #769.

**Comment by GrabYourPitchforks** [comment] 2020-03-02 21:04
@Unknown6656 The API portion would be tracked by https://github.com/dotnet/runtime/issues/31895 and https://github.com/dotnet/runtime/issues/23716. In theory you'd be able to use the public APIs even without language support. They're just APIs, after all.

I'm not on the language team so can't speak for their plans in this area.

**Comment by Richiban** [comment] 2020-03-03 10:42
This would be covered by the Shapes proposal (https://github.com/dotnet/csharplang/issues/164), where generic constraints should cover every type of member of a type, including constructors.

**Comment by YairHalberstadt** [comment] 2020-11-19 10:17
Closing as duplicate of #769.

**Closed by YairHalberstadt** 2020-11-19 10:17 UTC
