### ISSUE TITLE
[Proposal] List of allowed types as generic constraint

### ISSUE THREAD

**Issue by Expro** [dotnet/csharplang#1629] opened 2018-06-13 23:27 UTC
Generic type constraint in form of
`public static T Extension<T>(this T) where T : InterfaceOne, InterfaceTwo`
Means that T must implement **both** interfaces: InterfaceOne and InterfaceTwo.

Currently, there is no way to define overloaded (extension) method with same signature, but different constraints. For example, following code is not valid:
`public static T Extension<T>(this T) where T : InterfaceOne`
`public static T Extension<T>(this T) where T : InterfaceTwo`

Proposal: allow for listing of type constraints, where constaint will be met if generic parameter meets **any** of listed types. For example, if we assume following code:
`public static T Extension<T>(this T) where T in InterfaceOne, InterfaceTwo`
Would allow for any object implementing only InterfaceOne, only InterfaceOne or both.

Alternative syntax:
`public static T Extension<T>(this T) where T from InterfaceOne, InterfaceTwo`

**Comment by benaadams** [comment] 2018-06-13 23:39
```csharp
public static T Extension<T>(this T) where T : InterfaceOne
public static T Extension<T>(this T) where T : InterfaceTwo
```
Would be better (perhaps via garbled names under the covers for the clr)

Otherwise it would potentially lead to runtime type casting in a shared generic which would be inefficient vs a compile time link up.

Related https://github.com/dotnet/csharplang/issues/1628

**Comment by ufcpp** [comment] 2018-06-14 00:59
[Union types](https://github.com/dotnet/csharplang/issues/399)?

**Comment by YairHalberstadt** [comment] 2018-07-02 15:17
Would definitely aid on defining a method on eg byte, int16, int32, int64, float, double, decimal etc all at once.
However shapes may solve this issue.

**Comment by YairHalberstadt** [comment] 2020-10-16 07:39
Closing as a duplicate of https://github.com/dotnet/csharplang/discussions/1371

**Closed by YairHalberstadt** 2020-10-16 07:39 UTC
