### ISSUE TITLE
lambda expression with 'out' keyword omitting type

### ISSUE THREAD

**Issue by goyzhang** [dotnet/csharplang#2248] opened 2019-02-20 07:46 UTC
If we define `out` parameter in a lambda, we have to explicitly define the type like:
```
           delegate int D<TResult, TArgument>(TArgument argument,  out TResult result);
            D<int, int> d = (int arg, out int rst) => {...};  //have to claim int
            //D<int, int> d = (arg, out rst) => {...};  //CS2046

```
Can we get rid of `int` (the type define) for `out` and do the similar thing like the case without `out`?
```
           delegate int D<TResult, TArgument>(TArgument argument,  TResult result);
            D<int, int> d = (arg, rst) => {...};  // without `out`, you can just omit `int`
```

**Comment by Thaina** [comment] 2019-02-20 08:56
We already have `out var result`

**Comment by goyzhang** [comment] 2019-02-20 09:11
> We already have `out var result`

Yes, I know, but it 's not the case I talked about. And it doesn't work with lambda

**Comment by svick** [comment] 2019-02-28 18:29
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/338.

**Comment by YairHalberstadt** [comment] 2020-10-22 09:36
Closing as champione dat https://github.com/dotnet/csharplang/issues/338

**Closed by YairHalberstadt** 2020-10-22 09:36 UTC
