### ISSUE TITLE
Add new keyword "leftjoin" to make LINQ more readable

### ISSUE THREAD

**Issue by uyhung** [dotnet/csharplang#508] opened 2017-04-28 17:15 UTC
LINQ is amazing, but only if I don't need to do left / right outer join, the solution to use the DefaultIfEmpty() method looks weird.
I wish if C# could extend it keywords to add "leftjoin", "rightjoin" so that I can simply code as following:
var q = from c in db.Categories
            leftjoin p in db.Products on c.CategoryID equals p.CategoryID
            select new 
            {
                     p.ProductName, 
                     c.CategoryName
            }

**Comment by jnm2** [comment] 2017-04-28 17:20
````markdown
```c#
// Code block
```
````

**Comment by svick** [comment] 2017-04-28 17:33
This is a duplicate of https://github.com/dotnet/csharplang/issues/361.

**Comment by lachbaer** [comment] 2017-04-28 22:24
@jnm2 I'm using \`\`\`cs instead of \`\`\`c#. Easier to type with one hand ;-)

**Comment by gafter** [comment] 2017-04-28 23:17
Per @svick this is a duplicate of #361.

**Closed by gafter** 2017-04-28 23:17 UTC
