### ISSUE TITLE
Allow attributes with AttributeTargets.Method above Expression-Bodied Indexers and Readonly Properties

### ISSUE THREAD

**Issue by fitdev** [dotnet/csharplang#2638] opened 2019-07-08 06:55 UTC
Right now this is not allowed:

```csharp
    [DebuggerStepThrough] //<- CS0592: Attribute not valid on declaration type
    public char this[int i] => unchecked((char)(From + i));
```

And one has to write it in a more verbose way like so:

```csharp
    public char this[int i] {
      [DebuggerStepThrough, MethodImpl(MethodImplOptions.AggressiveInlining)]
      get {
        return unchecked((char)(From + i));
      }
    }
```

It would be great if `AttributeTargets.Method` could be interpreted slightly differently for Expression-Bodied Indexers and Properties and be automatically applied to their getters and setters.

**Comment by Joe4evr** [comment] 2019-07-08 08:08
Duplicate of #1355.

**Comment by mburbea** [comment] 2019-07-08 13:24
Not that it's much of a consolation, but it is legal to do so when writing getters and setters using expression bodied notation. Just not when you fully do it expression body e.g.

```cs 
public char this[int i]
{
     [DebuggerStepThrough, MethodImpl(MethodImplOptions.AggressiveInlining)]
      get => unchecked((char)(From + i));
}
```

**Comment by YairHalberstadt** [comment] 2020-11-01 09:42
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/887

**Closed by YairHalberstadt** 2020-11-01 09:42 UTC
