### ISSUE TITLE
[Proposal]: Field and value as contextual keywords

### ISSUE THREAD

**Issue by MadsTorgersen** [dotnet/csharplang#7964] opened 2024-02-23 20:14 UTC
# Field and value as contextual keywords

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

This proposal explores introducing `field` as a contextual keyword instead of an implicit parameter, and changing `value` to similarly be a contextual keyword.

## Motivation
[motivation]: #motivation

As we're adding ["Field access in auto-properties"](https://github.com/dotnet/csharplang/blob/main/proposals/semi-auto-properties.md) to C# we've been aiming at having `field` be an implicitly declared parameter in property accessors, just as `value` already is in property set and init accessors.

Issue #7918 and subsequent discussion explores the breaking change aspects of this design, along with proposed default fixes.

Here we propose instead adding `field` as a contextual keyword. It would only be a keyword when used as a simple name inside a property accessor. This would result in fewer breaking changes and simpler "default fixes" for those breaks that do occur.

Declarations of `field` as a local variable would no longer be a breaking change:

``` c#
public int P
{
    get
    {
        var field = 0; // Allowed today, breaks with implicit parameter, allowed with contextual keyword
    }
}
```

This would eliminate the arguably most gnarly automated default fix, in that such locals would have had to be renamed, leading to a non-obvious choice of which name to change them to.

For the remaining breaks, the implicit parameter approach involves changing existing occurrences of `field` as a simple name to a member access, possibly rewriting primary constructor parameters to introduce an explicit field declaration. Instead, with `field` as a contextual keyword all those occurrences can simply be replaced with `@field`.

The proposal also suggests changing `value` to a contextual keyword for consistency. This is a breaking change, but likely a very small one occurring only in niche situations. The default fixes for those are simple, changing `value` to `@value` or vice versa.

The idea for this proposal came from [this comment](https://github.com/dotnet/csharplang/issues/7918#issuecomment-1934508743) on issue #7918.

## Detailed design
[design]: #detailed-design

### Contextual keywords

Whenever `field` or `value` occurs as a *simple_name* within a set, init or (for `field`) get accessor of a property, it is considered a contextual keyword. This allows code to refer *both* to the special parameters (using `field` and `value`) *and* to the nearest explicit declaration of that name (using `@field` and `@value`).

From a specification point of view, we would make the following changes:

- Adding `field` and `value` to the list of contextual keywords in the [Keywords](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/lexical-structure.md#644-keywords) section.
- Introducing separate *field_access* and *value_access* primary expressions under the *primary_no_array_creation_expression* production, adding new sections under [Primary expressions](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/expressions.md#128-primary-expressions).
- Specifying in those sections that they apply only within the appropriate property accessors, and are otherwise ordinary *simple_name*s.
- Adjusting [Accessors](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/classes.md#1573-accessors) to alter its description of `value` and add a description of `field`.

Note that this narrowly treats `field` and `value` as keywords *only when used as simple names*. It does not prohibit declarations of local variables and parameters with those names within applicable accessors, but access to those variables and parameters would have to use `@`.

Some existing contextual keywords are reserved throughout a given region of code, e.g. [await expressions](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/expressions.md#1298-await-expressions), which reserve the `await` identifier throughout the body of an async function. Others are only keywords in a very specific syntactic position, e.g. `set` and `get`. This proposal is a combination of both those two flavors: `field` and `value` are only keywords when used as *simple_name*s and *even then* only within applicable property accessor bodies.

### Breaks and fixes

**`field` as a simple name** within the bodies of existing property accessors: These occurrences would now be contextual keywords and denote a *field_access*. This break occurs no more or less frequently than the equivalent break with the implicit-parameter design. The default fix is to change this occurrences to `@field`. 

The fix is significantly simpler than the default fix in the implicit-parameter design, which is to replace with a member access. The receiver of that member access would vary with the specifics - `this` or a type - and also may lead to generation of a new field, when `field` is a captured primary constructor parameter.

The proposal avoids breaking changes to declarations of locals or parameters named `field` within a property body, since those would continue to be allowed with the same meaning. However, see "Alternatives" below.

**`value` as a simple name** within the bodies of existing property set or init accessors: As long as `value` already refers to the implicit parameter of the accessor this is not a break. However, if it refers to a different variable it would now be a contextual keyword denoting a *value_access*. Current C# rules prevent shadowing of parameters and local values except within nested - local or anonymous - functions, so this break can only occur within a nested function of the accessor. Furthermore, the programmer will have had to deliberately declare a parameter or local variable with the name `value`, despite the fact that it shadows the implicit parameter to the property and prevents access to it. All in all, while this is certainly *possible*, it is likely very rare. The fix is to replace with `@value`.

**`nameof(value)`** within the bodies of existing property set or init accessors: This is an exception to the previous category. `nameof` accepts a *simple_name*, so `value` would now be a keyword, but a keyword is not allowed here. Adding an `@` wouldn't help, since `value` may no longer be declared as an identifier. The fix is to replace with the "value" string itself. However, see "Alternatives" below.

**`@value` as a simple name** within the bodies of existing property set or init accessors: If `@value` currently refers to the implicit parameter of the accessor, it will no longer do so. Instead it will denote the nearest explicit declaration of `value`, yielding an error if not found. Either is a break. It seems unlikely that existing code would prefix `value` with `@`, since it does not currently change the meaning in any way, so this is probably quite rare. The fix is to replace `@value` with `value`.

Here are representative examples of the breaks and fixes:

``` c#
class C
{
    int field = 0;
    int value = 1;
    
    public int P
    {
        set
        {
            field = value;   // Break! Replace 'field' with '@field'
            @field = @value; // Break! Replace '@value' with 'value'

            this.field = this.value; // Not a break;

            var s1 = nameof(field); // Break! Replace `field` with `@field`
            var s2 = nameof(value); // Break! Replace `nameof(value)` with `"value"`

            void F(ref int field, ref int value) // Not a break
            {
                field = 2; // Break! Replace 'field' with '@field'
                value = 3; // Break! Replace 'value' with '@value'
            }
        }
    }
}
```

## Drawbacks
[drawbacks]: #drawbacks

**Different breaks**: Compared to the field-as-implicit-parameter approach, the proposal avoids a class of breaks around `field` (local variable declarations within the accessor). On the other hand it introduces new breaks around `value`, though they are arguably much more rare.

**More churn**: By subtly changing the semantics of `value` the proposal arguably introduces more conceptual churn, even if the actual breaks might be fewer. On the other hand, many people probably already think `value` is a contextual keyword, since it is "just there" without declaration and actually colors as a keyword in popular editors.

## Alternatives
[alternatives]: #alternatives

**Stick with implicit-parameter design**: We could choose to keep the current design. We'll need to decide which names to generate for the default fix for local variable declarations of `field`.

**Don't change `value`**: We could choose to adopt only the `field` part of the proposal. This is a bit less breaking, while introducing a subtle difference between the workings of `field` and `value`.

**Broaden the context**: The fact that `field` and `value` are still allowed as identifiers within applicable property bodies *except* as simple names might allow for confusing scenarios. On the one hand it is probably nice that `this.field` doesn't break. However, is it weird that you can declare `var field = 4;` in your accessor body, yet you need to say `@field` to refer to that variable? 

Any broadening of the context would lead to further breaks, so there's a very significant trade-off there. However, a sensible landing point might be for local and parameter declarations of `field` and `value` to "refer to the keyword" and thus be an error, similar to how `var this = 5;` is an error today. This feels like it targets all uses (declare and consume) of local variables/parameters equally, for a more balanced/less confusing experience. It would reintroduce breaks around variable declarations similar to the "implicit-parameter" design, but the fixes remain simple: add `@` in front.

**Handle `nameof` gracefully**: We could specially allow `nameof(value)` and `nameof(field)` on the keywords, producing the obvious strings as a result.

## Unresolved questions
[unresolved]: #unresolved-questions

No known open questions at this point.

## Design meetings

https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-03-04.md#breaking-changes-making-field-and-value-contextual-keywords

Issue #7918 was discussed here:

- https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-02-07.md#breaking-change-warnings
- https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-05-15.md#field-and-value-as-contextual-keywords

**Comment by CyrusNajmabadi** [comment] 2024-02-23 21:27
> It would only be a keyword when used as a simple name inside a property accessor. 

Does 'simple' name just mean 'pure identifier'?  Or does it include type arguments, a-la `field<int>`?

**Comment by CyrusNajmabadi** [comment] 2024-02-23 21:29
```
var field = 0; // Allowed today, breaks with implicit parameter, allowed with contextual keyword
```

fwiw, i don't love this.  We don't allow `int await;` in an async method.  So i'd prefer that within a property we simply disallow this and make `field` *always* a keyword.  If we did this, an easy workaround would be do to `var @field = 0;`.

**Comment by CyrusNajmabadi** [comment] 2024-02-23 21:31
> Whenever field or value occurs as a simple_name within a set, init or (for field) get accessor of a property, it is considered a contextual keyword. 

We might want to do this for event accessors with `value` for consistency.

**Comment by CyrusNajmabadi** [comment] 2024-02-23 21:35
> are only keywords when used as simple_names and even then only within applicable property accessor bodies.

We should be clear and explicit as to what extent those bodies extend to.  For example, do they apply once you're inside a lambda/local funciton within an accessor? 

Since the spec allows for `int field` to be an inner lambda/local-function parameter, we should still be very clear if that means that code *within* those lambdas/local-functions needs `@field` to reference that parameter, or if within the lambda you can go back to `field`.

---

Note: the hybrid approach again slightly unnerves me.  Primarily because i think getting it right will be hard.  Here are examples of places we'd need to still allow `field` (not meaning the keyword).

```
Foo(field: 0);
new { field = 0 };
// etc.
```

My compiler hat makes me just want this to always be a keyword (like `await`).  And if you really want to use it as an identifier, you *always* use `@`.   i think that's simpler, and much more in line with async/await (which i actually like as a model ehre).

**Comment by CyrusNajmabadi** [comment] 2024-02-23 21:40
> The proposal avoids breaking changes to declarations of locals or parameters named field within a property body, since those would continue to be allowed with the same meaning.

True.  But as the fix there is trivial as well, i would ask if that's important enough.  Def something to get a read of people on.  Personally, i think taht code would now look *weird*.  If `field` is a contextual keyword, defining something called `field` would be an anti-pattern/smell.  It might be a virtue to push people away from that.

**Comment by CyrusNajmabadi** [comment] 2024-02-23 21:41
I'm 100% in favor of taking this approach.  My preference is to tweak slightly.  But that tweak is def optional, and this proposal is great even without that :)

**Comment by CyrusNajmabadi** [comment] 2024-02-23 21:47
Implementation note: We were able to squeeze out a few more bits to store on nodes.  This means we can store the contextual information about where `value` or `field` was parsed in.  That means we dont' have an incremental parsing issue here.

Specifically, we need to make sure that there is no issue transforming:

```
void Foo()
{
     field++;
}
```

into

```
void Foo
{
    get
    {
        field++;
    }
}
```

That node (and its parents) for the `field` in the method cannot be reused in the property (and vice versa).  It is actually lexed parsed differently, and we must rerun the parser in the new context to get this right.

**Comment by MadsTorgersen** [comment] 2024-02-23 22:47
> Does 'simple name' just mean 'pure identifier'? Or does it include type arguments, a-la `field<int>`?

Good point of clarification, thanks. I don't think it has real-world impact, but we do need to decide one way or the other.

**Comment by MadsTorgersen** [comment] 2024-02-23 22:53
> > Note that this narrowly treats field and value as keywords only when used as simple names. It does not prohibit declarations of local variables and parameters with those names within applicable accessors, but access to those variables and parameters would have to use @.
> 
> fwiw, i don't love this. We don't allow `int await;` in an async method. So i'd prefer that within a property we simply disallow this and make `field` _always_ a keyword. If we did this, an easy workaround would be do to `var @field = 0;`.

I understand, and the "Broaden the context" alternative was intended to acknowledge that issue. With `await` we had the luxury of a brand-new context that hadn't existed before, so there was no breaking change impact. Here, every statement or expression form we break is more impact on the user who has existing code.

That said, perhaps the parameter and local declarations wouldn't be so bad to break. Presumably, if you have such a declaration in existing code, you'd also 9 times out of 10 have at least one usage of the declared variable that would also be broken. So it'd be rare for an otherwise "clean" property to break only because of declarations. Once you're in there fixing, you would just fix the declaration too (or the automated fix would).

**Comment by MadsTorgersen** [comment] 2024-02-23 22:58
> > are only keywords when used as simple_names and even then only within applicable property accessor bodies.
> 
> We should be clear and explicit as to what extent those bodies extend to. For example, do they apply once you're inside a lambda/local function within an accessor?

Yes they do. If that is not clear enough, it should be! ;-) I don't think the `await` reasoning applies here; in a nested function in an async method you are genuinely outside the async context. Not so for properties, where `field` and `value` continue to be meaningful inside nested functions.

> Since the spec allows for `int field` to be an inner lambda/local-function parameter, we should still be very clear if that means that code _within_ those lambdas/local-functions needs `@field` to reference that parameter, or if within the lambda you can go back to `field`.

According to this proposal, `field` as a primary expression in nested functions continue to be the keyword. You need `@` to make it an identifier - all the way down.

> Note: the hybrid approach again slightly unnerves me. Primarily because i think getting it right will be hard. Here are examples of places we'd need to still allow `field` (not meaning the keyword).
> 
> ```
> Foo(field: 0);
> new { field = 0 };
> // etc.
> ```
> 
> My compiler hat makes me just want this to always be a keyword (like `await`). And if you really want to use it as an identifier, you _always_ use `@`. i think that's simpler, and much more in line with async/await (which i actually like as a model ehre).

I get the compiler-hat thinking. I just worry it's too breaking.

**Comment by jnm2** [comment] 2024-02-23 23:25
Since `args` in top-level programs is so similar to `value` in properties, can that be kept consistent as well?

**Comment by ufcpp** [comment] 2024-02-24 13:13
If `value` is a keyword, how is `nameof(value)` handled?

```cs
    public int X
    {
        set
        {
            var n1 = nameof(value); // no error
            var n2 = nameof(this); // CS8081
            var n3 = nameof(int); // CS1525
        }
    }
```

**Comment by jnm2** [comment] 2024-02-24 13:47
That's a really good point, since `nameof(value)` is routinely passed to ArgumentException in setters.

**Comment by HaloFour** [comment] 2024-02-24 14:07
> That's a really good point, since `nameof(value)` is routinely passed to ArgumentException in setters.

That feels reasonable to me.  But, what should `nameof(field)` do?  I could see that being an error since the underlying field would be unspeakable.

**Comment by ufcpp** [comment] 2024-02-24 14:17
Would that problem be solved if it is recommended to use `ArgumentNullException.ThrowIfNull`?
`ThrowIfNull` accepts the keyword e.g. `ArgumentNullException.ThrowIfNull(this)`.

**Comment by jnm2** [comment] 2024-02-24 14:34
@HaloFour I agree that `nameof(field)` probably shouldn't work because it's not clear why you'd use it. As a side note, nameof does not return the metadata name of the thing, but the name being used in C# to refer to the thing. An example where this can be seen is generic class names.

@ufcpp There would have to be throw helpers for every overload of every argument exception type, like ArgumentOutOfRange, and potentially user-defined argument exceptions.

**Comment by MadsTorgersen** [comment] 2024-03-01 22:13
I added a few things to the proposal text ahead of Monday's LDM, primarily based on feedback here on this issue - thanks! ❤️

I added:
* An explanation of the `nameof(value)` break specifically, because the "add `@`" fix won't work for it.
* A few more lines to the example in the breaks and fixes section
* More detail on the alternative to disallow local variable and parameter declarations 
* An alternative design for `nameof` which is to simply let it work

**Comment by jnm2** [comment] 2024-03-04 14:58
@MadsTorgersen Could we consider treating `args` in top-level programs the same as `value`, since they seem to currently inhabit the same bucket?

**Comment by colejohnson66** [comment] 2024-03-12 13:57
I do not like this. In my opinion, the team's obsession with using contextual keywords instead of breaking syntax is wrong. It causes sharp edges (`nameof(int)` just flat-out doesn't work, and neither would `nameof(Int32)` if `nameof` exists in scope). These "contextual keywords" are actually *worse* because work is hoisted onto the compiler to determine if a word means one thing or another based on the context of the name scope.

Rust shows that breaking changes can be done safely through editions, and we already have such a thing: the `LangVersion` compilation property. Roslyn is already capable of not allowing certain syntax based on `LangVersion`. Just add `LangVersion=6` and, suddenly, all file-scoped namespaces are illegal.

In addition, there's talk here already about how this "contextual keyword" isn't actually contextual, but would break things. If I have `LangVersion=Latest`, upgrade to .NET 9, and my code breaks, how is that a good thing? It's not. The old proposal to lock `Latest` at C# 12 was better, as it forces the user to opt in to new constructs.

**Comment by colejohnson66** [comment] 2024-03-12 15:26
You ignored my point about `nameof(<type>)`. If `nameof` is in scope at all, I can't use the `nameof` "operator". Sure, "no one" is writing a method called `nameof`, but the point remains.

As for how they relate: I also understand that this proposal includes breaking changes. My gripe is that syntax evolution tends to be halted in the name of backwards compatibility. How long has this issue been requested? [Eight years](https://github.com/dotnet/roslyn/issues/8364) (3.5 if you count [the age of `semi-auto-properties.md`](https://github.com/dotnet/csharplang/commits/main/proposals/semi-auto-properties.md)). After all this time, breaking changes are decided to be a good thing(tm), but instead of actually solving the problem, rules are created to still keep things contextual instead of going just all the way.

**Comment by HaloFour** [comment] 2024-03-12 18:31
@colejohnson66 

`nameof` was designed at a different time, where the team was much less willing to accept breaking changes.  For this particular case with `field` the team is willing to wade into making those breaking changes to better ensure that the feature has better ergonomics and more consistency with the existing `value` "keyword".

If `nameof` was being designed today perhaps that discussion would be different.  However, that doesn't mean that `nameof(int)` would _just work_, as the compiler would have to have explicit rules as to how to handle that case.  Beyond the contextual keyword consideration around _potential_ existing `nameof` methods, the team also didn't want to spin out to a lot of completely new forms of syntax just to support `nameof`, and making it smell like a method invocation was done more to facilitate keeping the syntax simple than anything to do with keywords of breaking changes.

**Comment by CyrusNajmabadi** [comment] 2024-03-12 18:50
@HaloFour Right.  To us, `nameof` takes `named things`, and keywords are not named things.  Neither are other things that `typeof` is fine with.  For example, `typeof` works fine on arrays (like `typeof(int[])`.  But `int[]` is not named as far as the language is concerned, and we would not want that to work.  Just because they both are `xxxof(...)` operators doesn't mean they should accept the same set of values.

**Comment by HaloFour** [comment] 2024-03-12 20:08
@CyrusNajmabadi 

I still want my `methodof(M(int, string))` 😸

**Comment by CyrusNajmabadi** [comment] 2024-03-12 20:15
I have high confidence that given enough time, we will have `infoof`.

**Comment by HaloFour** [comment] 2024-03-12 20:16
@CyrusNajmabadi 

In Foof we Trust.

**Comment by jnm2** [comment] 2024-03-13 22:10
It would make sense to me to disallow `nameof(field)` since it's a keyword, just like how `nameof(class)` and `nameof(int)` don't work. What differentiates `nameof(value)` or `nameof(@value)` as something you'd want to do is that when property setters _do_ throw ArgumentException (and they do in the BCL), the existing pattern is to pass a `paramName` of `nameof(value)`. ParamName refers to the metadata parameter, not to other things like properties.

**Comment by GeirGrusom** [comment] 2024-04-11 13:42
> It would make sense to me to disallow nameof(field) since it's a keyword, just like how nameof(class) and nameof(int) don't work

Constraints are easier to lift than to add also, but I wouldn't think there's too much use for it.

I seem to remember that `nameof(int)` did work at one point, but that people were upset that it returned `Int32` rather than `int`. Would it return `field` or `__<field00001>_bishibosh_$$$`? First one seems completely useless, and the second could be used in reflection ~~clown show~~ code.

**Comment by wrexbe** [comment] 2024-04-26 06:13
How about making properties into a scope under the class? Maybe even allow methods in them.
It's a lot more flexible. I like the idea of being able to structure a class in a way that says, this stuff is only for this property. It is similar to how we can scope a method to only be for a method.

```
public int P
{
    int _field;
    get => _field;
    set => _field = value;
}
```

Pros:
1. Breaking changes? Nope
2. What does nameof(_field) do? it returns "_field"
3. What if you want a different backing field type? You declare the field a different type
4. What if you want more then one backing field? Go for it
5. What if you want some kind of conversion, or notify method specific to this property? You add it to the properties scope.
6. What if you want to copy the property, and rename it? Go for it, the names of everything inside can stay the same.
7.  Fields, and methods inside don't need accessibility modifiers, they are private to the property.
8. It can still be very small, if that is a goal `public int P {int f; get => f; set => f = value;}`
9. If not repeating the type is a goal, var could implicitly become the property type if it's used as a field in the property `public int P {var f; get => f; set => f = value;}`

**Comment by 333fred** [comment] 2024-12-06 23:57
Closing out. https://github.com/dotnet/csharplang/issues/8635 covers `field`, and `value` was rejected by LDM.

**Closed by 333fred** 2024-12-06 23:57 UTC
