### ISSUE TITLE
Implement string comparison operators

### ISSUE THREAD

**Issue by NetMage** [dotnet/csharplang#2364] opened 2019-03-26 18:47 UTC
Unlike VB, C# requires using `String.CompareTo` to compare strings, which unnecessarily clutters the most common usage case.

Implementing the comparison operators on `String` so that they are implemented as `CompareTo()` op `0` (.e.g `"ab" > "cd"` translates to `"ab".CompareTo("cd") > 0`) would make a lot of `string` comparison code easier to read and comprehend.

**Comment by HaloFour** [comment] 2019-03-26 18:52
I don't think this would work well in C#.  In VB you have `Option Compare` which lets you establish and control the policy for string comparison.  C# has no such thing, thus all string comparisons would be forced to default to some comparer which would likely be wrong for most people most of the time.  There are way too many gotchas with encoding, case, localization rules, etc.

**Comment by NetMage** [comment] 2019-03-26 22:37
And yet the common response to "How do I compare strings in C#?" is use `CompareTo`, not talk about culture and only sometimes about case sensitivity. How many VB projects do you really think use `Option Compare Text`?

**Comment by YairHalberstadt** [comment] 2019-03-26 22:44
@NetMage
Perhaps that's the real problem...
Everything's going to be working fine, until one day they get sent Chinese text, an everything crashes. A strong case could be made that string.CompareTo should require you to pass on the method of comparison.

**Comment by HaloFour** [comment] 2019-03-27 01:37
@NetMage 

The official documentation on comparing Strings in C# goes immediately into those details:

https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings

**Comment by theunrepentantgeek** [comment] 2019-03-27 01:41
Debugging errors caused by inconsistencies between `Equals()`, `GetHashCode()` and `CompareTo()` are a real source of pain.

(E.g. Given two strings `a` and `b` then if `Equals(a, b)` is **true**, then `GetHashCode()` must return the same value for both `a` and `b` ... dictionaries will *lose* your instances if they're not.)

I've standardized on an internal cache of the `StringComparer()`:
```
private static readonly _nameComparer = StringComparer.OrdinalIgnoreCase;
```

and then forcing everything in that class to use that cached instance.

Making it _easier_ to introduce inconsistencies is of dubious value.

**Comment by yaakov-h** [comment] 2019-03-27 02:20
(@theunrepentantgeek pssst, that's [already](https://referencesource.microsoft.com/#mscorlib/system/stringcomparer.cs,22) [cached](https://source.dot.net/#System.Private.CoreLib/shared/System/StringComparer.cs,19).)

**Comment by theunrepentantgeek** [comment] 2019-03-27 02:23
@yaakov-h wrote

> (@theunrepentantgeek pssst, that's already cached.)

Yep. It is.

There is both madness to my method, and method to my madness. :wink:

Having a local cache makes it really easy to verify that every use of a `StringComparer` is using the *same* `StringComparer`.

If `Equals()` was using `StringComparer.OrginalIgnoreCase` while `GetHashCode()` was using `StringComparer.Ordinal` then I'd be back in the dark hole of inconsistent results that causes bugs in the first place.

**Comment by MgSam** [comment] 2019-03-27 18:42
If [extension everything](https://github.com/dotnet/roslyn/issues/11159) happens eventually, you'll be able to make comparison operators on String that do anything you want.

**Comment by juliusfriedman** [comment] 2019-03-31 18:24
Does the syntax sugar really buy me that much here, if so can't I just wrap string in a OperatorOverloaded T and extension that ?

**Comment by NetMage** [comment] 2019-04-02 20:49
Having it built-in and not (eventually) written as an extension means that it should work correctly with `Expression` and be supported by LINQ to SQL/EF and other translation environments, just as (a.CompareTo(b) > 0) is handled.

**Comment by NetMage** [comment] 2019-04-02 20:51
> @NetMage
> 
> The official documentation on comparing Strings in C# goes immediately into those details:
> 
> https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings
> 

And yet that page says "the most common operations"... I wonder how common?

**Comment by YairHalberstadt** [comment] 2020-10-23 13:05
Closing as this is probably a request for dotnet/runtime

**Closed by YairHalberstadt** 2020-10-23 13:05 UTC
