### ISSUE TITLE
Proposal: immutable `val` key

### ISSUE THREAD

**Issue by HKhademian** [dotnet/csharplang#1893] opened 2018-09-27 17:28 UTC
I often use kotlin about 2-3 years.
It has separate keys for mutable and immutable varibales, like:
```
var i = 1 // mutable: like java: int i =1;
i = 2
```
and
```
val i = 1 // immutable: like java: final int i = 1;
i = 2 // compiler error
```

I hope we have this feature in C#. ( `readonly`  vars )

**Comment by jnm2** [comment] 2018-09-27 17:36
Duplicate of https://github.com/dotnet/csharplang/issues/188.

**Comment by willard720** [comment] 2018-09-28 02:50
@SilentSin He was only using `int` as `int` tends to be a goto example. He should've used `val foo = new Foo();` which has no equivalent. 

Also, what I like about this is that it's a very short and sensible keyword. `Dictionary<string, string>` is already long enough but `readonly Dictionary<string, string>` is even worse. `val` would be much more desierable in that instance.

**Comment by SilentSin** [comment] 2018-09-28 03:00
@willard720 Yes, that's why I said "if you're actually using ints ..." instead of "this proposal is pointless because we already have a keyword for that".

I agree with you on the shortening, though I don't really think this needs a new keyword. `readonly var` is still pretty short and wouldn't be a breaking change where `val` would break existing code if there was a type with that name.

**Comment by HaloFour** [comment] 2018-09-28 15:43
@SilentSin 

`const` only works if the initializer is a constant expression or a literal.  That meets the very limited use cases described but doesn't align with the behavior of Java's `final` or Kotlin's `val` which would be more in line with #188.

The addition of a new keyword as shorthand for `readonly var` would not be a breaking change.  It would work the same way that `var` did when it was added in that it behaves as a keyword only if an existing type of that name does not exist in scope.  Given that the C# naming guidelines for types recommends PascalCase the likelihood of an existing type conflicting with the keyword would be fairly low and that code would continue to compile and behave as expected.  The options on the table seem to be `val` and `let`, although the latter seems to have more support (and is my preference) because it looks sufficiently different and because C# already has `let` as a contextual keyword to introduce a new readonly variable into the scope of a LINQ query.

**Comment by SilentSin** [comment] 2018-09-29 06:37
@willard720 I really with more people understood that not everyone knows everything about all the underlying intricacies of the language. As you said, someone already pointed it out, so why did you feel the need for that rant? I'm not the most experienced programmer around, I'm just trying to contribute to the discussion. But your attitude makes it seem like I shouldn't even try.

**Comment by HKhademian** [comment] 2018-09-29 08:32
one of main feature that today's programming languages try to archive is to easy the use of its own syntax.
we had `Foo foo = new Foo();` and `final Foo foo = new Foo();` in java, but Kotlin as its direct competitor in syntax provides `var foo = Foo()` and `val foo = Foo()` as alternative and most of all java programmers (at least in android community) like and use this new way to define variables.

As I write code for unity game engine, I use C# after about 4 years, happy to see new changes and features, but when I saw any code, they used `var foo = new Foo()` even when the `foo` variable didn't need to be mutable.
And as a good programming habit, I know it's better to use immutable variables as much as you can. so if there was an easy way to use something as easy as `var` like `let` or `val` keywords to define immutable variables, I think we see better programmer's habits in today's C# community.

```
    let foo = new Foo(); // use c# already defined keyword to define immutable variables
    val foo = new Foo(); // use Kotlin-like syntax, better case because it's very similar to var keyword
    readonly foo = new Foo(); // another case with c# already defined keyword, readonly: too bad it's long to use ( programmers are too lazy)
    readonly var foo = new Foo(); // worst case: too long, but can add/remove readonly keyword in a simple action to convert immutable to mutable variable and vise versa.
```

**Comment by brunnerh** [comment] 2019-02-01 09:45
Something i just noticed; compare the following:

```
val text1 = "Hello";
val text2 = "Hello";
var text3 = "Hello";
val text4 = "Hello";
val text5 = "Hello";
```

```
let text1 = "Hello";
let text2 = "Hello";
var text3 = "Hello";
let text4 = "Hello";
let text5 = "Hello";
```

```
readonly text1 = "Hello";
readonly text2 = "Hello";
var text3 = "Hello";
readonly text4 = "Hello";
readonly text5 = "Hello";
```

I like `val` in terms of the logic comparing *variable* with *value*, but i think it is too similar to `var` in appearance, making it harder to "parse" code. `readonly` is a bit long but completion can easily help with that. Additionally, both `readonly` and `let` already exist as keywords.

`value` instead of `val` would be a bit better in my opinion. It is unfortunate that `const` has this compile time semantic in C#, otherwise that would be a nice option as well (see JavaScript).

**Comment by YairHalberstadt** [comment] 2020-10-18 13:48
Closing as duplicate of #188.

**Closed by YairHalberstadt** 2020-10-18 13:48 UTC
