### ISSUE TITLE
Allow do-while condition to use variables in loop.

### ISSUE THREAD

**Issue by michaelcheers** [dotnet/csharplang#721] opened 2017-07-05 14:27 UTC
```csharp
do
{
    int v = 1;
}
while (v == 1);
```

You cannot use the v variable from inside the loop.

**Comment by HaloFour** [comment] 2017-07-05 14:41
@michaelcheers 

That is already legal code in the following context:

```cs
public class C
{
    private int v = 2;

    public void M()
    {
        do
        {
            int v = 1;
        }
        while (v == 1);
    }
}
```

**Comment by DavidArno** [comment] 2017-07-05 15:24
This is a duplicate of "[Can we let while access variable in do scope?](https://github.com/dotnet/csharplang/issues/141)".

Whilst I feel it was a mistake to not expose variables in the `do` block to the `while` expression, as noted in that other proposal, it would be a breaking change to allow it retrospectively, so it's very unlikely that this will happen.

**Comment by MillKaDe** [comment] 2017-07-05 16:00
I survived without that feature so far, but ...

What if the variable would be declared in the loop condition ..

```c#
void M () {
  // v = 0; // error, outside scope
  do {
    v = 1; // OK, inside scope
  } while (int v == 1);
  // v = 2; // error, outside scope
}
```
.. the scope of variable `v` would be limited to the loop body **and** condition.

Somewhat similar to already legal `for (int i = 0; i < 99; i++) { ... }`.

`v` would be initialized to `default` (0).  If a different initialization is wanted, it could be expressed like ..
`{ ... } while (int v = 99; v == 1);`

**Comment by MillKaDe** [comment] 2017-07-05 16:11
For head controlled loops, the syntax could be extended similar ..

```c#
void M () {
  while (int i = 0; i < 9) {
    i = func ();
  }
}
```
.. but that can already be written as ..
```c#
void M () {
  for (int i = 0; i < 9; /* empty */) {
    i = func ();
  }
}
```

**Closed** 2017-07-05 19:16 UTC
