### ISSUE TITLE
[Proposal] Uninitialized variable type inference

### ISSUE THREAD

**Issue by ghord** [dotnet/csharplang#2595] opened 2019-06-13 06:17 UTC
There is often a case when we need to create a variable without initializing it due to branching initialization logic. Unfortunetly, you then lose the ability to infer the type with `var`. I propose to relax this and allow compiler to infer common type of branching initialization expressions of a variable. Since there already is a concept of common type (e.x. conditional operator) it should be possible to generalize it to more than two types.

Given class hierarchy:
```c#
class Figure { }
class Square : Figure { public Square(float side) ... }
class Rectange : Figure { public Rectangle(float a, float b) ... }
class Line : Figure { public Line(float length) ... }
```
Here are some examples:

```c#
var figure;
if(x == 0 || y == 0)
{
    figure = new Line(Math.Max(x, y));
}
else if(x == y) 
{
    figure = new Square(x);
}
else 
{
    figure = new Rectangle(x, y);
}
//compiler infers that figure has type Figure here
```

```c#
var figure;
try
{
    figure = new Square(1);
}
catch
{
    figure = null;
}
//compiler infers that figure has type Square
```

```c#
var text;

using(var file = File.Open(...))
using(var reader = new StreamReader(file))
{
    text = file.ReadToEnd();
}

//text has type string inferred here
```

**Comment by yaakov-h** [comment] 2019-06-13 08:02
This looks like a duplicate of #448 and #520.

**Comment by ghord** [comment] 2019-06-13 08:15
Yeah, sorry didn't see the previous issues

**Closed** 2019-06-13 08:15 UTC
