### ISSUE TITLE
Feature: Property fields 

### ISSUE THREAD

**Issue by diegohcanepa** [dotnet/csharplang#1420] opened 2018-03-29 16:12 UTC
What about a new field scope that give us more protection over private fields that are used for coding property accessors. Although fields should be always private to the containing type, they are exposed to accidental changes within the type. So, what about some kind of local fields that can only be accessed with in property scope.

Instead of:

```
private int _amount;
property int Amount
{
   get => _amount;
   set
   {
      if (value != _amount)
      {
         _ amount = value; 
         ...additional code...
      }
   }
}
```

Might be:

```
property int Amount
{
   int _amount = 0;
   get => _amount;
   set
   {
      if (value != _amount)
      {
         _ amount = value;
        ...additional code...
      }
   }
}
```
In this way, the _amount field scope is restricted to the the property accessor body and protected from unintended changes within the containing type.

Just a thought

**Comment by Richiban** [comment] 2018-03-29 16:41
@diegohcanepa 

Nice idea, but dupe of https://github.com/dotnet/csharplang/issues/133, https://github.com/dotnet/csharplang/issues/318, https://github.com/dotnet/csharplang/issues/1336 and https://github.com/dotnet/csharplang/issues/1240 at least.

**Comment by Joe4evr** [comment] 2018-03-29 16:44
And #140

**Comment by alrz** [comment] 2018-03-29 18:29
Currently roslyn use ancient `#region` to group those and still it doesn't prevent assignments to the field from outside of the accessors.

**Comment by AustinBryan** [comment] 2018-06-08 04:11
Maybe instead of the name being `_amount`, it's always `backingField`, `field`, or something like that. 

This will prevent naming clashes and make it more consistent. `field` would be a context keyword, like `value`, and mirrors it rather well.

```csharp
property int Amount
{
   int field = 0;
   get => field;
   set
   {
      if (value != field)
      {
         field = value;
        ...additional code...
      }
   }
}
```

**Comment by Joe4evr** [comment] 2018-06-08 06:14
@AustinBryan Please don't bump threads that are duplicates of other threads.

**Comment by jnm2** [comment] 2018-06-08 13:10
Speaking of which, @diegohcanepa, we usually ask folks to close duplicates so the discussion doesn't become repetitive or lost.

**Closed** 2018-06-08 13:14 UTC

**Comment by Unknown6656** [comment] 2020-04-04 10:51
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md

**Comment by jnm2** [comment] 2020-04-04 12:51
@Unknown6656 #140 (use backing field without naming it) was discussed in that meeting, but this issue is a duplicate of #133 (declare normal fields with property scope) which is a different and partially independent request.
