### ISSUE TITLE
[Proposal] Extend "new" Generic Type Constraint 

### ISSUE THREAD

**Issue by andyolivares** [dotnet/csharplang#4723] opened 2021-05-05 05:02 UTC
# Extend "new" Generic Type Constraint 

* [x] Proposed
* [ ] Prototype
* [ ] Implementation
* [ ] Specification

## Summary
[summary]: #summary

Extend the [`new` generic type constraint](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-constraint) to be able to specify constructors other than public parameterless one. It could be useful to be able to type something like this:

```csharp
public class MyGeneric<T> where T : new(string, int)
{
    public void MyMethod()
    {
        ...
        var t = new T("foobar", 123);
        ...
    }
}
```

Also, I see no reason why we shouldn't allow multiple "new" constraints to be specified, for example:

```csharp
public class MyGeneric<T> where T : new(), new(string, int)
{
    public void MyMethod()
    {
        ...
        var t1 = new T(); // Valid
        var t2 = new T("foobar", 123); // Also valid
        var t3 = new T(true); // Invalid
        ...
    }
}
```

In this last case, the compiler has to make sure that `T` has at least 2 constructors, one parameterless and another one with parameters `string` and `int`.

## Motivation
[motivation]: #motivation

I see good use to something like this specially when creating immutable classes. As of today, there is no easy way to create immutable instances within a generic type (at least that I know of) without recurring to other means like factories, etc.

Also, it doesn't seem like a breaking change that shouldn't be there at least for completeness of the language.

## Detailed design
[design]: #detailed-design

N/A

## Drawbacks
[drawbacks]: #drawbacks

I don't see a good reason :)

## Alternatives
[alternatives]: #alternatives

One can use other means/workarounds, like the use of other "factory" types that could receive arguments.

## Unresolved questions
[unresolved]: #unresolved-questions

N/A

## Design meetings

N/A

**Comment by 333fred** [comment] 2021-05-05 05:50
Closing as a duplicate of https://github.com/dotnet/csharplang/discussions/769.

**Closed by 333fred** 2021-05-05 05:50 UTC
