### ISSUE TITLE
Proposal: Make System.Void the type can be used in code

### ISSUE THREAD

**Issue by hez2010** [dotnet/csharplang#1892] opened 2018-09-27 12:15 UTC
Currently the System.Void cannot be used directly in code, and we have to use Action<T...> for non returned-value delegate and Func<T...> for has returned-value delegate.

But if we can use System.Void directly, then we can declare a delegate as below:

Non returned-value function:
```
Func<T1, T2, ..., System.Void> 
```
Has Returned-value function:
```
Func<T1, T2, ... Tx> //'Tx' is the type of return value.
```
 
And in this way there's no need to split the delegate declaration into 2 forms with Action<T..> and Func<T..>.

**Comment by jnm2** [comment] 2018-09-27 12:16
Duplicate of https://github.com/dotnet/csharplang/issues/1603.

**Comment by hez2010** [comment] 2018-09-27 12:19
@jnm2 
Thanks!

**Closed** 2018-09-27 12:19 UTC
