### ISSUE TITLE
Implicit not external accessable field for not-auto-properties

### ISSUE THREAD

**Issue by andrey-messi** [dotnet/csharplang#1336] opened 2018-02-24 13:37 UTC
I have a property with custom logic
```
class Animal {
    float _satiety;

    public float Satiety {
        get {
            return _satiety;
        }
        set {
            if (value >= SATIETY_MAX)
                _satiety = SATIETY_MAX;
            else
                _satiety = value;
        }
    }
    
    const float SATIETY_MAX = 10;

    public void DoSmth() { 
        // mistake here: I should use Satiety instead of _satiety
        _satiety = 99999999 ;
    }
}
```
In this case I'm forced to declare a private field "_satiety" to serve a property "Satiety". But in my logic "_satiety" should never be more than "SATIETY_MAX". A bad thing that I see here is that I can mistakenly access to a field "_satiety"" from any part of a class "Animal" and set it directly without checking "if (value >= SATIETY_MAX)" in a setter of a property "Satiety". Obviously a field "_satiety" should not be accessable anywhere except inside a property "Satiety".
I suggest to allow a programmer to no explicitly declare a private field for serving a property. This field can be created implicitly by a compiler and visible only inside a property (property-scoped field). A name for this field should be same as a name of a property but in camel case and with underscore in a start position. Therefore code above can be rewritten as this:
```
class Animal {
    public float Satiety {
        get {
            // compiler sees an access to a not-declared field "_satiety" so it implicitly creates an property-scoped field "_satiety".
            return _satiety;
        }
        set {
            if (value >= SATIETY_MAX)
                _satiety = SATIETY_MAX;
            else
                _satiety = value;
        }
    }
    
    const float SATIETY_MAX = 10;

    public void DoSmth() { 
        /* not chance for a mistake here: it is not compiled
        _satiety = 99999999 ;*/
        // changing a _satiety in a right way only throught a property 
        Satiety = 99999999 ;
    }
}
```
But if a programmer then explicitly declares a variable "float _satiety;" in "Animal" class then this breaks logic (an access to an implicit property-scoped field "_satiety" in a setter becomes an access to an explicit class-scoped field "_satiety"), so a compiler should forbid declaring an explicit fields that match to a properties' names (if I have a property "AaaBbb", then I can't have a field "_aaaBbb" in that class).
Or if a programmer want to use his own name for a property-scoped field he can do that:
```
    public float Satiety {
        var _myOwnName;
        get {
            return _myOwnName;
        }
        set {
            if (value >= SATIETY_MAX)
                _myOwnName = SATIETY_MAX;
            else
                _myOwnName = value;
        }
    }
    
    const float SATIETY_MAX = 10;
```
Of course, _myOwnName is not accessable outside of property Satiety.

**Comment by svick** [comment] 2018-02-24 14:03
This is pretty much a duplicate of https://github.com/dotnet/csharplang/issues/318.

**Comment by Unknown6656** [comment] 2018-02-24 14:11
Mentioned before / duplicates:
#1240 
#318
#140
#133

**Comment by bondsbw** [comment] 2018-02-24 16:06
The main difference is that this version creates a named field without declaring it.

It pretty much ignores precedent in the language. All members and locals need to have a declaration (even if it is just `var`).

So for those reasons, I'm out.

**Comment by jnm2** [comment] 2018-02-24 16:12
Some of us have been referring to https://github.com/dotnet/csharplang/issues/140 as the 'gold standard.' I think the `field` keyword has much wider merit. It reduces verbosity and removes the burden of maintaining a second redundant name when you should be able to do:

```cs
public int SomeProperty { get; set => Set(ref field, value); }

public string OtherProperty { get; set => field = value ?? string.Empty; }
```

**Comment by andrey-messi** [comment] 2018-02-24 16:16
> 
> The main difference is that this version creates a named field without declaring it.
> 
> It pretty much ignores precedent in the language. All members and locals need to have a declaration (even if it is just var).
> 

But a keyword "value" in a property setter nowhere has a declaration.

**Comment by BobSammers** [comment] 2018-02-24 17:29
@andrey-messi 
> But a keyword "value" in a property setter nowhere has a declaration.
That is, as you say, a keyword. Your suggestion is that variables should be initialised with essentially arbitrary identifiers - the result would be that the list of reserved words is added to by every property created, which is not done anywhere else.

As others have pointed out, if it becomes an error to create an identifier derived from the name of the property ( `_MyProp` from `MyProp`, for example) that would break millions of lines of existing code. Obviously that's a non-starter without some sort of modification.

**Comment by DavidArno** [comment] 2018-02-24 21:27
With #140:

```cs
class Animal 
{
    public float Satiety { get;  set => field = Math.Min(value, SATIETY_MAX); }
    const float SATIETY_MAX = 10;
}
```
So #140 gets my vote.

I love the word, satiety, BTW. Never come across that one before. 😀

**Comment by Unknown6656** [comment] 2020-04-04 10:52
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md

**Comment by jnm2** [comment] 2020-04-04 12:51
@Unknown6656 #140 (use backing field without naming it) was discussed in that meeting, but this issue is a duplicate of #133 (declare normal fields with property scope) which is a different and partially independent request.

**Comment by 333fred** [comment] 2020-04-04 15:54
Closing as a duplicate. FWIW, @jnm2, we're looking at both of those options.

**Comment by amis92** [comment] 2020-04-06 09:56
@333fred you didn't *actually* close. :)

**Closed** 2020-04-06 10:12 UTC

**Comment by Unknown6656** [comment] 2020-04-08 17:45
@jnm2 ok, you're right. Sorry for spamming this reply across the repo  😅

**Comment by jnm2** [comment] 2020-04-08 18:11
I think I shouldn't have spammed either. Everyone following those issues was probably directed to #140 (though I'm actually not sure).
