### ISSUE TITLE
Fixed-length Array Type: T[n]

### ISSUE THREAD

**Issue by SinDynasty** [dotnet/csharplang#3356] opened 2020-04-12 06:01 UTC
#### About Create
```
T[n] myTArray = new T[n];
```
T[n] is a fixed-length array type, that length = n

#### About Use
```
T[3] myTArray = new T[3];

T t0 = myTArray[0];
T t1 = myTArray[1];
T t2 = myTArray[2];

foreach(T t in myTArray) { ... }
```
Of course，```T t3 = myTArray[3]``` will throw ArgumentOutOfRangeException.

At compile-time, if the index is a known invalid index, we should throw a compiler warning, not a compiler error.

#### About Type
Every T[n] is a separate type, and T[n] inherited from T[].
```typeof(T[n]) != typeof(T[m]) != typeof(T[])```

#### About type conversions
```
int[3] myIntArray3 = new int[3] {1, 2, 3};

//int[3] -> int[2] = {1, 2}
int[2] myIntArray2 = (int[2])myIntArray3;

//int[3] -> int[4] = {1, 2, 3, default(int)}
int[4] myIntArray4 = (int[4])myIntArray3;

//int[3] -> int[] = {1, 2, 3}
int[] myArray3 = myIntArray3;

//int[3] -> int[] -> int[3] = {1, 2, 3}
int[3] myNewIntArray3 = (int[3])myArray3; 

//int[3] -> int[] -> int[2] = {1, 2}
int[2] myNewIntArray2 = (int[2])myArray3; 

//int[3] -> int[] -> int[4] = {1, 2, 3, default(int)}
int[4] myNewIntArray4 = (int[4])myArray3; 
```

#### About C/C++
C/C++ struct Array -> C# struct Array :
```
C/C++ :
struct MyStruct {
    short s1[128];
}
```
```
C# :
public struct MyStruct {
   public short[128] s1;
}
```

C/C++ method Array -> C# method Array :
```
C/C++ :
extern "C" _declspec(dllexport) void New1(int ar[10]);
extern "C" _declspec(dllexport) void New2(double ar[10][20]);
```
```
C# :
[DllImport(...)]
public static extern void New1(int[10] ar);
[DllImport(...)]
public static extern void New2(double[10][20] ar);
```

......

**Comment by Joe4evr** [comment] 2020-04-12 08:21
Duplicate of #1320

**Comment by SinDynasty** [comment] 2020-04-12 10:00
#### About numeric generic parameter
Add a 'num' Key. Usage: num(number type)

For example:
```
public class T<n> where n : num(int)
{
    public int[n] ts;
}

int[3] myIntArray3 = new T<3>().ts;
```
The n must be a number of int type, and ```typeof(n) == typeof(int)``` is true.

**Comment by Unknown6656** [comment] 2020-04-14 18:36
> Of course，`T t3 = myTArray[3]` well throw ArgumentOutOfRangeException.

Should `(new T[3] { .... }) [5]` not result in a _compiler error_ instead of a _runtime error_?
I can understand that an `ArgumentOutOfRangeException´ should be thrown if the index is not known at compile-time. However, a known invalid index should result in a compiler error, IMO.

**Comment by SinDynasty** [comment] 2020-04-15 02:37
> > Of course，`T t3 = myTArray[3]` will throw ArgumentOutOfRangeException.
> 
> Should `(new T[3] { .... }) [5]` not result in a _compiler error_ instead of a _runtime error_?
> I can understand that an `ArgumentOutOfRangeException` should be thrown if the index is not known at compile-time. However, a known invalid index should result in a compiler error, IMO.

I think we should throw a ```ArgumentOutOfRangeException```, if the index is unknown at compile-time.But if the index is a known invalid index, we should throw a compiler warning, not a compiler error.

**Closed** 2020-05-10 03:59 UTC
