### ISSUE TITLE
Support block expressions inside pattern matching

### ISSUE THREAD

**Issue by oliverjanik** [dotnet/csharplang#3481] opened 2020-05-21 13:59 UTC
Version Used: C# 8

At the moment the following is not possible:

            return list.Count switch
            {
                0 => null,
                1 => list[0],
                _ => {
                    LogError();
                    return null;
                }
            };

I get Invalid expression term '{'

The obvious workaround here is defining a quick little private function.

**Comment by 333fred** [comment] 2020-05-21 14:05
Duplicate of https://github.com/dotnet/csharplang/issues/3037.

**Comment by svick** [comment] 2020-05-21 14:05
I think this is covered by the more general expression blocks proposal: https://github.com/dotnet/csharplang/issues/3086.

With that, your example would be:

```c#
return list.Count switch
{
    0 => null,
    1 => list[0],
    _ => {
        LogError();
        null
    }
};
```

**Closed** 2020-05-21 14:05 UTC

**Comment by 333fred** [comment] 2020-05-21 14:13
It would be, yes, but this issue was specifically about switch expressions, unlike the general block expression proposal.
