### ISSUE TITLE
Proposal: extend pattern matching for types

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/csharplang#1839] opened 2018-09-07 07:34 UTC
Proposal: extend pattern matching for types.

Pattern matching for types will be useful if we want to use a method that is appropriate for our type under a certain condition, for example the method has a where constraint on some interface.

For example, we want to write the `IndexOf` method for `Span` and type `T` without limits: `public static int IndexOfEquals<T>(this Span<T> span, T value)`.

We can notice that if the type `T` implements the interface `IEquatable<T>` then for such `T` corresponding method is already exists and we just need to call it, but the compiler will not allow us to do that.
```cs
        public static int IndexOfEquals<T>(this Span<T> span, T value)
        {
            if (T is IEquatable<T> Equatable)
                return System.MemoryExtensions.IndexOf(span, (Equatable)value);
            // something else           
        }
```
So I suggest to extend compiler to enable code with pattern matching for types.

**Comment by stepanbenes** [comment] 2018-09-07 09:06
You can use this instead
```cs
public static int IndexOfEquals<T>(this Span<T> span, T value)
{
    if (value is IEquatable<T> equatable)
    {
        return System.MemoryExtensions.IndexOf(span, equatable);
    }
    return -1;
}
```

**Comment by AlexRadch** [comment] 2018-09-07 09:10
@stepanbenes your code is incorrect because we have ` Span<T> span` but not ` Span<IEquatable<T>> span`

**Comment by DavidArno** [comment] 2018-09-07 09:12
I'm confused by your code example as existing pattern matching already handles this better than you are proposing:
```cs
public static int IndexOfEquals<T>(this Span<T> span, T value)
{
    if (value is IEquatable<T> equatableValue)
        return System.MemoryExtensions.IndexOf(span, equatableValue);
}
```

**Comment by AlexRadch** [comment] 2018-09-07 09:14
@DavidArno your code is incorrect because we have `Span<T> span` but not `Span<IEquatable<T>> span`

**Comment by stepanbenes** [comment] 2018-09-07 09:16
@AlexRadch then add the type constraint `where T : IEquatable<T>` to your method.

**Comment by stepanbenes** [comment] 2018-09-07 09:18
```cs
public static int IndexOfEquals<T>(this Span<T> span, T value) where T : IEquatable<T>
{
    if (value is IEquatable<T> equatable)
    {
        return System.MemoryExtensions.IndexOf(span, equatable);
    }
    return -1;
}
```

**Comment by AlexRadch** [comment] 2018-09-07 09:19
@stepanbenes then it will be copy of MemoryExtensions.IndexOf

> @AlexRadch then add the type constraint where T : IEquatable<T> to your method.

Then it will be copy of `MemoryExtensions.IndexOf` method, but I am creating new method for any `T`

**Comment by stepanbenes** [comment] 2018-09-07 09:26
@AlexRadch Yes, you are right. I was confused by your example. You should have mentioned that you want to extend the functionality of `MemoryExtensions.IndexOf<T>(...) where T : IEquatable<T>` method to work with unconstrained `T`.

**Comment by AlexRadch** [comment] 2018-09-07 09:33
> @AlexRadch Yes, you are right. I was confused by your example. You should have mentioned that you want to extend the functionality of MemoryExtensions.IndexOf<T>(...) where T : IEquatable<T> method to work with unconstrained T.

I think there are many cases where pattern matching will be useful. I added is only one small example.

**Comment by DavidArno** [comment] 2018-09-07 09:41
@AlexRadch,

You have posted the same code example here and in #1840 and have received the same code advice three times. This suggests that you need to improve what you are asking for as it's clearly causing confusion. Could you expand your OP please to better explain things? Also, your request for pattern matching of types makes sense but gets lost due to this confusion.

**Comment by AlexRadch** [comment] 2018-09-07 09:47
> You have posted the same code example here and in #1840 and have received the same code advice three times. This suggests that you need to improve what you are asking for as it's clearly causing confusion. Could you expand your OP please to better explain things? Also, your request for pattern matching of types makes sense but gets lost due to this confusion.

You are right, but I have bad English for it. I will think how to improve my question on english.

**Comment by DavidArno** [comment] 2018-09-07 11:36
I don't see how your proposal would work:

```cs
public static int IndexOfEquals<T>(this Span<T> span, T value)
{
    if (T is IEquatable<T> Equatable)
        return System.MemoryExtensions.IndexOf(span, (Equatable)value);
    // something else           
}
```
would still have the problem that `span` needs casting too to `Span<IEquatable<T>>` too. How is the compiler to know that?

So I think your example wants to look something like:
```cs
public static int IndexOfEquals<T>(this Span<T> span, T value)
{
    if (T is IEquatable<> TEquatable && 
        value is TEquatable equatableValue &&
        span is Span<TEquatable> equatableSpan)
        return MemoryExtensions.IndexOf(equatbleSpan, equatableValue);
    // something else           
}
```
Or have I just misunderstood?

**Comment by bondsbw** [comment] 2018-09-07 14:18
Duplicate of #631.

**Comment by AlexRadch** [comment] 2018-09-07 14:51
@DavidArno I think that next code:
```cs
    if (T is IEquatable<T> Equatable)
        return System.MemoryExtensions.IndexOf(span, (Equatable)value);
 ```

should work like next code
```cs
    if (T is IEquatable<T>)
        return System.MemoryExtensions.IndexOf(span, (T: IEquatable<T>)value);
 ```

It looks like that T support IEquatable<T> interface.

**Closed** 2020-10-19 04:21 UTC
