### ISSUE TITLE
API Proposal: Deconstruct overloads for Array<T>

### ISSUE THREAD

**Issue by gsfreema** [dotnet/csharplang#3225] opened 2020-02-19 17:54 UTC
Other languages such as javascript and python provide the ability to deconstruct an array into named variables.  One example where this can be useful is when you have a string with known parts an a separator.  A simple example would be a key and value separated by a semicolon.  In C#6, someone could write the following code.

```cs
var parts = s.Split(';');

if (parts.Length > 1)
{
    var k = parts[0];
    var v = parts[1];
    // use k and v
}
```

C#7 introduced ValueTuple and Deconstruction so this could be condensed.
```cs
var parts = s.Split(';');

if (parts.Length > 1)
{
    var (k, v) = (parts[0], parts[1]);
    // use k and v
}
```

Taking this one step further with Deconstruct overloads on Array<T> would allow for this code.
```cs
var parts = s.Split(';');

if (parts.Length > 1)
{
    var (k, v) = parts;
    // use k and v
}
```

Given that arrays can have various lengths, Array<T> would need to have many overloads with 1 to N out parameters to have this feature work.  It should be easy enough to justify an upper limit on out parameters because too much deconstruction is just bad code.  Also, tuples do something similar already where there is a limit on the number of items they can have.

There is also a question as to what happens if you're trying to deconstruct an array into more variables than there are items in the array.  The code you would write by hand today would check the length before accessing items in the array so you don't run into an ArgumentOutOfRangeException.  I would expect the same to happen here.  If you're trying to deconstruct into 3+ variables and you only have 2 items in the array, you should receive an ArgumentOutOfRangeException.

**Comment by HaloFour** [comment] 2020-02-21 19:05
This is a dupe of #3215

**Comment by YairHalberstadt** [comment] 2020-11-19 10:10
Closing as duplicate of #3215

**Closed by YairHalberstadt** 2020-11-19 10:10 UTC
