### ISSUE TITLE
Proposal - Automatic or internal instance

### ISSUE THREAD

**Issue by Mteheran** [dotnet/csharplang#1613] opened 2018-06-08 05:18 UTC
I have the following class:

```
public class Movie
    {
        public string Title { get; set; }
        public string Genre { get; set; }
        public int Year { get; set; }
    }

```
Now we can create a collection of that class in this way:
List<Movie> lstMovies = new List<Movie>();

In order to add a new element I can create an instance of the object directly into when I call the method:

` lstMovies.Add(new Movie { Title = "Avengers", Genre = "Action", Year = 2012 });`

My proposal is to try to remove the clause "new Movie" because the parameter can declare an instance of the object automatically keeping in mind the values within the braces. something like this:

` lstMovies.Add({ Title= "Avengers", Genre = "Action", Year = 2012 });`

This works when the method receive 2 or more parameters as well, for example:

`CompareMovies(Movie movie1, Movie movie2)`
 
Calling the method:

`CompareMovies({ Title = "Avengers", Genre = "Action", Year = 2012 }, {Title = "Titanic", Genre = "Drama", Year = 1998 })`

**Comment by Joe4evr** [comment] 2018-06-08 06:17
As pointed out, please close as a duplicate of 100.

**Closed** 2018-06-08 06:18 UTC
