### ISSUE TITLE
Feature request: allow extension method to participate in 'using declarations' for regular structs

### ISSUE THREAD

**Issue by RagnaStrife** [dotnet/csharplang#2686] opened 2019-07-24 19:19 UTC
Today only IDisposable.Dispose() can be used for 'using declarations' and pattern-based ones require the method signature to be identical to that of the aformentioned interface.

What I am proposing is something similar to this (a quickly improvised example, though related to actual stuff currently in the works):

```csharp
[DisposeExtensionAttribute] // or whatever could work for this
public static unsafe long Release<T>( this T value )
    where T : unmanaged, IComObject
{
    if ( sizeof(T) == IntPtr.Size )
        return IUnknownReleaseImpl();
    else
        throw new NotSupportedException();
}
```
The extension method would have any return value which could be used in direct calls, or wasted on compiler-generated calls through the use of 'using declarations'.

The only requirement should be that the extension method parameters are limited to `this`.

The idea too is that only one extension method should be available for a type. I don't know how to deal with more than one at the moment.
I don't exactly know how the custom attribute would apply to the generic constrained arguments though, so I'd appreciate your input on this.

I'd like to know if this is feasible in any shape or form, or if some of the experts here know a better implementation aproach which could be used the way I proposed.

Please note: I've just arrived into C#7+ (after a few years hiatus) and I'm a bit out of the latest language design details so excuse me if this is totally out of place or my example is any confusing.
Also bear in mind, this is my first feature request here.

Thanks in advance.

**Comment by DaZombieKiller** [comment] 2019-07-25 06:54
#93

**Comment by yaakov-h** [comment] 2019-07-25 07:17
I thought that was implemented for `ref structs` and the LDM decided against for anything else?

Or am I mixing my features up?

**Comment by DaZombieKiller** [comment] 2019-07-25 07:18
@yaakov-h 
>I thought that was implemented for ref structs and the LDM decided against for anything else?

>Or am I mixing my features up?

That is indeed how it seems to be implemented today.

**Comment by YairHalberstadt** [comment] 2020-11-02 08:37
Closing as duplicate of #93

**Closed by YairHalberstadt** 2020-11-02 08:37 UTC
