### ISSUE TITLE
Proposal: single-assignment `let` variables

### ISSUE THREAD

**Issue by JesperTreetop** [dotnet/csharplang#1341] opened 2018-02-26 12:23 UTC
# Single-assignment `let` variables

* [x] Proposed
* [ ] Prototype: [NONE](https://github.com/PROTOTYPE_OWNER/roslyn/BRANCH_NAME)
* [ ] Implementation: [NONE](https://github.com/dotnet/roslyn/BRANCH_NAME)
* [ ] Specification: [NONE](pr/1)

## Summary
[summary]: #summary

Introduce `let` declarations, a variant of `var` declarations that define variables that are not allowed to be mutated or reassigned after their initialization expression.

## Motivation
[motivation]: #motivation

The motivation is to provide more clarity and intent into the possible reuse of a variable and to allow compiler or JIT optimizations. `let` is short and parallels the assumption of an axiomatic value that does not change in mathematics. In short, being able to distinguish between which variables vary and which don't is useful both for the compiler, the current code writer and the future maintainer.

## Detailed design
[design]: #detailed-design

For every `var` expression, there should be an equivalent `let` expression to declare a variable that can not be mutated after its initialization expression. 

```csharp
var x = 42;
x++;
var (one, two) = (42, 43);
one = two;

let x = 42;
x++; // error
let (one, two) = (42, 43);
one = two; // error

let x = /* .. */;
ReadOnlyFunction(ref x); // error
ReadOnlyFunctionWithIn(in x); // allowed if x is allowed as an in parameter
```

It would document that this variable is not expected to actually "vary", and may be seen just as a name for a value, in the same vein that a temporary variable can be introduced by a state machine to prevent multiple evaluations. Depending on compilation optimization, the variable could be inlined into subsequent expressions.

It is tempting to want to reuse `const` for this. `const` was designed for baked-in constants and comes with undesirable characteristics *for this use case*, like only supporting compile-time constants and not supporting type inference. `let` would be allowed in any context where `var` is allowed. It would be intuitively similar to LINQ expression `let` clauses, which introduce a new, unchangeable "range variable" for the remainder of the query and are free of `const`'s restrictions, and to `readonly` fields, except that they are also assignable multiple times and in multiple places (constructor and initialization expression).

It would be a compile time error to capture a non-`in`, non-`readonly` reference or a pointer to a `let` variable. You would have to declare a new variable and use it instead.

## Drawbacks
[drawbacks]: #drawbacks

It would introduce a new way to define variables and a new distinction. There is a learning cost to figuring out what `var`, `let`, `const` and `readonly` do and mean across the language - even learning about what you're not likely to be hit by. (Although this meaning is easily distinguished in comparison to some of the others.)

Additionally, it would introduce two slightly different, non-overlapping, meanings to the keyword `let`. (Although this is not without precedence: look at `using`.)

## Alternatives
[alternatives]: #alternatives

Two alternatives, which are orthogonal and could be combined, are to introduce type inference for `const` and/or to relax the compile-time restrictions for local (or any) `const`s. Both could be done without changing the meaning of existing programs (they only make new programs legal), but would introduce differences between `const` use and relaxing the compile-time restrictions would make the original use of `const` fuzzier because it would no longer be obviously safe to bake in the assigned value at every use.

The cost of doing nothing is low.

## Unresolved questions
[unresolved]: #unresolved-questions

There may be interactions with closures/display classes and various state machines that I am unaware of. When I made an early prototype of this in the very early public Roslyn codebase, I gated this by introducing a flag on the variable and checking it when a reference is captured or during assignment; this seems exhaustive to me but I am not a compiler engineer. Most control flow and analysis should start in a good place by making the same assumptions about `let` variables as about any other variables, and `const` optimizations can gradually include support for `let`.

## Design meetings

I am not aware of relevant design notes.

**Comment by DavidArno** [comment] 2018-02-26 12:29
Good(ish) news:
1. This is a duplicate of #188
2. #188 is "championed", ie is being considered as a possible future feature by the language team,
3. @alrz has created a prototype already.

The bad news is that it opens up a whole can of worms around `ref`, parameters, patterns etc for such a small gain that a number of folk now question if it's really worth it.

**Comment by JesperTreetop** [comment] 2018-02-26 12:30
Great - searching for `let` among the issues is an exercise in frustration. Feel free to close this if necessary.

**Comment by DavidArno** [comment] 2018-02-26 12:31
@JesperTreetop,

You'll need to close it, please.

**Closed** 2018-02-26 12:32 UTC
