### ISSUE TITLE
[Proposal] Constructor constraint with params in generic class or method definition like where T : new(*ctor_signature*)

### ISSUE THREAD

**Issue by woldemar89** [dotnet/csharplang#1974] opened 2018-10-31 20:01 UTC
I would like to have possibility to add params to constructor constraint in generic classes and methods:

`public class MyClass<T1, T2> where T1 : new(*parameters*) { }`

For example, I want to create next class: 

`public class MyClass<T1, T2> where T2 : new(T1) { }` 

to oblige T2 have ctor which accepts T1 instance, but can point only 'new()' constraint, 
and at the moment I need to use next way:

```
abstract class MustHaveConstructor<T>
{
     public MustHaveConstructor(T param) { }
}

class A { }

class B : MustHaveConstructor<A>
{
     public B(A a) : base(a) { }
}

public class MyClass<T1, T2> where T2 : MustHaveConstructor<T1> { }
```

Okay, fine, but the problem begins then I also want to have T2 inherited from T1:

`public class MyClass<T1, T2> where T2 : MustHaveConstructor<T1>, T1`

C# does not support multiple inheritance, so it is not possible to have both requirements.

I think it is not a single problem that can be solved by having params in constructor constraints.

**Comment by Logerfo** [comment] 2018-10-31 20:08
#769

**Comment by Tom01098** [comment] 2018-10-31 20:12
I like this, but I can't seem to think of any use cases? The `new()` constraint is useful because it ensures that the class/struct can be instantiated with no parameters, but in what case will I need to call `new T(42)`, with no context on how the 42 is used?

**Comment by woldemar89** [comment] 2018-10-31 20:52
> in what case will I need to call new T(42)

I did not meant concrete values, oppositely, it is all about generics.

For example, when due to some reason, you use Activator.CreateInstance in generic
method and need to be sure the call will not crash with exception.

```
 static T2 UpgradeRank<T1, T2>(T1 person) where T2 : T1, new(T1)
 {
       return (T2)Activator.CreateInstance(typeof(T2), person);
 }
```

**Comment by gafter** [comment] 2018-10-31 21:33
As mentioned, this is a duplicate of #769. This would be solved either by [Shapes](https://github.com/dotnet/csharplang/issues/164) or [Type Classes](https://github.com/dotnet/csharplang/issues/110).

**Closed by gafter** 2018-10-31 21:33 UTC
