### ISSUE TITLE
Proposal: delegate shorthand similar to method group for other language features

### ISSUE THREAD

**Issue by uvero** [dotnet/csharplang#3611] opened 2020-06-25 09:25 UTC
## Existing syntax

With C# delegates, one can refer to static methods as delegates by name. For example, when in the same type, if there is a method `static void Foo()` we can refer to it by `Action a = Foo;`. If `Foo` is accessible then it can be referred from the outside like `Action a = ClassName.Foo;`. 

This is also true for instance-methods if within the same type. For example, if `void Bar()` exists, we can use `Action a = Bar; // or this.Bar`. This can also be done with a reference to an instance, such as `Action a = x.Bar;` (if the method is accessible).

(Of course, this is true for other types of delegates).

## Proposal for extending this syntax

However, say that we want to create a delegate that takes an argument and calls an instance method on the argument. For example, the `ToString` to be used with the Linq `Select` method. Currently, in C#, you'd type `enumerable.Select(x => x.ToString())` - which of course isn't terrible, but if I had a static method called `ToString` and took a parameter I could type `enumerable.Select(ToString)`. the proposal is, for this case, to have a syntax like

```cs
Func<Type, string> fun = Type::ToString;
```

This becomes more noticable when defaling with a method that takes some arguments. Take for example:
```cs
Action<MyType, int, double, string> action = (myt, i, d, s) => StaticMethod(myt, i, d, s); // can already be shortened to StaticMethod
Action<MyType, int, double, string> another = (myt, i, d, s) => myType.InstanceMethod(i, d, s); // should be able to shorten to somethong like MyType::InstanceMethod
```

We may also want to do this for properties, both static and instance. Such as

```cs
Func<Type, int> getter = Type::Property;
Action<Type, int> setter = Type::Property=;
```

And index properties, such as:
```cs
Func<Type, int> indexGet = Type::[];
Action<Type,int> indexSet = Type::[]=;
```

The latter, but also the suggestion in general, is inspired by Ruby, where, for example, setters are just methods with a name that ends with an equal sign (`=`). That is, `foo.property = value` is just syntax for `foo.property=(value)`, where `property=` is just a method, with a valid method name.

Edit: I forgot - also constructors! 

existing:
```cs
Func<MyType> ctorNoArg = () => new MyType();
Func<int, MyType> ctorArg = x => new MyType(x);
```

proposal:
```cs
Func<MyType> ctorNoArg = MyType::new;
Func<int, MyType> ctorArg = x => MyType::new;
```

**Comment by leandromoh** [comment] 2020-06-27 02:13
I found this can be a bit confuse for the most part of developers, but it make sense. 
Properties and constructors are methods at all, so we might have a way to assing it to a delegate without a mandatory wrapper.

**Comment by HaloFour** [comment] 2020-06-27 02:23
I like the idea of the method references.  I don't know that `::` would work as that's [already an operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/namespace-alias-qualifier) for resolving types from aliases.  I also don't care for borrowing that Ruby syntax.  I think the compiler can figure out which accessor you're referencing based on the signature of the delegate, e.g. `Action<Type, int>` for a setter vs. `Func<Type, int>` for a getter.

**Comment by HaloFour** [comment] 2020-06-27 02:24
Mostly a dupe of #84

**Comment by YairHalberstadt** [comment] 2020-12-03 12:45
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/84

**Closed by YairHalberstadt** 2020-12-03 12:45 UTC
