### ISSUE TITLE
Converted constants in a switch statement [spec bug and proposed fix]

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#1282] opened 2018-01-26 07:01 UTC
There appears to be a bug in the [specification of the `switch` statement](https://github.com/dotnet/csharplang/blob/master/spec/statements.md#the-switch-statement) (ECMA 13.8.3). This appear in the spec:

> The constant expression of each `case` label must denote a value that is implicitly convertible ([Implicit conversions](https://github.com/dotnet/csharplang/blob/master/spec/conversions.md#implicit-conversions)) to the governing type of the `switch` statement. A compile-time error occurs if two or more `case` labels in the same `switch` statement specify the same constant value.

This permits the following code, which the compiler rejects:

``` c#
    {
        const int N1 = 1;
        const short N2 = 1;
        int x = 1;
        switch (x)
        {
            case N1:
            case N2: // error CS0152: The switch statement contains multiple cases with the label value '1'
        		break;
        }
    }
```

This is permitted by the spec because `N1` and `N2` do not "specify the same constant value". They are not even of the same type.

The simple "fix" would be to require that the ***converted expressions*** do not specify the same constant value. However, that would expose a different problem. In the current spec, a null literal is not a constant value after it has been converted to a nullable type such as `int?`. As a result, the modified rule would permit multiple `null` cases (because they do not specify the same constant value after conversion, as they do not in fact specify a constant value at all after conversion).

I believe the way to fix these issues is to
1. Modify the quoted section to say something like "A compile-time error occurs if two or more `case` labels in the same `switch` statement specify the same constant value after the conversion."
2. In the section [Constant expressions](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#constant-expressions) (ECMA 12.20), in the bullet list following the introductory sentence "The following conversions are permitted in constant expressions:", add a new bullet reading "Null literal conversions".

These proposed changes correspond to what the Roslyn compiler actually does.

[This is a duplicate of an [open issue being tracked in the C# ECMA specification](https://github.com/ECMA-TC49-TG2/spec/issues/942). I have created this copy for reference by the Roslyn team. -@gafter]

**Comment by Unknown6656** [comment] 2018-01-26 07:42
@gafter : I openend a pull request.

**Comment by AlekseyTs** [comment] 2018-01-26 18:18
I do not believe the "Constant expressions" section should change. Values of nullable types should never be considered as valid constant expressions.

**Comment by gafter** [comment] 2018-01-26 18:26
@AlekseyTs Do you have an alternate proposal to fix the spec that aligns with your belief?

**Comment by AlekseyTs** [comment] 2018-01-26 19:01
I do not have exact wording at the moment, but a change to the specification for the switch statement would align with my belief.  For example, somehow we were able to specify what expressions are permitted in a default-argument syntax without permitting values of nullable types to be valid constant expressions. I am sure we can manage that for switch as well.  

In addition, it looks like the problem with the switch is not limited to null literals. For example, the following code is valid today:
```
        int? nullable = null;
        switch (nullable)
        {
            case null:
                break;
            case 2:
                break;
        }
```

However, ```2``` converted to ```int?``` is not a valid constant expression. Not today, not even according to the proposed change above. And that does match how compiler works today, meaning the constant value does not survive a conversion like this. Whatever the switch implementation is doing to handle ```case 2:``` is not based on the constant value of converted expression and I don't think we would find it hard to do the same for the ```null``` literal case, or at least describe it in the specification.

**Comment by gafter** [comment] 2018-01-26 20:21
It sounds like the conversion from `2` to `int?` should also be treated as a constant. How would that conflict with the (externally observable) behavior of the language as implemented today?

**Comment by AlekseyTs** [comment] 2018-01-26 21:12
@Unknown6656 I think it is too early to submit pull requests, the proposal has to approved by LDM first.

**Comment by gafter** [comment] 2018-01-26 21:57
@AlekseyTs this issue is for the ECMA committee to deal with. We do not take normative changes in this version of the spec.

**Comment by MkazemAkhgary** [comment] 2018-01-26 23:39
I don't think spec is wrong because at first it says

>The constant expression of each case label must denote a value that is implicitly convertible (Implicit conversions) to the governing type of the switch statement.

`short` is implicitly convertible to `int` so following sentence becomes true

A compile-time error occurs if two or more case labels in the same switch statement specify the same constant value.

**Comment by gafter** [comment] 2018-01-28 18:21
@MkazemAkhgary The spec requires the constant values specified to be distinct. The constant value specified is the one before the conversion to the governing type of the switch statement.

**Comment by gafter** [comment] 2018-01-28 18:25
> somehow we were able to specify what expressions are permitted in a default-argument syntax without permitting values of nullable types to be valid constant expressions

@AlekseyTs The spec currently forbids this:

``` c#
        void M(int? x = (int?)null)
        {
        }
```

but the compiler permits it. The second bullet in the OP would help align the spec and the implementation for parameter defaults as well.

The relevant spec text is [here](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#method-parameters):

> The *expression* in a *default_argument* must be one of the following:
> 
> *  a *constant_expression*
> *  an expression of the form `new S()` where `S` is a value type
> *  an expression of the form `default(S)` where `S` is a value type

**Comment by AlekseyTs** [comment] 2018-01-28 18:44
@gafter  

What I meant is that we already able to specify how how to deal with non-constant expressions in context of default argument values. It doesn't mean that that section is complete, it should be easy to expand it to other forms of non-constant expressions.

**Comment by gafter** [comment] 2018-01-28 19:01
@AlekseyTs Yes, there are multiple ways of fixing a bug in the spec of parameter defaults with the same root cause. We can fix it in one place - constant expression - or in multiple places where "constant expression" is mentioned. We have the same bug here too:

``` c#
    case (int?)null:
```

The spec does not permit this, but the compiler does. It would seem simpler to fix the spec in one place.

**Comment by AlekseyTs** [comment] 2018-01-28 19:58
The place where you propose the fix, especially if we are going to make a change for non-null literals as well, has far reaching effects throughout the language and throughout the compiler. It might look easier, but, in fact, is very likely to cause compiler to change behavior or stop following the spec in other places, therefore, it is significantly more riskier. Clearly, a small bug in the compiler around conversions of null literals that is only observable through IOperation and can be easily fixed (even without modifying compiler's implementation) does not worth all this trouble. In my opinion it is better to fix **obvious omissions** in the specification of specific features  rather than trying to reshape a "corner stone".

**Comment by gafter** [comment] 2018-01-28 22:54
The compiler and the specification disagree not merely in the behavior of the `IOperation` API. Many of the places where constant expressions are used in the language (case expression, goto case expression, parameter default, etc) fail to obey the language specification, e.g. because of a misalignment involving nullable types. We (including specifically ECMA) need to find the best fix for the specification (i.e. what is the intended shape of the language), and then make `IOperation` behavior align with that specification. It doesn't make sense to make `IOperation` align with an error in the specification.

**Comment by AlekseyTs** [comment] 2018-01-29 00:28
> It doesn't make sense to make IOperation align with an error in the specification.

I think that there is no error in specification of "Constant Expression". Changes in this section are likely to cause unintended consequences. I have no problem fixing errors in specification of switch, etc.

**Comment by gafter** [comment] 2018-01-29 01:30
If you have a different proposal for how you'd like ECMA to fix all of the affected sections of the specification, I'll be happy to forward that to ECMA. At the moment we only have one proposal.

**Comment by BillWagner** [comment] 2021-04-30 17:35
Closing as a duplicate of dotnet/csharpstandard#174

**Closed by BillWagner** 2021-04-30 17:35 UTC
Labels: Spec
