### ISSUE TITLE
Feature Request: Allow return with Null coalescing operator

### ISSUE THREAD

**Issue by TwentyFourMinutes** [dotnet/csharplang#1932] opened 2018-10-14 09:42 UTC
Since you can do
```cs
int? test = 0;
int test2 = test ?? throw new Exception("Error");
```
I would suggest to also let it work with return like:
```cs
int? test = 0;
int test2 = test ?? return;
```

**Comment by yaakov-h** [comment] 2018-10-14 10:07
Partial duplicate of #176.

**Comment by willard720** [comment] 2018-10-15 19:10
I like it. Makes the code much shorter for a very common practice.

**Comment by jnm2** [comment] 2018-10-16 00:45
Sorry to bring the news, since I want this as much as everyone else:

> LDM discussed this feature yesterday and decided we do not want to do the feature.
There are possible interactions with expression blocks and other advanced control flow features, both of which aren't designed yet.
See upcoming LDM meeting notes for more details.

https://github.com/dotnet/csharplang/issues/867#issuecomment-391101967

**Comment by willard720** [comment] 2018-10-17 07:34
@jnm2 Not too surprised. I can also imagine it not being lacked for "hiding" the `return` statement to the righthand side, on top of making a lot more code paths

**Closed** 2019-09-04 17:31 UTC
