### ISSUE TITLE
switch implicit break

### ISSUE THREAD

**Issue by kameko** [dotnet/csharplang#1381] opened 2018-03-15 09:33 UTC
Per the conversation had in issue #1378, I am proposing a new syntax to the ``switch`` statement that does not add any new keywords or break existing code:
```cs
switch implicit break (X)
{
    case Y:
    {
        ...
        //no break;
    }
    case Z:
    {
        ...
    }
    //no break;
    default:
    {
        ...
    }
}
```

This enables the ``switch`` statement to implicitly add a ``break;`` statement at the end of every ``case`` statement, but every ``case`` statement must have brackets enclosing them. This syntax is consistent with other constructs ``try/catch``, and, if the Visual Studio options are enabled, the ``if`` statement and other constructs that create scope.
I very often use brackets to separate the ``case`` statement scope in ``switch`` statements, it would be a nice addition to give ``switch`` consistent syntax rules with the rest of the language.

Other variations to the syntax could be 
``switch (X) implicit break { ...`` or 
``switch break (x) { ...`` or 
``switch (X) break { ...``

My primary concern is that the cost of implementing this outweighs the benefits, but I can't tell since I have no statistics over how often people break up scope in their ``switch`` statements with brackets. I know that I personally use brackets in all my ``switch/case`` statements to keep consistent with using brackets in all my ``if`` and ``using`` statements, as well as to keep the scope of ``case`` statements separated.

**Comment by CyrusNajmabadi** [comment] 2018-03-15 09:39
> , if the Visual Studio options are enabled

Sorry, i'm not sure what this is in reference to.

**Comment by CyrusNajmabadi** [comment] 2018-03-15 09:40
> but every case statement must have brackets enclosing them. 

This seems weird.  You save on not needing a 'break' per case.   But then you require brackets for each case.  So, overall, it's a net gain of one-line per case in your switch  (with default formatting patterns).

This seems like it is actually worse overall compared to the syntax people can use today in switches.

**Comment by kameko** [comment] 2018-03-15 09:46
>Sorry, i'm not sure what this is in reference to.
Sorry, what I meant was navigating to ``Options > Text Editor > C# > Code Style > Auto Braces`` and changing it from "None".

>This seems weird. You save on not needing a 'break' per case. But then you require brackets for each case. So, overall, it's a net gain of one-line per case in your switch (with default formatting patterns).
I just feel this syntax is more consistent with the language. C# is a bracket-driven language, not a keyword-driven language. Most things open with a bracket and close with one, without any additional keywords at the end.

**Comment by stuartstein777** [comment] 2018-03-15 10:13
>> C# is a bracket-driven language, not a keyword-driven language. 

Given expression body everywhere, is that really the case?

Personally, I dislike unecessary brackets.

**Comment by kameko** [comment] 2018-03-15 10:21
>Personally, I dislike unecessary brackets.

Which is why this is syntactically an opt-in thing. There are some of us which use brackets everywhere (it may even be our company's standard), so it's nice to lessen the burden.

**Comment by jnm2** [comment] 2018-03-15 13:08
I only use braces in switch statements when variable names conflict.

**Comment by bondsbw** [comment] 2018-03-15 18:07
I see this as a questionable improvement on a dying language feature.

**Comment by fanoI** [comment] 2018-03-16 00:27
I usually use switch to avoid braces! I could do if / else if / else at that point...

**Comment by Thaina** [comment] 2018-03-16 05:29
Dying? I think with **pattern matching** and **switch expression** this keyword will got more usage in the near future

**Comment by Alxandr** [comment] 2018-03-16 08:15
If this syntax is to be adopted, the colon might be unnecessary. The switch could even be made to look  much more like an if:

```csharp
switch (foo) {
  case ("bar") {

  }

  case ("baz") {

  }

  case ("fizz")
  case ("buzz") {

  }

  default {

  }
}
```

The "fizz" and "buzz" case also inlines with how `using` syntax looks when you have multiple nested usings.

**Comment by bondsbw** [comment] 2018-03-16 13:19
@Thaina That is what I'm talking about.  The existing `switch` statement feature will be replaced for many use cases.

**Comment by YairHalberstadt** [comment] 2020-10-14 05:50
closing as duplicate of #3038 which is championed, and covers this and more

**Closed by YairHalberstadt** 2020-10-14 05:50 UTC
