### ISSUE TITLE
Proposal: Comma Operator

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/csharplang#3274] opened 2020-03-17 21:40 UTC
comma operator is good feature in javascript that evaluates each of its operands (from left to right) and returns the value of the last operand. can have same feature in c#?

suggested syntax:
```
var x = 1;
x = x++, x;
```
or 
```
var x = 1;
var z = x > 0 ? var y = 0, x++, x == y : 0;
```
or
```
var x = 1, x + 1;
```

**Comment by HaloFour** [comment] 2020-03-17 21:54
#3086

**Comment by CyrusNajmabadi** [comment] 2020-03-17 22:00
> `x = (x++, x);`

This is legal syntax.  So it definitely wouldn't be allowed :)

**Comment by mojtabakaviani** [comment] 2020-03-18 08:28
Comma operator uesuly use in condition experssion, proposal #3086 block experssion is same comma operator,
`var x = y > 10 ?  z++,y : 0;`
with block:
`var x = y > 10 ? { z++; y; } :  0;`
with Comma is cleaner!

**Comment by Joe4evr** [comment] 2020-03-18 10:59
Really? Because I had to squint to notice that comma. Shortening code does not make it cleaner.

**Comment by YairHalberstadt** [comment] 2020-11-23 12:03
Closing as duplicate of https://github.com/dotnet/csharplang/issues/3086. Whilst the syntax is different, the championed issue is the place to discuss it.

**Closed by YairHalberstadt** 2020-11-23 12:03 UTC
