### ISSUE TITLE
Bug when dynamic parameter is passed to an async method

### ISSUE THREAD

**Issue by CalinBunea** [dotnet/csharplang#6841] opened 2022-12-29 12:41 UTC
Hello,
I have the following code:
```

        private async Task TestDynamicAsync()
        {
            dynamic myDynamicParameter = null;
            string[] arrayOfStrings = { "1", "2", "3" };
            //this produces compilation error 
            //IEnumerable<Task<string>> enumerable = arrayOfStrings.Select(str => DoSomeWorkAsync(str, myDynamicParameter));
            
            //this is the return type of Select
            IEnumerable<dynamic> enumerable = arrayOfStrings.Select(str => DoSomeWorkAsync(str, myDynamicParameter));
        }

        private async Task<string> DoSomeWorkAsync(string someStringParameter, dynamic someDynamicParameter)
        {
            await Task.Yield();
            return string.Empty;
        }


```
Why the compiler forces return type to be `IEnumerable<dynamic>`  when is crystal clear that the method signatures specifies the return type of `IEnumerable<Task<string>>`  ? Why the return type is changed to dynamic when you use an input parameter as dynamic? Isn't this a bug?

**Comment by svick** [comment] 2022-12-29 14:18
This is a duplicate of https://github.com/dotnet/csharplang/discussions/2803.

**Closed by svick** 2022-12-29 14:18 UTC
