### ISSUE TITLE
Allow methods, properties, etc. to be called on nullable value types as if they were the real type.

### ISSUE THREAD

**Issue by ekolis** [dotnet/csharplang#2822] opened 2019-09-24 14:27 UTC
For instance, if I have a struct `MyStruct` with a method `DoStuff` then I can't say

```
MyStruct? s = new MyStruct();
s.DoStuff();
```

Instead I have to say

```
s.Value.DoStuff();
```

This is inconsistent with the C# 8 "nullable reference types" behavior and requires extra typing; I think this should be made consistent.

**Comment by HaloFour** [comment] 2019-09-24 15:13
IMO having to unbox the NVT explicitly makes it clear what you intend to do.  You can avoid using `Value` by using pattern matching against the type of the struct directly.

If this were to be added to the language in order to avoid breaking changes it would have to be the last thing the compiler considered and only apply where it would otherwise be a compiler error.  That includes resolution of extension methods.  So it could be confusing if sometimes the compiler accessed the underlying struct directly but other times it accessed `Nullable<T>`, e.g.:

```cs
using System;

public struct MyStruct {
    public string Value => "foo";
    public string GetValue() => "foo";
    public string DoStuff() => "foo";
}

public static class Extensions {
    public static string GetValue(this MyStruct? ms) => "bar";
}

static class Program {
    static void Main() {
        MyStruct? ms = new MyStruct();
        
        Console.WriteLine(ms.Value); // prints "bar"
        Console.WriteLine(ms.GetValue()); // prints "MyStruct"
        Console.WriteLine(ms.DoStuff()); // prints "foo"
    }
}
```

**Comment by ufcpp** [comment] 2019-09-24 15:17
See https://github.com/dotnet/csharplang/issues/1865

**Comment by 333fred** [comment] 2019-09-24 15:52
We considered this: https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-10-24.md#using-nullable-values-as-non-nullable-values. Ultimately, we decided against it for a few reasons, most importantly the lack of precision in some areas of the flow analysis.

**Comment by gafter** [comment] 2019-09-24 20:30
Interesting that customers would ask for *additional* cases that throw an implicit `NullReferenceException`s rather than fewer.

**Comment by Thaina** [comment] 2019-09-27 04:11
That was all of the point we have `?.` syntax. You could just use `s?.DoStuff();
`

**Comment by YairHalberstadt** [comment] 2020-11-05 11:55
Closing as duplicate of https://github.com/dotnet/csharplang/issues/1865

**Closed by YairHalberstadt** 2020-11-05 11:55 UTC
