### ISSUE TITLE
antlr grammar license?

### ISSUE THREAD

**Issue by xied75** [dotnet/csharplang#773] opened 2017-07-27 21:58 UTC
Dear team,

Just want to clarify the licensing model on the antlr grammar in the specs markdown? e.g. for the C# 6 draft  spec. Would it be ok for the antlr community to use those grammars in a suitable open license?

Currently there is a set of g4 files here: https://github.com/antlr/grammars-v4
https://github.com/antlr/grammars-v4/tree/master/csharp

It would be great if the work can be unified into One.

p.s. By any chance all those segments we saw over multiple markdowns are in fact in a single file form somewhere?

**Comment by svick** [comment] 2017-07-27 22:35
The spec was originally converted to Markdown and grammar to ANTLR in [ljw1004/csharpspec](https://github.com/ljw1004/csharpspec), which also contains [the grammar in a single file](https://github.com/ljw1004/csharpspec/blob/gh-pages/csharp.g4).

And I agree it would be great if the spec and grammar were licensed under an open license, but I think [this file](https://github.com/dotnet/csharplang/blob/master/spec/LICENSE.md) makes it clear that's not currently the case.

**Comment by 4creators** [comment] 2017-07-27 22:40
How does this license statement relates to the fact that C# language specification is an approved international standard? Is this an overreaching copyright declaration?

**Comment by svick** [comment] 2017-07-27 23:14
@4creators I don't think that changes anything. Especially considering that, AFAIK, standards often aren't licensed under open licenses, and certainly aren't released into the public domain. For example, the ISO C++ standard is not even gratis (free as in beer), let alone libre (free as in speech).

Specifically, I couldn't find any kind of license for [the ECMA version of the C# 2.0 spec](http://www.ecma-international.org/flat/publications/Standards/Ecma-334.htm) and [the ISO version of the C# 2.0 spec has a really draconian license](http://standards.iso.org/ittf/PubliclyAvailableStandards/c042926_ISO_IEC_23270_2006(E).zip):

> The document is a single-user, non-revisable Adobe Acrobat® PDF file. You are downloading a single-user licence to store this file on your personal computer. Under no circumstances may the electronic file you are licensing be copied, transferred, or placed on a network of any sort without the authorization of the copyright owner.
>
> You may print out and retain one-only printed copy of the PDF file.

**Comment by jnm2** [comment] 2017-07-28 01:23
> The document is a single-user, non-revisable Adobe Acrobat® PDF file. You are downloading a single-user licence to store this file on your personal computer. Under no circumstances may the electronic file you are licensing be copied, transferred, or placed on a network of any sort without the authorization of the copyright owner.
> 
> You may print out and retain one-only printed copy of the PDF file.

Who comes up with this stuff? 😆

**Comment by eyalsk** [comment] 2017-07-28 06:16
@jnm2 lawyers, ofc! 😆

**Comment by 4creators** [comment] 2017-07-28 11:39
> The unauthorized reproduction or distribution of this copyrighted work is illegal and may be punishable by criminal law.

That is another part of ISO licence language, however, I doubt it is enforceable with regard to syntax which is in the document as any reproduction and use i.e. for lexer/parser code generation is an intended use of the standard itself.  

This same goes for ECMA. 

> You may download without any restriction annotated by Microsoft ECMA standards. Inside there is an statement:This fourth edition cancels and replaces the third edition. Changes from the previous edition were made to align this Standard with ISO/IEC 23271:2006. The following companies and organizations have participated in the development of this standard, and their contributions are gratefully acknowledged: Borland, Fujitsu Software Corporation, Hewlett-Packard, Intel Corporation, IBM Corporation, ISE, IT University of Copenhagen, Jagger Software Ltd., Microsoft Corporation, Monash University, Netscape, Novell/Ximian, Phone.Com, Plum Hall, Sun Microsystems, and University of Canterbury (NZ)

Lack of copyright on any of documents produced by ECMA and Microsoft and statement as below:

> You may download without any restriction annotated by Microsoft ECMA standards

moves it into public domain. It is the same with photography -> publish picture without copyright notice and it is in public domain automatically.

**Comment by svick** [comment] 2017-07-28 12:20
@4creators 

> Lack of copyright on any of documents produced by ECMA and Microsoft […]
> moves it into public domain. It is the same with photography -> publish picture without copyright notice and it is in public domain automatically.

That's really not how copyright works. [Since 1989, copyright notices are optional in the US.](https://en.wikipedia.org/wiki/Copyright_notice)

**Comment by 4creators** [comment] 2017-07-28 13:40
But US is not a whole of the world and if you distribute work via internet ...

**Comment by svick** [comment] 2017-07-28 13:56
@4creators 

> But US is not a whole of the world and if you distribute work via internet

Yes, but [most of the world adopted the Berne convention](https://en.wikipedia.org/wiki/Copyright_formalities), which means copyright notices are not necessary.

> at least in EU there is huge distinction between work having copy notice or not having one

I don't believe there is. Do you have some source backing that claim?

**Comment by 4creators** [comment] 2017-07-28 14:52
No I dont have sources to back this claim and cannot provide them in reasonable time bcs I am not a lawyer :)

**Closed** 2020-09-08 21:42 UTC
Labels: Discussion, Move to Discussion
