### ISSUE TITLE
Code does not have correct font size in titles

### ISSUE THREAD

**Issue by sudeepku** [dotnet/csharplang#2386] opened 2019-04-02 19:23 UTC
Issue originally reported by @fghzxm on https://github.com/MicrosoftDocs/feedback/issues/1321
Describe the bug
If an article's title contains code, the code portion is not rendered in title font size, rather in contents font size.
To Reproduce
Visit https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.3/indexing-movable-fixed-fields (as of 3/24/2019 UTC).

Expected behavior
"fixed" has big, title font size.

Observed behavior
"fixed" has small, contents font size.
![image](https://user-images.githubusercontent.com/16726119/55430138-28aade80-5542-11e9-9fc2-6a3d0f872cf5.png)

**Comment by johnkellyoxford** [comment] 2019-04-02 22:43
Incorrect repo. This is for discussion of the C# language and design. Try dotnet/docs for this

**Comment by yaakov-h** [comment] 2019-04-02 23:28
This was transferred _from_ docs, but it seems to me that the issue is the rendering, not the content. GitHub [renders it correctly](https://github.com/dotnet/csharplang/blob/0f70a6dd94bb9fcefc9b47d2abea187fda8724d0/proposals/csharp-7.3/indexing-movable-fixed-fields.md#indexing-fixed-fields-should-not-require-pinning-regardless-of-the-movableunmovable-context).

**Comment by gafter** [comment] 2019-04-03 19:44
@sudeepku Why have you opened an issue in this repository?  What, exactly, do you think should change here?

**Comment by gafter** [comment] 2019-04-03 21:15
I looked at https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/indexing-movable-fixed-fields.md and can confirm that the source is correct.  I see that there is a rendering error on https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.3/indexing-movable-fixed-fields but this repo has no control over the randering of markdown elsewhere.

Closing. @sudeepku I recommend you reopen the original issue https://github.com/MicrosoftDocs/feedback/issues/1321

**Closed by gafter** 2019-04-03 21:15 UTC
