### ISSUE TITLE
Tuple types in using directives

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#423] opened 2017-04-10 01:24 UTC
@gafter commented on [Mon Nov 07 2016](https://github.com/dotnet/roslyn/issues/15072)

It has [been requested that](https://github.com/dotnet/roslyn/issues/347#issuecomment-258845034) we support

```cs
using Subject = (bool Gender, double Age);
```

---

@HaloFour commented on [Mon Nov 07 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259030127)

🍝   Generic version when combined with #3993?

``` cs
using Subject<T> = (T Gender, double Age);
```

---

@eyalsk commented on [Mon Nov 07 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259031337)

That's pretty cool! 

---

@DavidArno commented on [Wed Nov 09 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259089369)

At first glance, this seems an excellent idea. But then it takes on the texture of "aerosol cream": it looks like rich, thick, real cream but turns out to be 90% air. Yes, it would be useful occasionally, but the scope would then just be within that file. Some means of giving it a wider scope would really make this useful, eg:

**Subject.cs**

``` cs
public global Subject<T> = (T Gender, double Age);
```

**OtherFile.cs**

``` cs
bool GetGender(Subject<bool> subject) => subject.Gender; 

var gender = GetGender((false, 10));
```

**Update**
Having thought though this topic, I now feel that @alrz's point re records is pertinent. There should be no need for tuple aliases when we have records. So I no longer think this a useful feature at all.

---

@dsaf commented on [Tue Nov 08 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259096054)

@DavidArno this was previously rejected for some reason #7451.

---

@DavidArno commented on [Tue Nov 08 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259096680)

@dsaf,
That's a shame, but thanks for the link.

---

@MgSam commented on [Tue Nov 08 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259140337)

I'm happy with the proposal as @gafter specified. I think generics and global scope are both orthogonal to this feature and should be considered separately.

---

@DavidArno commented on [Tue Nov 08 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259141337)

Generics and global scope are enhancements to the basic proposal. So you appear to be misusing the term "orthogonal" :stuck_out_tongue: 

---

@MgSam commented on [Tue Nov 08 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259142957)

@DavidArno They are completely separable proposals that do not impact the merits of this feature as proposed. I'd call that orthogonal. Scope creep is the death of feature requests.

---

@qrli commented on [Tue Nov 08 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259344431)

I don't see this necessary. It is at best low priority.

If you want a type, define a type. 

---

@alrz commented on [Tue Nov 08 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259349637)

Once we have records, it'll be a piece of cake.

``` cs
struct Subject(bool Gender, double Age);
```

 I'd personally prefer to have generic and global type aliases over this.

---

@orthoxerox commented on [Wed Nov 09 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259386034)

@DavidArno records do not cover all the use cases you might need aliases for. See my example in #7453, there's no way a record can replace a long-winded generic interface type declaration. 

---

@DavidArno commented on [Wed Nov 09 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259387693)

@orthoxerox,

Apologies, my comment wasn't clear. I was referring to this specific feature request: tuple aliases, not type aliases in general. I've updated my comment to fix that.

---

@alrz commented on [Wed Nov 09 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259390825)

@DavidArno I'm saying that when you want a named tuple you'd better to define a struct record. But generic and global type aliases are useful for other scenarios, regardless of this proposal.

---

@AdamSpeight2008 commented on [Wed Nov 09 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-259468936)

Will the diposable form of using also be supported.

``` c#
using ( ( MyDisposable0, MyDisposable1 ) )
[
  ...
}
```

---

@alrz commented on [Sat Nov 12 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-260133252)

@AdamSpeight2008 This is already supported:

``` cs
using (IDisposable d1 = e1, d2 = e2) {}
```

Also see #9882 and #11420.

---

@AdamSpeight2008 commented on [Sat Nov 12 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-260134147)

@alrz That's not what I'm asking. 
Let's we have this function.

```
Function Foo(Of T As IDisposable(Of T), U As IDisposable(Of U)) () As ( T, U )
End Function
```

And it is call within the header of a using block.

```
using( Foo() ) { ... }
 // Will both part of the Tuple<T,U> be disposed?
```

Do the `Tuple<T,U>` dispose correctly the disposable items within the tuple? eg `.Item1` , `.Item2`

---

@HaloFour commented on [Sat Nov 12 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-260134282)

@AdamSpeight2008 

#9882

---

@AdamSpeight2008 commented on [Sat Nov 12 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-260134596)

@HaloFour  If the tuple is decomposed into separate variables, we risk the chance of disposing of a copy.

---

@HaloFour commented on [Sat Nov 12 2016](https://github.com/dotnet/roslyn/issues/15072#issuecomment-260134862)

@AdamSpeight2008 

That proposal goes over several potential implementations.  Either way, this proposal is about `using` for aliases, not `using` for disposables.  #9882 is about `using` for disposables and how that might relate to tuples, if at all.

---

@jcouv commented on [Sat Apr 08 2017](https://github.com/dotnet/roslyn/issues/15072#issuecomment-292746025)

@gafter Should this be moved to csharplang?

---

@gafter commented on [Sun Apr 09 2017](https://github.com/dotnet/roslyn/issues/15072#issuecomment-292828714)

@jcouv yes, I'll move it.

**Comment by jnm2** [comment] 2017-04-10 18:29
I'd like to see `using` directive aliases for all types, including generic constructions. Tuples would be one particular case of that.

**Comment by mattwar** [comment] 2017-04-14 17:15
Global usings sounds like something I would use.  I like the generic declaration too.. Let's turn usings into full on type aliases!

**Comment by jnm2** [comment] 2017-04-14 17:24
I want two things for two different reasons:

 1. Using directives, only in effect at compile time and no trace of them in the compiled output
 2. Type aliases, in effect at run time, the use of which would enable types to change namespace and name while staying binary compatible.

**Comment by hardhub** [comment] 2017-04-23 14:10
Regarding this:
using Subject = (bool Gender, double Age);

Can this be added in something like C# 7.1? I mean it is necessary ASAP.

We can declare tuple like this:
using Subject = ValueTuple<bool, double>;

And work with (bool Gender, double Age) as Subject
But it this case we are loosing names of fields!

Otherwise we will have to use structs as usual... no benefits from new tuples...

**Comment by jnm2** [comment] 2017-04-24 00:01
I disagree. I'm using tuples over structs to great effect already. Though I am looking forward to using aliases in general, including this.

**Comment by hardhub** [comment] 2017-04-24 06:57
> I disagree. I'm using tuples over structs to great effect already. Though I am looking forward to using aliases in general, including this.

If you want to abandon your code clarity it is your choice! But stop propagation of that!

This code de-facto is much less readable without tuples aliases:
```
if (this.Dictionary.TryGetValue(someuser.Code, out (string Name, string Surname, bool Active) value))
{
}
```

So I will repeat my question.. Why can we do this?

`using Setup = Dictionary<string, (string Name, string Surname, bool Active)>;`

But not this?
```
using Value = (string Name, string Surname, bool Active);
using Setup = Dictionary<string, Value>;

if (this.Dictionary.TryGetValue(someuser.Code, out Value value))
{
}
```

@DavidArno
`public global Subject<T> = (T Gender, double Age);`

It should NOT be global! It is local alias of type and should be local!

**Comment by DavidArno** [comment] 2017-04-24 07:08
@Hard hub,

It's clear you want these local aliases. What's way less clear to me, is what use they'd be. I've never used a type alias and really cannot see how your dictionary example would improve my code. Tuples though have obvious use cases in my view and are the single best feature of C#7. 

I'm looking forward to records, but not this alias suggestion.

**Comment by hardhub** [comment] 2017-04-24 07:51
> What's way less clear to me, is what use they'd be
As I directly specified above for code clarity...
Let's say it will be 10 parameters not 3...
Then structs becomes again more and more actual.
I tried new tuples to replace structs in my projects and realized that I cannot get the same clarity without aliases.

> cannot see how your dictionary example would improve my code.
It is not about your code it is about my code.. which can look like example provided above...
So does scrolling in GitHub example not make any sense for you?

**Comment by DavidArno** [comment] 2017-04-24 08:11
> As I directly specified above: for code clarity...

If you have 10 parameters, creating an alias would be sticking a plaster over the invected cut. That's not clarity; that's denial. If you have a 10 parameter tuple then it's time to pull up those refactoring tools and get addressing that.

And for your example, I'm not sure you have understood how to use tuples as you appear to be fighting with them, rather than working with them. A simpleway to do what you are trying to do, is:
```cs
class C
{
    private Dictionary<string, (string Name, string Surname, bool Active)> _dictionary = ...

    void M()
    {
        if (dict.TryGetValue("a", out var value))
        {
           // value.Name, value.Surname and val;ue.Active are all in scope here
        }

    ...
}
```

**Comment by hardhub** [comment] 2017-04-24 09:08
>If you have 10 parameters, creating an alias would be sticking a plaster over the invected cut. That's not >clarity; that's denial. If you have a 10 parameter tuple then it's time to pull up those refactoring tools and >get addressing that.

I do not agree. if we need 10 parameters we still need 10 parameters.. And it should be represented in most clear way available in language for the moment. And tuples without aliases are not the ones. For now it is solved with structs, but it is additional definition which I want to avoid with aliases and new tuples.

>private Dictionary<string, (string Name, string Surname, bool Active)> _dictionary =

You will have to specify this tuple everywhere... in each method accepting this value.. or returning this value... in other words in all code related to this tuple or this dictionary. Once again it is question of clarity... Anything complex (massive) is not clear by its definition.

>   if (dict.TryGetValue("a", out var value))

Nice trick...  But...
1) I prefer solution instead of tricks... Using of tuples aliases is very natural since it is existing for other types.
2) Using "var" everywhere is evil... it is OK only in cases when it is strongly mandatory. 
We will not discuss that here... you can google different articles why var is not accepted... I can only confirm this fact from point of view of my own experience.

**Comment by DavidArno** [comment] 2017-04-24 09:15
> Using "var" everywhere is evil...

Ah, I see the problem. What I see as the correct way to use tuples, you see as "tricks". What I see as the best way to write code, you see as "evil". What you see as "clarity", I see as badly written code. Clearly our views are too divergent at a fundamental level for any further meaningful discussion.

**Comment by DavidArno** [comment] 2017-04-24 09:22
Reading back through this thread is an interesting view on how my take on some ideas changes over time. I started out liking the idea of being able to express something like:
```cs
// Subject.cs
global using Subject<T> = (T Gender, double Age);
```
Then decided that there was little point to this if we had records. I now find this view reversed: there actually seems little point to records if we can have global aliases like the above.

**Comment by GeirGrusom** [comment] 2017-04-24 10:07
> there actually seems little point to records if we can have global aliases like the above.

Metadata. Conversion operators. Interface implementations.

**Comment by hardhub** [comment] 2017-04-24 10:08
> What I see as the correct way to use tuples, you see as "tricks". What I see as the best way to write code, you see as "evil". What you see as "clarity", I see as badly written code. 

I do not see any point to treat your opinion as correct.
You ignored absolutely all explanations and just try to say if it is not like I am doing that then all others are idiots.

Just one very simple thing to show your manner of discussion:
I said: Using of tuples aliases is very natural since it is existing for other types.
For me it is argument because it is unified approach for all data types possible in C#.
So why not for tuples?  Any your arguments why it should not be this way?

P.S.
Do you think thousands of developers said that var is evil because they are idiots? Or maybe they have some point of view which you cannot simply understand? What is most probable?

**Comment by DavidArno** [comment] 2017-04-24 10:18
@GeirGrusom,
> Metadata. Conversion operators. Interface implementations.

In my experience, conversion operators are more trouble than they are worth. Why would you want a pure data type to implement an interface? Metadata? Maybe...

**Comment by DavidArno** [comment] 2017-04-24 10:20
@hardhub,

You may find it useful to read up on ["appeal to the majority" fallacies](https://en.wikipedia.org/wiki/Argumentum_ad_populum).

**Comment by GeirGrusom** [comment] 2017-04-24 10:25
> In my experience, conversion operators are more trouble than they are worth. Why would you want a pure data type to implement an interface? Metadata? Maybe...

Conversion operators can be useful for value types. For example `public struct Id<TEntity>(Guid Id)` which would allow you a typesafe ID for database items it could be useful to have an explicit cast operator to `Guid` and vice-versa.

For the interface I guess you could provide an `IDeepClone` interface, or `IWith`. It's really difficult to pretend to know every use-case for this, but there definitely are some.

Metadata I think is obvious since ORM objects is an obvious use-case for records.

**Comment by DavidArno** [comment] 2017-04-24 10:27
@GeirGrusom,

Damn, I might have to flip-flop again! 😀

**Comment by GeirGrusom** [comment] 2017-04-24 10:47
Speaking of `Id<TEntity>` there might be a use-case for exporting aliases as well.

```csharp

public struct Id<TEntity, TId>(TId Value);
using Gid<TEntity> = Id<TEntity, Guid>;
using CustomerId = Id<Customer, long>;

public class Api
{
  public SynergizeCustomerRelation(CustomerId id);

  public CorrelateProfitAgility(Gid<Quarter> quarter);
}
```

It could be useful to have those type aliases available to API consumers as well.

**Comment by hardhub** [comment] 2017-04-24 10:49
> You may find it useful to read up on consensus fallacies. Whilst you are at it, it might help to read about false dichotomies too.

Exactly what I want to say.. You do not have any arguments even in very simple technical questions. And you try to guard yourself with high-flown words!

Non limitus hominus dolboebus!

**Comment by DavidArno** [comment] 2017-04-24 11:07
@GeirGrusom,

Nice example that actually shows the benefit of having both records and global type aliases.

This could be achieved using `public` to denote it's an exported alias:
```cs
public struct Id<TEntity, TId>(TId Value);
public using Gid<TEntity> = Id<TEntity, Guid>;
public using CustomerId = Id<Customer, long>;

public class Api
{
  public SynergizeCustomerRelation(CustomerId id);

  public CorrelateProfitAgility(Gid<Quarter> quarter);
}
```
Could use the simple rule:
```cs
using Alias = Type; // local to file
private using Alias = Type; // same as above; "private" thus optional as it's the default
internal using Alias = Type; // alias exposed to this project/assembly
public using Alias = Type; // alias exposed to all consumers of this assembly
```

**Comment by HaloFour** [comment] 2017-04-24 12:37
Also remember that aliases can't reference other aliases, only fully qualified types.  So you wouldn't be able to alias a named tuple and then use that alias as generic type arguments in other aliases.  You'd need to submit another proposal to expand those rules, which will likely have to include ways that the compiler can avoid circular references.

**Comment by jnm2** [comment] 2017-04-24 13:27
@hardhub Using `var` is a a valid and established practice designed specifically to address this very scenario. For all the years we've used anonymous type projections, we've had no choice but to use `var`.

**Comment by hardhub** [comment] 2017-04-24 13:35
@jnm2, anonymous types is single valid usage for var.. for all other cases it is bad practice...
Anonymous types are created during compilation.. for all other cases you know type and it should be used explicitly. But I do not want to discuss it now.. there are lot of information in the internet why it is bad ti use var...

I am just voting to add aliases for tuples as it is now for all other types...

You can do this:
`using MyValue = ValueTuple<int, int, int>;`

but not this:
`using MyValue = (int CustomName1, int CustomName2, int CustomName3);`

I think it is ridiculous...

**Comment by jnm2** [comment] 2017-04-24 13:45
@hardhub I agree that aliases would be useful. There is plenty of developer consensus on both sides of the `var` issue. If I had to guess from all my personal interactions and the articles I've read, I'd say `var` has become the majority position. But each is a valid point of view with plenty of people behind it. I make it a rule to always use `var` for the same reasons people make it a rule to always use `auto` in C++. Forced initialization encourages single assignment and a more immutable style of programming. To me `var` is more readable, maintainable and stylish. But even though I can't relate, I know there are downsides to `var` for some people too and that's okay.

**Comment by DavidArno** [comment] 2017-04-24 13:52
> To me var is more readable, maintainable and stylish

I can't remember which of the language team recently said it, but a good rule of thumb here is:

1. If most developers will read your code in an IDE, use `var`. It cuts down noise and improves readability, without reducing discoverability.
2. If most developers will read your code outside an IDE (eg the BCL code in Github), then avoid `var` as explicit typing carries more information and improves discoverability.

**Comment by jnm2** [comment] 2017-04-24 13:59
See, as to #2, I'd say that to properly understand the returned value's type in context, you'd want to start by look at the method returning it anyway. Once you do that, the type name is right in front of you. 😈

**Comment by CyrusNajmabadi** [comment] 2017-04-24 18:46
Geez guys.  Just cool it a bit.  :)   Let's have a nice relaxing discussion about incredibly geeky stuff.

**Comment by CyrusNajmabadi** [comment] 2017-04-24 19:12
My 2c.  There are two restrictions going on with aliases that i think we can improve on.  The first is that we just generally allow *any* type syntax to be supplied on the RHS.  It seems basically like an oversight that the RHS is limited to only named-types.  For example, you should be able to also say:

```c#
using mdtoken = int;
using StringArray = String[];
using MyLittleTuple = (int friendship, bool isMagic);
```

Such a system would be trivially easy for us to handle.  And i think it would actually just fall out by removing the named-type restriction on the RHS.

The second restriction is that an alias is just a simple name, whereas some people want it to be generic.  i.e. 

```c#
using StringMap<T> = Dictionary<string, T>;
```

This is much more complex as it means that aliases really are more than just a simple-name-to-type-mapping.  I think there's value here, but from a language/implementation perspective, it definitely gets more complex.

I would be interested in championing '1', but i think '2' is simply too large and should be broken into other proposals.  

Note: while i'm interested in championing, i've also been a terrible champion as i just haven't been able to get the time to work on these things with the enormous amount of other work i've had on my plate as well :-/   So take that as you will...

**Comment by HaloFour** [comment] 2017-04-24 19:17
@CyrusNajmabadi 

It's already #90.  Based on Roslyn's [#3993](https://github.com/dotnet/roslyn/issues/3993) which @gafter [preferred](https://github.com/dotnet/roslyn/issues/116#issuecomment-161866245) to the alternatives.

I think that there's a third proposal buried here too and that's having aliases that refer to other aliases, which is probably even more complicated than either 1 or 2.

**Comment by CyrusNajmabadi** [comment] 2017-04-24 19:20
> I think that there's a third proposal buried here too and that's having aliases that refer to other aliases, which is probably even more complicated than either 1 or 2.

Ah yeah.  I would like that as well. We could always implement that as a post pass.  i.e. if a typename in an  alias it looked up with our current rules, and it fails to find anything, then you can look at the names of previous aliases and bind to those.  

That said, again, I think allowing arbitrary type-syntaxes on hte RHS of a normal 'simple name' alias is reasonable, and ideally not that expensive.  I would champion it.

**Comment by mattwar** [comment] 2017-04-24 19:38
I'll champion any proposal that adds more var.

**Comment by CyrusNajmabadi** [comment] 2017-04-24 19:38
```using Cowbell = var;```

**Comment by DavidArno** [comment] 2017-04-24 19:43
@mattwar,

I'd prefer more let. Perhaps @CyrusNajmabadi could champion the following being valid:
````cs
using let = var;
```
Then I could use `let` instead of `var` throughout my code.

🙈 🙉 🙊

**Comment by AdamSpeight2008** [comment] 2017-04-24 19:46
@mattwar and @DavidArno 
I'd prefer more dim.
```c#
using dim = var;
```
So it more akin to VB and we all win.

**Comment by IllidanS4** [comment] 2017-05-05 21:42
using dim = dynamic;
Even more akin to VB.

**Comment by TruePluto** [comment] 2017-09-29 08:45
```
        Dictionary<MyNameIsVeryLong, Lazy<Dictionary<(MyNameIsVeryLong MyNameIsVeryLonga, (MyNameIsVeryLongLong MyNameIsVeryLongab, MyNameIsVeryLongLongLong MyNameIsVeryLongabb)), Lazy<((MyNameIsVeryLong MyNameIsVeryLongaa, (MyNameIsVeryLongLong MyNameIsVeryLongab, MyNameIsVeryLongLongLong MyNameIsVeryLongabb)) Key, (YouNameIsVeryLongToo MyNameIsVeryLongac, (YourNameIsVeryLongToo MyNameIsVeryLongad, HisNameIsVeryLongToo MyNameIsVeryLongae)) Value)>>>> ssssss
            = new Dictionary<MyNameIsVeryLong, Lazy<Dictionary<(MyNameIsVeryLong MyNameIsVeryLonga, (MyNameIsVeryLongLong MyNameIsVeryLongab, MyNameIsVeryLongLongLong MyNameIsVeryLongabb)), Lazy<((MyNameIsVeryLong MyNameIsVeryLongaa, (MyNameIsVeryLongLong MyNameIsVeryLongab, MyNameIsVeryLongLongLong MyNameIsVeryLongabb)) Key, (YouNameIsVeryLongToo MyNameIsVeryLongac, (YourNameIsVeryLongToo MyNameIsVeryLongad, HisNameIsVeryLongToo MyNameIsVeryLongae)) Value)>>>>();

```
that will be ok

**Comment by Thaina** [comment] 2017-12-29 03:56
This would be really great feature

**Comment by madelson** [comment] 2018-05-09 10:58
I'd be in favor of supporting the basic version of this:

```
using MyName = (int a, string b...);
```

While this would be a new feature, conceptually it feels more like it removes a caveat in how two existing features work together. The language becomes easier to learn and understand when there are fewer caveats like this.

**Comment by AustinBryan** [comment] 2018-06-08 03:22
I think global aliases are a great idea. I've had to reuse an alias before in multiple files and it's annoying to have to keep typing or copy and pasting. Plus, then we'd only have to change the alias value in one place, instead of 20.

**Comment by weitzhandler** [comment] 2018-10-17 22:38
Yes please. Very compelling feature indeed.

**Comment by weitzhandler** [comment] 2018-10-17 22:53
Very compelling, because when using `ValueTuple` as an alias you can't name the various field.

Please implement this feature!

**Comment by Thaina** [comment] 2018-10-18 01:41
Somehow I think global alias is better be normal plain old `struct`

**Comment by weitzhandler** [comment] 2018-10-18 02:50
I think `global` is out of this issues scope. Although `global` might be a good idea in general, I see the current suggestion of addressing C# value type `using` aliases more important to me.

**Comment by Thaina** [comment] 2018-10-18 12:52
@weitzhandler I don't think so. If you need to have alias for tuple more than one file it suspiciously should be solid `class` or `struct`

**Comment by weitzhandler** [comment] 2018-10-20 19:31
@Thaina that's why I was saying that `global` doesn't belong here.

Again, although I don't think `global` is a bad idea general, not just for `Tuple`s. Say you need a `Dictionary<UniqueID, UserRoleProjectDetails>` and then `KeyValuePair<UniqueID, UserRoleProjectDetails>` of the above. Maybe you'd want to make a global alias for that. It's arguable, but in any case doesn't belong here.

**Comment by pellet** [comment] 2018-10-30 06:15
as a workaround you can use a delegate alias to return your tuple type eg:
```
public delegate IObservable<Unit> WriteCache(JObject json);
public delegate IObservable<JObject> ReadCache();
public delegate (WriteCache Write, ReadCache Read) CacheTupleFactory();
```

**Comment by IanKemp** [comment] 2018-11-16 10:13
@pellet not sure how your suggestion works around this problem, could you provide a fuller example?

**Comment by pellet** [comment] 2018-11-16 13:34
Subject.cs
```csharp
delegate (bool Gender, double Age) GetSubject();
```

OtherFile.cs
```csharp
bool GetGender(GetSubject getSubject) => getSubject().Gender;
var gender = GetGender(() => (false, 10));
```

I couldn't live with passing around lambdas just to be able to refactor tuples easily via something like an alias so I went back to using interfaces.

**Comment by kofifus** [comment] 2019-01-11 00:55
Would be great to have this in v 7.x .. as it now seems v8 is late and may not include records ..

**Comment by yaakov-h** [comment] 2019-01-11 01:18
A C# release is never late, nor is it early, it arrives precisely when it means to.

**Comment by kofifus** [comment] 2019-01-11 01:33
(like Chuck Norris)

**Comment by mlhpdx** [comment] 2019-01-24 01:20
> @hardhub,
> 
> It's clear you want these local aliases. What's way less clear to me, is what use they'd be. I've never used a type alias and really cannot see how your dictionary example would improve my code. Tuples though have obvious use cases in my view and are the single best feature of C#7.
> 
> I'm looking forward to records, but not this alias suggestion.

I am *very much* looking forward to it.

Clarity.  Repeated type (tuple) declarations require readers to carefully inspect each to ensure they are identical.

Efficiency.  Edit once, change everywhere.

Consistency. The current limitations on aliasing tuples (but not generic that use tuples?!) is just one more inconsistency that folks encounter in learning C# today.

**Comment by MohammadHamdyGhanem** [comment] 2019-03-04 17:28
Why is not this proposal a champion?

**Comment by jcouv** [comment] 2019-03-04 17:58
> Why is not this proposal a champion?

No LDM member has felt passionate enough about this proposal yet to take ownership and drive it. Most likely there are other proposal that they feel are more worthwhile at this point.
One way to help is to voice your interest in the proposal and explain why it is important and why you care.

**Comment by MohammadHamdyGhanem** [comment] 2019-03-04 18:12
@jcouv 
This proposal solves the issue I posted in #1547 , and is better than my own proposal
Instead writing:
```C#
protected List<(Char from, Char to)> Ranges = new List<(Char from, Char to)>();
public CharClass(params (Char from, Char to)[] ranges){
}
```
it can be:
`using Range = (Char from, Char to)`

```C#
protected List<Range> Ranges = new List<Range>();
public CharClass(params Range[] ranges){
}
```

**Comment by CyrusNajmabadi** [comment] 2019-03-04 19:02
@MohammadHamdyGhanem I would recommend participating in these discussions over at gitter.im/dotnet/roslyn or gitterim/dotnet/csharplang.  People will be able to answer your questions quickly and you can hvae the sort of discussions you seem to want to participate in.  Cheers!

**Comment by IanKemp** [comment] 2019-07-31 08:13
Still no LDM champion for this? :(

**Comment by dustinlacewell** [comment] 2019-08-25 07:45
Pls.

**Comment by Thaina** [comment] 2020-03-31 08:14
I want to retracted my against on `global alias`

Currently now I have working on idea to make a `double` typed `Vector` library that utilize tuple instead of specific struct. And so I have many function that look like this

```C#
public namespace DoubleNumerics
{
	public static class Vector2Tuple
	{
		public static double Distance(this in (double X,double Y) min,in (double X,double Y) max) => Math.Sqrt(min.DistanceSquare(max));
		public static double DistanceSquare(this in (double X,double Y) min,in (double X,double Y) max)
		{
			var (x,y) = max.Remove(min).Pow(2);
			return x + y;
		}

		public static (double X,double Y) Pow(this in (double X,double Y) value,double p) => (Math.Pow(value.X,p),Math.Pow(value.Y,p));
		public static (double X,double Y) Add(this in (double X,double Y) left,in (double X,double Y) right) => (left.X + right.X,left.Y + right.Y);
		public static (double X,double Y) Remove(this in (double X,double Y) left,in (double X,double Y) right) => (left.X - right.X,left.Y - right.Y);
		public static (double X,double Y) Average(this in (double X,double Y) left,in (double X,double Y) right) => ((left.X + right.X) / 2,(left.Y + right.Y) / 2);
	}
}
```

This would be great if I could `global using` on the namespace level. So I could write these function with `using alias Vector2 = (double X,double Y);`  across multiple file in the same namespace

**Comment by michal-ciechan** [comment] 2020-07-17 10:39
> I think global aliases are a great idea. I've had to reuse an alias before in multiple files and it's annoying to have to keep typing or copy and pasting. Plus, then we'd only have to change the alias value in one place, instead of 20.

But then I would want namespace scoped aliases so that when I have a clash of class names. I can 

```csharp
namespace BusinessLogic
{
    global using User = Core.User   
}
```

And then everything underneath BusinessLogic will default to Core.User.

But personally I am with @madelson and 100% believe that adding a simple type alias local to a file is the best approach and a step in the right direction. 

I believe `globals` aliasing should be a separate feature, as I think it should potentially affect **all** type aliases, not just value tuples.

For now worst case scenario you can do `ReplaceAll` if it changes. not a massive deal. better than currently reading really long method/field declarations.

As a workaround you can always create a custom struct. using record types is a no go for me in a lot of cases, as it looks like its `class` based.

**Comment by IAmTheCShark** [comment] 2021-05-12 11:09
I just want to point out something I couldn't find in the discussion so far.
It is allready possible to use named tuples in those aliases, right now they do not work in a stand alone fashion, but they do for generic arguments.

This works:
`    using Bananas = System.Collections.Generic.IEnumerable<(int a, int b)>`

this doesnt (just for completenes)

`    using Banana = (int a, int b)`

and this would be really nice

```
    using Banana = (int a, int b)
    using Bananas = System.Collections.Generic.IEnumerable<Banana>
```

So it feels a little like an oversight to me.
Also the requirement for fully qualified names is a bit messy.

**Comment by tullo-x86** [comment] 2021-05-12 17:28
This gets even more ironic when you use an even-simpler generic like `Nullable<T>`:

```csharp
using Foo = System.Nullable<(string Key, object Value)>;

class Bar
{
	private Foo baz = ("A", new object());
	private Foo qux = null;
}
```

That said, since the language team seems to care more about records going forward, I'll probably just ignore tuples entirely from here on out. As long as something works 🤷🏼‍♂️.

**Comment by CyrusNajmabadi** [comment] 2021-05-12 17:42
> That said, since the language team seems to care more about records going forward

I am already championing the feature to address this :)

**Comment by jnm2** [comment] 2021-05-12 17:50
(https://github.com/dotnet/csharplang/issues/4284 tracks the fact that Andy and Cyrus are championing this)

**Comment by 333fred** [comment] 2021-05-12 18:52
I'm going to close this as a duplicate of #4284.

**Closed by 333fred** 2021-05-12 18:52 UTC
Labels: Discussion, Feature Request
