### ISSUE TITLE
Default literal in default value for nullable-typed parameter

### ISSUE THREAD

**Issue by ufcpp** [dotnet/csharplang#970] opened 2017-10-04 09:13 UTC
Is this by spec? or bug?

```cs
    static void Main()
    {
        int? x = default; // null
        int y = default; // 0

        Console.WriteLine(x); // null
        Console.WriteLine(y); // 0
        A(); // 0 !!
        A(default); // null !!
    }

    static void A(int? x = default) // 0 !!
    {
        Console.WriteLine(x);
    }
```

**Comment by HaloFour** [comment] 2017-10-04 15:17
To be honest I've found the way through which the compiler resolves the type of `default` to be very unintuitive.  The [proposal](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/target-typed-default.md) alludes to the rules being similar to the `null` literal.  As your example demonstrates it can be hard to discern what type the compiler will infer when which directly impacts the actual values and behavior of your code.

This is a perfect example of where I think the inference in this feature fails.  There's simply no reason the compiler should treat `int? x = default` differently when it's a parameter vs. a local vs. an argument.  The inference should be the same in all three cases.  It's perfectly legal for the parameter default value to be `null` for nullable value types, and even if it weren't to infer the non-nullable value type default still wouldn't be the right behavior.

Personally I'd probably go out of my way to avoid `default` in most cases, and especially where value types are concerned.  It becomes too difficult to reason about what the code is actually going to do or what values you'll end up with.

**Comment by lorcanmooney** [comment] 2017-10-04 18:16
Wow, that _has_ to be a bug ... right?

Even `IDE0034` thinks so:

![ide0034](https://user-images.githubusercontent.com/13181165/31192145-4b7a5df8-a938-11e7-853d-fa688459b589.png)

**Comment by HaloFour** [comment] 2017-10-04 18:24
@lorcanmooney 

There's an [open issue on Roslyn](https://github.com/dotnet/roslyn/issues/22184) tracking a bug where the IDE will suggest simplifying `default(T)` to `default` in circumstances where it will change the meaning of the code.  That case probably falls under that bug.

e.g.

```cs
object o = default(int); // IDE will suggest simplifying here which changes the value from 0 to null
```

**Comment by MgSam** [comment] 2017-10-04 19:43
That behavior of the parameter default is crazy and seems like it should be changed.

**Comment by alrz** [comment] 2017-10-04 20:32
I believe this has something to do with https://github.com/dotnet/roslyn/issues/20015#issuecomment-329856805:

>According to the language specification, a value of type int? is not a constant.

but a default parameter value *needs* to be a constant. so in case of a nullable type, we generate a cast to the underlying type which in this case it overrides the original target type with a non-nullable integer. boom.

**Comment by svick** [comment] 2017-10-04 20:40
@alrz 

Good guess, that's exactly what [the problematic code](https://github.com/dotnet/roslyn/blob/d5b6246e3528ea912564a0eb57d30c45df391bdd/src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs#L201-L211) does.

I should have a PR fixing this later today.

**Comment by HaloFour** [comment] 2017-10-04 20:43
@alrz 

Yet the following is perfectly legal?

```cs
public void M(int? i = (int?)null) { }
```

The bigger question here is whether this is a bug or intended behavior.  And if it's a bug is this something that can be corrected since the cat is out of the bag?

**Comment by MgSam** [comment] 2017-10-04 20:46
Overall usage of 7.2 so soon after release is probably very low. That and people will probably need to be more tolerant of breaking changes if they're consuming point releases.

**Comment by MkazemAkhgary** [comment] 2017-10-04 21:03
if its bug, why leave it as a bug? Imho this should be fixed, I don't think any one use this bug in his code by intent. because thats not what you expect. `default` is supposed to be an alternative to `default(T)` @HaloFour

**Comment by svick** [comment] 2017-10-04 22:11
I have created the PR to fix this: https://github.com/dotnet/roslyn/pull/22527.

**Comment by alrz** [comment] 2017-10-04 22:12
@HaloFour 

The expressions `null` or `(int?)null` always have a ConstantValue "null" but `default` doesn't (not after a conversion (compiler-generated or otherwise) which is the core issue here) so it won't get passed the condition. 

The `default(int?)` and `default(struct)` both represented as null constants here, none of which can be declared as `const` (special case). Seems like patterns also didn't cover this case (dotnet/roslyn#20015) but since we don't silently cast to `int`, we get an error.

**Comment by jnm2** [comment] 2017-10-05 15:19
> Overall usage of 7.2 so soon after release is probably very low.

I missed something. Was there a non-preview release of C# 7.1 yet?

**Comment by svick** [comment] 2017-10-05 16:07
@jnm2 

Yes, [Roslyn 2.3, which is included in VS 2017 15.3, supports C# 7.1](https://github.com/dotnet/roslyn/wiki/NuGet-packages#versioning). Though you have to opt-in by specifying language version of 7.1 or `latest`.

**Comment by jnm2** [comment] 2017-10-05 16:09
I understood that VS 15.3 was RTM and Roslyn was RTM but that Roslyn was implementing a non-RTM version of C# 7.1.

Is the rule of thumb then that RTM versions of Roslyn will never implement preview versions of C#?

**Comment by jnm2** [comment] 2017-10-06 12:58
I suppose this means 7.1 is RTM? https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1

I've been waiting to use it till I heard for sure. The [7.1 milestone](https://github.com/dotnet/csharplang/milestone/5) is incomplete here and there is no blog post which IIRC is supposed to be the only official channel for C# version announcements. ([Here was 7.0.](https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/))

**Comment by jnm2** [comment] 2017-10-06 12:59
And why do we need opt-in for it if it's RTM? That's weird.

**Comment by jcouv** [comment] 2017-10-06 17:10
@ufcpp Thanks a lot for reporting this. This is definitely a bug. 
The general rule of thumb is that `default` behaves like `default(T)` where `T` is inferred in all the places where we infer a type for `null`. In this case `void M(int? x = default)` should be the same as `void M(int? x = default(int?))`, but it's not. :-(

@svick Thanks for the PR. I'll start email thread with compat council.

@jnm2 C# 7.1 shipped RTM along with Visual Studio 2017 version 15.3. Yes, we need to make an announcement blog post. Sorry for the confusion.
You are correct: VS RTM ships with RTM version of the compiler and languages.
As far as opt-in story, most projects and most templates in VS use "default" as the `LangVersion`. It means "latest major version". You can use C# 7.1 by setting the `LangVersion` explicitly to `7.1` or by setting it to `latest` (which means "latest minor version"). A lightbulb will offer both options whenever you start using new syntax (supported by the compiler but not allowed in your project's current `LangVersion`).

**Comment by jnm2** [comment] 2017-10-06 17:38
I still think it's weird that the SDK doesn't set `<LangVersion>latest</LangVersion>` by default. Why force a difference between major and minor updates? To me it makes no sense to insulate people from minor changes while shoving them up to the next major version without asking as soon as it comes out.

**Comment by jnm2** [comment] 2017-10-06 17:43
Previews, yes; minor updates, no.

**Comment by jcouv** [comment] 2017-10-06 17:45
@jnm2 If we set LangVersion=latest in templates, then all the developers in a team would need to install the same Visual Studio update. Otherwise, some devs with version 15.5 would start using C# 7.2 features, while some other team members are still using version 15.3 (which only supports C# 7.1).

It is more reasonable to expect a team or company to align on a major version (everybody needs to update to Visual Studio 2017, for instance). Also, that has historically been the update model.

Switching your project(s) to use "latest" is an easy and one-time operation (again, a lightbulb helps you for that).

**Comment by jnm2** [comment] 2017-10-06 18:17
Okay, so you're tying major updates of C# to major updates of VS and minor updates of C# to minor updates of VS, RTM in all cases. Then that makes sense. Thanks for explaining.

**Comment by HaloFour** [comment] 2017-10-06 18:55
@jcouv 

I think that the obvious answer there is that if the compiler hits any syntax that it doesn't recognize that it should assume that it's probably a new feature in a later release and to prompt the developer to check for updates.

**Comment by jnm2** [comment] 2017-10-06 18:58
@HaloFour How would it be distinguishable from syntax that has never been legal?

**Comment by jcouv** [comment] 2017-10-06 19:05
Since this is an implementation bug rather than a spec bug. I'll close this issue in favor of Roslyn issue: https://github.com/dotnet/roslyn/issues/22578

Feel free to continue discussion.

**Closed by jcouv** 2017-10-06 19:05 UTC

**Comment by alrz** [comment] 2017-10-07 05:49
@HaloFour @jnm2  The compiler already does that? e.g. `default` in "default" or "7.0" langversion produce error since it's not available in that version. AFAIK there is also a code action to upgrade the project.

**Comment by jcouv** [comment] 2017-10-10 23:01
The fix will go into 15.5 (C# 7.2). Thanks @svick for the PR!

**Comment by aluanhaddad** [comment] 2017-11-07 03:57
If nothing prompts users to upgrade from 7.1 to 7.2 and had explicitly opted for 7.1 to use features such as tuple projection initializers, they may stay on 7.1 for an indefinite period. It would be good if there  were an advisory regarding this bug.

**Comment by jcouv** [comment] 2017-11-07 04:29
@aluanhaddad Any users that update to Visual Studio 2017 version 15.5 from version 15.3 will get the fix regardless of the language version setting they choose.
That said, I'll look in documenting this as a known issue. Thanks

**Comment by aluanhaddad** [comment] 2017-11-07 04:32
@jcouv thank you. That explains why I couldn't reproduce the issue ;)
