### ISSUE TITLE
Proposal: Polymorphic this types

### ISSUE THREAD

**Issue by lucasteles** [dotnet/csharplang#3472] opened 2020-05-20 21:39 UTC
Fluent style code is very common pattern in C# and I think we can improve the way we write it,

The problem is when we inherit from a class and call a fluent method from the base class the expected return type is the base class

there are better approaches to deal with this type of code, like having a way to return the derivated class type in methods of the base class 

[TypeScript have a feature to deal with this](https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types)

So my proposal is to mimic this TypeScript feature

Code sample:
```cs
public class Calc {
     public this Sum(int n) { ... } // note the 'this' return type
     public this Subtract(int n) { ... }
}

public class CientificCalc : Calc {
     public this Exp(int n) { ... }
}

var calc  = new ScientificCalc(1)
     .Sum(1) // method from Calc, but return ScientificCalc
     .Exp(2) // because it still a ScientificCalc we can call Exp()
     .Sub(1);
```

thinking of having an implicit `return this`  in this kind of method could be a good idea too.

**Comment by yaakov-h** [comment] 2020-05-20 21:54
This looks like a duplicate of #902.

**Comment by CyrusNajmabadi** [comment] 2020-05-20 22:03
CLosing out as dupe of https://github.com/dotnet/csharplang/issues/902.  Thanks!

**Closed by CyrusNajmabadi** 2020-05-20 22:03 UTC
