### ISSUE TITLE
covariance records and structs

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#1152] opened 2017-11-27 20:12 UTC
readonly records and structs can be covariant.

```
public class Foo<out T>
{
    public T Value { get; }    
    public T GetValue() => Value; // or this
}
public struct Bar<out T>
{
    public T Value { get; }
}
```

restrictions are as follows

 - covariant generic type must be only used as output. (except at constructor can be safely used as input)
 - if covariant field is used, it must be marked as readonly.
 - if covariant type is used in generic parameter of other type, that type must be also covariant.

do not get confused, structs can also support covariance. as long as `T` is not value type, `Bar` it self as a record can support covariance and `T` can be variant.

due to lack of knowledge i propose it here, although this may require improvements to CLR.

with above restrictions I don't see any other concerns, but if there is, let me know. attempting to change variant field of record via reflection, should cause run time exception. even if assignment is type safe.

**Comment by Happypig375** [comment] 2017-11-28 13:31
See https://github.com/dotnet/roslyn/issues/13982 and https://github.com/dotnet/roslyn/issues/171.
Quoting https://github.com/dotnet/roslyn/issues/171#issuecomment-239947729:
>This would be a large undertaking including required CLR support, for marginal gain in language expressiveness. We don't think this is where we want to invest.

You may want to make sure this is not a duplicate of Item 3 in https://github.com/dotnet/csharplang/issues/317.

**Closed** 2018-02-02 08:57 UTC
Labels: Discussion, Feature Request
