### ISSUE TITLE
Delegate parameters cannot mark attribute, why?

### ISSUE THREAD

**Issue by Sc7-git** [dotnet/csharplang#3653] opened 2020-07-08 01:11 UTC
Delegate cannot mark attribute, why?

```
    class Program
    {
        static void Main(string[] args)
        {
            Test.Add((s, o) => { });

            Test.Add(([MyAttribute]s, o) => { });//error
        }
    }

    public class MyAttribute : Attribute
    {

    }

    public class Test
    {
        public static void Add([My]Action<string,object> action )
        {

        }
    }

```

**Comment by Sc7-git** [comment] 2020-07-08 01:21
I need to know that this is important to me

**Comment by CyrusNajmabadi** [comment] 2020-07-08 01:26
HI @Sc7-git, it sounds like you're asking a question here.  In regards to why this is not supported, the answer is simply that we never did the work to make it possible.  The default state of hte language is that anything not explicitly allowed is disallowed, and so that's why you can't add attributes here.

Now, if you're not asking a question and instead are asking for this to be supported, it would then be good if you can actually write up a proposal here for what you want and explain how it would work.  Thanks!

**Comment by Sc7-git** [comment] 2020-07-08 02:37
I have a demo of dependency injection here. I hope that the lambda parameter can be marked with RequiredServiceAttribute,so that my program throws an exception when it is injected, rather than at runtime. Thank you for your help！
`
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

namespace Test
{
    class Program
    {
        /*I have a demo of dependency injection here. 
          I hope that the lambda parameter can be marked with RequiredServiceAttribute,
          so that my program throws an exception when it is injected, rather than at runtime.
        */
        static void Main(string[] args)
        {
            var mysp = new MyServiceProvider();
            mysp.Add(typeof(IPerson), new Person() { Age = 22, Gender = false, Name = "jack" });        
            //mysp.Add(typeof(ITeacher), new Teacher() { Age = 23, Gender = true, Name = "tom" });
            Test.ServiceProvider = mysp;
            Test test = new Test();

            //Inject IPerson, ITeacher
            test.Use<IPerson, ITeacher>((s, p) =>
            {
                Console.WriteLine(s.Name);               
                Console.WriteLine(p.Name);//Error.   

                //If the RequiredServiceAttribute can be marked in the lambda parameter, then the exception should be thrown during injection
                //Examples: test.Use<IPerson, [RequiredService]ITeacher>((s, p) =>{}
            });

            Console.ReadKey();
        }
    }

    #region infrastructure

    public class Test
    {
        public void Use<T1, T2>(Action<T1, T2> action)
        {
            if (action == null)
                throw new ArgumentException(nameof(action));
            var type = action.GetType();
            var methodInfo = type.GetMethod("Invoke");
            var parameterInfos = methodInfo.GetParameters();
            List<object> list = new List<object>();
            foreach (var parameterInfo in parameterInfos)
            {
                var requiredServiceAttribute = parameterInfo.GetCustomAttributes<RequiredServiceAttribute>().FirstOrDefault();
                if (requiredServiceAttribute == null)
                    list.Add(ServiceProvider.GetService(parameterInfo.ParameterType));
                else
                    list.Add(ServiceProvider.GetRequiredService(parameterInfo.ParameterType));
            }

            methodInfo.Invoke(action, list.ToArray());
        }

        //Dependency injection
        public static IServiceProvider ServiceProvider { get; set; }
    }

    public class RequiredServiceAttribute : Attribute
    {

    }

    public static class ExtensionMethod
    {
        public static object GetRequiredService(this IServiceProvider serviceProvider, Type type)
        {
            var obj = serviceProvider.GetService(type);
            if (obj == null)
                throw new ArgumentException(nameof(type));
            return obj;
        }
    }

    public class MyServiceProvider : IServiceProvider
    {
        private Dictionary<Type, object> dict = new Dictionary<Type, object>();

        public IServiceProvider Add(Type serviceType, object value)
        {
            dict.Add(serviceType, value);
            return this;
        }

        public object GetService(Type serviceType)
        {
            if (dict.ContainsKey(serviceType))
                return dict[serviceType];
            return null;
        }

    }

    public interface IPerson
    {
        string Name { get; set; }
        int Age { get; set; }
        bool Gender { get; set; }
    }
    public class Person : IPerson
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public bool Gender { get; set; }
    }

    public interface ITeacher
    {
        string Name { get; set; }
        int Age { get; set; }

        bool Gender { get; set; }
    }
    public class Teacher : ITeacher
    {
        public string Name { get; set; }
        public int Age { get; set; }

        public bool Gender { get; set; }
    } 
    #endregion

}
`

**Comment by Sc7-git** [comment] 2020-07-08 03:48
> HI @Sc7-git, it sounds like you're asking a question here. In regards to why this is not supported, the answer is simply that we never did the work to make it possible. The default state of hte language is that anything not explicitly allowed is disallowed, and so that's why you can't add attributes here.
> 
> Now, if you're not asking a question and instead are asking for this to be supported, it would then be good if you can actually write up a proposal here for what you want and explain how it would work. Thanks!

@CyrusNajmabadi ,I have a demo of dependency injection here. I hope that the lambda parameter can be marked with RequiredServiceAttribute,so that my program throws an exception when it is injected, rather than at runtime. Thank you for your help！
`
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

namespace Test
{
    class Program
    {
        /*I have a demo of dependency injection here. 
          I hope that the lambda parameter can be marked with RequiredServiceAttribute,
          so that my program throws an exception when it is injected, rather than at runtime.
        */
        static void Main(string[] args)
        {
            var mysp = new MyServiceProvider();
            mysp.Add(typeof(IPerson), new Person() { Age = 22, Gender = false, Name = "jack" });        
            //mysp.Add(typeof(ITeacher), new Teacher() { Age = 23, Gender = true, Name = "tom" });
            Test.ServiceProvider = mysp;
            Test test = new Test();

            //Inject IPerson, ITeacher
            test.Use<IPerson, ITeacher>((s, p) =>
            {
                Console.WriteLine(s.Name);               
                Console.WriteLine(p.Name);//Error.   

                //If the RequiredServiceAttribute can be marked in the lambda parameter, then the exception should be thrown during injection
                //Examples: test.Use<IPerson, [RequiredService]ITeacher>((s, p) =>{}
            });

            Console.ReadKey();
        }
    }

    #region infrastructure

    public class Test
    {
        public void Use<T1, T2>(Action<T1, T2> action)
        {
            if (action == null)
                throw new ArgumentException(nameof(action));
            var type = action.GetType();
            var methodInfo = type.GetMethod("Invoke");
            var parameterInfos = methodInfo.GetParameters();
            List<object> list = new List<object>();
            foreach (var parameterInfo in parameterInfos)
            {
                var requiredServiceAttribute = parameterInfo.GetCustomAttributes<RequiredServiceAttribute>().FirstOrDefault();
                if (requiredServiceAttribute == null)
                    list.Add(ServiceProvider.GetService(parameterInfo.ParameterType));
                else
                    list.Add(ServiceProvider.GetRequiredService(parameterInfo.ParameterType));
            }

            methodInfo.Invoke(action, list.ToArray());
        }

        //Dependency injection
        public static IServiceProvider ServiceProvider { get; set; }
    }

    public class RequiredServiceAttribute : Attribute
    {

    }

    public static class ExtensionMethod
    {
        public static object GetRequiredService(this IServiceProvider serviceProvider, Type type)
        {
            var obj = serviceProvider.GetService(type);
            if (obj == null)
                throw new ArgumentException(nameof(type));
            return obj;
        }
    }

    public class MyServiceProvider : IServiceProvider
    {
        private Dictionary<Type, object> dict = new Dictionary<Type, object>();

        public IServiceProvider Add(Type serviceType, object value)
        {
            dict.Add(serviceType, value);
            return this;
        }

        public object GetService(Type serviceType)
        {
            if (dict.ContainsKey(serviceType))
                return dict[serviceType];
            return null;
        }

    }

    public interface IPerson
    {
        string Name { get; set; }
        int Age { get; set; }
        bool Gender { get; set; }
    }
    public class Person : IPerson
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public bool Gender { get; set; }
    }

    public interface ITeacher
    {
        string Name { get; set; }
        int Age { get; set; }

        bool Gender { get; set; }
    }
    public class Teacher : ITeacher
    {
        public string Name { get; set; }
        public int Age { get; set; }

        public bool Gender { get; set; }
    } 
    #endregion

}
`

**Comment by CyrusNajmabadi** [comment] 2020-07-08 09:21
> I hope that the lambda parameter can be marked with RequiredServiceAttribute,

You will have to create a proposal and have it accepted into the language by the design team for this to happen.

**Comment by jnm2** [comment] 2020-07-08 14:56
Not necessarily you, though. Duplicate of https://github.com/dotnet/csharplang/issues/3115?

**Comment by Sc7-git** [comment] 2020-07-08 15:32
> Not necessarily you, though. Duplicate of #3115?

Not exactly repeat, no mention of Delegate.

**Comment by HaloFour** [comment] 2020-07-08 15:37
The feature is related to lambdas, not delegates.  A delegate itself is just a declaration of a method pointer, and you can apply attributes to the parameters of the delegate.  What you can't do is apply attributes to the parameters of the method generated by the compiler when you use lambda syntax, so this proposal is effectively a duplicate of #3115.

**Comment by Sc7-git** [comment] 2020-07-08 16:11
> The feature is related to lambdas, not delegates. A delegate itself is just a declaration of a method pointer, and you can apply attributes to the parameters of the delegate. What you can't do is apply attributes to the parameters of the method generated by the compiler when you use lambda syntax, so this proposal is effectively a duplicate of #3115.

This is indeed feasible.
```
 public delegate void DelegateMethod([My] object a, string s);
```

But I hope this is the case because it is more flexible.

```
 DelegateMethod delegateMethod = delegate ([My] object a, string s) { };	
```

**Comment by CyrusNajmabadi** [comment] 2020-07-08 17:21
Closing this out as this is a duplicate.  If we were to do this for lambdas, we would do this for anonymous methods as well.

**Closed by CyrusNajmabadi** 2020-07-08 17:21 UTC
