### ISSUE TITLE
Default Generic parameters

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#3770] opened 2020-08-03 17:22 UTC
I find that I often have to write code like this:

````
 public static Task FileJob() {
            return FileJob<PreservationDialogModel>();
        }

        public static async Task FileJob<TDialogModel>() where TDialogModel:PreservationDialogModel, new() {
//....
}

````

It would be really nice if I could do this instead:
````
        public static async Task FileJob<TDialogModel = PreservationDialogModel>() where TDialogModel:PreservationDialogModel, new() {
//....
}
````

**Comment by svick** [comment] 2020-08-03 17:33
This is a duplicate of https://github.com/dotnet/csharplang/issues/278.

**Comment by 333fred** [comment] 2020-08-03 17:46
Closing as a duplicate.

**Closed by 333fred** 2020-08-03 17:46 UTC
