### ISSUE TITLE
Make new keyword optional when creating instances just as Dart

### ISSUE THREAD

**Issue by imgen** [dotnet/csharplang#2607] opened 2019-06-17 11:10 UTC
In Dart, we can create a new instance of a class like below
```
var x = ClassA();
```
I think it's quite good, esp. with nested instantiation

**Comment by canton7** [comment] 2019-06-17 12:24
Surely this is a breaking change, if there's a method called `ClassA`?

**Comment by Unknown6656** [comment] 2019-06-19 18:21
There is a proposal to use the following instead (#100):
```csharp
ClassA x = new();
```
This would use the same amount of characters as your proposal.

Besides, this proposal is a duplicate of #350.

**Comment by WrongBit** [comment] 2019-06-25 09:25
Variant with:
    ClassA x = new();
...is mostly helpful, but doesn't work when ClassA is abstract or it is "parent", which should be assigned with derived type. But I agree, shorter syntax could be nice:
    ClassA x = new; // who needs these parents??
    ClassB y = new(some args);

**Comment by YairHalberstadt** [comment] 2020-10-29 07:19
CLosing as duplicate of https://github.com/dotnet/csharplang/issues/350

**Closed by YairHalberstadt** 2020-10-29 07:19 UTC
