### ISSUE TITLE
Nullable reference types should support late initialization.

### ISSUE THREAD

**Issue by SittenSpynne** [dotnet/csharplang#2825] opened 2019-09-25 14:25 UTC
Many APIs and patterns use "late" initialization for a type's properties. Two examples:

* Entity Framework DbContexts populate any `DbSet<T>` properties of the object via reflection when the type is constructed.
* JSON parsing encourages the creation of POCOs that are created via default constructor and properties are set by the parser.

In either case, changing the property's type to nullable can imply semantics that are not intended. For example, nullable properties on a type that represents JSON can indicate "this member is not required". On EF model types it can indicate "this column should be nullable". 

These properties trigger nullability warnings as it is easiest to leave the variable uninitialized. To work around, one can use #pragma or set the properties to the confounding `null!`, but this adds a tedium penalty when one decides to enable nullable reference types.

I think there should be syntax (or an attribute) to allow a developer to indicate a property/field is going to be initialized before use by some mechanism static analysis can't see. For example, the null forgiveness operator could be expanded to have this meaning. Or, a keyword might fit:

```
public DbSet<Customer>! Customers { get; set; }
public lateinit DbSet<Customer> Customers { get; set; }
```

At runtime, failure to initialize these members will result in a NullReferenceException, but that is already the case with the #pragma or `null!` workarounds. The purpose of this proposal is to minimize the tedium of those manual steps for these use cases.

**Comment by Joe4evr** [comment] 2019-09-25 14:27
Duplicate of #2328.

**Comment by canton7** [comment] 2019-09-25 14:49
> set the properties to the confounding null!, but this adds a tedium penalty when one decides to enable nullable reference types.

I've done this in one of my codebases, and I don't think it's that bad. It's a nice reminder that you've got nullable semantics which you're violating, if only for a short period.

**Comment by sharwell** [comment] 2019-09-25 14:51
> I think there should be syntax (or an attribute) to allow a developer to indicate a property/field is going to be initialized before use by some mechanism static analysis can't see.

You can do this:

```csharp
[DisallowNull, NotNull]
public DbSet<Customer>? Customers { get; set; }
```

**Comment by ronnygunawan** [comment] 2019-09-26 09:26
You can write your own wrapper:

```cs
public class UninitializedPropertyAccessException : Exception {
    public UninitializedPropertyAccessException() : base("Lateinit property has not been initialized.") { }
}

public readonly struct Lateinit<T> {
    private readonly bool _isInitialized;
    private readonly T _value;

    public T Value {
        [DebuggerStepThrough] get => _isInitialized ? _value : throw new UninitializedPropertyAccessException();
    }

    private Lateinit(T value) {
        _isInitialized = true;
        _value = value;
    }

    [DebuggerStepThrough] public static implicit operator Lateinit<T>(T value) => new Lateinit<T>(value);
    [DebuggerStepThrough] public static implicit operator T(Lateinit<T> prop) => prop.Value;
}
```

Then use it like how you use it in kotlin:
```cs
class Foo : Page {
    public Lateinit<string?> Title { get; }

    void Page_Load() {
        Title = "Hello";
    }

    void Button_Click() {
        Debug.WriteLine(Title);
    }
}
```

**Comment by SittenSpynne** [comment] 2019-09-26 17:37
> Duplicate of #2328.
> 
> Also, one thing you can already do today is marking the files with your DTOs with
> 
> ```
> #nullable disable warnings
> ```
> 
> to avoid needing to use the `null!` workaround.

It's [documented](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) as being `#pragma warning disable nullable` but [Microsoft forgot to read their documentation](https://developercommunity.visualstudio.com/content/problem/745884/vs-for-mac-does-not-respect-pragma-warning-nullabl.html) so it's unclear what or if there is a solution.

**Comment by 333fred** [comment] 2019-09-26 19:55
@BillWagner ^

**Comment by PathogenDavid** [comment] 2019-09-27 09:29
Depending on your exact needs, you might consider writing a [diagnostic suppressor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticsuppressor?view=roslyn-dotnet) (More info: [Design](https://gist.github.com/mavasani/fcac17a9581b5c54cef8a689eeec954a), [Roslyn issue](https://github.com/dotnet/roslyn/issues/30172), [example](https://github.com/PathogenPlayground/DiagnosticSuppressorTest)) to disable nullable warnings programmatically on types affected by this issue.

**Comment by YairHalberstadt** [comment] 2020-11-05 12:03
Closing as championed at #3630

**Closed by YairHalberstadt** 2020-11-05 12:03 UTC
