### ISSUE TITLE
[Proposal] Implement interface via extension method

### ISSUE THREAD

**Issue by BenBeattieHood** [dotnet/csharplang#1520] opened 2018-05-14 03:48 UTC
We should be able to implement interfaces retrospectively via extension methods, eg:
```
// Original class
class Person {
   public string FirstName { get; set; }
   public string LastName { get; set; }
   ...
}

// And, elsewhere in the universe, an interface not implemented in the above
interface IDisplayable {
   string GetTitle();
}
```

```
// Later extension method
static class PersonExtensions {
   public string GetTitle(this Person p) => $"{p.FirstName} {p.LastName}"
}

using PersonExtensions;
extends Person : IDisplayable;
```

**Comment by ufcpp** [comment] 2018-05-14 04:02
dup of https://github.com/dotnet/csharplang/issues/514
related to https://github.com/dotnet/csharplang/issues/110, https://github.com/dotnet/csharplang/issues/164

**Comment by YairHalberstadt** [comment] 2020-10-15 12:40
Closing as duplicate of #514, and subsumed by #110, #164

**Closed by YairHalberstadt** 2020-10-15 12:40 UTC
