### ISSUE TITLE
Allow to pass a reference of a Property using 'ref' keyword

### ISSUE THREAD

**Issue by PontiacGTX** [dotnet/csharplang#3092] opened 2020-01-11 00:52 UTC
**Problem**

Currently C# developers are becoming used to writing a autoimplemened property without a second thought that they should use a backing field for storing their data, and classes could contain many declared autoimplemented properties to be later used as a field rather a property with getter and setter function,Some developers who might take some old code which contain these kind of classes would find out that when they are going to pass what should be a field as a reference to a function,they cant do it because properties cant be passed with out or ref  keyword.

some simple example of this issue could be:

```
        public class Color
        {
            public int R { get; set; }
            public int G { get; set; }
            public int B { get; set; }
            public int A { get; set; }
        }

        List<Color> Colors { get; set; } //Property field containing Color from each pixel

        void GetLighterColor(ref Color cv)
        {
            cv = new Color()
            {
                R = ((byte)Math.Sqrt(cv.R) * 255),
                G = ((byte)Math.Sqrt(cv.G) * 255),
                B = ((byte)Math.Sqrt(cv.B) * 255),
                A = ((byte)Math.Sqrt(cv.A) * 255)
             };
        }
      
        void FunctionCaller()
        {
            Bitmap photo = (Bitmap)Image.FromFile(@"..\Images\photo.jpg");
            int index = 0;
            for (int i = 0; i < photo.Width; i++)
            {
                for (int j = 0; j < photo.Height; j++)
                {
                    Colors.Add(new Color() 
                    { 
                        A= photo.GetPixel(i,j).A,
                        R= photo.GetPixel(i, j).R,
                        G= photo.GetPixel(i, j).G,
                        B= photo.GetPixel(i, j).B 
                    });
                    GetLighterColor(ref Colors[index]);//not possible to pass a reference of the Color object 
                    index++;
                }
            }
           
        }```

**Comment by tannergooding** [comment] 2020-01-11 01:01
You can have `ref` returning properties for classes (although it is a breaking change to switch existing properties to it).

For example:
```csharp
class MyClass
{
    private Guid _guid;

    public ref Guid Id => ref _guid;
}
```

**Comment by mikernet** [comment] 2020-01-16 00:54
@tannergooding Yes you can do that but that's not equivalent to a simple property. He's asking something different here is just a bad idea, which is to allow an indexer on a list to be accessed by ref.

That said, being able to ref an auto property within the scope of the type that defined the property would be awesome:

class MyClass
{
    public Guid Id { get; private set; }

    private void SetID() => Helper.SetId(ref Id); // pass backing field by ref
}

**Comment by mikernet** [comment] 2020-01-16 01:33
@PontiacGTX I think you've confused a couple related but slightly different issues here. The line:

```c#
GetLighterColor(ref Colors[index]);
```

Doesn't have a problem because of your `Colors` auto-property, rather you are trying to pass the return value of the list indexer by ref.

You can create a ref list that does something like what you are looking for:

```c#
public class RefList<T>
{
    private T[] _array = new T[10];

    public ref T this[int index] => ref _array[index];
}

public void SetString(ref string s) => s = "test";

var list = new RefList<string>();
SetString(ref list[5]);

Console.WriteLine(list[5]); // Outputs "test"
```

But the normal `List<T>` is unlikely to ever support that kind of functionality since saving the ref, manipulating the list and then doing something with the ref will lead to unintuitive results.

I kind of wish C# supported the VB way of passing properties by ref, but I can understand why it doesn't. VB copies the property value into a temp variable, passed it by ref, then writes the value back to the property. This can lead to what some consider unexpected behavior in some situations but I think the tradeoff is worth it.

What I definitely think should be allowed is the example in my prior post for auto-properties where the backing field can just be passed by ref as that works how you would expect.

**Comment by svick** [comment] 2020-01-16 15:14
@mikernet 

> the normal `List<T>` is unlikely to ever support built-in ref indexer functionality

There's a proposal to add ref indexer-like functionality to `List<T>` (though with a different syntax) at https://github.com/dotnet/corefx/issues/31598.

**Comment by mikernet** [comment] 2020-01-16 15:22
@svick I meant as a replacement for the normal indexer, which is why I mentioned that being a breaking change. I can see that being useful as an "unsafe" side API with different behavior for performance optimizing, as your link shows. I haven't seen that before though or I would have mentioned it in my previous response, so thanks for the neat find :)

**Comment by mikernet** [comment] 2020-01-16 15:38
@svick It doesn't look like that proposal is happening, but we do have this approved and merged which lets you get a span from a list which you can then ref into: https://github.com/dotnet/corefx/issues/31597

@PontiacGTX You can use the functionality added in the related PR to do this:

```c#
GetLighterColor(ref CollectionsMarshal.AsSpan(Colors)[index]);
```

**Comment by tannergooding** [comment] 2020-01-16 15:39
In the case of `List<T>`, <https://github.com/dotnet/corefx/issues/31597> was already reviewed/approved and we have `System.Runtime.InteropServices.CollectionsMarshal.AsSpan<T>(List<T>)`: https://source.dot.net/#System.Private.CoreLib/CollectionsMarshal.cs,18

**Closed** 2020-11-17 11:41 UTC
