### ISSUE TITLE
[Proposal] .= operator

### ISSUE THREAD

**Issue by kjata30** [dotnet/csharplang#1887] opened 2018-09-25 17:44 UTC
I apologize if this has been requested or discussed before, but I frequently find that when using a fluent api pattern (like LINQ), I end up assigning a variable the return value of an instance function of that ~~variable's type~~ instance. For example:

`arr = arr.OrderBy(x => x);`

Although this can be continued fluently in some cases, for example

`arr = arr.OrderBy(x => x.Foo).ThenBy(x => x.Bar);`

the assignment still feels awkward; with the `.=` operator, this would be written more succinctly as

`arr.=OrderBy(x => x.Foo).ThenBy(x => x.Bar);`

**Comment by HaloFour** [comment] 2018-09-25 17:50
IMHO that assignment is one of the most important things happening in that expression and should not be glossed over or hidden.

**Comment by kjata30** [comment] 2018-09-25 18:16
> should not be glossed over or hidden.

Can you elaborate? Does this glossing over of assignment extend to other existing operators like `+=`?

**Comment by CyrusNajmabadi** [comment] 2018-09-25 18:44
Can you clarify this:

> the assignment still feels awkward;

What feels awkard here... it feels utterly natural and familiar to me :)

**Comment by kjata30** [comment] 2018-09-25 18:54
Sure. When the variable being assigned is a parameter of a static operator like `+` I can choose to omit the variable on the right side of the equality using the equivalent assignment operator, in this case `+=`.  For static extension methods in particular, the instance is already omitted in the method call, and therefore I would like to use the same operator pattern. In this way it seems to be a "natural" syntactic extension of the language.

**Comment by willard720** [comment] 2018-09-25 19:52
@kjata30 You're only saving a few characters here.

```csharp
arr = arr.OrderBy(x => x.Foo).ThenBy(x => x.Bar);
arr .= OrderBy(x => x.Foo).ThenBy(x => x.Bar);
``` 

I mean, yeah, it's gonna depend on the name length of the variable, but really it's not that big of a deal. 
Besides, this feels very unnatural.

**Comment by DavidArno** [comment] 2018-09-25 20:19
For what it's worth, I dislike `+=` etc operators for the same reason I dislike this idea.

To explain why, I'd never want to write:
```cs
arr = arr.OrderBy(x => x.Foo).ThenBy(x => x.Bar);
```
Instead, I'd want to do:
```cs
var orderedArr = arr.OrderBy(x => x.Foo).ThenBy(x => x.Bar);
```
ie, assign the result to a new variable. I'm a simple person that can only keep a few things in my head at once when reading code. Constantly mutating variables all too quickly fill up that small space. So I don't mutate variables; I create new ones for the result of an expression.

So for me, `.=` is taking the language in the wrong direction.

Just my opinion on such things...

**Comment by TheUnlocked** [comment] 2018-09-25 20:47
This seems like it could be useful but it just _feels_ wrong to do. The dot operator should always be _immediately_  followed by a member of the object. Otherwise, our brains have been trained to think that the member exists in the current scope, which would not be true here.

That's how it is for me at least.

**Comment by MgSam** [comment] 2018-09-26 01:08
@DavidArno Has by far the best explanation of why this might be undesirable. 

Dotting into an object and assigning that to the original variable seems like a pretty rare scenario, and potentially a source of bugs. 

When languages, including C#, are moving towards readonly variables whenever possible, adding a new way to mutate variables that would likely be used more with complex types than with primitives seems like the wrong path to take.

**Comment by dsaf** [comment] 2018-09-26 08:27
This can also be solved by creating an imperative/mutating flavour of LINQ:

```csharp
arr.OrderBy(x => x.Foo).ThenBy(x => x.Bar).Apply();
```

**Comment by AdrienTorris** [comment] 2018-09-28 09:46
Similar discussion :  https://github.com/dotnet/csharplang/issues/500

**Comment by AdrienTorris** [comment] 2018-09-28 09:46
https://github.com/dotnet/csharplang/issues/500

**Comment by jnm2** [comment] 2018-09-28 15:02
There's been discussion of directly addressing constructors (`Foo.new`) or accessors (`Bar.get`) to create delegates. Directly addressing operators, if it ever existed, would look like `Foo.==` then which is close to the syntax being discussed here.

**Comment by kkm000** [comment] 2018-10-26 15:14
@dsaf, 

> This can also be solved by creating an imperative/mutating flavour of LINQ:

Let me explain my 👎 . The IEnumerable expresses a well-defined algebraic structure, namely the List monad. It's a bit dusguised, as it follows rather SQL naming, but the difference is only notational. The monadic `bind` is `SelectMany`, and  it does not have a clearly expressed monadic `return`; `new [] { x }` is the closest thing. All other operations in the point-free ("fluent") chain can be expressed in terms of just these these two functions (it would be clumsy and inefficient, but it's possible in theory). So it is built upon this exact abstract algebra, and side effects, such as this `Apply()`, goes so much against the grain of it. To be fair, stuff like `ForEach` also does, and the `foreach` statement is a much better, manifest way to transition out of the pure monadic into the imperative world, breaking its functor traits explicitly. Such a drastic change in semantics better not be expressed in a superficially similar syntax.

**Comment by aaulmer** [comment] 2020-01-16 00:02
The wonderful thing about syntactic sugar in the first place is allowing for an optional convenience if you want to use it. Other similar operators like __+=__ are definitely not taking this language in the wrong direction. In examples we use variable like __foo__ or __x__ but in practice we use camel-case meaningful variable names. So, it's nice to read code without having to see the long variable names rewritten in the same line just to do some self-assigning op.

Collections is the obvious, and probably most relevant example of where to use __.=__ operators, but I would argue that other types such as strings could also benefit. There are plenty of times when we need to convert a string, but only care about the final state and not retaining the initial state. So it makes sense to self reassign. For example, setting to uppercase, or replacing a delimiter.

I would even say, that any object that has a method which returns the same type as that object type could also benefit, especially in the scope of custom classes.

**Comment by YairHalberstadt** [comment] 2020-10-18 13:46
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/500

**Closed by YairHalberstadt** 2020-10-18 13:46 UTC
