### ISSUE TITLE
[Proposal]: Method Group syntax improvement

### ISSUE THREAD

**Issue by dylech30th** [dotnet/csharplang#4139] opened 2020-11-15 16:51 UTC
# Method Group syntax improvement

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

> I have read discussions #91 and my opinion is slightly different and seems easier to implement

C# has introduced Method Group, which is a syntax sugar that allows you to use the method name directly instead of a full-lambda-syntax. but it's only suitable for a few kinds of scenarios and we can barely have the chances to use it in daily programming. Since the Method Group can actually improve the performance and reduce the code size, I think we can do something furthermore to generalize its utilization

## Detailed Design
According to C#'s Method Group syntax, you can write:

```csharp
Action<string> printAction = Console.WriteLine;
```
instead of a normal lambda expression
```csharp
Action<string> printAction = t => Console.WriteLine(t)
```

Similarly, if we have the following function:

```csharp
static int StringToInt(string str)
{
    return int.Parse(str);
}
```

we can wrap it into a `Func<string, int>` by using:

```csharp
Func<string, int> transform = StringToInt;
```

instead of

```csharp
Func<string, int> transform = s => StringToInt(s);
```

normally, C# will generate a special function in a special class corresponds to each Lambda Expression(or call it a delegate or anonymous function whatsoever), but when you are using Method Group, the special function will not be generated, C# will pass the function pointer by which Method Group provided directly into the Delegates' constructor. For example, `Action<string> printAction = Console.WriteLine;` has the following IL code at .NET 5

```
IL_000a: ldsfld       class LambdaExprExample.Program/'<>c' LambdaExprExample.Program/'<>c'::'<>9'
IL_000f: ldftn         instance void LambdaExprExample.Program/'<>c'::'<Main>b__0_0'(string)
IL_0015: newobj    instance void class [System.Runtime]System.Action`1<string>::.ctor(object, native int)
```

where `'<>c'` is the generated special class and `'<Main>b__0_0'` is the generated special function, C# will take the function pointer of `'<Main>b__0_0'` and pass it into `Action<string>::ctor`, if we dig a step further we will find that `'<Main>b__0_0'` basically do nothing else but call another function`System.Console::WriteLine(string)`:

```
.method assembly hidebysig instance void
      '<Main>b__0_0'(
        string s
      ) cil managed
    {
      .maxstack 8

      // [9 42 - 9 62]
      IL_0000: ldarg.1      // s
      IL_0001: call         void [System.Console]System.Console::WriteLine(string) // the only thing this function do is call another function
      IL_0006: nop
      IL_0007: ret

    } // end of method '<>c'::'<Main>b__0_0'
```
when we use Method Group, the special function will not be generated, instead, it will directly pass the function pointer of `System.Console::WriteLine(string)` to `Action<string>::ctor`:

```
IL_002e: ldftn        void [System.Console]System.Console::WriteLine(string)
IL_0034: newobj    instance void class [System.Runtime]System.Action`1<string>::.ctor(object, native int)
```

so that we can reduce the object allocation and write less than normal. Now, let's consider some other special cases:
```csharp
// Assume that StringToInt is an instance method of PString which return an int
var pString = new PString("hello world");
Func<PString, int> toIntFunc = ps => ps.StringToInt();
// just create a new FileInfo from string
Func<string, FileInfo> createFileInfo = s => new FileInfo(s);
```

and let's check their generated special functions' IL code respectively:

for `toIntFunc`:
```
.method assembly hidebysig instance int32
      '<Main>b__0_0'(
        class LambdaExprExample.PString ps
      ) cil managed
    {
      .maxstack 8

      // [24 50 - 24 66]
      IL_0000: ldarg.1      // ps
      IL_0001: callvirt     instance int32 LambdaExprExample.PString::StringToInt()
      IL_0006: ret

    } // end of method '<>c'::'<Main>b__0_0'
```

for `createFileInfo`:

```
.method assembly hidebysig instance class [System.IO.FileSystem]System.IO.FileInfo
      '<Main>b__0_0'(
        string s
      ) cil managed
    {
      .maxstack 8

      // [25 58 - 25 73]
      IL_0000: ldarg.1      // s
      IL_0001: newobj       instance void [System.IO.FileSystem]System.IO.FileInfo::.ctor(string)
      IL_0006: ret

    } // end of method '<>c'::'<Main>b__0_0'
```

in these two cases, the generated functions are just called another function and do nothing else, so I think we can just reduce them to Method Group to reduce object allocation and make it easier to write:
```csharp
Func<PString, int> toIntFunc = PString.StringToInt;
Func<string, FileInfo> createFileInfo = FileInfo;
```

and there's also a special case is the array allocation, if we have following code:
```csharp
Func<int, string[]> createStringArray = i => new string[i];
```
it will also generate a function like:
```
.method assembly hidebysig instance string[]
      '<Main>b__0_0'(
        int32 i
      ) cil managed
    {
      .maxstack 8

      // [25 58 - 25 71]
      IL_0000: ldarg.1      // i
      IL_0001: newarr       [System.Runtime]System.String
      IL_0006: ret

    } // end of method '<>c'::'<Main>b__0_0'
```
it's a bit different from the examples above but I think they're rather similar, you can consider `newarr` instruction is yet another kind of function invocation, what all of them have in common is that the generated function is very simple, they just call another external function, no variable capture, no internal complex logic. So I think all of them are suitable for Method Group, as for the `createStringArray`, I think it can be written in:
```csharp
Func<int, string[]> createStringArray = string[];
```

## Motivation
[motivation]: #motivation

This proposal is highly inspired by Java's [method reference](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html), although the underlying implementation is completely different but there's indeed something in common like what I've mentioned above, by using more Method Group we can reduce the package size and the object allocations which may generally improve the performance of the program, on the other hand, it will also make programmers feel better when programming because `=>` indeed requires more steps than a single `.` or just a pure name

**Comment by HaloFour** [comment] 2020-11-15 17:03
The C# compiler already caches a single delegate instance for any lambdas that don't require capturing state from the current method so I don't see where the performance benefit would come from.

**Comment by HaloFour** [comment] 2020-11-15 17:04
Also, duplicate of https://github.com/dotnet/csharplang/discussions/84

**Comment by svick** [comment] 2020-11-15 17:23
Closing as a duplicate of https://github.com/dotnet/csharplang/discussions/84. The syntax proposed here is different, but I think it's better to discuss variations of the same idea in a single place.

**Closed by svick** 2020-11-15 17:23 UTC

**Comment by rootflood** [comment] 2020-11-15 17:56
hi, i think the code optimizing by JIT

https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcDMACR2DC2A3utmdunACzZRIAUAlOiWubkggDxxIAMAPmwAHAE4BLAHbBeCbAF5sAdQBKAblLkxUmZ3oAiTvsYa0AX01lKNKAiYtLHbr0EiJ02QuzAFQ1fWATR20PPUMEY1MLNnJrZRV6AGVgdwBzbAgUxnkBXgBOekzRIJircyA==
