### ISSUE TITLE
proposal - implicit lambdas using "."

### ISSUE THREAD

**Issue by darrenoakey** [dotnet/csharplang#3755] opened 2020-07-30 04:50 UTC
For me by far the most common use of lambdas is to extract a single variable - eg:

```c#
    var greatItems = allItems.Where( item => item.IsGreat)      
    var names = theObjects.Select( anObject => anObject.Name )
```

Now, I'd argue that we can come up with a much better syntax,  and it's justified by just how common this is - in fact, I think in every case it ends up with cleaner, more "obvious" code - which is to basically just implicitly declare the lambda x=>x.blah by just saying .blah

```c#
     var greatItems = allItems.Where( .IsGreat );
     var names = theObjects.Select( .Name );
```

I believe the syntax is far more intuitive than lambda - is pretty easy for anyone to understand regardless of whether you are familiar with lambdas or not - reads more cleanly - and has no conflicts with any existing syntax.

**Comment by YairHalberstadt** [comment] 2020-07-30 05:09
Scala has this using the `_.IsGreat` syntax.
I tend to find the rules about when you can and can't use it or complex enough that it ends up being more of a time waster than a time saver, and it tends to make files look very inconsistent.

**Comment by darrenoakey** [comment] 2020-07-30 06:38
yeah - that's horrible - because it looks like there's this weird context object "_" floating around that you need to understand.  Also it's _not_ a completely distinct syntax, and not obvious where _ is available.

whereas    .blah is literally just a shorthand for x => x.blah (assuming some x that can't conflict with anything)... so it's not a special thing... and doesn't have special rules - it's purely just alternate syntax for writing the same code.   It could actually be done with a pre-processor/lexical analyser step without going anywhere near the compiler.

(ok, you could argue that _. is special, and you could similarly rewrite it, which is true.... but... it's just truly awful)

**Comment by yaakov-h** [comment] 2020-07-30 06:45
There's a lot of existing discussion around this on #91.

FWIW, Swift now has `\.IsGreat` for keypath literals, which are quite similar in effect.

**Comment by 333fred** [comment] 2020-07-30 07:21
I'm going to close this as a duplicate of #91 with a slightly different syntax.

**Closed by 333fred** 2020-07-30 07:21 UTC
