### ISSUE TITLE
C# Error "Use of unassigned local variable"

### ISSUE THREAD

**Issue by diryboy** [dotnet/csharplang#3660] opened 2020-07-09 04:31 UTC
**Version Used**: 
VS2019 16.6.3

**Steps to Reproduce**:

```C#
    class Program
    {
        static Dictionary<string, string> D;

        static void Main(string[] args)
        {
            if (D?.TryGetValue("k", out var value) == true)
            {
                var v = value;
            }
        }
    }
```

**Expected Behavior**:

No error.

**Actual Behavior**:

Error	 CS0165	Use of unassigned local variable 'value'

**Comment by CyrusNajmabadi** [comment] 2020-07-09 08:41
Transfered to C# lang, as this is a language change request.  Virtually certain it's a dupe of something that already exists :)

**Comment by yaakov-h** [comment] 2020-07-09 12:06
Duplicate of #3365.

**Comment by 333fred** [comment] 2020-07-09 15:09
Closing as a duplicate.

**Closed by 333fred** 2020-07-09 15:09 UTC
