### ISSUE TITLE
Syntax sugar for right side assignment and extending property initializer blocks

### ISSUE THREAD

**Issue by Makeloft** [dotnet/csharplang#1228] opened 2017-12-29 03:25 UTC
Related with proposals:
https://github.com/dotnet/csharplang/issues/377
https://github.com/dotnet/csharplang/issues/402
https://github.com/dotnet/csharplang/issues/595
https://github.com/dotnet/csharplang/issues/803
https://github.com/dotnet/csharplang/issues/973
https://github.com/dotnet/csharplang/issues/1224

Consider following valid code
```c#
new AnyModel { AnyProp0 = "abc" }.AttachModel();
new AnyModel() { AnyProp0 = "abc" }.AttachModel();
```
But nice to have too
```c#
GetModel() { AnyProp0 = "abc" }.AttachModel();
/* possible even following variation */
GetModel { AnyProp0 = "abc" }.AttachModel();
```
Moreover nice to have right side assignment into initializer blocks
```c#
/* field, property, local variable */
string activeValue = default(string);
...
GetModel() { AnyProp0 to activeValue }.AttachModel();

GetModel() { AnyProp0 to var newLocalValue }.AttachModel();
```
By the same logic valid expressions
```c#
GetModel() to var m { AnyProp0 = GetValueFor(m) }.AttachModel();

GetModel() { AnyProp0 to var newLocalValue } to var m.AttachModel();

GetModel() { AnyProp0 to var newLocalValue } to AnyModel m.AttachModel();
```
Also helps to avoid crazy braces
```c#
((AnyModel) ((Button) sender).DataContext).UpdateModel();
sender to Button _.DataContext to AnyModel _.UpdateModel();
```

**Summary**
What really nice to have at C#
- right side assignment operator `to` which has logic similar to extension methods 
```c#
public static T To<T>(this T o, out T result) => result = o;

public static T To<T, TResult>(this T o, Func<T, TResult> decomposer, out TResult result)
{
        result = o == null ? default(TResult) : decomposer(o);
        return o;
}
```
- extended property initializer pattern `{ }` with clear meaning

Valid variations of syntax
```c#
public string AnyField = "aaa";
public string AnyProperty { get; set; } = "bbb";

var anyLocalVariable = "ccc";

GetModel() to m /* define new variable 'm' [optional] */
{
    AnyProp0 = "abc", /* set value "abc" to the property */
    AnyProp1 to var p1, /* define new variable 'p1' with value from 'AnyProp1'  */
    AnyProp2 = "xyz" to var p2, /* define new variable 'p2' with value "xyz" and  set the value to the property AnyProp2 */
    AnyProp3 to AnyField, /* update 'AnyField' by value from 'AnyProp3' */
    AnyProp4 to AnyProperty, /* update 'AnyProperty' by value from 'AnyProp5' */
    AnyProp5 to anyLocalVariable, /* update 'anyLocalVariable' by value from 'AnyProp5' */
}.RedrawModel();

new AnyModel to m /* define new variable 'm' [optional] */
{
    AnyProp0 = "abc", /* set value "abc" to the property */
    AnyProp1 to var p1, /* define new variable 'p1' with DEFAULT value from 'AnyProp1'  */
    AnyProp2 = "xyz" to var p2, /* define new variable 'p2' with value "xyz" and  set the value to the property AnyProp2 */
}.AttachModel();
```
According sample with `swith`
```c#
switch(GetShape() to var s { Color to var color, Texture to var texture })
{
	case Circle c { Radius to var r, Color = color = "Red" }: /* override Color value ! */
	    WriteLine($"Circle with Radius={r}, Color={color}, Texture={texture}"); 
	    break;
	case Rectangle r { Width to var w, Heigth to var h } where w > h: /* additional validation */
	    WriteLine($"Rectangle with Width={w}, Heigth={h}, Color={color}, Texture={texture}"); 
	    break;
	case Heart h:
	    WriteLine($"Heart with Color={color}, Texture={texture}");
	    break;
	default:
	    WriteLine($"Unrecognized or invalid shape {s}");
	    break;
}
```
**Tuples**
We may use following syntax
```c#
GetTuple() { to var x0, to var x1, to AnyModel m }
```

**Problems and solution**
Which problems may occurs

Consider code
```c#
//new AnyModel() to var m
GetModel() to var m
{ 
    AnyProp0 = "abc",
    AnyProp1 to anyVariable,
    AnyProp2 to AnyProperty,
    AnyProp3 to var newLocalVariable
};
```
and the coincident possible unwrapping
```c#
AnyType newLocalVariable;
newLocalVariable = default(AnyType); /* see below: to avoid [CS0165] Use of unassigned local variable */

//var tmp = new AnyModel();
var tmp = GetModel();
var m = tmp;
tmp.AnyProp0 = "abc";
anyVariable = tmp.AnyProp1;
AnyProperty = tmp.AnyProp2;
newLocalVariable = tmp.AnyProp3;
```

Obviously that we can get `NullReferenceException` for nullable types. How can we avoid this?

Consider the following simple sample and put attention to `Unwrap` method
```c#
public class Point
{
    public int? X { get; set; }
    public int? Y { get; set; }

    public static Point Unwrap(out int? x, out int? y)
    {
        x = p.X;
        y = p.Y;
        return this;
    } 
}

switch(GetPoint().To(var p)?.Unwrap(out var x, out var y))
{
	case Point _:
	    WriteLine($"X={x}; Y={y}; Name={p.Name}"); 
	    break;
	case null:
	    WriteLine($"It is null"); 
	    break;
}
```
It is safe from NRE but compiler says that 
```
[CS0165] Use of unassigned local variable 'x'
[CS0165] Use of unassigned local variable 'y'
```
Try to understand why. Expression `out var x` equals to simple variable declaration like `int? x;` without initialization. Compiler can not be sure that `x` and `y` will be initialized every time and show compile error to avoid possible reading of unassigned variable.

But now we may rewrite `Unwrap` method like extension, then compile code and fully avoid NRE.
```c#
public class Point
{
    public int? X { get; set; }
    public int? Y { get; set; }
}

public static class PointExtensions
{
    public static Point Unwrap(this Point p, out int? x, out int? y)
    {
        x = default(int?);
        y = default(int?);
        if (p == null) return null;
        x = p.X;
        y = p.Y;
        return p;
    } 
}

switch(GetPoint().To(var p).Unwrap(out var x, out var y))
{
	case Point _:
	    WriteLine($"X={x}; Y={y}; Name={p.Name}"); 
	    break;
	case null:
	    WriteLine($"It is null"); 
	    break;
}
```
It means that the complete unwrapping looks like
```c#
AnyType newLocalVariable;
newLocalVariable = default(AnyType);

//var tmp = new AnyModel();
var tmp = GetModel();
var m = tmp;
if (tmp != null)
{
    tmp.AnyProp0 = "abc";
    anyVariable = tmp.AnyProp1;
    AnyProperty = tmp.AnyProp2;
    newLocalVariable = tmp.AnyProp3;
}
```
There are not another unsolved problems.

**Comment by jnm2** [comment] 2017-12-29 03:28
Dude.

**Comment by yaakov-h** [comment] 2017-12-29 03:36
Dude.

You have addressed none the concerns raised in any of the issues along your trail of nonsense.

(For anyone else who wants to see what's changed here, [try this](https://www.diffchecker.com/UKdQ6fzs).)

**Comment by bondsbw** [comment] 2017-12-29 03:37
@yaakov-h Thanks for the diff.

**Comment by Makeloft** [comment] 2017-12-29 03:54
Guys, I understand your feelings, but if you dislike this features, please, try to explain your opinion with objective arguments.

For example, I dislike right side assignment but initializers looks good or otherwise. If something is not intuitive for you describe your expectations...

**Comment by jnm2** [comment] 2017-12-29 04:04
My feeling is that you've disregarded everyone who has explained their opinions with objective arguments and are repeating yourself. For example, `to`.

**Comment by yaakov-h** [comment] 2017-12-29 04:17
> Guys, I understand your feelings

Clearly you don't.

> but if you dislike this features, please, try to explain your opinion with objective arguments.

1. This is not how this works. Proposals do not have a default state of "good", or even of "neutral". All proposals are well into the negative until it can be proven that they have not only enough value to bring them up into neutral, but all the way up into "yes this is good, it is worth building and maintaining this new addition to the language until the end of time". This is the "100 points" mantra that has been often repeated around here.
2. We already have explained ourselves. Numerous times. Individually.

Most of your proposal pieces make little to no sense.

Factory initializers have already been discussed at #803. This is not a bad idea by itself.

Your "right-side assignment" is a reverse form of deconstruction. C# already has deconstruction. Use it. Or, don't, and split your code across multiple lines. More code isn't necessarily bad.

You have not managed to convince **anyone** here of the value of a new `to` operator - and that's a rare thing. Most proposals have at least two or three people who like the idea.

You have proposed the following:

```cs
GetModel() { AnyProp0 to activeValue }.AttachModel();
```

This can be expressed today as:

```cs
var temp = GetModel();
activeValue = temp.AnyProp0;
temp.AttachModel();
```

You have not managed to explain why this is insufficient and requires entirely new syntax, which appears to piggyback off factory initializers.

You're also continuously pushing your way through to:

```cs
sender to Button _.DataContext to AnyModel _.UpdateModel();
```

This syntax makes little sense and is almost completely unreadable to anyone except yourself.

You have already been provided with about 4 different ways to achieve this today, ranging from regular casts to your own extension methods to `dynamic`. You have failed to demonstrate a need for this new - and warped - syntax.

Your `switch` examples make no sense. You have provided the following example as code that you are trying to "solve":

```cs
switch(GetPoint().To(var p)?.Unwrap(out var x, out var y))
{
	case Point _:
	    WriteLine($"X={x}; Y={y}; Name={p.Name}"); 
	    break;
	case null:
	    WriteLine($"It is null"); 
	    break;
}
```

Yet you clearly know that this is a point, but you're using type matching, which is designed for cases when you do not know what type the value is. This is the sort of case where you should just use an `if` statement (with your funky extension methods), or pattern matching (without the extension methods).

Aside from factory initializers, none of this appears to have any value whatsoever, and is comfortably sitting in the negatives.

Please please please refrain from any more language proposals until you can clean up your syntax, your use cases, and your personal etiquette.

**Comment by Makeloft** [comment] 2017-12-29 04:55
Ok, thanks for your opinions.
This proposal is the complete result of previous.

Yes, I repeat self, but creation or inventing something new is iterative process. Many key ideas was born into discussions.

Sounds good that you like factory initializers. Try to explain why right side assignment is useful.
At first it is just a syntax sugar, sometimes very helpful to have
```c#
public string ActiveModelName;
...
GetModel() { Name to ActiveModelName }.AttachModel();
```
But you may retort that this situation can solved by extension method
```c#
public string ActiveModelName;
...
GetModel().To(o => o.Name, out ActiveModelName).AttachModel();
```
Yes, it is true. But possible another situation with class auto properties [without implicit backing fields]
```c#
public string ActiveModelName { get; set; }
...
GetModel() { Name to ActiveModelName }.AttachModel();
```
We can solve this by the elegant way with `to` operator or by creating another type of not very beautiful extension method
```c#
GetModel().To(o => o.Name, v => ActiveModelName = v).AttachModel();
```

Actually many language features and operators may emulated with extensions methods, but we have them at language level. If right side assignment is not intuitive you may use classical operator `=` but for me the operator `to` looks very useful too.

**Comment by Makeloft** [comment] 2017-12-29 05:09
Yes, we already have deconstruction pattern for tuples.
But for classes may be used a very flexible and convient approach with factory initializer blocks and right side assignment.

**Comment by Makeloft** [comment] 2017-12-29 05:30
Moreover tuples deconstruction may be combined with the `to` operator.
```c#
GetModel() { AnyTupleProperty to (var x1, int x2, var _) };
GetModel() { AnyTupleProperty to var(x1, x2, _) };
GetTuple() to (var x1, int x2, var _);
GetTuple() to var(x1, x2, _);

switch(GetAnyTuple() to var(x1, x2, _))
{
    case Tuple _ where x1 > 10 && x2 > 100: WriteLine("Case0"); break;
    case Tuple _ where x1 >  x2: WriteLine("Case1"); break;
    case null: WriteLine("Case2"); break;
    default: WriteLine("Case3"); break;
}
```

**Comment by Makeloft** [comment] 2017-12-29 05:42
Even for other types we may use custom Deconstruct method implementation with specific logic or simple unwrapping for common cases
```c#
//switch(GetPerson() to { FirstName to var firstName, LastName to var lastName })
switch(GetPerson() to var(firstName, lastName,  _))
{
    case Person _ where firstName.StartWith("A"): WriteLine("Case0"); break;
    case Person _ where lastName.StartWith("B"): WriteLine("Case1"); break;
    case null: WriteLine("Case2"); break;
    default: WriteLine("Case3"); break;
}
```

**Comment by orthoxerox** [comment] 2017-12-29 07:10
@Makeloft 

The greatest problem with `to` is that it doesn't really bring any huge benefits to the language. We already have regular assignment for that.

Let's take a look at some of the "duplicate" features in C# right now:

### Lambdas

They are a duplicate of anonymous delegates, but they allow you to infer types. They were designed to practically replace anonymous delegates, being better in every way.

### Expression-bodied methods

EBMs look like a feature very similar to `to`, simply providing a more terse syntax with no new functionality. But they really increase the readability of read-only properties and short helper methods:

```c#
public string X => Y().Z;
//vs
public string X
{
    get {
        return Y().Z;
    }
}
```

What does `to` do? 

```c#
GetModel() { AnyProp0 to var newLocalValue }.AttachModel();
//vs
var model = GetModel();
var newLocalValue = model.AnyProp0;
model.AttachModel();
```

Yes, it saves a few lines. I won't say it looks cryptic, because that's a subjective response (and I see that pattern matching looks cryptic to you). However, I will say that it doesn't look that useful. It's only useful when the expression you're applying the "initializer" to will be discarded after this statement. If you want to keep the value `GetModel()` returns, then regular assignment is much easier to read.

**Comment by gafter** [comment] 2017-12-29 09:24
The purpose of an object initializer is to create a new object, with all of its pieces; each element of the initializer initializes one part. This proposal muddies that construct by mixing up the writing and the reading of the object. That sort of mixing up would be better suited to a new construct, perhaps something akin to VB's [_with statement_](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/with-end-with-statement).

**Comment by Makeloft** [comment] 2017-12-29 10:26
@orthoxerox thank for opinion.

@gafter yes, possible using `with` keyword. But actually for me looks more prefer and clear variation without additional keywords because we have very closely intuition with another kinds of initializers.

Moreover we can extend array initializers too.

```c#
var array = new object[] {  "abc", 123, "xyz" to var xyz, 321 to AnyVariable };
```

**Comment by DavidArno** [comment] 2017-12-29 11:08
@Makeloft,
> Guys, I understand your feelings, but if you dislike this features, please, try to explain your opinion with objective arguments.

**Objective argument one: this proposal is muddled and confusing.**
It is helpful if folk post single, focused suggestions here. Your proposal covers multiple things:
1. Using initializer-style syntax to bulk-modify the properties of an exiting object,
2. Using `to` to assign to new and existing variables within expressions,
3. Using that `to` syntax within the same `{}`'s as the bulk-modify, to simultaneously read and write properties of an object.
4. Using those blocks and `to` to create a new way of using `switch`.  

Because you muddle multiple ideas into one proposal, it becomes harder to comment on any particular aspect of your proposal. You would therefore be better off splitting the proposal into at least two parts (extended initializer syntax and the `to` feature).

**Objective argument two: initializer-style syntax is closely related to "with expressions" (#162).**
As such, this part of your proposal is a dupe of #162 and you should really address your suggestions for your expanded initialiser syntax (**but not the `to` operator**) there. However, be aware that in my view at least, your proposal is inferior to what has already been proposed as yours involves mutating existing objects, rather than creating copies.

**Objective argument three: `to` operator is a duplicate of numerous existing proposals (#973, #595, #402, #377)**
Again, you should choose one of these existing issues to discuss why you think `to` a better choice of syntax, without discussing the unrelated expanded initialiser syntax.

**Objective argument four: the only reason any of this exists is because you are unable to be objective over `x is var y`
And here's the real rub: there is truly no point to us offering you objective arguments against your ideas as your ideas are being generated in response to a completely irrational reaction to a language decision.  

But feel free to prove me wrong by becoming more rational...

**Comment by Makeloft** [comment] 2017-12-29 12:07
@DavidArno thank for your opinion.

Actually I have opposite question. There are wide range related proposals 
#162
#377
#402
#595
#803
#973
#1224
which may be resolved by the universal generic way suggested by the current.

Yes, it is new and unfamiliar syntax. But actually more simple to have one common solution for all cases instead separated specific solution for every one. Guys, why do you want second scenario?

**Comment by DavidArno** [comment] 2017-12-29 12:33
@Makeloft,

Ah, I see what you mean. So if we add another random piece of code to this proposal:
```cs
GetModel() { AnyProp0 to var ``new local value`` }.AttachModel();
```
Then we can drag #1213 (allow spaces into identifiers) into this proposal too as it's now related by your reasoning.

 😆🤣🙄

**Comment by Makeloft** [comment] 2017-12-29 13:33
@gafter I rethink your proposal about `with` keyword. Possible it is may sense like implicit null check.
But seems that syntax `new AnyModel() with { AnyProp = 123 }.Register();` should be valid too [but `with` for this context is redundant]. Also `with` keyword may be redundant with C# 8 non nullable reference types.

**Comment by Makeloft** [comment] 2017-12-29 13:35
For example if we want to have NRE we may use
`GetModel() { AnyProp = 123 }.Register()`
But if we want to avoid NRE
`GetModel() with { AnyProp = 123 }.Register()`

**Comment by DavidArno** [comment] 2017-12-29 14:12
@Makeloft,

> But seems that syntax `new AnyModel() with { AnyProp = 123 }.Register();` should be valid too [but with for this context is redundant].

That is correct: it would be valid; not it would be redundant. What that piece of code would be doing is creating an `AnyModel` instance, that creating a second `AnyModel` instance, copying all properties except `AnyProp` from the first instance to the second and then setting `AnyProp` to `123` for that second instance. Finally, `Register()` is called on that second instance.

Creating two instances like this would indeed by inefficient.
   
> Also with keyword may be redundant with C# 8 non nullable reference types.

Not so. The purpose of `with` is to create a copy of an existing object/struct and to apply changes to some of the properties of that copy. `NRE` is completely orthogonal to this.

**Comment by Makeloft** [comment] 2017-12-29 14:19
@DavidArno thanks!
I don't want to create any copies. The keyword `with` may sense for me like the optional non null check. Otherwise preferred to avoid them.

**Comment by gafter** [comment] 2017-12-30 17:52
When I wrote

> That sort of mixing up would be better suited to a new construct, perhaps something akin to VB's [_with statement_](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/with-end-with-statement).

I was referring to VB's [_with statement_](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/with-end-with-statement), not the proposed `with` expression for C#.

**Comment by gafter** [comment] 2017-12-31 20:11
The proposal to extend object initializers to handle objects other than those created with an object creation expression is tracked at https://github.com/dotnet/csharplang/issues/803 and discussion of that proposal should go there. So closing as a dup with respect to that part of this issue.

We do not have any appetite for extending the object initializer syntax to permit extracting values from the object under construction. So closing as declined with respect to that part of this issue.

If you are still interested in an assignment expression in which the sides of the assignment are reversed, please open a separate issue for that. However, I should warn you that it seems unlikely to me such a proposal would gain much traction.

**Closed by gafter** 2017-12-31 20:11 UTC
Labels: Discussion
