### ISSUE TITLE
Shortcut for  "object == null"

### ISSUE THREAD

**Issue by reschjo** [dotnet/csharplang#2525] opened 2019-05-14 13:16 UTC
I very oftend use "if(Object == null) or if(Object != null)" in my sourcecode.
It would be great to have a shortcut like "if(?Object)" for that.
The return value would be "true" if the Object exists (not null) or "false" if the object doesn't exist (is null)

**Comment by tpetrina** [comment] 2019-05-14 13:23
For the former you can use `if (o is null)`. For the latter use `if (o is object)`

**Comment by HaloFour** [comment] 2019-05-14 13:32
Or `if (o is {})` which will work for checking that `o` is not null in C# 8.0 when that is released

**Comment by DavidArno** [comment] 2019-05-14 13:38
And of course, when we get nullable reference types with C# 8, the need to scatter `if (o is null)` throughout the code should largely go away.

**Comment by VanKrock** [comment] 2019-05-15 06:45
You can to use ?? ?: ?.

**Comment by yaakov-h** [comment] 2019-05-15 07:39
Duplicate of #545, which was closed.

**Closed** 2019-05-15 08:42 UTC

**Comment by reschjo** [comment] 2019-05-15 08:44
@yaakov-h  you are right. I closed the duplicated issue.

ToAll: Thanks for your answers !
