### ISSUE TITLE
Proposal: abbreviate generic extension methods with generic return types 

### ISSUE THREAD

**Issue by Ultrahead** [dotnet/csharplang#1435] opened 2018-04-04 18:47 UTC
Say that you have declared and extension method like this:

`public static TOutput MyCheck<TSelf, TOutput, TParameter1, ...>(this T self, TParameter1 arg1, ...) { ... }`

To call this method you end up using somewhere in your code:

`this.MyCheck<MySelfClass, MyOutputClass, MyParameter1Class, ...>(...)`

The idea here is that the compiler allows this call:

`this.MyCheck<MyOutputClass>(myTParameter1arg, ...);`

since it could infer TSelf, adn TParameter1 ... from the call it-self.

**Comment by svick** [comment] 2018-04-04 18:59
How does the compiler figure out which parameter are you specifying?

This is also closely related to https://github.com/dotnet/csharplang/issues/1349.

**Comment by Ultrahead** [comment] 2018-04-04 19:11
From "this"" it would infer T self, and from the parameters you input in the call, TParameter1, TParameter2, etc. (as it does now in many cases).

The only one it could not "safely" infer is TOutput (unless -and I'm thinking loud here, you assign it to a field declared for a non-abstract type).

**Comment by theunrepentantgeek** [comment] 2018-04-04 19:35
I *think* that what you're suggesting is the ability to omit type parameters from the call if/when they can be worked out from the parameters, allowing the developer to supply only the type parameters that can't be worked out. 

(If I'm wrong, ignore this comment. 😄 )

I can see two issues with this.

Firstly, when the compiler *can* work out most of the parameters but you want/need to control one of them more closely. For example, the compiler might be able to easily tell that your fifth parameter is of type `Person` but for this method call, you need it to be treated as `IRole` instead.

Secondly, you run up against issues as the compiler is developed further. It's not hard to see a situation where the C# 8 compiler might need help for two of ten parameters, but the C# 9 compiler is significantly smarter and only needs help for one. Now you've got a case where a smarter compiler breaks existing code. 😢 

I guess you could work around these by following the example of named parameters for methods and attributes, explicitly naming the type parameter you're supplying:

```
MyCheck<TOutput: MyOutputClass>(myTParameter1arg, ...);
```

I'm not a fan, though. In my experience too many type parameters (*) is often a *code smell* associated with code that needs some TLC.

(*) I don't use a hard limit of 3 or 5 or ..., but if the code has trouble sitting on a single line, or if it becomes troublesome to read, it's a candidate for attention.

**Comment by Ultrahead** [comment] 2018-04-04 19:47
I know what you mean. Those signatures have been used as an example. And this issue is not for common scenarios when declaring a type, but sometimes, when extending a method.

You could take a simplified example:

`this.MyCheck<MyOutputClass>(myOnlyParameter);`

Right now, you are force to use:

`this.MyCheck<MySelfClass, MyOutputClass, MyParameter1Class>(myOnlyParameter);`

**Comment by DarthVella** [comment] 2018-04-04 23:25
>Secondly, you run up against issues as the compiler is developed further. It's not hard to see a situation where the C# 8 compiler might need help for two of ten parameters, but the C# 9 compiler is significantly smarter and only needs help for one. Now you've got a case where a smarter compiler breaks existing code. 

This could be averted by requiring explicit specification for the parameter(s) being specified, if any are being omitted/inferred.
```csharp
this.MyCheck<TOutput: MyOutputClass>(myOnlyParameter);
```

**Comment by Ultrahead** [comment] 2018-10-31 19:06
@DarthVella I like your idea. Thoughts?

**Comment by MadsTorgersen** [comment] 2018-10-31 22:57
I remember discussing this all the way back to C# 3.0! 😃 

If we were to support partial type inference, it wouldn't be just for extension methods, as proposed, but for all invocations (and elsewhere we would add type argument inference in the future). 

It would need to be in a way that still uniquely identified which type arguments were being explicitly passed. I like @DarthVella's proposal of "named typed arguments". It shares with named arguments (when they were introduced) the problem that it changes the contract around how type parameter names are used. That's probably a smaller issue.

**Comment by Ultrahead** [comment] 2018-11-01 00:18
> If we were to support partial type inference, it wouldn't be just for extension methods, as proposed, but for all invocations (and elsewhere we would add type argument inference in the future).

+ 1

**Comment by Ultrahead** [comment] 2020-04-26 01:35
Any news on this proposal?

**Comment by YairHalberstadt** [comment] 2020-10-14 09:22
Closing as a duplicate of #1349 which is championed

**Closed by YairHalberstadt** 2020-10-14 09:22 UTC
