### ISSUE TITLE
Proposal: 'this' as return type

### ISSUE THREAD

**Issue by StevenLiekens** [dotnet/csharplang#2559] opened 2019-05-24 19:42 UTC
This is my first proposal so please go easy on me. :-)

It would be cool if we could use `this` as the return type for instance methods, to indicate that the method returns its containing object.

Use cases include builder objects and other fluent APIs.

```csharp
public class PizzaBuilder {
    private string _dough;
    private string _sauce;
    private string _topping;

    public this UseDough(string dough) => _dough = dough;

    public this UseSauce(string sauce) => _sauce = sauce;

    public this UseTopping(string topping) => _topping = topping;
    
    public Pizza Build() {
        return new Pizza(_dough, _sauce, _topping);
    }
}
```

It would be synonymous for the following:

```csharp
public class PizzaBuilder {
    private string _dough;
    private string _sauce;
    private string _topping;

    public PizzaBuilder UseDough(string dough) {
        _dough = dough; 
        return this;
    }
    public PizzaBuilder UseSauce(string sauce) {
        _sauce = sauce; 
        return this;
    }
    public PizzaBuilder UseTopping(string topping) {
        _topping = topping;
        return this;
    }

    public Pizza Build() {
        return new Pizza(_dough, _sauce, _topping);
    }
}
```

**Comment by orthoxerox** [comment] 2019-05-24 20:41
Thank you for your interest in C# design!

I think there multiple issues requesting this feature already, so if you could repost your approach to the one with the most :+1:s it would be great.

**Comment by jnm2** [comment] 2019-05-24 23:47
Duplicate of https://github.com/dotnet/csharplang/issues/252 and https://github.com/dotnet/csharplang/issues/902.

**Closed** 2019-05-25 01:11 UTC
