### ISSUE TITLE
Shorthand to update multiple fields of an object at once (similar to simple object creation)

### ISSUE THREAD

**Issue by audigex** [dotnet/csharplang#3364] opened 2020-04-17 01:49 UTC
I think everyone is familiar with the nice simple "create a new instance and populate some fields" syntax, it's nice, it's clean, it keeps related code together, and I've never found anyone who doesn't love it... for example:

```
foo = new Bar()
{
    BarID = id,
    Value = 123,
    Title = "Something"
};
```

That's great when we're creating foo while setting the values.

But now let's assume that foo already exists, so we can't create it using the above syntax, but we still want to update some fields. It feels like this should be just as easy to do and with similar syntax, but the following isn't possible:

```
foo {
    BarID = id,
    Value = 123,
    Title = "Something"
};
```

Instead we have to resort to the old, ugly version:

```
foo.BarID = id;
foo.Value = 123;
foo.Title = "Something";
```

Hopefully my request is self explanatory: allow us to use that nice clean syntax when updating fields on an existing instance of an object, not just when creating the object.

**Comment by hez2010** [comment] 2020-04-17 01:59
With records you can approach this with below code:
```csharp
foo = foo with {
    BarID = id,
    Value = 123,
    Title = "Something"
};
```

**Comment by jnm2** [comment] 2020-04-17 01:59
Work is underway for a feature that uses the syntax `foo with { BarId = id }` to do a non-destructive update (returning a new value). See https://github.com/dotnet/csharplang/issues/162.

**Comment by YairHalberstadt** [comment] 2020-11-24 11:08
Closing as duplicate of #803 and #1534

**Closed by YairHalberstadt** 2020-11-24 11:08 UTC
