### ISSUE TITLE
Discussion: default constructors for structs

### ISSUE THREAD

**Issue by louthy** [dotnet/csharplang#412] opened 2017-04-05 17:24 UTC
This is a real pain point when trying to use `struct` as non-nullable wrappers for more complex types.  [In my functional library](https://github.com/louthy/language-ext/tree/master/LanguageExt.Core/DataTypes) I have a ton of immutable collection types (Lists, Maps, Sets, etc.).  They are all structs that contain a single reference to a `class` with the full implementation.  It means I can have:
```c#
    Map<string, int> x = default(Map<string, int>); 
```
But that then requires a `null` check every time the type is used:
```c#
    public struct Map<A, B>
    {
        readonly MapInternal<A, B> value;

        // This property is used throughout the type to get a valid MapInternal
        MapInternal<A, B> Value => value ?? MapInternal<A, B>.Empty;

        // .. impl ...
    }
```
Obviously this is still better than forcing the programmer to do it manually, but less efficient overall.

> I seem to remember this being brought up for C#6 and was dropped, so I'd be interested to know why?

Right now no `struct` will compile with a default constructor, and existing structs can continue working as they are, with the same semantics for default instantiation and copying.  My proposal is to not change any layout behaviours, array layout behaviour, default zeroing behaviour for structs that have no default constructor.  

For types with a default constructor then I expect it only to be called when the type is instantiated via `new`, any copying semantics should stay the same and not call the default constructor.

**Comment by svick** [comment] 2017-04-05 18:26
This is a duplicate of https://github.com/dotnet/csharplang/issues/99.

**Comment by louthy** [comment] 2017-04-05 19:13
Thanks @svick

**Closed** 2017-04-05 19:12 UTC
