### ISSUE TITLE
Allow to use discard in useless method parameters.

### ISSUE THREAD

**Issue by watsonsong** [dotnet/csharplang#2341] opened 2019-03-14 12:47 UTC
I have a method with some useless parameters and I want to name them as the discard '_'. It keep name easy and remove the no-used parameters.
The code like below:
```
someObj.OnEvent += (p1, _, _, p4)
{
    System.Console.WriteLine(p1);
    System.Console.WriteLine(p4);
}
```

The compiler report CS0100 error and prevent this snytax. I think this could be allowed.

**Comment by HaloFour** [comment] 2019-03-14 12:50
Dupe of #111

**Closed** 2020-10-12 21:21 UTC
