### ISSUE TITLE
[Proposal]: Mathematical range expression (10 < foo <= 100)

### ISSUE THREAD

**Issue by gstrasd** [dotnet/csharplang#4254] opened 2020-12-21 00:21 UTC
# FEATURE_NAME

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

This would be a feature that mirrors a mathematical expression that defines an allowed range of values.

## Motivation
[motivation]: #motivation

This for brevity and to better express a range of valid (or invalid) values in a mathematical context.

## Detailed design
[design]: #detailed-design

Instead of pairing two boolean expressions, declare the expression in a simpler, more concise syntax.

Instead of...
if (foo > 10 && foo <= 100) { }
Do this...
if (10 < foo <= 100) { }

Instead of...
if (bar < 23 || bar > 456) { }
Do this...
if (23 > bar > 456) { }

## Drawbacks
[drawbacks]: #drawbacks

The syntax might be confusing to those without a mathematical background.

## Alternatives
[alternatives]: #alternatives

NA

## Unresolved questions
[unresolved]: #unresolved-questions

NA

## Design meetings

NA

**Comment by 333fred** [comment] 2020-12-21 00:55
Duplicate of https://github.com/dotnet/csharplang/issues/4108.

**Closed by 333fred** 2020-12-21 00:55 UTC
