### ISSUE TITLE
[Proposal] Type parameters in "new" generic constraint

### ISSUE THREAD

**Issue by scottperham** [dotnet/csharplang#2600] opened 2019-06-14 16:41 UTC
Something that seems to come up from time to time is the need to define a generic method where the constraints specify the constructor of the generic type(s) have specific parameters (as opposed to a parameterless constructor as it is currently).

An example of this would be something like the following example where `T` can be any type that has a constructor that accepts only an `ILogger` instance.

``` c#
public T CreateInstance<T>()
    where T : new(ILogger)
{
    var t = new T(_logger);
    return t;
}
```
The constructor parameters could allow more specific types as long as they derive from the types specified and where there are multiple public constructors, as long as one matches:

``` c#
public class LoggerImpl : ILogger
{
}

public class Test
{
    public Test(LoggerImpl logger)
    {  }

    public Test(SomeOtherClass instance)
    {  }
}
```

This could of course also be more complex with something like:

``` c#
public T CreateInstance<T, U>()
    where U : new(string)
    where T : new(ILogger, List<U>)
{
    ...
}
```

**Comment by johnkellyoxford** [comment] 2019-06-14 17:35
I know there is a workaround using a delegate, but I do really like this idea.

**Comment by svick** [comment] 2019-06-14 17:49
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/769.

**Comment by BreyerW** [comment] 2019-06-14 18:45
Yes there are several duplicates and whats more this will be likely covered by shapes proposal or extended interfaces (extended interface will be able to hold almost all kinds of members except fields like bodiless constructors with parameters and operators) rather than `new()` being extended.

**Comment by JustNrik** [comment] 2019-06-15 14:48
Just use Activator.CreateInstance, fyi that's what new T() gets translated into. Which is kinda a pointless contraint whose only benefit is probably prevent abstract classes/interfaces to be passed as generic argument.

**Comment by johnkellyoxford** [comment] 2019-06-15 14:51
> Just use Activator.CreateInstance

Compile time checks > runtime checks. Hence `where T : new()`

**Comment by svick** [comment] 2020-10-18 10:13
Closing as a duplicate of https://github.com/dotnet/csharplang/discussions/769.

**Closed by svick** 2020-10-18 10:13 UTC
