### ISSUE TITLE
[Proposal] Interfaces implementation with inherited property type

### ISSUE THREAD

**Issue by LePtitDev** [dotnet/csharplang#2589] opened 2019-06-10 20:53 UTC
I know the summary is quite complex to understand but I don't know how to explain it without an example, so:

```csharp
public interface IParent
{
    ICollection<IChild> Children { get; }
}

public class Parent : IParent
{
    public List<IChild> Children { get; } = new List<IChild>();
}
```

For now in C#, the interface `IParent` require to implement the property `Children` with the type `ICollection<IChild>`. So if we want to use a list, we must do this:

```csharp
public class Parent : IParent
{
    public ICollection<IChild> Children { get; } = new List<IChild>();

    public void Add(IChild child)
    {
        ((List<IChild>)Children).Add(child);
    }
}
```

The objective is to simplify implementation of interfaces by allowing to use property types in class that inherit of property types in interface.

**Comment by theunrepentantgeek** [comment] 2019-06-10 20:58
If I'm reading your examples correctly, this would be a duplicate of Covariant Return Types - #49

**Comment by LePtitDev** [comment] 2019-06-11 04:13
Yes, I haven't seen this issue before. In my mind it would be great to limit it to the interfaces because it's more like a contract that this example respect. I don't know if extend it to virtualization is more complex or not.

**Comment by YairHalberstadt** [comment] 2020-10-28 10:12
Closing as duplicate of https://github.com/dotnet/csharplang/issues/49.

This has been implemented for C# 9, but only for virtual methods, not interface implementations.

It's possible to do manually with interface implementations as follows:

```csharp
public interface IParent
{
    ICollection<IChild> Children { get; }
}

public class Parent : IParent
{
    public List<IChild> Children { get; } = new List<IChild>();
    ICollection<IChild> IParent.Children => Children;
}
```

**Closed by YairHalberstadt** 2020-10-28 10:12 UTC
