### ISSUE TITLE
[Proposal] Generic constraint that enforces specific properties

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/csharplang#3550] opened 2020-06-09 07:26 UTC
It'd be nice if the developers can define a generic method that accepts any type "T" **if and only if** it has some specific property and/or indexer. I can't come up with a neat syntax, but let's say for example:

```csharp
// It means that the passed type MUST have a property "Length" and an indexer that takes an int and returns char.
// This can then accepts a string, ReadOnlySpan<char>, char[], or any other type that has this indexer and the Length property.
public static void PrintMe<T>(this T value) where T : property("Length"), indexer(int, char)
{
    for (int i = 0; i < value.Length; i++)
    {
        Console.WriteLine($"index {i}: value[i]");
    }
}
```

That will help reduce introducing different overloads. Previously, I'd have to introduce an overload for each type I'd want to support.

**Comment by Joe4evr** [comment] 2020-06-09 07:33
#164

**Comment by YairHalberstadt** [comment] 2020-12-01 11:51
Closing as duplicate of #164

**Closed by YairHalberstadt** 2020-12-01 11:51 UTC
