### ISSUE TITLE
Allow bool? in boolean_expression

### ISSUE THREAD

**Issue by maxtoroq** [dotnet/csharplang#1410] opened 2018-03-23 02:35 UTC
This won't compile:

```csharp
if (partialFieldName?.StartsWith("[", StringComparison.Ordinal)) {

}
```

...you have to turn `bool?` into `bool`, e.g. `partialFieldName?.StartsWith(...) == true`.

**Comment by CyrusNajmabadi** [comment] 2018-03-23 02:40
Yes.  That's by design.  The result of ?. on somthing returning ```bool``` is ```bool?```.  Whereas if-statements require a conditional that is of type ```bool```**.  there are some slight subtleties here (i.e. if you implement ```operator true/false```), but that's pretty much expected.

**Comment by jnm2** [comment] 2018-03-23 02:45
Relevant: https://blogs.msdn.microsoft.com/ericlippert/2012/03/26/null-is-not-false/

**Comment by jnm2** [comment] 2018-03-23 02:47
And I think my point at https://github.com/dotnet/csharplang/issues/871#comment-326716664 applies.

**Comment by maxtoroq** [comment] 2018-03-23 03:09
Other languages have solved this.

**Comment by jnm2** [comment] 2018-03-23 03:12
I think C#'s solution (making you explicitly say what you want `null` to mean) is really smart.

**Comment by yaakov-h** [comment] 2018-03-23 03:49
> Other languages have solved this.

You're making an implicit assumption that this is a problem that needs to be solved.

**Comment by maxtoroq** [comment] 2018-03-23 13:14
XQuery: `not(())` returns false.
C#: `!default(bool?)` returns null.

**Comment by HaloFour** [comment] 2018-03-23 13:19
Yes, different languages have different behaviors.  C# chose this behavior because it prefers the developer be explicit about their intent in order to avoid unintended logic bugs.

**Comment by maxtoroq** [comment] 2018-03-23 13:25
@HaloFour can you give examples of the bugs?

**Comment by jnm2** [comment] 2018-03-23 13:27
@maxtoroq [Here's some examples](https://github.com/dotnet/csharplang/issues/438#issuecomment-294171926), from yet another earlier discussion on this topic.

**Comment by Joe4evr** [comment] 2018-03-23 14:07
Here's a tip for the use-case in the OP: `if (partialFieldName?.StartsWith(...) ?? false)`

**Comment by jnm2** [comment] 2018-03-23 14:09
I like `?? false` because it puts the emphasis on what the default is.

**Comment by Joe4evr** [comment] 2018-03-23 14:14
Ever-so-slightly more advanced version:
```cs
//there may not be a childConfig associated with a particular object,
//so fall back to the global setting when that is the case
if (childConfig?.OptionEnabled ?? globalConfig.OptionEnabled)
{
    //....
}
```

**Comment by CyrusNajmabadi** [comment] 2018-03-23 18:17
> I think C#'s solution (making you explicitly say what you want null to mean) is really smart.

Agreed.  Another form i would like might be something like:

```c#
if (GetNullableBool()) {
} else {
} null {
}
```

If you have a nulloolean, you can provide a tri-switch specifying what you want to do for each of the three cases.

**Comment by HaloFour** [comment] 2018-03-23 18:20
@CyrusNajmabadi 

No need for more new syntax, pattern matching has that covered:

```cs
switch (GetNullableBool()) {
    case true: return 1;
    case false: return 2;
    case null: return 3;
}
```

Although currently the compiler can't tell that this is exhaustive, but you could replace `null` with `default` in the interim.

**Comment by Hosch250** [comment] 2018-03-23 18:21
@CyrusNajmabadi How does that work if the expression compiles to `true && null`?

**Comment by CyrusNajmabadi** [comment] 2018-03-23 18:23
> No need for more new syntax, pattern matching has that covered:

Yup.  I know about that.  But, personally, i think that's a bit of a jump for someone to take.  The mental model is: "i had an if that handled my bool.  now htat it's a ```bool?``` i'd really like to be able to handle this, without moving to some very different (and more verbose) structure. 

Note: i'm not saying that that makes it worth doing.  Just that it feels it fits this problem area better than jumping all the way to pattern matching switches.

**Comment by Joe4evr** [comment] 2018-03-23 18:38
> Although currently the compiler can't tell that this is exhaustive

:thinking: So after teaching the compiler "switching on a `bool` is exhaustive if there's a case for `true` and a case for `false`", is it really that much more work to add "switching on a `bool?` is exhaustive if there's a case for `true`, a case for `false`, and a case for `null`"?

**Comment by CyrusNajmabadi** [comment] 2018-03-23 18:41
@gafter See above.  A reasonable request (IMO) that hte compiler be able to tell exhaustiveness with ```T?``` if it can tell exhaustiveness with ```T```.  Note: you may have already done this.  But if not, i wanted to bring it to your attention!

**Comment by HaloFour** [comment] 2018-03-23 18:42
@CyrusNajmabadi 

Maybe.  It's certainly a much smaller jump, but it's also quite narrow in utility compared to general purpose matching.  It would also be weird that `else` isn't already the catch all when the expression doesn't evaluate to `true`, even if the type is `bool?`.

**Comment by CyrusNajmabadi** [comment] 2018-03-23 18:45
> Maybe. It's certainly a much smaller jump, but it's also quite narrow in utility compared to general purpose matching. 

"Note: i'm not saying that that makes it worth doing. Just that it feels it fits this problem area better than jumping all the way to pattern matching switches."

:)

**Comment by HaloFour** [comment] 2018-03-23 18:50
@CyrusNajmabadi 

Looks like the exhaustiveness issue is already partially fixed as using `when true` as @gafter suggested does work when matching on `bool?`:

```cs
// nice and exhaustive
switch (GetNullableBool()) {
    case true when true: return 1;
    case false: return 2;
    case null: return 3;
}
```

I assume that will probably be in C# 8.0 without requiring the case guard.

**Comment by CyrusNajmabadi** [comment] 2018-03-23 18:56
bleagh.  That looks awful :)

**Comment by gafter** [comment] 2018-03-23 23:34
@CyrusNajmabadi That's not for you. You get to write

``` c#
return GetNullableBool() switch { true => 1, false => 2, null => 3 };
```

**Comment by CyrusNajmabadi** [comment] 2018-03-23 23:57
@gafter .  Now that i can deal with :)

**Comment by MgSam** [comment] 2018-03-24 02:21
``` C#
if (partialFieldName?.StartsWith("[", StringComparison.Ordinal) == true) {

}
```

**Comment by AustinBryan** [comment] 2018-06-08 04:19
The best solution is we define what `bool?` should be when it's `null`. You might think it makes sense for it to be `true`, so you do `nullBool ?? true`, but I think it makes more sense to be `false`, so I do, `nullBool ?? false`. 

Jon Skeet explains `bool?` effectively `true`, `false`, `maybe?`

**Closed** 2020-01-18 20:16 UTC
