### ISSUE TITLE
Proposal: enhance using statement to declare an alias for value tuple

### ISSUE THREAD

**Issue by vwxyzh** [dotnet/csharplang#3402] opened 2020-04-27 07:02 UTC
In current c# 8.0, we can declare an alias for value tuple like following:
```c#
using MyResponse = ValueTuple<int, string>;
```
But it is not good enough.
We cannot use naming item, we can only use `Item1`, `Item2` in the code.
If we can support using statement like this:
```c#
using MyResponse = (int Code, string Message);
```
Then we can write following code:
```c#
public void HandleResponse(MyResponse response)
{
   Console.WriteLine($"{response.Code}: {response.Message}");
}
```

**Comment by svick** [comment] 2020-04-27 08:48
This is a duplicate of https://github.com/dotnet/csharplang/issues/423.

**Comment by CyrusNajmabadi** [comment] 2020-04-27 15:41
Closing as dupe.

**Closed by CyrusNajmabadi** 2020-04-27 15:41 UTC
