### ISSUE TITLE
Extend deconstruction to any type, based on members name (similar to pattern match syntaxe)

### ISSUE THREAD

**Issue by leandromoh** [dotnet/csharplang#3605] opened 2020-06-24 05:11 UTC
The same way we can deconstruct tuples (or types with `Deconstruct` method) by its positions, would be nice to deconstruct any type by specify its members names, *similar to what is done in pattern matching* .

So giving an object
```c#
var person = new Person { Name = "bob", Age = 45, Sex = 'M', Email = "email@bob.com" };
```

We would be able to decontruct it by specifying the name of public members of interesting, "à la" pattern matching, 

```c#
var { Name: name, Age: age } = person;

Console.WriteLine(name); // "bob"
Console.WriteLine(age); // 45
```
As well [there are three ways to deconstruct a tuple](https://docs.microsoft.com/pt-br/dotnet/csharp/deconstruct#deconstructing-a-tuple), the same syntaxes would be allowed here.

1) use the `var` keyword so that C# infers the type of each variable
```c#
var { Name: name, Age: age } = person;
```
2) use the `var` keyword individually with any or all of the variable declarations inside the curly brackets
```c#
{ Name: var name, Age: var age } = person;
```
3) explicitly declare the type of each field inside parentheses
```c#
{ Name: string name, Age: var age } = person;
```

As well in pattern matching, we can only use public members of the source object. 

The advantage over `Deconstruct` method is that this is a lot more flexible.
- reuse the well know pattern matching syntaxe to deconstruct, which might be more intuitive than create extension methods for an existing type
- users does not need to reason about members position on deconstruct
- no need to define any deconstruct method (which might become a lot of boilerplate code since we would need one method for each tuple deconstruct cardinality)   
- avoid ambiguity (when there is more than one deconstruct method with same quantity of parameters compiler show compilation error)

**Comment by YairHalberstadt** [comment] 2020-06-24 07:50
Duplicate of https://github.com/dotnet/csharplang/issues/3546

**Comment by 333fred** [comment] 2020-06-24 16:17
Closing as a duplicate. Another relevant issue: https://github.com/dotnet/csharplang/issues/3107

**Closed by 333fred** 2020-06-24 16:18 UTC
