### ISSUE TITLE
'var' return for private methods

### ISSUE THREAD

**Issue by ymassad** [dotnet/csharplang#1820] opened 2018-08-28 06:19 UTC
Allow 'var' to be the return type of private methods.

```
private var GetDictionary()
{
      return new Dictionary<string, (int, int)>();
}
```

There is another [issue entry](https://github.com/dotnet/csharplang/issues/1484) asking for the same thing for all methods, including public methods. I am assuming that the main objection regarding that was that public methods should not have their signatures implicitly changed because they form APIs that we should be very careful when changing. I agree.

In the same issue, other people talked about doing the same thing but only for private methods (and also internal methods). I guess that internal methods might make implementing this one a bit hard, so I am not including it in this issue.

I am adding this issue so that this topic can be discussed/voted on after having removed the main complaint point about it.

There is [another related issue](https://github.com/dotnet/csharplang/issues/943) that is about supporting 'var' as the return type for local functions.

I assume that implementing var for local functions and for private methods would be very similar. Maybe even the same compiler code can be used for both.

The reason I am interested in this feature is that it allows us to have methods whose return types are too complex to specify manually. I working on a project where this feature would be very useful. I will update this post with a concrete example later.

IMO, this feature will not be very useful if we are not allowed to have 'var' returning methods call other 'var' returning methods (and have inference work correctly). The return type of simple methods will not be complex enough to warrant the use of 'var' as the return type (or to warrant adding such feature to C#).

**Comment by yaakov-h** [comment] 2018-08-28 06:33
I dunno, this sounds fairly conclusive to me: https://github.com/dotnet/csharplang/issues/1484#issuecomment-394531995

**Comment by Mafii** [comment] 2018-08-28 06:48
> The reason I am interested in this feature is that it allows us to have methods whose return types are too complex to specify manually.

Well, define an alias with `using`. If the type is really that complex, maybe rethink your code.

I'm very curious about your example. However, the link yaakov-h posted shows the C#-teams last known stance on this issue. This feature is probably not going to happen, with good reasons.

**Comment by ymassad** [comment] 2018-08-28 08:33
@yaakov-h , in that comment, they are saying that there are no plans to implement such features. They don't say they are never going to implement them.

**Comment by ymassad** [comment] 2018-08-28 09:09
@Mafii , with an alias, you still have to write the type manually. With 'var', you can compose the type automatically by aggregating types returned from other methods (which themselves could be 'var' returning).

For example:

`return (method1(), method2(), method3(), method4());`

The other example I talked about is related to dependency injection, I will post it later. In a nutshell, we can use such feature to make it easier to introduce a dependency to a class/method with low maintenance cost.

This feature can be simulated using 'var' based variables which are delegates (e.g. Func). For example:

`var method1 = Func.Of((int a, int b) => a + b);`

But of course, there are limitations to this. For example, a "method" that is defined before another "method" cannot call it.

**Comment by TheUnlocked** [comment] 2018-08-30 18:07
By requiring that the programmer explicitly specifies the type in the signature, it adds a certain amount of self-documentation to the code. Removing that will surely lead to bugs and therefore much more wasted development time than the small amount of time it takes to type a few more characters.

If your type is too complex to specify manually with ease, not specifying the type would likely cause far more issues.

**Comment by HaloFour** [comment] 2018-08-30 18:17
I think all of the arguments as to why local functions will not be getting return type inference apply here.  And that was something that the team was interested in perusing at one point.

In short, it's too complicated and could easily result in circular inference problems.  Even if the compiler could work through the details attempting to write that in English for the spec would likely be quite involved.

**Comment by YairHalberstadt** [comment] 2020-10-18 11:58
Closing as duplicate of https://github.com/dotnet/csharplang/issues/1484

**Closed by YairHalberstadt** 2020-10-18 11:58 UTC
