### ISSUE TITLE
[Proposal]: [FEATURE_NAME]

### ISSUE THREAD

**Issue by xkentertainment** [dotnet/csharplang#4063] opened 2020-10-23 21:30 UTC
# Static Classes Having containing members be static  by default
Static classes having all methods, fields and properties as static without having to have the keyword before them
* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary

Have any class marked as static have any fields, properties or methods be static without having to add the keyword, this works well because you have to mark everything else as static regardless, which is pointless

## Motivation

Simplify what a user has to do to declare a field/property/method, there's no need to have to put the keyword "static" behind every single thing in a static class because they're static by default.

## Detailed design

Have a static class let's say, public static class Thing
eg.
static class Thing
{
    static bool done;
    public static bool Done => done;
    public static void Done()
    {
        done = true;
    }
}

and every method, let's say, static  \<return type\> Do() {}, or a field static \<return type\> done, or a property static \<return type\> Done { get; set; }
not have to require the coder to have to write static for every method.

so if you have a static class named Thing
every method/property/field will not have you to add static in front of them
eg.

static class Thing()
{
    bool done;
    public bool Done => done;
    void Done()
    {
        done = true;
    }

}

the current way of doing things makes it tedious, because you have to always remember that you are in a static class,
and even when you don't *have* to remember, it's a useless feature to have to add the keyword.

## Drawbacks

It'll probably be unclear to someone writing code whether they're in a static class or not, but this honestly sounds like a them problem. It's definitely annoying to have to put the keyword "static" behind every single thing once a class is marked as static, but it helps to some degree to recognize that a single method is in fact, static.

**Comment by Joe4evr** [comment] 2020-10-23 21:38
You're not the first one to suggest this, [the last one wasn't even three weeks ago](https://github.com/dotnet/csharplang/discussions/3967).
> The reason `static` is required to be specified on all members of a static class is because removing `static` from the class declaration in a future version is a binary-compatible change. If `static` was implicit on its members, you'd have to remember to add it to everything when you remove it from the class to avoid breaking your consumers.

**Comment by theunrepentantgeek** [comment] 2020-10-23 21:38
Duplicate of #1962 (static keyword for members declared inside static class should be optional/implied) and #1753 (Feature Request: Inferred static keyword for members in static classes)

There are other, earlier, discussions as well, but I'm unable to find them.

IIRC, the C# Language design team are strongly in favour of the existing explicitness of requiring **static** on all members.

**Comment by 333fred** [comment] 2020-10-23 22:37
Closing a duplicate of https://github.com/dotnet/csharplang/discussions/1753.

**Closed by 333fred** 2020-10-23 22:37 UTC
