### ISSUE TITLE
Constructor Delegate

### ISSUE THREAD

**Issue by DarkChowder** [dotnet/csharplang#2253] opened 2019-02-22 21:52 UTC
I would like the ability to use constructors the same as other static functions.

```
    class Program
    {
        static void Main(string[] args)
        {
            //Before
            Func<string, Person> personFactory1 = (string name)=>new Person(name);

            //After
            Func<string, Person> personFactory2 = new Person;
        }
    }

    class Person
    {
        public Person(string name)
        {
            Name = name;
        }
        public string Name { get; }
    }
```

**Comment by Joe4evr** [comment] 2019-02-22 23:05
Duplicate of #674.

**Closed** 2019-02-22 23:46 UTC
