### ISSUE TITLE
Discussion: Improving ability for override property between getter and setter.

### ISSUE THREAD

**Issue by kekyo** [dotnet/csharplang#2780] opened 2019-09-05 00:42 UTC
# Summary
Currently C# properties have limitation for inheritance both getter and setter combinations. I feel can safely remove it.

# Motivation
Sometimes base property implementations and/or abstract declaration has only getter or setter. We can override these properties, but cannot simplify. For example:

```csharp
// Base implementation
public abstract class Foo
{
	public abstract string Name { get; }
}

// CANNOT: Inherited with private setter
public sealed class Bar : Foo
{
	public override string Name { get; private set; }    // (A)
}

// CURRENT SOLUTION 1: Manually extracted backing field
public sealed class Bar : Foo
{
	private string name_;
	public override string Name => name_;
}

// CURRENT SOLUTION 2: Only setting at constructor
public sealed class Bar : Foo
{
	public Foo(string name) => this.Name = name;

	public override string Name { get; }
}
```

This issue is grants the case (A).

# Another way

More improvement (but I feel it's second solution) is with syntax changing (adding):

```csharp
// Can append override attribute at getter and setter token:
public sealed class Bar : Foo
{
	public string Name { override get; private set; }
}
```

**Comment by yaakov-h** [comment] 2019-09-05 02:05
Duplicate of https://github.com/dotnet/csharplang/issues/1568.

**Comment by YairHalberstadt** [comment] 2020-11-04 13:18
Closing as duplicate of #1568

**Closed by YairHalberstadt** 2020-11-04 13:18 UTC
