### ISSUE TITLE
Nullable tuple generic inference

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#2169] opened 2019-01-24 07:19 UTC
```C#
public static (K,V) GetKV<K,V>(Func<(K,V)> func) => func();
public static (K,V)? GetKVNullable<K,V>(Func<(K,V)?> func) => func();

////

int x	= 0;
var a = GetKV(() => {
	if(x < 0)
		return ("negative",-1);

	if(x > 0)
		return ("positive",1);

	return ("zero",0);
});

var mayBeA = GetKVNullable(() => { // ERROR on this line
	if(x < 0)
		return ("negative",-1);

	if(x > 0)
		return ("positive",1);

	return ("zero",0);
});

```

Above code cause error

`The type arguments for method 'GetKVNullable<K, V>(Func<(K, V)?>)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [Assembly-CSharp]`

While `GetKV` can be inferred correctly. Is it impossible to infer usage in nullable return function?

**Comment by YairHalberstadt** [comment] 2019-01-24 07:37
You'll have a similar issue when doing

```csharp
int? x = condition ? 42 : null;
```
Since null can't be cast to a value type, and a value type can't be case to null, C# can't work out the type of an expression returning one or the other.

I think there was a championed proposal somewhere to fix this, but I'm not sure.

The solution in both cases is to cast null to the value type:

```csharp
int? x = condition ? 42 : (int?)null;
```

**Comment by Joe4evr** [comment] 2019-01-24 07:59
Duplicate of #33.

**Closed** 2019-01-24 08:03 UTC
