### ISSUE TITLE
DI: Access modifiers on constructor parameters

### ISSUE THREAD

**Issue by PieterjanDeClippel** [dotnet/csharplang#3584] opened 2020-06-18 21:55 UTC
Hi,

I was wondering if there are/have been plans to implement an angular-style of DI in Roslyn/c#. In angular you have the following neat notation:

    export class AppComponent {
        constructor(private accountService: AccountService) {
        }
    }

Which makes the `accountService` available within the class. In c# you have to declare a variable and perform an assignment.

    public class AccountController : Controller {
        private readonly AccountService accountService;
        public AccountController(AccountService accountService) {
            this.accountService = accountService;
        }
    }

But if you'd think of the angular notation, it could be written like this (the code below would imply the above code, including the readonly access modifier):

    public class AccountController : Controller {
        public AccountController(private AccountService accountService) {
        }
    }

Is this something that could be considered, or is there a caveat that makes this impossible?

**Comment by PathogenDavid** [comment] 2020-06-18 22:52
The proposal uses different syntax, but this is a duplicate of https://github.com/dotnet/csharplang/issues/2691, which is marked as a candidate of C# 9.

It's currently in as part of records, I'm unsure if there are any plans to bring it to normal classes/structs or whether it works with non-public accessibility.

[Here's an example of it being used:](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMYHsEBNkA0MICcAdgbiANQA+AAgMwAEmOuzAsgJ4BKE2PAAoAlmRjMAGgWZiJATQCUAWABQAbzXNtzJrPHMAynAC2zALwA+Kc2rN5AbjUBfNWvoAmRms2qdujw8tHV9/fwA3KARmGBQJc2YyCAB3Lj4BdiEARgAGHJkPPMUnPzDteiyAOgqATiEAEgAidVjkGErJZ1tmFrjK+S6E3rbK4xNnRuLg7VdVWbUAegXmAClyAGsYrGYTKHWIGIALA7FUXAhwiAAbLAAHEwgDbBNbkSuIaMOoW9vuSrUyFAHshblAMAcKpVeOQYCIHpUAMJYF5vD6GD7hETg5A+aa6FjIaDvDieZgASWQAFEAB6xBCAq5ksgiCTqZizWZAA)

```csharp
public record MyRecord(int X, int Y)
{
    public int Sum => X + Y;
}

public static class Program
{
    public static void Main()
    {
        var test = new MyRecord(100, 200);
        System.Console.WriteLine($"{test.X} + {test.Y} = {test.Sum}");
    }
}
```

**Comment by CyrusNajmabadi** [comment] 2020-06-18 23:30
Dupe of existing proposal (and likely several others from the past :) ).  Closing out.

**Closed by CyrusNajmabadi** 2020-06-18 23:30 UTC
