### ISSUE TITLE
Proposal: analyzers should be able to waive a specific instance of a warning or suggestion

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/csharplang#574] opened 2017-05-13 01:36 UTC
Some warnings are irrelevant in some specific contexts. 

For instance:
*  warning cs0420 (*a reference to a volatile field will not be treated as volatile*) does not make sense in the context of a method of an Interlocked class -- example where a specific warning does not make sense within the context of a specific class library, which could come with its own analyzer.
* warning cs0067 (*the event ‘event’ is never used*) could be irrelevant is the event is required by a specific class library that uses reflection and requires the event as a part of the contract (although there is a design alternative in this case, which is to rely on a interface for the contract). 
* a suggestion to make a field read-only could be irrelevant if the class is made serializable by some custom serializer that does not support read-only fields 
* warning CS1998 (*this async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'a wait Task.Run(...)' to do CPU-bound work on a background thread.*) is irrelevant if a compiler extension (PostSharp or so) changes the threading behavior of the method, for instance with a [Background] aspect (forces a CPU-bound method to completely execute in a background thread), an [Actor] aspect (enqueues all method calls and execute them one by one), or even a simple [Synchronized] aspect (which would asynchronously await for and acquire a lock).

All these examples show that some specific warnings are useful in general (and therefore should not be disabled globally) but confusing in specific contexts, and it is a legitimate concern for a class library or an aspect library author to disable this warning.

This proposal is to add an API that would allow an analyzer to waive a warning or code suggestion proposed by the compiler or any other analyzer. This API would receive semantic information, not only syntactic (file/line) information. Therefore the changes must be done upstream in the process of emitting warnings, which is a relatively expensive change to the compiler.

**Comment by HaloFour** [comment] 2017-05-13 01:42
You can use `#pragma warning disable` to suppress those warnings when you feel that they don't apply.

**Comment by svick** [comment] 2017-05-13 02:35
> warning cs0420 (*a reference to a volatile field will not be treated as volatile*) does not make sense in the context of a method of an Interlocked class

[This one is already special-cased in the compiler](https://github.com/dotnet/roslyn/blob/a2e2bf4/src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs#L56), so the warning should not be produced for `Interlocked` methods. Not sure if that is a point for or against this proposal.

**Comment by gfraiteur** [comment] 2017-05-13 18:32
@HaloFour `#pragma warning disable` is a kind of last-chance think, meaning that the compiler toolchain failed to produce relevant intelligence. My proposal helps avoid false positives in the first place.

@svick Nice to see you again! And thanks for the head up. (btw, we're finally releasing the bits you codes for us in PostSharp 5.0 :). I've noticed this specific example has been addressed, but this is a specific example where my proposal is a general one and allows all class library authors to make the warnings and suggestions smarter.

**Comment by sharwell** [comment] 2017-11-01 13:20
:memo: Without objection (@gafter, @MadsTorgersen, @jaredpar) I believe this can be closed as a duplicate of dotnet/roslyn#20242, meaning specifically that a change to the C# language specification is not required in order to proceed with the feature in the compiler layer.

**Comment by gfraiteur** [comment] 2017-11-01 14:03
@sharwell Agreed.

**Comment by sharwell** [comment] 2018-12-03 13:02
Duplicate of dotnet/roslyn#20242

**Closed** 2020-10-13 06:04 UTC
