### ISSUE TITLE
Feature : Add ability to yield return IEnumerable<T> in a  method that returns IEnumerable<T>

### ISSUE THREAD

**Issue by MuziburRahman** [dotnet/csharplang#3574] opened 2020-06-16 16:00 UTC
Consider this code:

```
IEnumerable<int> collection = ...;

public IEnumerable<int> SomeMethod()
{
    if (...)
        yield return 1;

    else if(...)
    {
        foreach (var item in collection)
        {
            yield return item;
        }
    }
}
```
Sometimes it seems an overkill. I know that all the items in  `collection` is going to be returned. Now, wouldn't it be nice if I could just yield return the whole `collection` like this:
```
yield return collection;
```
The idea is that, when a collection is yielded, it's elements will be yielded instead;

May be an additional keyword will make it easier:
```
yield return all collection;
```

**Comment by svick** [comment] 2020-06-16 16:18
This is a duplicate of https://github.com/dotnet/csharplang/issues/378.

**Comment by 333fred** [comment] 2020-06-16 16:46
Closing as a duplicate.

**Closed by 333fred** 2020-06-16 16:46 UTC

**Comment by fschmied** [comment] 2024-03-18 10:22
The discussion actually covering this is #5303 (but it seems it's not coming without first solving #378).
