### ISSUE TITLE
Decorator pattern for functions in .NET

### ISSUE THREAD

**Issue by mmojgani77** [dotnet/csharplang#6358] opened 2022-06-29 11:24 UTC
Python programming language has decorator concept that you can run some codes before and after calling the method.
It is a useful feature for concepts like logging, caching, etc.
I suggest to implement this feature that makes that ability for developer to run another functions before and after a function or method call

**Comment by 333fred** [comment] 2022-08-10 00:13
Duplicate of https://github.com/dotnet/csharplang/discussions/862.

**Closed** 2022-08-10 00:13 UTC
Labels: untriaged, Area-Compilers
