### ISSUE TITLE
Proposal: Caller Parameter Name

### ISSUE THREAD

**Issue by JackTheSpades** [dotnet/csharplang#1557] opened 2018-05-23 10:15 UTC
Subset of #87 

The idea of additional `Caller` Attributes has been brought up before, though not these two so I thought might as well throw them out there.

Currently we have `CallerMemberNameAttribute`, `CallerFilePathAttribute` and `CallerLineNumberAttribute`. All of which can be a huge help when debugging but `CallerMemberName` is especially useful since it can be used to implement `INotifyPropertyChanged` through one Method rather than the constant need for `nameof()`.

So I'd like to propose an addition to the set with `CallerParameterNameAttribute` containing the name of the expression which was passed to a given parameter.

This could prove useful especially for Guard classes. Here a simple example.

```cs
public class Foo
{
   public static void GuardNull(object obj, [CallerParameterName("obj")] string obj_caller = null)
   {
      if(obj is null)
         throw new ArgumentNullException(obj_caller, $"{obj_caller} cannot be null.");
   }
}
```
As the C# example shows, the desired caller could be passed as a string parameter to the attribute. The content of `obj_caller` could be something like this:

```cs
public string Foo { get; private set; }
public void Bar(object obj)
{
   string format = "{0}.{1}";
   int number = 3;

   GuardNull(obj);      // "obj"
   GuardNull(format);   // "format"
   GuardNull(number);   // "number"
   GuardNull(this.Foo); // "this.Foo"
   GuardNull(3);        // "#const"
   GuardNull("baz");    // "#const"
}
```
Not sure if const expressions should be invalid (hence the `#const` in my example above, as '#' is not valid for variable names) or just passed as their actual const value like "null", "3" and ""baz"".

Perhaps, to simplify things, instead of a string for each parameter, a single `Dictionary<string, string>` mapping parameter name and caller name could be used. But given how these attributes are handled, I'm not sure it's possible.

I've seen numerous examples where it would be helpful to be able to fetch the name of argument like gcc Marco Stringizing using the '#' operation:

```cpp
#define GuardNull(ptr) { if(!ptr) printf("%s was nullptr", #ptr); }

void foo(const char* msg) {
   GuardNull(msg)
   //...
}
```

Lastly, and really more as a side note, maybe we could also have a `CallerObjectAttribute` simply indicating that `this` gets passed to it. From it one could fetch the caller Type and further the Assembly, Namespace, etz as well as perform further debug operations.

I'm aware that this is somewhat lazy, but then again the whole point of these attributes is to take work of off the programmers hands.

**Comment by alrz** [comment] 2018-05-23 10:30
https://github.com/dotnet/csharplang/issues/287

**Comment by dotnetchris** [comment] 2018-11-01 23:03
I wanted to do something like this for doing json style patching to c# objects with method parameters.

I was able to accomplish it via Sigil / IL, man was that painful. Having CallerParameterName would have been much easier.

**Comment by YairHalberstadt** [comment] 2020-10-15 13:56
Closing as duplicate of championed issue #287

**Closed by YairHalberstadt** 2020-10-15 13:56 UTC
