### ISSUE TITLE
[Proposal] Generic type inference based on method return type

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/csharplang#2710] opened 2019-08-02 18:40 UTC
This is a request for comments on a generic inference feature that infers the generic type of a method/class based on the return type of the method when returning a call to that method.

**Example**:

```cs
public class MyStatus<T> : MyStatus
{
    T Result { get; set; }

    public MyStatus(string error)
        :base(error)
    {
        Result = default(T);
    }

}

public class MyStatus
{
    public string Error { get; private protected set; }

    public MyStatus (string error)
    {
        Error = error;
    }

    public static MyStatus CreateWithError(string error)
    {
        return new MyStatus(error);
    }

    public static MyStatus<T> CreateWithError<T>(string error)
    {
        return new MyStatus<T>(error);
    }

    public static MyStatus<T> CreateGenericWithError<T>(string error)
    {
        return new MyStatus<T>(error);
    }
}

public class SomeClass
{
    // Compiler Error
    MyStatus<IEnumerable<int>> DoSomethingFails()
    {
        return MyStatus.CreateWithError("Some Error");
    }

    // Compiler Error
    MyStatus<IEnumerable<int>> DoSomethingFail2()
    {
        return MyStatus.CreateGenericWithError("Some Error");
    }

    MyStatus<IEnumerable<int>> DoSomethingWorks()
    {
        return MyStatus.CreateWithError<IEnumerable<int>>("Some Error");
    }
}
```

Would it be acceptable for the compiler to inter the generic type parameter for the call under `DoSomethingFails`? At first glance it seems like it's  safe assumption under the restriction that it's returning that call.

For nested generics, calls like this can get abusively long.

**Comment by HaloFour** [comment] 2019-08-02 18:53
Sounds similar to this proposal here:  #92

**Comment by TonyValenti** [comment] 2019-08-03 15:20
I have wanted this this for such a long time!  I work around this by have a static class with generic "create" methods that call into the generic constructor.

**Comment by alrz** [comment] 2019-08-03 17:49
@TonyValenti

You should have had some arguments to infer type arguments, this'll work with no args at all e.g. `Array.Empty()`

**Comment by YairHalberstadt** [comment] 2020-11-02 08:59
Closing as duplicate of #92

**Closed by YairHalberstadt** 2020-11-02 08:59 UTC
