### ISSUE TITLE
Champion Operators for System.IntPtr and System.UIntPtr

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#120] opened 2017-02-15 18:27 UTC
- [x] Proposal added: https://github.com/dotnet/csharplang/blob/master/proposals/intptr-operators.md
- [ ] Discussed in LDM
- [ ] Decision in LDM
- [ ] Finalized (done, rejected, inactive)
- [ ] Spec'ed

**Comment by jkotas** [comment] 2017-02-16 04:59
Duplicate of https://github.com/dotnet/csharplang/issues/48

**Closed** 2017-02-16 18:47 UTC
Labels: Proposal champion

**Comment by adamsitnik** [comment] 2017-06-15 14:54
Could you remove the 7.2 milestone from this duplicate? It gives false impression that C# 7.2 is WIP by showing that 7% is already completed.

/cc @gafter 

![image](https://user-images.githubusercontent.com/6011991/27187333-366d4366-51eb-11e7-97ff-9744887c6b3b.png)

**Comment by gafter** [comment] 2017-06-16 03:43
C# 7.2 *is* a Work In Progress.

**Comment by adamsitnik** [comment] 2017-06-16 08:11
I used the wrong term.

It's WIP, but the "7% Completed" looks like something is actually completed. And completed might be understood as accepted language change, implemented and tested ;)
