### ISSUE TITLE
Pointer to generic Type are not allowed.

### ISSUE THREAD

**Issue by jkotas** [dotnet/csharplang#1649] opened 2018-06-19 17:10 UTC
_From @Neo-Ciber94 on June 19, 2018 16:44_

**Is impossible to declare pointers to generic types, .NET 7.3**  

        public struct Unmanaged<T> where T: unmanaged { }

        public unsafe struct SomeCoolAndSexyStruct<T> where T: unmanaged
        {
                public Unmanaged<T>* _pointer; //Not allowed
        }

_Copied from original issue: dotnet/coreclr#18547_

**Comment by jkotas** [comment] 2018-06-19 17:10
This is C# language limitation.

**Comment by svick** [comment] 2018-06-19 19:20
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/1504.

**Comment by dzmitry-lahoda** [comment] 2018-09-09 15:30
I got from pointers to `wrongly` reported error here https://stackoverflow.com/questions/52228109/a-generic-construct-requires-that-the-type-cellt-is-an-unmanaged-type

**Comment by YairHalberstadt** [comment] 2020-10-16 08:13
Closing as championed in #1937 and implemented in C# 8

**Closed by YairHalberstadt** 2020-10-16 08:13 UTC
