### ISSUE TITLE
Proposal: typedef

### ISSUE THREAD

**Issue by darrenoakey** [dotnet/csharplang#3738] opened 2020-07-28 10:42 UTC
It's been a long time since C++ - but after all these years of C#, there's a few things I still miss, and the most important of which is typedef.

The trouble is, when you use generics - it can start to get real messy real fast.   Usually we end up creating a wrapper class, just to make the code cleaner and the intention more obvious - and we create static implicit casts so you can pass the types you actually have, or pass your type to someone else's function - so we regularly end up with this:

```c#
 public class NameList
    {
        private readonly string[] _underlying;

        private NameList(string[] underlying)
        {
            _underlying = underlying;
        }

        public static implicit operator string [](NameList values)
        {
            return values._underlying;
        }

        public static implicit operator NameList(string[] values)
        {
            return new NameList( values);
        }

        public override string ToString()
        {
            return _underlying.AsCommaSeparatedList();
        }
    }
   
```

where what we really wanted was 

```c#
    public define type alias string [] NameList;
```

**Comment by AartBluestoke** [comment] 2020-07-28 11:17
except that if you go and define a second type the same way
public void nameFoo(NameList myList){...}
...

ColorList colourList = new string[]{"red","green","blue"};
nameFoo(colourList); // <-- is a compile error because a NameList is not a ColourList

....
I find myself wanting the reverse - a way to trivially define a sub-type of string, just for holding specific types of strings, and single value structs are the only solution to guarantee that you can't stick a colour into a function expecting a name.

**Comment by darrenoakey** [comment] 2020-07-28 11:22
I understand everything you've written except the word "except" - because that argument is exactly why we want typedefs... if ColorList is a typedef, and NameList is a typedef - then they both erase to string []... which is good - your code works.  If we make wrapper types like above - the code fails.    

So more reason why typedef is better than a wrapper class?

**Comment by HaloFour** [comment] 2020-07-28 11:31
You can use type aliases for this in C# already:

```cs
using NameList = string[];`
```

**Comment by darrenoakey** [comment] 2020-07-28 11:32
but that's only scoped to a file.  I want this as part of my external library signature

**Comment by AartBluestoke** [comment] 2020-07-28 11:36
because if you're declaring it to be a different type you want it to fail. a string list may be a Colour List. a string list may be a Name List. 
A NameList is not a ColourList.

you can use local using statements of you just want an alias to the erased type.:

[using NameList=using NameList = System.Collections.Generic.List<string>;](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACAcgQwFsBTAXjiQDoBlYMASygHMBudLPI4gGXoGdg2UtgoAWSrwEAeCpgB8bDAgDM2AN7psWkQgTrN2wwRIBtALrYoXAIJgw+AJ5DLxAO7ZzagEQAjAPY+XgA0XgBW+FDEXgC+ioZGXJKCUAA2/ILCke7GPOne/oEh4ZExcfFaFACcABS0DMyUAFJ+jNXBwanpAJRdZVrR6NFAA===)
you can't quite do that with arrays - you need to do using Name=System.String; (also at the link above)

**Comment by HaloFour** [comment] 2020-07-28 11:44
@darrenoakey 

The team has expressed interest in expanding type aliases in general, including allowing them to be exported:

https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-07-13.md#Generics-and-generic-type-parameters-in-aliases

**Comment by darrenoakey** [comment] 2020-07-28 12:00
> because if you're declaring it to be a different type you want it to fail. a string list may be a Colour List. a string list may be a Name List.
> A NameList is not a ColourList.

I both agree with you and disagree.  In theory you are 100% correct - and half the time you are doing it - you are doing it because you like strong typing and correct code and so on.

The other half of the time, it's because you have an IEnumerable<Tuple<Dictionary<string,string>, Int, Dictionary<String,Int>>> - and you'd prefer that mess never appear more than once in your code.  It's not really a meaningful concept - it's just what the shape that spat out of the processing you want on it - and you just want to write it more simply.... but fundamentally - _that_ is the type you are dealing with - there is no meaningful business concept you are encapsulating - it's just a shape that appears in the middle of a process and gets sent to something else.    THEN I just want an alias.  The last thing I want to is to then have to go _and coerce something into or out of that type_!

so the theorist in my agrees with you - but the pragmatist thinks a simple alias will be as or more useful.  But honestly - if they are doing the work - they might as well support both, because 99% of the work will be identical.

**Comment by AartBluestoke** [comment] 2020-07-28 12:13
(incidentally, you code will probably be much more performant if it's a struct, not a class; structs with a single member can be optimised much further; the compiler can basically make it 100% equal to using the underlying value)

Also, you added a custom "toString" functionality, not something you can do with your 'strict typedef' you propose.

 I'd suggest that if you end up exposing an enumerable of tuples, that you are instead exposing some other specific object type. struct MyThing{ Dictionary<string,string> reference;Dictionary<String,Int> children; int Id;} and you should be passing around an IEnumerable<MyThing>

implicit conversion to/from a highly complex shape doesn't seem like it would be safe, and if it's eg:json, libraries handle serializing collections into collections, so naming the intermediate types as something will increase you readability, and also mean that if the shape changes, you still only have 1 place to change the code.

**Comment by HaloFour** [comment] 2020-07-28 12:21
IMO I would not like aliases to be something encouraged by the language unless those "aliases" provided a degree of type safety, the compiler treating each named "alias" as a separate type.  Single-element positional records I think get you pretty close:

```cs
public record NameList(string[] value);
```

It would be nicer if they could be a struct which would eliminate the unnecessary allocation which will hopefully happen by C# 10.

I really don't want to see the typedef mess that is C++ Win32API coming to the C# world, where there are a thousand aliases for `DWORD` that are all interchangeable and since the compiler allows assigning between them freely your only real defense to layer a logic typing on top of them is Systems Hungarian notation.

**Comment by PathogenDavid** [comment] 2020-07-28 12:24
Duplicate of #1300, #2488, #259, and #1170

Subset of: #410

**Comment by 333fred** [comment] 2020-07-28 14:26
Closing as a duplicate.

**Closed by 333fred** 2020-07-28 14:26 UTC
