### ISSUE TITLE
Proposal: allow a [RegexColorization] pseudo-attribute for colorization of regex strings.

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/csharplang#2662] opened 2019-07-17 08:47 UTC
VisualStudio colorizes strings passed as `pattern`-Parameter to various static methods of the `System.Text.RegularExpressions.Regex`-class. This colorization feature is, however, only available for said methods.

E.g. the regex-colorization will not be available for the following method (A custom utility method which I use quite often):
```csharp
static bool TryMatch(this string s, string pattern, out Match m, RegexOptions opt = RegexOptions.Compiled | RegexOptions.IgnoreCase) =>
    (m = Regex.Match(s, pattern, opt).Success;
```

I propose a relaxation of this 'strictness', meaning that the colorization should be available for any parameter (or field/variable) of the type `System.String` marked with a special pseudo-attribute, e.g. `[RegexColorization]`.

I am proposing this feature request here, as I assume that the colorization information is emitted by the Roslyn engine and the addition of pseudo-attributes is part of the language specification.

**Comment by YairHalberstadt** [comment] 2019-07-17 08:57
https://github.com/dotnet/roslyn/issues/34640

**Comment by YairHalberstadt** [comment] 2019-07-17 09:00
> the addition of pseudo-attributes is part of the language specification

I don't believe it is. Tooling can use whatever it likes to generate whatever diagnostic or visualisations it wants.

**Comment by yaakov-h** [comment] 2019-07-17 09:16
This isn't part of the language specification. It's part of the Visual Studio tooling, and what happens [when Cyrus gets bored](https://github.com/dotnet/roslyn/pull/23984).

You can colorize any string by prefixing it with `/* language=regex */`.

**Comment by CyrusNajmabadi** [comment] 2019-07-17 17:28
> You can colorize any string by prefixing it with `/* language=regex */`.

I even support `// lang=regex` for brevity :)

**Comment by CyrusNajmabadi** [comment] 2019-07-17 17:30
But yes, this is a dupe of https://github.com/dotnet/roslyn/issues/34640 which is def the more general way to accomplish this for all embedded languages teh IDE eventually supports.

**Comment by 333fred** [comment] 2019-07-18 17:58
@Unknown6656 I'm going to close this issue, as it isn't proposing anything about the C# language, and let discussion happen in the linked roslyn issue.

**Closed by 333fred** 2019-07-18 17:58 UTC

**Comment by Unknown6656** [comment] 2019-07-19 11:44
@333fred thanks - sorry, I forgot to close the issue myself yesterday.
