### ISSUE TITLE
Is it possible to extend c# compiler to mimic properties {get; set;} the same way as a field? details in attached picture below.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/csharplang#2639] opened 2019-07-01 17:47 UTC
![image](https://user-images.githubusercontent.com/1408396/60535103-30505f80-9cb8-11e9-85e7-8832ab2dea40.png)

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/622696/is-it-possible-to-extend-c-compiler-to-mimic-prope.html
VSTS ticketId: 937516_
_These are the original issue comments:_

Serge Sudja on 6/25/2019, 09:06 PM (5 days ago): <p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/80561-proposal-serges-1.png">proposal-serges-1.png</a></p><p>Updated code example to expose question.</p>

Jane Wu [MSFT] on 6/26/2019, 01:05 AM (5 days ago): <markdown><p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>
</markdown>

**Comment by gafter** [comment] 2019-07-09 20:44
I think the OP is asking if properties can be made to work with `ref` and `out` parameters.

**Comment by yaakov-h** [comment] 2019-07-09 21:37
See #748, #1235.

**Comment by YairHalberstadt** [comment] 2020-11-01 09:43
Closing as duplicate of #748, #1235 among others

**Closed by YairHalberstadt** 2020-11-01 09:43 UTC
