### ISSUE TITLE
Proposal: Allow Void type as a Generic parameter

### ISSUE THREAD

**Issue by kind-serge** [dotnet/csharplang#696] opened 2017-06-22 15:23 UTC
Currently,  `void` is not allowed as a generic parameter for a type or a method, what makes it hard in some cases to implement a common logic for a method, that's why we have `Task` and `Task<T>` for instance.

However, nothing stops you from defining your own `Void` type like this:
```csharp
    [StructLayout(LayoutKind.Sequential, Size = 0)]
    public struct Void { }
```
and use it as a generic parameter for any type or method.

This solves the problem is your app, but your own `Void` type is not the same as built-in `System.Void`, even though they are semantically equal, what introduces a confusion for a consumer that does type analysis when using reflection for instance.

Now with your own `Void` type you are obliged to use the `return` statement in methods:
```csharp
MyNamespace.Void FunctionAsProcedure()
{
    // must use return statement, even though the type size is 0
    return default(MyNamespace.Void);
}
```
what is not a requirement for `System.Void`. This optional use of the `return` statement should be considered as an optimization for well-known 0-length value types.

Thus, the `System.Void` must support the `new` operator, and must be allowed (but not required) to be explicitly returned as the result of a method.
Such behavior intersects with another feature request: [Allow return void function with void function](https://github.com/dotnet/csharplang/issues/135).

**Comment by mikedn** [comment] 2017-06-22 15:59
>  even though they are semantically equal

How so? You can create an array of type `MyNamespace.Void[]` but you can't create an array of type `void[]`. Same for fields - you can have a field of type `MyNamespace.Void` but of type `void`. They're obviously semantically equal. What you're really saying is that you'd like to change the semantic of `void` to be like `MyNamespace.Void`.

> This optional use of the return statement should be considered as an optimization for well-known 0-length value types.

There's no such thing as a 0 length value type. Your `Void` type has in fact size 1. The idea of a 0 length value type is rather bizarre, among other things this means that the following code would generate a division by 0 error:
```C#
long distance(Void* p1, Void* p2) => p2 - p1;
```

**Comment by svick** [comment] 2017-06-22 15:59
1. The type `System.Void` already exists, but it's very special. You can't even write `typeof(System.Void)` (`typeof(void)` works) and you can't create an instance of that type. If you wanted to reuse this type, I belive the CLR would have to be modified. Some related discussions: https://github.com/dotnet/roslyn/issues/234, https://github.com/dotnet/roslyn/issues/14424.
2. In functional programming in general, and in F# in particular, a unit type is used for this purpose, which is considered equivalent to zero-tuple. Zero-tuple already exists (in the form of the non-generic `System.ValueTuple`), but it doesn't have language support in C#. Maybe this type could be used instead? See also: https://github.com/dotnet/roslyn/issues/16313.

**Comment by mikedn** [comment] 2017-06-22 16:20
> The type System.Void already exists, but it's very special.

Strictly speaking it's not even a type. If it weren't for pointers (where it has to sort of behave like a type for consistency and simplicity) maybe it wouldn't even exist. `void` could have been just a language keyword indicating that the method doesn't return anything and `MethodInfo.ReturnType` could just return `null` for void returning methods.

**Comment by tyrotoxin** [comment] 2017-06-22 16:25
@mikedn,
1. Those types are semantically equal - i.e. they mean the same, but you are right that you can do different things with them - that's not semantics.
2. Actual size is 1 - that's should not be related to the language specs, it's rather a compiler/runtime implementation details.
3. The example with pointers is not good - a pointer size depends on bitness of your compiled application, and subtracting pointers gives you a pointer.

**Comment by HaloFour** [comment] 2017-06-22 16:29
This suggestion was already argued over on Roslyn.  The issue is that it would require quite a few changes to the CLR and at this point wouldn't help much since many of the core APIs are already written.  Rather than trying to shoe-horn the existing concept of `void` into the equation I'd rather the BCL simply provided its own `Unit` struct.

**Comment by mikedn** [comment] 2017-06-22 16:34
>  that's not semantics

But what is it?

> and subtracting pointers gives you a pointer

No, subtracting pointers gives you a `long`, the distance in objects between those pointers. Since pointers are really memory addresses that means that `p2 - p1` is in fact `((long)p2 - (long)p1) / sizeof(object_type)`.

**Comment by tannergooding** [comment] 2017-06-22 16:44
I think the fact that subtracting two pointers in C# giving you a long is an implementation detail.

If C# had proper support for `IntPtr/UIntPtr` from the beginning, it would have returned that instead (and not waste 4 bytes on platforms that don't need it). Two pointers subtracted from each other should give the equivalent of the native `size_t`.

**Comment by mikedn** [comment] 2017-06-22 17:15
> If C# had proper support for IntPtr/UIntPtr from the beginning, it would have returned that instead

Sure but that doesn't change the fact that subtracting 2 0-sized type pointers is not possible. If 0-sized types would be allowed then subtracting such pointers should be a compile time error, just like subtracting 2 `void*` pointers is today but for different reasons.

**Comment by Joe4evr** [comment] 2017-06-22 17:47
> I think the fact that subtracting two pointers in C# giving you a long is an implementation detail.

Well, this whole part of the discussion got started *because of* the fact that specifying `Size = 0` for your own struct gives it a size of 1 is also an implementation detail.

**Comment by tannergooding** [comment] 2017-06-22 17:56
@Joe4evr, specifying `Size = 0` and giving a struct of non-0 is not an implementation detail, it is part of the CLI specification and is not up to interpretation.

> The .size directive indicates a minimum size, and is intended to allow for padding. Therefore, the amount of memory allocated is the maximum of the size calculated from the layout and the .size directive. Note that if this directive applies to a value type, then the size shall be less than 1 MByte. 

> ClassSize of zero does not mean the class has zero size.  It means that no .size directive was specified at definition time, in which case, the actual size is calculated from the field types, taking account of packing size (default or specified) and natural alignment on the target, runtime platform.

> A ValueType shall have a non-zero size - either by defining at least one field, or by providing a non-zero ClassSize  [ERROR]

**Comment by tannergooding** [comment] 2017-06-22 17:59
Which is entirely separate from what a language decides to return when the delta between two pointers is taken, where the return type is up to the language and not defined by the runtime.

**Comment by ijsgaus** [comment] 2017-06-22 18:07
Can be made with ValueTuple

**Comment by alrz** [comment] 2017-06-22 20:25
Whatever it is, I hope we use `void` to denote it, that makes it transparent in case of type substitution.
```cs
interface I<T> { T M(); }
class C : I<void> { public void M(){} } // the compiler automatically emits `return` 
```

**Comment by tyrotoxin** [comment] 2017-06-22 23:00
I feel like this conversation starts going slightly wrong direction. Let's set aside all thinking about void pointers, which are not allowed in generic methods (correct me if I'm wrong).

I'd rather scope this down to particular feature request to allow `void` in as generic parameters in types and methods, so that:

1. Methods with generic return types like:
```csharp
T Method<T>()
{
    return default(T);
}
```
with `void` translate to:
```
void Method()
{
    return;
}
```

2. Allow parameters and fields of type `void`.
This is needed to support let's say async state machines, when you define an `async` method which returns `Task<T>` when `T` is `void`.

As @tannergooding mentioned the CLI specification, there must be no value type of 0 size, and `System.Void` is indeed defined as:
```csharp
[StructLayout(LayoutKind.Sequential, Size = 1)]
public struct Void { }
```
What makes it pseudo non-unit type.

**Comment by HaloFour** [comment] 2017-06-23 00:13
@tyrotoxin 

The method translation that you described is not possible.  C# the compiler can only emit said method exactly once and the IL must work for any possible generic type argument.  A method that returns a value must `push` the value onto the evaluation stack before `ret`.  But a `void` method is required to have an empty evaluation stack.  The same problem exists for callers.  The size of the evaluation stack, which must be known by the C# compiler and predictable by the CLR *before* JIT or specialization, suddenly becomes completely impossible to calculate, and there's never a single set of valid IL instructions which can represent a generic method.  And we're not even touching the possibility of `void` parameters.

At best you can treat `System.Void` as more than nothing, but that makes little sense, offers no benefit over a proper `unit` type and involves modifications to the CLR which are entirely extraneous.  Comparatively, the effort to add `System.Unit` to the BCL is infinitesimal.

**Comment by Joe4evr** [comment] 2017-06-23 00:57
The main take-away from this and the related issues is the fact that people desire a standard, Microsoft-supported implementation of `Unit`. It should behave like a real type (which `void` is not), but can (optionally) also carry a little bit of `void` semantics.

For example, I imagine it could allow the bare `return;` to break out of a method early (the compiler would make it `return default(System.Unit);`), but it wouldn't be required as the last statement (the compiler would insert the same return statement implicitly as the last thing if not there). On the other hand, since it *would* be a real type, [`return AnotherUnitReturningMethod();` would also be legal](https://github.com/dotnet/csharplang/issues/135).

There should probably be a few analysis rules that come along to provide a little guidance around the use of `Unit`, to prevent newcomers from missing the "pit of success". But that bridge can be crossed when MS gets to it.

**Comment by mikedn** [comment] 2017-06-23 05:44
> This is needed to support let's say async state machines, when you define an async method which returns Task<T> when T is void.

Being able to create a `Task<void>` (or `Task<Unit>` or whatever the unit type is) doesn't help much. There's no way to convert `Task` to `Task<void>` and thus you won't be able to write generic code that handles both `Task` and `Task<T>`. For this to be useful we need a time machine to go back in time and remove `Task` (or make it abstract) and replace all its uses with `Task<void>`.

> The method translation that you described is not possible. C# the compiler can only emit said method exactly once and the IL must work for any possible generic type argument. A method that returns a value must push the value onto the evaluation stack before ret. 

So what? The C# compiler doesn't have to do anything in this regard, the emitted IL doesn't change. The runtime/JIT may then choose to elide the return code when `T = void` or continue to behave like today and do a `return 0;` (that's what happens today when you return an empty `struct`).

> over a proper unit type and involves modifications to the CLR which are entirely extraneous

Somehow I doubt that you can make a proper unit type without CLR modifications. I guess it ultimately depends on how useful you want it to be. And no matter what you do you still won't be able to treat `Task` as `Task<unit>` and this limits its usefulness.

**Comment by Opiumtm** [comment] 2017-06-23 10:13
Major reason for desire to make `System.Void` full-blown type is desire to make `Action` equal to `Func<void>`. Often, generic "functional-like" code require to have two versions of methods. One for "functions that not return any value" (so, parameter is `Action`) and another one for functions, that return value of any type (generic `Func<T>`). Although such functional-like code do essentially same things for both cases. `unit` isn't apply here as there are heaps of external or own code that uses `void` when it doesn't return anything. So you **should** keep both versions because `System.Void` doesn't behave like functional `unit`. And `Action` isn't compatible with `Func<MyNamespace.Unit>`.
So too many people do double work with functional-like code because of `System.Void` isn't proper `unit`.

**Comment by HaloFour** [comment] 2017-06-23 11:50
@mikedn 

> So what? The C# compiler doesn't have to do anything in this regard, the emitted IL doesn't change. 

It does if the result is supposed to behave as described and nothing is to be returned.  If something is to be returned then yes, the evaluation stack would still have a value.  But then you're not dealing with `void`, you're dealing with "unit".

> Somehow I doubt that you can make a proper unit type without CLR modifications. I guess it ultimately depends on how useful you want it to be.

Why not?  This is exactly what F# did.  You just need a marker type.  It could be a tiny struct.  It could be a non-instantiatable class.  In either case it represents no value.  CLR modifications could enable better optimization, but you could get the functionality out of the box.

>  And no matter what you do you still won't be able to treat `Task` as `Task<unit>` and this limits its usefulness.

I agree.  I feel that this ship has sailed.  Attempting to retroactively address it at this point would only further fracture the API and there really isn't any practical benefit to doing so.

**Comment by mikedn** [comment] 2017-06-23 12:40
> It does if the result is supposed to behave as described and nothing is to be returned

If something is to be returned then returning nothing is never an option. But the opposite is not a problem, you can always fake it by returning something, doesn't matter what, and ignoring that something. In this case of a generic method you just return `initobj T` as before.

> Why not?

For example because you can't convert between `Action` and `Func<unit>` as it has already been mentioned.

**Comment by HaloFour** [comment] 2017-06-23 14:02
@mikedn 

> For example because you can't convert between `Action` and `Func<unit>` as it has already been mentioned.

Well you can't convert between `Func<T, bool>` and `Predicate<T>` either.  But I get your point.  Thing is, the only way that could ever work is if the CLR does something in the delegate invocation to fix the stack so that both the caller and the callee can `push`/`pop` the appropriate number of values.  And while it kinda makes sense with `Action` and `Func<unit>`, what the heck does `Func<unit, unit, int>` mean?  And how does it apply to non-delegates?  What is a `List<unit>`?  Does it have an `Add` method that takes zero parameters?  Can you assign an `Action` delegate to that?

All-in-all I think the concept represents way too much work for very little gain.  Nothing stops anyone from using marker types to represent no value.  Adapting delegate types is very easy.

**Comment by Binderbound** [comment] 2017-06-29 03:44
I might be completely dumb here - but what could you do with Generic<void> that you couldn't do with Generic<object>?

**Comment by DavidArno** [comment] 2017-06-29 12:15
@Binderbound,

The commonly used example is that the method:
```cs
void Foo();
```
could be assigned to a `Func<T>` variable or parameter, as it would be a `Func<void>`

This then removes the need to have to duplicate classes or overload methods to handle both `Func<T>` and `Action`.

**Comment by tyrotoxin** [comment] 2017-06-29 15:29
> I might be completely dumb here - but what could you do with Generic[void] that you couldn't do with Generic[object]?

That's actually a very good question which must be asked in the first place to understand why this feature is requested.

As @DavidArno is already answered, this is about convenience. My personal motivation was to add this request when I got enough of writing __duplicate methods__ that do exactly the same, but differ in the result type - `Task` and `Task<T>` in my case. I want to write 1 single generic method whenever I deal with such types, so `Task<void>` would be almost the same as `Task`.

How is `Task<void>` different from `Task<object>`? There is a big difference. The `void` indicates that the task has no result object - this is very important distinction for a framework that I'm working on - that's why I had to introduce my own `Void` type.

Why can't I just keep using my own `Void` type? I can. But thought it would be nice to have such feature to be built-in into the language, so anyone can use it out-of-the-box, and it would be nice to have 1 single standard vs many possible custom Void pseudo non-unit types.

Even though it might not be technically feasible to implement this feature, I'd like to explore possibilities of doing it, even if the final potential implementation has a lot of restrictions.

**Comment by Rhialto** [comment] 2017-09-26 21:17
C++ people have had an extremely similar discussion, with very similar arguments for and against, and discussion on whether void (in either language) is a unit or bottom type (it turns out it is some of both, in C++ at least). This was in the context of template programming, where void  in many cases forms an irregular exception.
Email discussion: https://groups.google.com/a/isocpp.org/forum/#!topic/std-proposals/05prNzycvYU[1-25]
Eventual  proposal document:http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0146r1.html

**Comment by Pzixel** [comment] 2017-12-18 16:31
Defenitly upvote this. We could introduce some other type (unit is good), but I'm sure that we need this in C#. I'm always writing interfaces like this:
```csharp
    public interface IRemoteRequestProcessor : IDisposable
    {
        Task<T> GetResultAsync<T>(IRemoteRequest request);
        Task ExecuteAsync(IRemoteRequest request);
    }
```
And this is pretty annoying...

**Comment by HaloFour** [comment] 2017-12-18 16:43
@Pzixel 

You can already do that.  Introduce a marker type that indicates that you don't care about the response and then have `GetResultAsync<T>` check for that as the generic type argument.

**Comment by Pzixel** [comment] 2017-12-18 16:54
@HaloFour it's a solution for interface consumer, but it forces interface implementor to return some dummy type when T is ignored.

**Comment by HaloFour** [comment] 2017-12-18 16:59
@Pzixel 

Yes it does.  That's completely unavoidable.  The IL can't conditionally push a value onto the stack based on generic type arguments.  You can always just return `null` or `default(T)`.

**Comment by Pzixel** [comment] 2017-12-18 17:09
@HaloFour it's unavoidable on IL level, but we could consider it as error in C#. I imagine it would be just a structure Unit, without any properties and which has several restriction on language level, such as impossibility to use it in any construct other than signature parameters. Something like:
```csharp
public struct Unit : IEquatable<Unit>
{
	public static readonly Unit Default = new Unit();

	public override int GetHashCode() => 0;
	public override bool Equals(object obj) => obj is Unit;
	public override string ToString() =>"()";
	public bool Equals(Unit other) => true;
	public static bool operator ==(Unit lhs, Unit rhs) => true;
	public static bool operator !=(Unit lhs, Unit rhs) => false;
}
```
With pack of extra rules on C# level. It doesn't sounds really complicated. Returning default(T) is not really good implementation for a caller. This is why we are in the situation when lib authors provide two overloads just to express "this method might or might not return a value".

**Comment by Joe4evr** [comment] 2017-12-18 17:13
🤔 That's exactly what I said 6 months ago.

**Comment by HaloFour** [comment] 2017-12-18 18:13
@Pzixel 

We already have `ValueTuple` representing a tuple of no elements, which is effectively `unit`.  Language support for that might be nice in the sense that you use the `unit` alias and that you never have to explicitly return anything from a method returning `unit`.  But it's such a minor difference to the state of the language today, and it doesn't solve the major generic problems that seem to crop up during these conversations like treating `Func<T, unit>` as an equivalent of `Action<T>`.

**Comment by mikedn** [comment] 2017-12-18 18:16
> that you never have to explicitly return anything from a method returning unit

Hmm, how exactly is that useful anyway? It seems that this type of problem appears most often in generic code. And if it's generic code then you have to return something anyway because the compiler doesn't know that `T` is `unit` or not.

**Comment by quinmars** [comment] 2017-12-18 20:16
> which has several restriction on language level, such as impossibility to use it in any construct other than signature parameters.

@Pzixel There is no need to restrict the usage. The unit type is a normal value type with exactly one value. Think of it that way: a variable of the type `byte` can have potentially 256 different values, a variable of the type `bool` can have two values and a variable of the type `unit` has (always the same) one value. If you return `Unit.Default` you do not return nothing but a value, which happened to always be the same.

The unit type is only useful if something like the following would be possible:

```csharp
Task<unit> task = Task.Run(() => Unit.Default);
var result = await task;
return result;
```

**Comment by Pzixel** [comment] 2017-12-19 08:50
@Joe4evr so I agree with you :)

@HaloFour we don't need this conversion, we could just not use `Action` when/if this feature releases. Just like `Func<T, bool>` is used in BCL virtually anywhere while we have more specialized `Predicate<T>` which is pretty rare. Don't convert existing code, just opportunities for new one, and probably some IDE level refactoring that does it. Compiler has no idea thar second generic parameter in `Func` is `TResult` so I don't believe he could perform such a conversion even in the ideal world. Well, your example with `ValueTuple` is great, I didn't think about it.

@mikedn for example, if return type is `unit` tools like serializers could even not read return stream but return `unit` immediatly. It's just like `return null`/`return default(T)`, but more convinient and clear to user that he shouldn't use return value.

@quinmars you're probably right. I had a thought that we don't need things like array of unit, but on the other hand we could run `await Task.WhenAll(...)` on multiple tasks that may return unit, so we have array of units here.

**Comment by Neme12** [comment] 2018-01-09 21:12
I agree this is definitely useful. The ship might have sailed for `Task`, `Func`, `Action`, but the BCL is not everything... we still face the same problem with our own types. How many times have you seen either double implementation with a lot of duplicate code for a return/no return value (roslyn `CSharpSyntaxVisitor`) or code that uses bool as a bogus value? (`TaskCompletionSource`)

Could `void` be a keyword that maps to this unit type (possibly `ValueTuple`) except in non-generic method return values where it would map to regular void?

To hide this distinction, a regular `void` method call expression could be assignable to a void variable (this would silently create an actual value), a void method could have an explicit return value (let's say `return ();` if it's the empty tuple).

As someone mentioned earlier, you can't convert between `Predicate<T>` and `Func<T, bool>` either but it would still be useful to have a method that takes Func<T, void> (probably from a generic type) and pass in a lambda that has no return value. Is that possible?

**Comment by HaloFour** [comment] 2018-01-10 01:59
@Neme12 

> but it would still be useful to have a method that takes `Func<T, void>` (probably from a generic type) and pass in a lambda that has no return value. Is that possible?

Not at the IL level.  You'd need `void` to map to some kind of actual type, and you'd need the compiler to actually have that lambda return a value of that type.  It's something that the compiler could do, although I'm not personally convinced it would be that useful.  `void` doesn't just mean the lack of a value, it means the lack of a place to even put a value.  

The bigger question might be what does `Func<void, T>` mean?  Or `Func<T1, void, T2, TR>`?  Or `List<void>`?  There's a much bigger and hairier story there.  And at the end of the day, `Task<void>` still wouldn't be `Task`, and `Func<void>` still wouldn't be `Action`.

**Comment by yaakov-h** [comment] 2018-01-10 06:39
`Func<void, T>` could be the same as `Func<T>` in theory... a function that takes no argument and returns an object.

`Func<T1, void, T2, TR>` I cannot even begin to conjure up a meaning for.

**Comment by Neme12** [comment] 2018-01-10 09:42
@HaloFour My idea was that it would map to `ValueTuple`. `void` would change its meaning - it would now mean the empty tuple, which is a unit type. It would get compiled to `ValueTuple`, except in regular method return positions, which would still get compiled to actual `void` - but the compiler would do everything it can to make it look like the `void` that those methods are returning is actually an empty tuple. Therefore you could do this:

`var x = VoidMethod();`

where x would be of type `void`, which in this case would get compiled to `ValueTuple` and the compiler would require that type. Since `VoidMethod` doesn't actually return that at the IL level, the compiler would just create a value for you. It would be the equivalent of this:

`VoidMethod(); var x = default(void); /* or () */`

But when you create a lambda:

`Func<void> f = () => { }; /* or () => () */`

it would get compiled to return a `ValueTuple`, since in Func<T> a generic T is being returned and that can't ,possibly be plain old `void`.

As to what `Func<void, T>` or `List<void>` would mean - I agree it's pretty much useless, but you can do the same exact thing today by having a `List<ValueTuple>`. You could only keep add`default(void)` to it.

`Task<void>` and `Task` can't be the same because they are a completely different class. You *could* pass `Task<void>` to `Task` but not the other way around.

Apart from reflection, the only issue I see is that:

    void VoidMethod();
    
    class Generic<T>
    {
        T GetDefaultOfT();
    }
    
    var x = new Generic<void>();

these signatures (`VoidMethod` and `x.GetDefaultOfT`) would not be equal. Is there no way to get these to be compatible? So that it would be possible to do this:
`Func<void> f = VoidMethod;` and `Action a = x.GetDefaultOfT;`

@yaakov-h  `Func<void, T>` would never be the same as `Func<T>`, because they take a different *number* of arguments.

**Comment by Pzixel** [comment] 2018-01-10 13:11
I think you are on the wrong way, guys.

We just need some compiler support for empty tuple type aka `Unit`. Then JIT may implement some features like [Rust does](https://doc.rust-lang.org/beta/nomicon/exotic-sizes.html):

> On their own, Zero Sized Types (ZSTs) are, for obvious reasons, pretty useless. However as with many curious layout choices in Rust, their potential is realized in a generic context: Rust largely understands that any operation that produces or stores a ZST can be reduced to a no-op. First off, storing it doesn't even make sense -- it doesn't occupy any space. Also there's only one value of that type, so anything that loads it can just produce it from the aether -- which is also a no-op since it doesn't occupy any space.
> 
> One of the most extreme example's of this is Sets and Maps. Given a `Map<Key, Value>`, it is common to implement a `Set<Key>` as just a thin wrapper around `Map<Key, UselessJunk>`. In many languages, this would necessitate allocating space for UselessJunk and doing work to store and load UselessJunk only to discard it. Proving this unnecessary would be a difficult analysis for the compiler.
> 
> However in Rust, we can just say that `Set<Key> = Map<Key, ()>`. Now Rust statically knows that every load and store is useless, and no allocation has any size. The result is that the monomorphized code is basically a custom implementation of a HashSet with none of the overhead that HashMap would have to support values.

**Comment by HaloFour** [comment] 2018-01-10 13:25
@Pzixel 

We have the zero-element tuple, `ValueTuple` (no generic parameters, no fields).  Compiler support for it might be nice, but as I mentioned before I'd go with the type name `unit` and/or the expression `()`.  The compiler could potentially optimize around that type where it was known, but I have a feeling that the more common scenario would be with generics where that onus would fall entirely on the JIT to optimize away.  Currently it doesn't; the JIT treats `ValueTuple` (and any other "empty" struct) as 1-byte.

**Comment by Pzixel** [comment] 2018-01-10 13:36
> Currently it doesn't; the JIT treats ValueTuple (and any other "empty" struct) as 1-byte.

Ok, I was unaware about it. However, I feel that we are on the same wave 😄 . Looking forward.

**Comment by Joe4evr** [comment] 2018-01-10 14:14
@HaloFour What I'd at least like to see is that a method returning that `unit`/`()` does not require an explicit `return <value>` at the end and allows the bare `return;` (the compiler can fill these in pretty easily), so that any method that currently returns `void` won't need changing the body if the developer decides to change that return type.

**Comment by Neme12** [comment] 2018-01-10 17:34
@Pzixel
I want a unit type too and thought it might be a good idea to unify it with the existing void "type"
a) to make it feel like C# and not introduce any new keyword such as `unit`
b) because if this type allows us to omit a return statement, that essentially makes `void` redundant
so these could actually be 1 thing and the fact that void methods compile to void would be sort of an "optimization" (but not really, it can't be an implementation detail and would have to be in the spec)

But it this is impossible, an empty tuple unit type separate from void would still be useful. But with the empty tuple `()` is syntax for both the value and the type: `() x = ();`. Is such a syntax possible and unambiguous?

**Comment by Pzixel** [comment] 2018-01-10 18:25
> I want a unit type too and thought it might be a good idea to unify it with the existing void "type"
a) to make it feel like C# and not introduce any new keyword such as unit
b) because if this type allows us to omit a return statement, that essentially makes void redundant
... so these could actually be 1 thing and the fact that void methods compile to void would be sort of an "optimization" (but not really, it can't be an implementation detail and would have to be in the spec)

I think they are many pitfall in treating `void` as `unit`. It's quite dangerous to perform such a conversion. And I'm almost sure it won't be 100% backward compatible and thus a no-no for the LDM.

> But if this is not realistic, an empty tuple type separate from void would still be useful. But with the empty tuple () is the syntax for both the value and the type: () x = ();. Is that possible and unambiguous? I tried to implement this and at first it seemed fine but after playing around a little more with casts the compiler started complaining about me trying to declare variables in an expression. But I'm definitely not an expert (and don't even understand all the parts that I changed).

I think we may just forbid `unit` type usage other than type declaration. You need is as generic argument only. If it's a unit type you don't need to compare it with anything - it's unit :) Why on the earth you need a value of the `unit` type? If you want return it just write `return;` just like for the void method. If you want to pass it as parameter you can use `default` keyword. In all other cases you are working with generic that _may_ be of unit type, but you work with it as regular variable. 

It's just an idea, it looks a bit hacky, but doesn't have mentioned issues and I see no drawbacks except some uglyness.

**Comment by quinmars** [comment] 2018-01-10 19:51
@Pzixel again, there are no restrictions needed. Infact your proposed restrictions would invalidate the whole purpose of the unit type. If you cannot compare (`Object.Equals`) it, you cannot box it and then you cannot use it as generic type parameter. If the unit type does not have a default value, you cannot use it as a generic type parameter. You may take a look at a possible, already used, and useful implementation of the unit type: https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Rx.NET/Source/src/System.Reactive/Unit.cs

It's not harmful to use the unit type as what it actually is/should be: a _normal_ value type.

**Comment by Pzixel** [comment] 2018-01-10 19:57
@quinmars why whould you like to run `object.Equals`? You don't have to compare `unit` object because it's a singleton. You don't have to box it because you want to box an emptiness. You obviously can use it as generic parameter but you cannot create a value of this type because it's useless.

If you thing the opposite provide any use case when it's necessary to declare a variable of type `Unit`, which is not monomorphed generic (i.e. T t = new T(); for `T: Unit` is valid while Unit unit = ... isn't).

**Comment by Pzixel** [comment] 2018-01-10 20:11
@quinmars I think these methods are allowed to be used by the compiler but not by the user. If you are comparing two `Unit` objects then you just don't understand what is it.

**Comment by quinmars** [comment] 2018-01-10 20:22
@Pzixel  `if (0 != 0) return;` is also useless, but valid. I still don't understand why you want to restrict the usage of the unit type.

**Comment by Pzixel** [comment] 2018-01-10 20:31
@quinmars it's the same thing as empty statement `;`. 99 out of 100 cases are just a typo. Unit it a bit different, it has NO valid usecases. `0` is on of ints so we just don't put an extra rule in the compiler. However, we show a warning anyway.

**Comment by Neme12** [comment] 2018-01-10 20:52
@Pzixel

Even with all your restrictions, things like `List<unit>` would still be allowed.
I don't think there's any reason to limit usage of this type. Yes, it's silly to have a variable of type void. It's also possible to make a lot of silly-looking expressions with the `()` syntax. But it's just as silly as doing this: `{{{{}}{{}}}}{};`. In fact it's silly to have an empty block on its own at all in your code - it doesn't do anything. That doesn't mean we should ban it.

As you admit, there's a really easy "workaround" to get this to work - by making the type generic. I don't think we should introduce inconsitencies around having a generic vs non-generic version of the same thing. `T` should be replacable by the actual type without errors.

I don't think there's going to be an epidemic of people making void variables just for the sake of it. It's not like we're gonna have to explain to people "don't do that! it's actually useless" - most people would be aware of that. Nobody writes code like this today: `();;{;{};{}}`. It's also silly to create an empty local function. And then call it. Or make a function that you don't call at all. But all of that should be legal. I don't think this is going to cause bugs either and therefore it doesn't warrant that we should ban it. There's no reason why we should pick and choose specific usages and make a list of what we think you don't need to do.

> you cannot create a value of this type because it's useless
> If you are comparing two Unit objects then you just don't understand what is it.

Do *you* understand what it is? The point of the unit type is that it *does* have a value - there's exactly one. No matter how useless it is. That's why it's called a *unit* type. Therefore comparison should always return true.
 
> Unit it a bit different, it has NO valid usecases

Then what is this thread all about?

> 0 is on of ints so we just don't put an extra rule in the compiler. 

I don't think we need any extra rules here either.

**Comment by Pzixel** [comment] 2018-01-10 21:07
@Neme12 I admit that I have to agree. At least I have checked this code and it's pretty valid in Rust:
```rust
fn main() {
    let _ = ();
    foo((), ());
}


fn foo(_: (), __:()) {
    
}
```

It's one of best designed language I know so if they are working this way then it's probably better than my silly proposal. I originally said that it looks `hacky`. Now you convinced me completely 😸

**Comment by GlassGrass** [comment] 2018-03-12 12:02
I think it is realizable this as user-code based syntax sugar in many case. How do you think?

- `void` return method will be wrapped by anonymous method which return `Unit` object when they will be assigned to generic delegate parameter.

  ```C#
  public void Foo<T>(Func<int, T> func) {}

  public void Bar(int arg) {}

  public static void Main()
  {
      // convert from
      Foo(Bar);

      // convert to
      Foo((arg) => { Bar(arg); return default(Unit); });
  }
  ```

- If there are several overloads, the one which do not need the conversion is always prior at name resolution.

  ```C#
  public void Foo(Action<int> func) {}

  public void Foo<T>(Func<int, T> func) {}

  public void Bar(int arg) {}

  public static void Main()
  {
      // resolve to Foo(Action<int> func)
      Foo(Bar);
  }
  ```

- If there are several overloads and all of them require the conversion, the caller will resolve to neither.

  ```C#
  public delegate T SomeDelegate<T>(int arg);

  public void Foo<T>(Func<int, T> func) {}

  public void Foo<T>(SomeDelegate<T> func) {}

  public static void Main()
  {
      // resolve to neither overloads (compile error)
      Foo(Bar);
  }
  ```

I think there are some advantages:

- Once concrete `Unit` type was decided, no modification for runtime or binary is need.

- All of conventional `void` return methods will get capable to assignment to generic return delegates just as it is.

- This is a syntax sugar and converted code is valid in current C#, so it may be able to be implemented comparatively easier.

**Comment by greatim** [comment] 2018-09-22 16:02
If we just do for Generic arguments, why not operates on the generic parser? We can use keyword "out?"  to hold the void only for output.

to define a delegate:
`public delegate TResult NewFunc<in T,out? TResult>(T arg);`

use "_" to be a placeholder, and replace Action<T> with NewFunc<T, _>.

so, we dont' change the void,  don't need a new type，and don't worry about the old code. we only use the new speciation if we need.

**Comment by EternalClickbait** [comment] 2020-01-16 08:57
I actually came across this thread when searching for a solution to this exact problem. I have a function that takes a `Func<T>` and returns the result (as well as doing some state changing behaviour). I have 2 versions, one with a `Func<T>` and one with an `Action`. To make it easier, I decided to make the void one call the `T` one. To fix the issue of being unable to use `void` as a generic parameter (which in my opinion is rather silly), I had to create a new function just to make it compile.

```
Simulate<int>( [parameters], () =>
{
    action();
    return 0;
});
```
As long as the value is not used (by passing it to other functions), I believe it should be possible, even if it's as simple as the CLR automatically returning `null` and forcing the result to be discarded.

**Closed** 2020-09-08 21:39 UTC
Labels: Discussion, Feature Request, Move to Discussion
