### ISSUE TITLE
Discussion: static variables

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#832] opened 2017-08-19 07:00 UTC
Originally proposed at https://github.com/dotnet/roslyn/issues/49, as it exists in VB,
```cs
string[] M(string str) {
  static var dot = new [] { '.' };
  return str.Split(dot);
}
```

------------

Alternatively we could use `static` keyword on the expression that we want to cache,
```cs
string[] M(string str) {
  return str.Split(static new[] { '.' });
}
```
**Open question:** should this turn to a class-level initializer or it should be initialized lazily as in VB?
**Open question:** would it make sense to generate a non-static field for a cached value?

Possible translations for the following:
```cs
object O => static new object();
```
->
```cs
// eager + static field
static object o = new object();
object O => o;

// eager + instance field
object o = new object();
object O => o;

// lazy + static field (similar to VB except for thread-safety)
static object o;
object O => o ?? (o = new object());

// lazy + instance field
object o;
object O => o ?? (o = new object());
```
plus thread safe variants (note: for value types we should probably use a boolean for lazy initialization.)

**Open question:** would it worth it to use different keywords to specify a particular translation?

**Comment by tuespetre** [comment] 2017-08-19 17:57
I found myself wanting a static keyword for inline expressions this week. This would be great to have.

**Comment by franzalex** [comment] 2017-08-20 00:33
Coming from a VB6 & VB.NET background, this is one thing I miss a lot even after over 7 years of programming with C#.  

I strongly believe that this is a must-have!

**Comment by franzalex** [comment] 2017-08-20 00:59
To address your questions:

> **Open question:** should this turn to a class-level initializer or it should be initialized lazily as in VB?

The VB.NET implementation does not initialize the value until the first time it is used (in the method in which it is located). Doing the same thing in C# will defer potentially expensive initializations until when it is really needed.

> **Open question:** would it make sense to generate a non-static field for a cached value?

Drawing again from the VB.NET implementation, I'd say it depends on where the variable is created.  
If it is created in a `static` method (equivalent to a `Shared` method in VB.NET), then, the variable ought to be implemented as a `static` field in order to keep it in scope and preserve its value whenever and however the method that relies on it is called.  
If, on the other hand, it is created in an instance method, then the variable ought to be implemented as a non-`static` field in order to ensure the per-instance integrity if two instances of a class initialize it to different values.

> **Open question:** would it worth it to use different keywords to specify a particular translation?

I'm not really sure of what you mean here. I'll just state that the VB.NET version doesn't allow the keyword to be combined with `ReadOnly`, `Shadows` or `Shared` (`readonly`, `new` or `static` respectively). 

It makes sense to disallow combining it with `new` (VB.NET `Shadows`) as regular variables tend to have this restriction anyway. Likewise, a person who wants to have a static variable will usually create one with the `static` keyword anyway. What is really up for discussion is the `readonly` modifier. I think it is unnecessary to put in that restriction however, it ends up saving you from yourself if a person 'accidentally' tries to assign to the variable after it has been initialized.

**Comment by Joe4evr** [comment] 2017-08-20 13:53
> **Open question:** would it make sense to generate a non-static field for a cached value?
> **Open question:** would it worth it to use different keywords to specify a particular translation?

I would say the following:
* Lazy init pretty much always
* Always in a thread-safe manner
* In a `static` method: Lift to a `static` field
* In an instance method: Lift to an instance field
  * Compiler is free to optimize to a `static` field if it can determine that all data written into the variable is static and wouldn't affect the rest of the program\*
* (Maybe) Combine with `readonly`: Can only assign once, but *may* be not an actual `readonly` field
  * Compiler should optimize to a real `readonly` field by lifting the assignment to either a field initializer, or (if dependent on other fields) into the constructor(s) (would become eager init)

\*This rule could be omitted altogether with some alternative syntax I propose at the bottom of this post.

Examples:
```cs
public class C
{
    public static string[] M1(string str)
    {
        //static method: lifts to static field
        static var splitchar = new [] { External.GetRandomChar() };
        return str.Split(splitchar);
    }

    public string[] M2(string str)
    {
        //instance method: lifts to instance field
        static var splitchar = new [] { External.GetRandomChar() };
        return str.Split(splitchar);
    }

    public string[] M3(string str)
    {
        //data is statically known: may be lifted to static field
        static var splitchar = new [] { '.' };
        return str.Split(splitchar);
    }

    public string[] M4(string str)
    {
        //lifts to non-readonly instance field, but makes next line illegal
        static readonly var splitchar = new [] { External.GetRandomChar() };
        splitchar = new [] { External.GetRandomChar() }; //ERROR
        return str.Split(splitchar);
    }
    
    private readonly ICharGenerator _generator;
    
    public C(ICharGenerator generator)
    {
        _generator = generator;
        //{A}
    }

    public string[] M5(string str)
    {
        //lifts to readonly instance field, assignment is placed in ctor on line marked with {A}
        static readonly var splitchar = new [] { _generator.GetRandomChar() };
        return str.Split(splitchar);
    }

    public string[] M6(string str)
    {
        //lifts to readonly field, potentially static, assignment is a field initializer
        static readonly var splitchar = new [] { ':' };
        return str.Split(splitchar);
    }
}
```
**Open question:** Syntax?

I'm not sold on what's proposed here. It seems to me like the variable is constantly re-assigned every time the method runs, which only makes it look like the very problem it's trying to solve.

Possible alternative:
```cs
public string[] M(string str)
    static var splitchar = new [] { External.GetRandomChar() }
{
    return str.Split(splitchar);
}
```
**Open question:** Are we married to the keyword `static`?

It would be symmetrical with VB.NET, but it may overload the `static` keyword too much for C#.  If someone new saw some code with this feature, it would be hard for them to Google what it means in that context since there's already 15+ years of documentation on `c# static keyword`. (VB doesn't have this problem since that uses `Shared` for static members and `Static` for specifically this feature.)

Continuing with the above suggested syntax alternative, a new keyword could be introduced instead.
* `cache`/`cached`
* `lifted`
* something else?

Bonus: Would allow to explicitly define instance/static scoping rather than hoping the compiler make the optimization *for* you.
```cs
public string[] M1(string str)
    cached var splitchar = new [] { External.GetRandomChar() } //instance field
{
    return str.Split(splitchar);
}

public string[] M2(string str)
    cached var splitchar = new [] { '.' } //force instance field, even if it could be static, IDE can suggest to make it static
{
    return str.Split(splitchar);
}

public string[] M3(string str)
    cached static var splitchar = new [] { External.GetRandomChar() } //force static field
{
    return str.Split(splitchar);
}

public string[] M4(string str)
    cached static var splitchar = new [] { _generator.GetRandomChar() }; //error CS0120
{
    return str.Split(splitchar);
}
```

**Comment by jnm2** [comment] 2017-08-20 14:35
I'd be happier with an `instance` contextual keyword. `void Foo() { static int scopedInstanceField... }` feels wrong to me.

**Comment by franzalex** [comment] 2017-08-20 15:27
In general, I think [@Joe4evr's suggestion](832#issuecomment-323586378) is in line with [mine](832#issuecomment-323556557) with the only difference being about the combination with the `readonly` modifier:

 > (Maybe) Combine with `readonly`: Can only assign once, but may be not an actual `readonly` field

Thinking it through once again, I can *possibly* see why we may want to allow combining with the `readonly` modifier. If that VB.NET restriction is not to be applied to the C# equivalent, however, I would like to know one thing:  

  _Does applying a `readonly` modifier cause the compiler to optimize the variable in any way?_

I feel like putting a `readonly` modifier on a variable whose scope is limited to a specific method is not really necessary. This is especially so since one cannot apply a `readonly` modifier to a variable created in a method. Should one want a `cached readonly`¹ variable, the person can go ahead to create a class-level variable that serves the purpose better as that modifier in its current state isn't allowed inside a method.

Note that I am not against allowing for a `cached readonly` field. I am only trying to let us have a more pointed discussion on this particular aspect before anything concrete is decided upon.

‾‾‾‾‾‾
 ¹ I prefer the `cached` keyword be used when instantiating such a variable as is being discussed in this thread.

**Comment by Joe4evr** [comment] 2017-08-20 16:23
> I feel like putting a `readonly` modifier on a variable whose scope is limited to a specific method is not really necessary. This is especially so since one cannot apply a `readonly` modifier to a variable created in a method.

It will be when #188 becomes a reality.

**Comment by franzalex** [comment] 2017-08-20 17:55
Sorry, I didn't know that such an idea had been proposed.
In that case, I think your suggestion can pass without need for any further
discussion.

**Comment by Thaina** [comment] 2017-08-24 05:11
Miss this since I was using PoC

**Comment by franzalex** [comment] 2017-08-24 07:30
@Joe4evr:

From a readability standpoint, I find your new syntax quite difficult to comprehend.
How do you suppose multiple static variables would be created? One per line? using a delimiter (which one)?
Most importantly, wouldn't your new syntax be too much of a breaking change?

I strongly believe that the way to go on this is to simply introduce a new keyword or adapt an existing one for use in this situation.
On 20/08/2017 13:54:01, Joe4evr <notifications@github.com> wrote:
Open question: would it make sense to generate a non-static field for a cached value?
Open question: would it worth it to use different keywords to specify a particular translation?
I would say the following:
* Lazy init pretty much always
* Always in a thread-safe manner
* In a static method: Lift to a static field
* In an instance method: Lift to an instance field
* Compiler is free to optimize to a static field if it can determine that all data written into the variable is static and wouldn't affect the rest of the program*
* (Maybe) Combine with readonly: Can only assign once, but may be not an actual readonly field
* Compiler should optimize to a real readonly field by lifting the assignment to either a field initializer, or (if dependent on other fields) into the constructor(s) (would become eager init)
*This rule could be omitted altogether with some alternative syntax I propose at the bottom of this post.
Examples:
public class C { public static string[] M1(string str) { //static method: lifts to static field static var splitchar = new [] { External.GetRandomChar() }; return str.Split(splitchar); } public string[] M2(string str) { //instance method: lifts to instance field static var splitchar = new [] { External.GetRandomChar() }; return str.Split(splitchar); } public string[] M3(string str) { //data is statically known: may be lifted to static field static var splitchar = new [] { '.' }; return str.Split(splitchar); } public string[] M4(string str) { //lifts to non-readonly instance field, but makes next line illegal static readonly var splitchar = new [] { External.GetRandomChar() }; splitchar = new [] { External.GetRandomChar() }; //ERROR return str.Split(splitchar); } private readonly ICharGenerator _generator; public C(ICharGenerator generator) { _generator = generator; //{A} } public string[] M5(string str) { //lifts to readonly instance field, assignment is placed in ctor on line marked with {A} static readonly var splitchar = new [] { _generator.GetRandomChar() }; return str.Split(splitchar); } public string[] M6(string str) { //lifts to readonly field, potentially static, assignment is a field initializer static readonly var splitchar = new [] { ':' }; return str.Split(splitchar); } }
Open question: Syntax?
I'm not sold on what's proposed here. It seems to me like the variable is constantly re-assigned every time the method runs, which only makes it look like the very problem it's trying to solve.
Possible alternative:
public string[] M(string str) static var splitchar = new [] { External.GetRandomChar() } { return str.Split(splitchar); }
Open question: Are we married to the keyword static?
It would be symmetrical with VB.NET, but it may overload the static keyword too much for C#. If someone new saw some code with this feature, it would be hard for them to Google what it means in that context since there's already 15+ years of documentation on c# static keyword. (VB doesn't have this problem since that uses Shared for static members and Static for specifically this feature.)
Continuing with the above suggested syntax alternative, a new keyword could be introduced instead.
* cache/cached
* lifted
* something else?
Bonus: Would allow to explicitly define instance/static scoping rather than hoping the compiler make the optimization for you.
public string[] M1(string str) cached var splitchar = new [] { External.GetRandomChar() } //instance field { return str.Split(splitchar); } public string[] M2(string str) cached var splitchar = new [] { '.' } //force instance field, even if it could be static, IDE can suggest to make it static { return str.Split(splitchar); } public string[] M3(string str) cached static var splitchar = new [] { External.GetRandomChar() } //force static field { return str.Split(splitchar); } public string[] M4(string str) cached static var splitchar = new [] { _generator.GetRandomChar() }; //error CS0120 { return str.Split(splitchar); }

**Comment by emeyers3** [comment] 2017-10-17 21:05
I would love to have this one in the language. The keyword should be "static". Here's the analogy. One can declare a class level "string foo;", and foo is available to the whole class. If "string foo;" is declared inside of a function, it is only accessible in the function. At the class level, one can declare "static string foo;"-- it is a static variable, but it is only accessible inside the class. In a function, you should be able to declare "static string foo;". It is statically scoped, but it can only be accessed from inside the function. 

This language tool is great for implementing singleton patterns. The Instance() function would declare "static MyClass _instance = new MyClass();" in the function itself and return it. This prevents others methods of the class from using _instance instead of Instance(). Statically typed variables are dangerous. Keeping all usage of a static method in one small function adds greatly to code clarity.

**Comment by scalablecory** [comment] 2017-10-27 22:50
I can see this replacing a lot of Lazy class usage, which would be nice.

**Comment by MkazemAkhgary** [comment] 2017-10-30 06:27
I suggest to change title of this proposal to "static initialization". 

the name "static variables" is misleading, and with [this comment  
](https://github.com/dotnet/csharplang/issues/832#issuecomment-323586378) which I'm really against it, some people got it really wrong. see #1051 that mentions it is exact duplicate. no its not. 

I liked this proposal but not the comments and the way discussion went through.

local and field variables have entirely different concept. they should not be mixed in single block.

**Comment by MkazemAkhgary** [comment] 2017-10-30 06:42
ok, as I read through, I apologize to author of [this comment](https://github.com/dotnet/csharplang/issues/832#issuecomment-323586378)

but you should make up your mind in comment, because comment is suggesting 3 different syntaxes. at least mention the significant update in first paragraph of your question so people like me don't get bothered 😸 

by the way last proposed syntax in that comment is not that bad, not good either, imagine how it would go with generic constraints 😮

**Comment by TheUnlocked** [comment] 2018-01-12 00:21
While I see the benefit of using `static` for caching, I believe that it certainly has uses beyond just caching values. I think that the very first example of static within a function should be added, though I don't necessarily oppose _also_ adding the in-line syntax.

**Comment by alrz** [comment] 2018-01-12 09:37
This is similar to local functions, you can bring static locals closer to their usage with a scoped name. I mentioned inline syntax to explore alternatives, that's not necessarily a "better" way to do this.

**Comment by miyu** [comment] 2018-07-07 03:11
Static locals are nice for declaring reusable (across calls) method-scoped variables that can't be consts.  
Here are some example use-cases:

1. Runtime-generated lookup tables for equations. These equations are completely meaningless and magical outside of their code context.

```
void HypotheticalFunction1(x) {
    // 10 LOC of stuff, introduces int y which hypothetically goes from [0, 10)

    // Nonoptimized:
    return SomeExpensiveFunction(y); // equation might even be in-line and depend on above statics

    // Optimized:
    static var lut = Range(0, 10).Map(SomeExpensiveFunction);
    return lut[y];
}
```

2. Reusing object instances (i.e. List<T>) across calls to avoid allocs (thread-local). 

```
void HypotheticalFunction2(x) {
    // Unoptimized
    var store = new List<T>();

    // Optimized
    [ThreadStatic] static List<T> storeTls;
    var store = storeTls ?? (storeTls = new List<T>()); // avoids per-call alloc

    // 20 LOC of work

    // Optimized
    store.Clear();
}
```

Imagine a class with 10 of the (2)-like functions. The scope gets polluted really quickly. To avoid naming conflicts, I name statics "HypotheticalFunction1_lut" or "tlsHypotheticalFunction2_store"... this is really gross. This is incredibly common for me - I'll have a function that allocates 10 collections of different types. I'll want to reuse 10 collections across calls. Guess what? Now I have 10 class-scoped statics. 😢


3. Workaround for inability to use const (i.e. with Fix64 from the fixed-precision arithmetic FixedMath.NET library).

```
Fix64 HypotheticalFunction3(x) {
    // 10 LOC of work

    static var weight = (Fix64)0.1; // currently can't be const, so computed each time
    static var weightSquared = weight * weight;
    static var invPi = (Fix64)(1.0 / Math.Pi);
    static var one = (Fix64)1;
    var temp = weightSquared * (one - F(x * invPi));

    // 10 LOC of work
}
```

My 3rd case would probably be better fixed with language support for constexpr functions. In any case, note how fluid changing from `var` to `static var` is. For this reason, I'm against forcing static locals to be placed immediately after the method signature. Note that in none of these use-cases is `static var` being used in a meaningfully stateful way.

**Comment by AustinBryan** [comment] 2018-08-16 21:01
@CyrusNajmabadi 

> You can just put them in nested static classes. :)

That's not nearly as simple and elegant as static local variables. I would much rather have to type a few characters than create a class, or do some other really weird workarounds that I have to wrap my brain around.

**Comment by CyrusNajmabadi** [comment] 2018-08-16 21:03
>  I would much rather have to type a few characters than create a class, or do some other really weird workarounds that I have to wrap my brain around.

It doesn't seem strange or weird, especially given the use case i was referring to.  When you have a collection of things that you want to group together, usign an existing language concept precisely created for that purpose seems natural and appropriate :)

**Comment by miyu** [comment] 2018-08-17 19:00
Nobody's arguing whether workarounds exist. There are many C# language features that could be (inelegantly) achieved with other language features + boilerplate. 

C# would be perfectly functional if local variable declarations were constrained to the top of a function. You'd just feel you were writing legacy code every time you declared a local variable. C#'s closures could also support a maximum of one captured local - you'd just have to declare your own heap-allocated closure object to store this + other locals, and each variable access would require lots of boilerplate to access a field in the closure object.

```csharp
environment.y = environment.@this.Compute(environment.x);
```

It's totally possible to work around C#'s lack of static locals by introducing a static class. It just feels like a non-intuitive and second-class workaround to C# lacking expressiveness. 

```csharp
void HypotheticalFunction2(x) {
    // Unoptimized
    var store = new List<T>();

    // Optimized
    var store = HypotheticalFunction2Statics.storeTls ?? (HypotheticalFunction2Statics.storeTls = new List<T>()); // avoids per-call alloc, holy crap boilerplate

    // 20 LOC of work

    // Optimized
    store.Clear();
}

static HypotheticalFunction2Statics {
    [ThreadStatic] static List<T> storeTls;
}
```

I don't think `HypothethicalFunction2` is a long method name. I don't think `HypotheticalFunction2Statics` is an unreasonable paired name. The LOC accessing HypotheticalFunction2Statics does so just twice and is already unreadable.

Beyond boilerplate, in this example we've also hoisted variable declarations further from their context of use, hurting readability and removing scoping protections. Given my common optimization use-case is for avoiding allocations, you can expect multiple allocations in many methods.

**Comment by CyrusNajmabadi** [comment] 2018-08-18 00:14
> Nobody's arguing whether workarounds exist. 

I guess i don't even view it as a workaround.  No more that i view a 'namespace' as a workaround when i have a collection of types i want to group together.  If i have a collection of data (and/or functionality) i want to group together, as per the post i was responding to, then a class seems like the *right* choice to make here.  It's exactly serving the purpose it was intended for and it's doing so in a manner that seems clear and simple to me.

> There are many C# language features that could be (inelegantly) achieved

I'm not sure how it's inelegant.  From a declaration standpoint it's just a few tokens.  It also gracefully gives scoping for when you have more than one entity you want to wall off.

**Comment by SilentSin** [comment] 2018-08-27 08:50
@CyrusNajmabadi Nested classes achieve lazy initialisation, but they can't control access. Kind of like how local functions can't be called by outsiders and are good for closures, local member variables can't be touched by outsiders and are good for lazy initialisation. A simple `if null then make new` check is enough for most lazy initialisation, but it's the ability to ensure that nothing else sees or messes with the variable that I'm really interested in.

Today I ran into a situation where this feature would have avoided a bunch of debugging time so it gets my upvote, but I'm unsure of why the `static` keyword was chosen when the feature would be plenty useful for instance variables as well. Why not use `private`?
```
private void Initialise()
{
    private bool isInitialised;

    if (isInitialised)
        return;

    isInitialised = true;

    // For simplicity, here's my entry into the "World's Most Contrived Examples" competition:
    private static List<Thing> thingsThatHaveBeenInitialised = new ...
    // Could even be readonly.

    thingsThatHaveBeenInitialised.Add(this);

    // No different from a regular local const, but allowed for consistency.
    private const float SomeValue = 42;
}
```
This is also great for refactoring since you can just move the variable in/out of the method without changing any syntax or meanings of any keywords.

Thinking of it as an access modifier, I can see potential for `protected` as well:
```
// Base Class:
protected virtual void Initialise()
{
    protected bool isInitialised;
    // stuff
}
// Child Class:
protected override void Initialise()
{
    if (base.isInitialised)
        return;

    base.Initialise();
}
```
Even `public` and `internal` could work, allowing other methods to access `Initialise.isInitialised` while keeping it plainly obvious that the variable is primarily used by that method. `private` would be by far the most useful though.

**Comment by PathogenDavid** [comment] 2018-08-27 11:56
> I'm unsure of why the `static` keyword was chosen when the feature would be plenty useful for instance variables as well. Why not use `private`?

`static` is the keyword C++ and VB.NET use.

`static` has its own problems, but I don't think `private` (or other access modifiers) are a good choice either. They don't properly convey that the variable is persistent between calls to the enclosing method.

**Comment by SilentSin** [comment] 2018-08-27 12:57
> static is the keyword C++ and VB.NET use.

Do they let you differentiate between instance and _static_ variables though?

> static has its own problems, but I don't think private (or other access modifiers) are a good choice either. They don't properly convey that the variable is persistent between calls to the enclosing method.

I can see your argument (that the scope indicates a member variable, not the private keyword), but I can't think of any other options that would be better (unless the feature is restricted to only statics). A new keyword could obviously work, but they don't particularly like adding new ones, and what would it be? member? cache? store? first? init? once? lazy?

**Comment by PathogenDavid** [comment] 2018-08-27 20:48
>Do they let you differentiate between instance and static variables though?

In C++ [they are not per-instance](https://gist.github.com/PathogenDavid/59a1fc2e0f9415ab30b45c4b6f7a11c9). In VB.NET [they are per-instance](https://gist.github.com/PathogenDavid/be4f7453185caf3fb117ca3c412b6f6c). In the case of both, you can't opt in to the other behavior as far as I am aware.

In the case of VB.NET, it helps that they used `Shared` for what C# calls `static`. The `Static` keyword only applies to variables within a method that don't change between invocations of that method on a per-instance basis.

> Keywords

IMO a new keyword is probably best if this feature is incorporated. I don't have a strong suggestion for what they keyword would be though. Although my gut reaction is that `once` sounds like it could be reasonable.

**Comment by TheUnlocked** [comment] 2018-08-27 22:18
I think `static` makes intuitive sense, especially if you think of `static` as "statically (rather than dynamically) tied to its enclosing thing." A static method or variable is tied to its class rather than an instance and a static local variable would be tied to its method rather than a particular call.

Static classes would be a bit weird in this sense I admit, but that usage of the keyword doesn't make a huge amount of sense as things are now either. I don't think any clarity is lost by using the keyword `static` and therefore I don't think making people remember a new keyword would be of any benefit.

**Comment by TheUnlocked** [comment] 2018-08-27 22:31
@CyrusNajmabadi The way to justify that is to say that `C<bool>` and `C<string>` are actually different classes instanced from a single class definition. I could be wrong but I don't think that there are any instances is which using `C` by itself is legal without having another class definition called `C` without the generics.

**Comment by SilentSin** [comment] 2018-08-27 23:45
> I think static makes intuitive sense, especially if you think of static as "statically (rather than dynamically) tied to its enclosing thing."

The problem is that for something to be intuitive it can't rely on "if you think of it like this ...". I don't think anyone has ever seen the word `static` and intuitively assumed that definition. For me and everyone else I've seen learning to code, the reaction to having `static` explained was basically "oh, so it doesn't actually mean that the thing can't be changed".

The meaning that "there is only one of this thing which isn't tied to a specific instance" easily covers all existing uses of the keyword as well as the _word_ in general (such as BindingFlags.Static vs BindingFlags.Instance or MethodInfo.IsStatic). But even if that original definition were intuitive, it certainly doesn't cover "there is one of these for every instance of the class, but it gets remembered between method calls".

You _could_ use your explanation to justify the way it works, but it would always be an excuse, never simply a clarification of the exact way in which a word intuitively works. For example:

- Q: "what's const?" A: "it's short for constant" - and you're already 90% of the way there.
- Q: "how's readonly different from const?" A: "it can only be set in a constructor rather than needing to be fixed in compile time" - also pretty good.
- Q: "how's static different from const?" A: "_Despite what the word implies_, a static variable can be changed normally, the keyword just means that it isn't tied to an instance of the class so you access it via ClassName.Variable similar to a constant. It also has a similar effect when used on methods/properties/classes. But it can also be used on variables inside a method body where it can make a local variable either behave like a static member variable (good so far) or behave like an instance member variable (is this a joke?) depending on whether the method is static or not."

**Comment by YairHalberstadt** [comment] 2018-09-26 17:53
How about `field` keyword, which can be modified by specifying `static` and or `readonly`

Eg:

```csharp
string[] M(string str) {
  static readonly field var dot = new [] { '.' };
  return str.Split(dot);
}
```

**Comment by jrmoreno1** [comment] 2018-10-03 20:11
Perl uses the keyword state, which nicely encapsulates the idea, but it would be a new keyword.   Coming from a C/VB background, I find the keyword static to be clear, and don't see any real source for confusion.  For an instance method, it's persists across invocations of the method in that instance, for a static method, it persists across invocations of the method on the static class.

**Comment by HaloFour** [comment] 2018-10-03 20:28
@jrmoreno1 

> For an instance method, it's persists across invocations of the method in that instance, for a static method, it persists across invocations of the method on the static class.

That policy is a potential source of confusion, and differs from `static` variables in C++ where they persist across the entire program regardless of whether they are defined in an instance method.

**Comment by TheUnlocked** [comment] 2018-10-04 01:05
I don't think that this would actually be as confusing as you might think it would be. Static already means something slightly different in pretty much every different context as is. People wouldn't expect static to work exactly the same way here as it does in other places because the keyword already has a record of inconsistency. They'd likely google what static does when used with a local variable, arrange that in their mental map of how C# works, and then be able to continue understanding whatever code they're reading. This usage of static wouldn't be exactly the same as any other way static is used, but it wouldn't be so different as to cause insurmountable confusion.

**Comment by jrmoreno1** [comment] 2018-10-04 11:10
@SilentSin: took me a minute to understand what you meant, I’ve never thought of needing both per instance and per program local variables for the same method. I can’t say I think it would worth a lot of extra work to get that flexibility.

@HaloFour: I would want to duplicate VB’s behavior in regards to threads and concurrency, yes it introduces more work for both the compiler devs and the program, and results in things happening behind the scenes, but it’s the pit of success that way.

**Comment by jrmoreno1** [comment] 2018-10-04 19:09
One additional comment, I know that every new feature starts at -100, so here's the benefit in adding it: it's a fairly popular VB feature, supporting it would make migrating from VB to C# easier. IMO in the not too distant future a lot of people are going to want do just that.

**Comment by xahon** [comment] 2019-04-02 15:26
Not only static, but instance variables could be good too. Like local functions to reduce visibility in class

**Comment by jrmoreno1** [comment] 2019-07-30 10:43
@xahon : this proposal is to duplicate vb’s static keyword, which creates a backing field in the class, that field is either an instance field or not, depending upon whether the single method/property that can use it is a instance method or not.

**Comment by mikernet** [comment] 2019-12-07 21:02
I think if this is going to be done then there should be a mechanism to allow you to define local instance fields as well as local static fields, which the `field` keyword syntax proposed above allows for. There are many situations where I want a local static field inside an instance method.

**Comment by jrmoreno1** [comment] 2019-12-08 16:26
I’m not clear on what you mean by local static field / local instance field.  

Not proposing this syntax, but are you saying you feel the need for

     public string Counter()
     {
          static static int calledSinceAppDomain ;
          static static int instances ;
          static int inThisInstance;
           if (inThisInstance ==0)   instances++;
          calledSinceAppDomain++;
          inThisInstance++;
          return $"This method called {calledSinceAppDomain} by {instances} individual classes since starting up the application and {inThisInstance} times for this specific instance of the class”;

      }

**Comment by mikernet** [comment] 2019-12-08 19:48
@jrmoreno1 No, I'm referring to the syntax proposed here or similar: https://github.com/dotnet/csharplang/issues/832#issuecomment-424810247

So that inside an instance method you can either do `field int fieldName` or `static field int fieldName` depending on whether it should be an instance field or a static field.

**Closed** 2020-09-08 21:45 UTC
Labels: Discussion, Feature Request, Move to Discussion
