### ISSUE TITLE
[Proposal] Postfix await operator

### ISSUE THREAD

**Issue by Timo-Weike** [dotnet/csharplang#3757] opened 2020-07-30 14:05 UTC
# Postfix await operator

- [x]  Proposed
- [ ]  Prototype: [Not Started]
- [ ]  Implementation: [Not Started]
- [ ]  Specification: [Not Started]

# Summary

If we have for examlple the following types
~~~ cs
public struct ResType { }

interface A
{
    Task<B> SomeAsync();
}
interface B
{
    Task<C> GetStuffAsync();
}
interface C
{
    Task<ResType> GetMoreStuffAsync();
}
~~~ 
and have an object of type `A` and want to get the result of `GetMoreStuffAsync` we currently can either do
~~~ cs
var res = await (await (await someA.SomeAsync()).GetStuffAsync()).GetMoreStuffAsync();
~~~
or
~~~ cs
var res = await someA.SomeAsync()
    .ContinueWith(t =>
        t.Result.GetStuffAsync()
    )
    .Unwrap()
    .ContinueWith(async t =>
        await t.Result.GetMoreStuffAsync()
    )
    .Unwrap();
~~~
both of which can become quiet ugly and hard to maintain.

That is the reason for proposing a new postfix operator, a little bit like `?.`.

It could for example by `~.`.
The semantik would be, for `t~.member` where `t` is a `Task<T>` the operator would await the task `t` and if it finishes successfully would do the member access on the result value of the task `t`.

The above example could then be written as
~~~ cs
var res = await someAObject.SomeAsync()
    ~.GetStuffAsync()
    ~.GetMoreStuffAsync();
~~~ 

# Motivation

 - hard to maintain syntax for caining call into the return value of a `Task<T>` 

# Detailed design

An expression like `var x = await a~.b~.c~.d;` would simpliy compiled to 
~~~
var x = await (await (await (await a).b).c).d
~~~

but it probably should work together with `?.` to form expressions like
~~~
var x = await a?~.b?~.c;
~~~
which probably should be compiled to
~~~
var x = await ((Func<Task<ReturnType>>)(async () =>
{
    var x1 = await a;
    if (x1 == null) return default;
    var x2 = await x1.b;
    if (x2 == null) return default;
    return await x2.c;
}))();
~~~

and a mixed expression like `var x = await a?~.b~.c;` could be compiled to 
~~~
var x = await ((Func<Task<ReturnType>>)(async () =>
{
    var x1 = await a;
    if (x1 == null)
        return default;
    var x2 = await x1.b;
    return await x2.c;
}))();
~~~

so the `?` in `?~.` would simply mean add a `if (tempName == null) return default;` to the delegate.

**Comment by YairHalberstadt** [comment] 2020-07-30 14:09
I would prefer rusts `.await`. `await` is already a keyword inside async methods so this should work fine.

**Comment by HaloFour** [comment] 2020-07-30 14:09
I don't like the idea of it being a single character.  `~` doesn't convey anything and would easily blend into an expression without being obvious.

IMO if the team was going to consider a postfix operator I'd rather it still be `await`, but in dotted form:

```cs
var result = someA.SomeAsync().await.GetStuffAsync().await.GetMoreStuffAsync();
```

**Comment by canton7** [comment] 2020-07-30 14:15
Duplicate of #35 (not the headline, but read the discussion)

**Comment by benaadams** [comment] 2020-07-30 14:15
See also https://github.com/dotnet/csharplang/issues/1117

**Comment by 333fred** [comment] 2020-07-30 14:52
Seems like a duplicate of #1117 to me. I'm going to close this.

**Closed by 333fred** 2020-07-30 14:52 UTC
