### ISSUE TITLE
[Proposal]: Allow use of return, break and continue with the null-coalescing operator (??)

### ISSUE THREAD

**Issue by H4xX0r1337** [dotnet/csharplang#4541] opened 2021-03-16 12:50 UTC
# Allow use of return, break and continue with the null-coalescing operator (??)

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
The null-coalescing operator ?? allows throwing exceptions. I propose extending this feature to also support returning from a method and breaking and continuing from loops.

## Motivation
Currently, only return is allowed. Also allowing the other keywords would make the language more consistent. 
That would also allow more compact early returns in methods or loops with less boilerplate.

## Example
IMHO, this way to read a file line-by-line would be the cleanest one.
```cs
using var reader = File.OpenText("path/to/file.txt");
while (true)
{
    var line = reader.ReadLine() ?? break; //exit loop if no line is available.
    Console.WriteLine(line);
}
```

**Comment by HaloFour** [comment] 2021-03-16 12:54
See: https://github.com/dotnet/csharplang/issues/867

**Comment by svick** [comment] 2021-03-16 14:10
Closing as a duplicate of https://github.com/dotnet/csharplang/issues/867.

**Closed by svick** 2021-03-16 14:10 UTC
