### ISSUE TITLE
Discussion: internal aliases

### ISSUE THREAD

**Issue by alrz** [dotnet/csharplang#259] opened 2017-03-13 08:15 UTC
Ported from https://github.com/dotnet/roslyn/issues/7451.

While using-alias-directive "introduces an identifier that serves as an alias for a namespace or type within the immediately enclosing compilation unit or namespace body", internal aliases can be referenced anywhere within a program.
```cs
internal using StringMap = Dictionary<string , string>;
```
- Internal aliases will be erased during compile-time and will be replaced with the underlying type.
- Internal aliases are totally equivalent to the underlying type but, for example, IntelliSense could be extended to suggest only extension methods on the specific type alias.
- Internal aliases (along with file-scoped aliases) could also support generics (https://github.com/dotnet/csharplang/issues/90),

```cs
internal using Map<T> = Dictionary<string , T>;
```

Alternatively we could use `alias` or `type`, since `internal` carries some implications:
-  `InternalsVisibleTo` should work with internal aliases but it won't.
-  `internal` is "the default" modifier in a global or namespace context.

However, with CLR support we could extend the set of allowed modifiers for a type alias in the future.

EDIT: Following `using static` perhaps `using internal` is a better choice here.

**Comment by HaloFour** [comment] 2017-03-13 13:29
So just to be clear, I could add a source file with the following contents:

```cs
namespace Foo {
    internal using Map<T> = System.Collections.Generic.Dictionary<string, T>;
}
```

And have some other source file with the following contents:

```cs
using Foo;

namespace Bar {
    static class Program {
        static void Main() {
            var map = new Map<int>();
            if (map is Dictionary<string, int>) Console.WriteLine("yay!");
        }
    }
}
```

And the compiler will resolve the `Foo.Map<T>` alias "pseudotype" to the actual type `System.Collections.Generic.Dictionary<string, T>`?

Also note that I used the fully-qualified type name to define the "alias" `Map<T>` as currently that is a requirement.  You don't appear to be proposing to change that.

**Comment by jnm2** [comment] 2017-03-13 13:43
Whatever we do here, I hope we don't block a future CLR improvement where I can declare a runtime type alias, enabling me to change the name of a type without breaking source or binary compatibility.

**Comment by alrz** [comment] 2017-03-13 13:44
@HaloFour 

>Also note that I used the fully-qualified type name to define the "alias" Map<T> as currently that is a requirement. You don't appear to be proposing to change that.

Here's the context.

```cs
using System.Collections.Generic;
namespace Foo {
    internal using Map<T> = Dictionary<string, T>;
}
```

To make that work in the same level, RHS should consider preceding using directives,
```cs
using System.Collections.Generic;
internal using Map<T> = Dictionary<string, T>;
````
Which might be a breaking change.

**Comment by alrz** [comment] 2017-03-13 13:47
@jnm2

>Whatever we do here, I hope we don't block a future CLR improvement where I can declare a runtime type alias, enabling me to change the name of a type without breaking source or binary compatibility.

Once CLR support this, we can extend the set of allowed modifiers to `public` and you'd get that in result.

**Comment by HaloFour** [comment] 2017-03-13 15:30
@alrz 

IIRC, currently the compiler requires fully-qualified type names in aliases in order to avoid potential circular references.  How would you propose avoiding that issue with "internal aliases"?

**Comment by alrz** [comment] 2017-03-13 15:36
Could you give an example? Supposedly the compiler can detect such conditions as it does for base class or struct member types.

**Comment by gulshan** [comment] 2017-03-20 07:20
I think rather than redefining what `using` does, a new `typealias` or `typedef` or simply `type` should be use for this aliasing. And the full qualified name should not be required. And then this should have option to be `public`, usable from outside of the assembly.

**Comment by playsomethingsaxman** [comment] 2017-03-24 22:05
> Whatever we do here, I hope we don't block a future CLR improvement where I can declare a runtime type alias, enabling me to change the name of a type without breaking source or binary compatibility.

[https://msdn.microsoft.com/en-us/library/ms404275%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396](url)

**Comment by jnm2** [comment] 2017-03-24 22:50
@playsomethingsaxman That allows moving a type between assemblies, which I have done, but there is no facility to typeforward a name change or namespace change.

**Comment by scottdorman** [comment] 2017-04-05 23:58
> EDIT: Following `using static` perhaps `using internal` is a better choice here.

Wouldn't `using alias` actually be better? It's clearer that you're creating a type alias and doesn't carry forward the other implications that `internal` has (as you already pointed out).

**Comment by gulshan** [comment] 2017-04-06 03:04
I think type parameters and user defined access modifiers look better with explicit aliasing syntax using some new keyword like `typealias`-

```csharp
public typealias StringKeyDictionary<T> = Dictionary<string, T>;
```

And `using` can remain scoped to files. If we prefer to introduce a keyword which can be used for other types of type definition, `typedef` of just `type` can be used, as I have already suggested.

**Comment by Jehoel** [comment] 2017-06-05 23:48
I'd like this to have an additional `strict` modifier that declares a type-alias as have the same binary/object representation, but that it represents an incompatible value as far as business-rules are concerned - for example, this would help prevent mixing identity-types in database systems (which tend to all be `Int32`), for example:

    using strict CustomerId = Int32;
    using strict OrderId = Int32;

    #region ORM/scaffold-generated code for business entities:
    class Order {
        public OrderId Id { get; set; }
        // ...
    }

    class Customer {
        public CustomerId Id { get; set; }
    }
    #endregion

    // This code would introduce a compile error:
    Customer customer = orm.GetCustomer( 123 );
    Order order = orm.GetOrder( orderId: 456 );
    customer.Id = order.Id; // CustomerId and OrderId are not assignable
    // or:
    Order order = orm.GetOrder( customer.Id ); // `CustomerId` values cannot be used as arguments for `OrderId` parameters.

**Comment by osdm** [comment] 2018-07-15 19:06
How about allowing this inside generic classes? For example:

    public class MyOneToListMap<TKey, TValue>
    {
        private using TValueList = List<TValue>;
        private using TDictionary = Dictionary<TKey, TValueList>;
        private readonly TDictionary dictionary = new TDictionary();
    }

**Comment by pongba** [comment] 2018-11-03 19:55
> Whatever we do here, I hope we don't block a future CLR improvement where I can declare a runtime type alias, enabling me to change the name of a type without breaking source or binary compatibility.

Agreed, exactly what I need

**Comment by johnkellyoxford** [comment] 2019-03-20 17:49
You could emit metadata into the assembly, some sort of attribute which defines the aliases (type, string). Then `InternalsVisibleTo` could work, right?

**Comment by wfowler1** [comment] 2019-03-25 20:17
I believe this is related to my situation. I use a lot of preprocessor definitions in my projects to conditionally compile aliases into my code. For example, if I have a piece of code designed for use in .NET standalone as well as Unity3D engine:

```
class MyClass
{
#if UNITY3D
	using Vector3 = UnityEngine.Vector3;
#else
	using Vector3 = System.Numerics.Vector3;
#endif
	// ...
}
```
Currently this snippet needs to be copied across every file that needs to use a Vector3 instance. What I'd really like is to be able to declare an alias like this across an entire namespace. Since as far as I know I don't have control over the assembly metadata Unity3D produces, this is currently the best way to do this.

**Comment by johnkellyoxford** [comment] 2019-03-25 20:23
A complete rework of using aliases would be nice:

* Allow them to be used across an assembly

* Store them as metadata so they can be used from other assemblies optionally, and can be decompiled properly 

* Allow using C# primitive aliases like `int`

* Allow using pointers

* Allow using `ref`s?? Maybe

**Comment by CyrusNajmabadi** [comment] 2019-03-25 21:27
@wfowler1 You could define your own struct that conditionally wraps either of these.  Then just reference your struct everywhere.

**Comment by Jehoel** [comment] 2019-03-26 00:11
@CyrusNajmabadi That would not be very ergonomic. C# doesn't support struct inheritance (so we can't do `struct MyVector3 : #if UNITY UnityEngine.Vector3 #else Numerics.Vector3`) and wrapping it as a member means having to update every usage to add the member - not to mention that may result in inefficient code if the JIT doesn't inline it all. There are also issues with having mutable structs if you want to reassign that member.

**Comment by wfowler1** [comment] 2019-03-26 00:39
Yes, the reasons @Jehoel cited make me shy away from that approach. Even using an approach which masks the issue by using implicit conversions is an ugly way to do things.

**Comment by CyrusNajmabadi** [comment] 2019-03-26 02:21
THe jit should have no problems with any of that.  This is an exceedingly common pattern, and is precisely how you can have a zero-overhead abstraction over other types (useful when you want to hide functionality or add new functionality).

**Comment by johnkellyoxford** [comment] 2019-03-26 07:32
@Jehoel

> while the CLR's memory layout of value-types is not well documented (by design)

Yes, but given the fact the struct stores no other data, there is no reason for the CLR to make it any larger. It doesn't just add padding for fun

**Comment by faldor20** [comment] 2019-12-23 05:19
Any idea if any progress is going to be made on this? It would seem very simple to implement this as just replacing what you wrote with the full type name during compilation. Just like a #define works in c or c++.

**Comment by CyrusNajmabadi** [comment] 2019-12-23 20:48
> Any idea if any progress is going to be made on this?

There is currently no champion for this item, so the ldm is not prioritizing this in any way. 

> It would seem very simple to implement this as just replacing what you wrote with the full type name during compilation.

It's definitely not that simple :-)

**Comment by alrz** [comment] 2019-12-23 21:11
Some things to consider in this space:

- generic type aliases 
- primitive type aliases (int, tuples, function pointers, etc)
- internal namespace aliases

There are already proposals for the first two, but I think this is a better place to invest instead of extending `using` directive.

For namespaces this would be really impactful for layered applications, e.g. in a web app you may have a domain model, api model and business model all with the same name. Using extern alias for each is even less convinient than repeating `using` on top of each file which still sounds like a workaround and at the end it's really hard to manage all of those and keep them in sync.


F# already supports this (I think only for types) and it's speced that these won't be accessible from outside of the assembly and that haven't been much of a problem so far.

I suspect one reason for this to not get prioritized is that there's no immediate usecase in roslyn or corefx, but it's an absolute necessity in other kinds of applications.

**Comment by gulshan** [comment] 2019-12-24 02:15
So proposals useful for Roslyn or CoreFx are prioritized? Maybe that's natural.

**Comment by YairHalberstadt** [comment] 2019-12-24 05:07
@gulshan 
Without a customer within Microsoft it's very difficult to thrash out the problem domain, and work out what is actually sufficient to solve the problem. Otherwise you're creating features and hoping that they solve the problems people are having, but not finding out till after they're already released.

**Comment by 333fred** [comment] 2019-12-25 17:08
> I suspect one reason for this to not get prioritized is that there's no immediate usecase in roslyn or corefx, but it's an absolute necessity in other kinds of applications.

I don't think this is true. Rather, I think that internal-only aliases is the approach we want to take. For example, are these a compile-time only construct? If so, what happens to assemblies with IVT? The only logical answer is that they see the original type, not the alias. And if it's not a compile-time only construct, and somehow encoded in metadata, then it would be sad if you couldn't use these in a public interface. But then we have the question of whether aliases are identity-convertible to their underlying type. You might want that for a simple alias of a complicated generic type, but if you were creating a units library, for example, you might want your miles alias to not be identity-convertible in your kilometers alias. Plus, a metadata encoding would likely want runtime support, particularly for the opaque version. So, I don't think that the problem is not something that we want to solve. Rather, I think that we haven't found a proposal yet that we like, and no one on the ldt has sat down to make one either.

**Comment by alrz** [comment] 2019-12-29 17:22
FWIW I think the introduction of DUs would make another use case for global aliases, for instance you may have a generic Result<T, E> and you'd want to define aliases for each kind of error:

`type ServiceResult<T> = Result<T, ServiceError>`

I think that is how all Rust's result types are defined.

**Comment by jukkahyv** [comment] 2019-12-30 11:29
This has been my personal favorite feature request for a while. It would increase our team's productivity significantly, and we can't be the only ones. I already explained our case at Build Developer Day, but let me post it there too.

Our system has many, many entities (over 200). It's common that their IDs are passed around as plain integers. There's been many cases where developer mixes IDs of different, similar sounding entities, let's say UserContact and UserConfig. So I got an idea to make strongly typed IDs for entities, to avoid mixing them. It's implemented as struct EntityID<TEntity>, for example EntityID<UserContact>. But writing EntityID<UserContact> everywhere is tedious, so we would like to have a type UserContactID that is compatible with EntityID<UserContact>. Obviously structs cannot be inherited, but even with classes, UserContactID and EntityID<UserContact> would be two different types: I cannot have a method that expects UserContactID and is given EntityID<UserContact> as parameter, even though these types are identical. I could work around this with implicit casts, but it's hacky at best, and doesn't work nearly everywhere (what if I have a collection of UserContactIDs?). Many other languages such as C++ have type aliases which would solve this use case. From what I remember from my C++ days, typedef was exactly what would be needed here. It seems simple, but I understand there are corner cases. Ideally we would want these to be public so that they can be shared between assemblies, but even internal aliases would be a big help.

**Comment by gulshan** [comment] 2019-12-30 17:28
@jukkahyv Let me just put a plug for my proposal #3046 here, which could be helpful for your specific case. It purposes to have generic types defined as `T.EntityId<T>` and then use as `UserContact.EntityId` (or shorter- define as `T.Id<T>`, use as `UserContact.Id`).

**Comment by Happypig375** [comment] 2019-12-30 17:29
Plugging an already negatively-reviewed proposal probably isn't a good idea.

**Comment by jukkahyv** [comment] 2019-12-30 18:08
Actually, I forgot to mention one big point. By making it a single name (like UserContactId), it can be autocompleted with intellisense much faster than generic type + parameter. It sounds like a small thing, and it is, until you realize you're doing it 10 or 50 times per day.

**Comment by Happypig375** [comment] 2019-12-30 18:10
And here I use F# type inference every day. 😃

**Comment by demensh** [comment] 2020-01-15 00:32
Imagine C# had aliases allowing this:
```csharp
public abstract class Base
{
  public abstract alias Inner<T>;
}

public Generic<T> {}
public Impl : Base
{
  public override alias Inner<T> = Generic<T>;
}
```
Then HKT would become unnecessary as you could be able to emulate them using this technique:
```csharp
H<T> F<H<>, T>(H<T> h) => h;
```
becomes
```csharp
class H
{
  public abstract alias Inner<T>;
}
G.Inner<T> F<G, T>(G.Inner<T> h) where G : H => h;
```

**Comment by VBAndCs** [comment] 2020-03-25 13:55
This will be more powerful if also allows generic aliases #3309.

**Comment by ChayimFriedman2** [comment] 2020-07-17 09:42
@Jehoel 

I greatly agree with your suggestion, but I think it's subject for a different proposal.

I would define `internal using` (or `using internal`) as C++'s `typedef`: type alias - shorten a type name.

For your proposal, I would suggest `type T = `, as you're creating a new type.

Also, this proposal don't require CLR changes (although can benefit from them) - even public aliases could be exposed as attributes, as already pointed out. But your proposal **requires** CLR changes, because otherwise the following code will result in wrong:
```c#
type MyType = int;

// ...

object o = new MyType(5);
if (o is int)
{
    Console.WriteLine("Oops, they should be different types.");
}
```

Although now it's crossing my mind that it can be implemented by the compiler by new struct containing the type, and re-exposing all of its public members:

```c#
struct MyType
{
    int _Field;
    // All int members
}
```

This **would** have an overhead, but since the JIT will optimize this away this should be fine.

**Closed** 2020-09-08 19:44 UTC
Labels: Discussion, Feature Request, Move to Discussion
