### ISSUE TITLE
New assignment operator: =.

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/csharplang#623] opened 2017-05-25 13:58 UTC
I've thought of a new assignment operator, the `=.` one.

What this operator does is assign the result of an extension function affecting that object. Here is an example:

```csharp
string eg = "This is an example string.";
eg=.Substring(5, 2);
// Equal to eg = eg.Substring(5, 2);
```

I hope you like this idea.

**Comment by jnm2** [comment] 2017-05-25 14:00
Pretty much a dupe of https://github.com/dotnet/csharplang/issues/500?

**Comment by janjoostvanzon** [comment] 2017-05-25 14:04
You beat me jnm2. I couldn't find it fast enough.

**Comment by AlFasGD** [comment] 2017-05-25 14:11
Sorry, didn't check if it exists... Gonna remove that post.

**Comment by jcouv** [comment] 2017-09-02 05:31
Closing as this is indeed a duplicate of #500.

**Closed by jcouv** 2017-09-02 05:31 UTC
