### ISSUE TITLE
[Proposal]: record-like constructor syntax for classes

### ISSUE THREAD

**Issue by wizofaus** [dotnet/csharplang#4602] opened 2021-03-29 09:57 UTC
I have quite a number of classes in my codebase that essentially look like:

    class Foo /* : IFoo */
    {
        public Foo(Bar bar, WidgetService service, ILogger logger)
        {
            this.bar = bar;
            this.service = service;
            this.logger = logger;
        }
 
        /* public functions etc. */
     
        readonly Bar bar;
        readonly WidgetService service;
        readonly Logger logger;
    }

Essentially the class has no state of its own and all dependencies are passed into the constructor.  But that means quite a lot of boilerplate code.  It can be removed by changing it to a record:

    record Foo(Bar bar, WidgetService service, ILogger logger)
    {  
        /* public functions etc. */
    }

And I do like how clean it looks - but at the expense of the fact that what were private fields are now public (but still read-only) properties, and that whatever Foo might actually be, a "Record" is a poor description of it.

So is there any way I can achieve similarly clean code free of boilerplate but keep it as a class with private/internal fields?  If not, could there be a reason C# doesn't support this?

**Comment by Phantonia** [comment] 2021-03-29 10:34
See #2691

**Comment by 333fred** [comment] 2021-03-29 15:01
Closing as a duplicate of #2691.

**Closed by 333fred** 2021-03-29 15:01 UTC
