### ISSUE TITLE
Index in foreach loop

### ISSUE THREAD

**Issue by RezaGhochkhani** [dotnet/csharplang#3237] opened 2020-02-28 10:35 UTC
Most often when we use the foreach loop, we need an index just like we have in the for loop. What we do most of the time is to define an index variable and increment it manually. But this does not need to be the case. 
if a keyword "index" is defined in the foreach loop that gets incremented automatically when the loop iterates, we can just use the index for accessing data structures that need index like an array. 
the index will be reset when the loop exits. 
I think this is quite a simple, non-breaking change and it can make the use of foreach loop a little easier.

**Comment by TonyValenti** [comment] 2020-02-28 11:12
I use a withIndex extension method that yields a class with an index and the original value

**Comment by DavidArno** [comment] 2020-02-28 13:41
Duplicate of #1584

**Comment by theunrepentantgeek** [comment] 2020-02-29 00:11
> Most often when we use the foreach loop, we need an index just like we have in the for loop.

I think your base assumption may be incorrect. It's certainly my experience that **foreach** loops that require an index are exceptionally rare.

Also, given that there are multiple simple approaches that can be easily used, I'd question the value of making the change _even if it was common_. It's far more valuable for the LDM to focus on making _hard things easy_ vs _easy things trivial_.

**Comment by theunrepentantgeek** [comment] 2020-04-25 04:54
Since this is a duplicate, I think it should be closed.

**Comment by 333fred** [comment] 2020-04-25 06:46
Closing as a duplicate.

**Closed by 333fred** 2020-04-25 06:46 UTC
