### ISSUE TITLE
Proposal: Allow $"" string interpolation for Attributes

### ISSUE THREAD

**Issue by neurospeech** [dotnet/csharplang#489] opened 2017-04-22 18:48 UTC
Usage:
Consider class customer in Entity Framework where it will be easier to declare attributes with name of class.
     
```C#
       [Table($"{nameof(Customer)}s")]
       public class Customer{

           [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
           public long CustomerID { get;set; }

           [Index($"IX_{nameof(Customer)}_{nameof(City)}")]
           public string City {get;set;}

       }

```

**Comment by jnm2** [comment] 2017-04-22 18:51
Dupe of https://github.com/dotnet/csharplang/issues/369 and https://github.com/dotnet/csharplang/issues/384

**Closed** 2020-09-08 20:15 UTC
Labels: Discussion, Feature Request, Move to Discussion
