### ISSUE TITLE
[suggestion] Ignore new keyword

### ISSUE THREAD

**Issue by surfsky** [dotnet/csharplang#3497] opened 2020-05-26 05:16 UTC
Allow Ignoring new keyword, and allow use : to replace =, more like dart and json

``` csharp
var t = Rectangle(Width: 10, Height: 20);

```

**Comment by yaakov-h** [comment] 2020-05-26 05:20
Dropping the `new` keyword is a duplicate of #350. C# 9.0 is actually doing the opposite with target-typed new (#100), so it is very unlikely that this will ever be accepted.

**Comment by surfsky** [comment] 2020-05-26 05:47
look at flutter code, Drop new keyword, It's awesome and much more clear:

``` dart
class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    final wordPair = new WordPair.random();
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(title: Text('Welcome to Flutter')),
        body: Center(child: Text(wordPair.asPascalCase)),
      ),
    );
  }
}
```

**Comment by yaakov-h** [comment] 2020-05-26 06:07
I still see the keyword word `new` in there...

**Comment by 333fred** [comment] 2020-05-26 06:43
Closing as a duplicate of #350.

**Closed by 333fred** 2020-05-26 06:43 UTC
