### ISSUE TITLE
[Proposal] fast return with ?? operator

### ISSUE THREAD

**Issue by tester346** [dotnet/csharplang#2524] opened 2019-05-14 10:13 UTC
Hi, I'd want to hear opinion about allowing something like that:

This one is currently possible

	[HttpGet]
	public async Task<IActionResult> DoSomething(Guid id)
	{
	    var user = GetUser(id) ?? throw new Exception("text");
	}

but this isn't

	[HttpGet]
	public async Task<IActionResult> DoSomething(Guid id)
	{
	    var user = GetUser(id) ?? return Json(new { error = "User not found"});
	}

I feel like I'd allow us to shorten a lot of code while maintaining good readability

My proposal is to allow to **return** right after **??** operator

What do you think?

**Comment by svick** [comment] 2019-05-14 10:17
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/176 to me.

**Closed** 2019-05-14 10:22 UTC
