### ISSUE TITLE
[Proposal]: record features for readonly structs

### ISSUE THREAD

**Issue by lucasteles** [dotnet/csharplang#4322] opened 2021-01-12 20:02 UTC
#  Block dependency using

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary

Would be nice to have the primary constructor and `with` of records on readonly structs

## Motivation

Make write immutable structs more easy

## Detailed design

Instead of write in this way:

```cs
var point = new Point(1,2);
var otherPoint = new Point(point.X, 10);

readonly struct Point {
   public int X {get;}
   public int Y {get;}
    
   public Point(int x, int y)
   {
       X = x;
       Y = y;
   }
}

```
Would be nice to write in this way

```cs
var point = new Point(1,2);
var otherPoint = point with { Y = 10 };

readonly struct Point(int X, int Y);
```

## Drawbacks
I don't know any

**Comment by HaloFour** [comment] 2021-01-12 20:12
The team has queued up a spec for struct records that they will be discussing in the coming weeks: https://github.com/dotnet/csharplang/pull/4307

```cs
readonly struct record Point(int X, int Y);
```

**Comment by YairHalberstadt** [comment] 2021-01-13 03:44
Closing as duplicate of https://github.com/dotnet/csharplang/pull/4307

**Closed by YairHalberstadt** 2021-01-13 03:44 UTC
