### ISSUE TITLE
check.. value pattern matching

### ISSUE THREAD

**Issue by ghost** [dotnet/csharplang#1915] opened 2018-10-06 18:00 UTC
I dislike the traditional-C switch statement, for two reasons:
1- the need for break to end each case block.
2- All the switch block is considered one continuous block, so we can't define a variable with the same name in each case, unless we enclose the case block in {}, which make the break statement more ugly and unnecessary.

And since C# already tries to improve the pattern matching, I suggest adding a new pattern matching statement and make all the new improvements to it. It can be like this:
``` 
int x = 5;
int y = 1
check (x)
{
    value 0:
    {
        Cosole.WriteLine("Err");
        throw new Exception("Zero");
        // no need for break. It works like if..else
    }
    value 1, 2, 3: // match many values
         Console.WriteLine(x); // no need for {} since it is one statement
    value 3..10:  //match a range
    {  
         \\ do something 
    }
    value y + 2:  //match an expression
    {  
         \\ do something 
    }
    any:  \\ any value else
          Console.WriteLine(x);
}
```

Note:
'value' keyword can be distinguished from value keyword in properties and any parameter or variable named value by the syntax and context. But you can suggest another word to avoid any confusion.

**Comment by HaloFour** [comment] 2018-10-06 18:14
Switch expressions can be used as statements.  You can use blocks with switch statements to introduce scope.  Not liking `break` is not reason enough to introduce completely redundant syntax.

**Comment by MohammadHamdyGhanem** [comment] 2018-10-06 18:32
@HaloFour 
> can use blocks with switch statements to introduce scope

I already said that as a dislike point:
> unless we enclose the case block in {}, which make the break statement more ugly and unnecessary.

The point is that switch seems like a one continous block and break seems like a goto statment, which is too traditional and unlike other language blocks. This design was the solution to merge more than one case together, and since C# will introduce another syntax for this, so this traditional design seems unnecessary. If you are going to allow many values in one case using 'or' or ',' , then what is the point of break?
I say it is time to get rid of legacy c code and add a new modern syntax (note necessarily
mine)

**Comment by MohammadHamdyGhanem** [comment] 2018-10-07 05:08
@theunrepentantgeek 
This is not a breaking change. switch statement will continue to exisit but new modifications in pattern matching  will be made to check statement, and over the time switch will be obsolete. 'goto' is still there in c# and vb.net but rarely used if ever used at all. Maybe I used the phrase get red of in a wrong context.

**Comment by HaloFour** [comment] 2018-10-07 05:30
@MohammadHamdyGhanem 

`switch` has already been enhanced to support pattern matching, and as pattern matching evolves so will `switch`.  The likelihood that `switch` will somehow be abandoned, because you don't like the syntax, is most definitely zero.

C# is certainly getting an expression version of `switch` (yes, called `switch`).  C# is likely getting sequence expressions to permit multiple statements within a single expression.  You'll have an alternate syntax if you so choose.  But the `switch` statement isn't going to be reinvented.

**Comment by MohammadHamdyGhanem** [comment] 2018-10-07 06:30
@HaloFour 
Ok. At least I ask to treat break as optional when the case block is enclosed with { }. This will not break anything, since C# doesn't allow the flow from one case ti another and throws an exception. If this happens, I can use switch like this:
```
switch (x)
{
    case 0:
    {
        Cosole.WriteLine("Err");
        throw new Exception("Zero");
        // no need for break.
    }
    case 1 or 2 or 3: 
    {
         Console.WriteLine(x);
    }    
    default:  
          Console.WriteLine(x);
}
```

**Comment by Happypig375** [comment] 2018-10-07 07:16
@MohammadHamdyGhanem 
Duplicate of #1350.

**Comment by MohammadHamdyGhanem** [comment] 2018-10-07 07:32
What is `match expression` ? They say it will be used instead of switch.

**Comment by ufcpp** [comment] 2018-10-07 09:03
It also uses `switch` eventually.
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgD4ACADAAS0CMA3ALABQtAzMwCZGAYUYBvboynN+tACyMAsgAoA9sABWEDDEYAPAJSTpErtPOM8UBIyiMAvPsbIA7jhgYAFsYvifv6RwKXRwHAD5GHAAafwDmFiZkcOcAOgAZCAoAcxhPGLM46QB9ZPpY6QBfTgKpCu4KoA

**Comment by YairHalberstadt** [comment] 2020-10-19 04:22
I'm closing this as the OP no longer seems to have a github account, and the proposal has been fairly negatively received. If you would like to discuss more, let me know and I'll move to a discussion.

**Closed by YairHalberstadt** 2020-10-19 04:22 UTC
