### ISSUE TITLE
$"{{0x{someInt:X4}}}" got wrong result

### ISSUE THREAD

**Issue by qaqz111** [dotnet/csharplang#2114] opened 2019-01-02 01:21 UTC
```C#
            var hour = DateTime.Now.Hour;
            var a1 = $"new[]{{0x{hour,8:X4}}}"; //"new[]{0x     X4}"
            var a2 = $"new[]{{0x{hour:X4}}}"; //"new[]{0xX4}"
            var a3 = $"new[]{{0x{hour,8}}}"; //"new[]{0x       9}"
            var a4 = $"new[]{{0x{hour}}}"; //"new[]{0x9}"
```
The result of `a1` and `a2` seems wrong. Is this a bug?

**Comment by yaakov-h** [comment] 2019-01-02 02:13
Try this:

```csharp
var hour = DateTime.Now.Hour;
var o = '{';
var c = '}';

var a1 = $"new[]{o}0x{hour:X4}{c}";
var a2 = $"new[]{o}0x{hour:X4}{c}";
var a3 = $"new[]{o}0x{hour,8}{c}";
var a4 = $"new[]{o}0x{hour}{c}";
```

With your example, the runtime is parsing the closing `}}}` as `}}` followed by `}`, rather than as `}` followed by `}}`.

**Comment by qaqz111** [comment] 2019-01-02 12:20
Yes I understand the `}}}` is parsed as `}}` + `}`, but what make confused is that the result is counterintuitive.

I know that the `formatString` which after `:` and before last single `}` will be splitted and pass to `ICustomFormatter.Format` or `IFormattable.ToString`, but I think there should be a way to escape `}` (for example `\}` ?) to avoid this problem.

At last I splitted the last `}` and connect it by `opreator+`:
```C#
            var hour = DateTime.Now.Hour;
            var a1 = $"new[]{{0x{hour,8:X4}" + "}";
            var a2 = $"new[]{{0x{hour:X4}" + "}";
            var a3 = $"new[]{{0x{hour,8}" + "}";
            var a4 = $"new[]{{0x{hour}" + "}";
```
Yes this can get the desired result but just look weird and a bit ugly.

**Comment by gafter** [comment] 2019-01-02 18:36
This issue is clearly documented in https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.7.2 and is behaving as designed and as expected.  I suggest

``` c#
        var a5 = $"new[]{'{'}0x{hour:X4}{'}'}");
```

**Closed by gafter** 2019-01-02 18:36 UTC

**Comment by theunrepentantgeek** [comment] 2019-01-02 18:38
This looks to me as though you're generating C# (or, at least, a closely related language), so why not write this instead?

``` csharp
var hour = DateTime.Now.Hour;
var a1 = $"new[]{{ 0x{hour,8:X4} }}";
var a2 = $"new[]{{ 0x{hour:X4} }}";
var a3 = $"new[]{{ 0x{hour,8} }}";
var a4 = $"new[]{{ 0x{hour} }}";
```

As a bonus, the additional whitespace will make the generated content easier to read for anyone needing to triage/diagnose issues.

**Comment by qaqz111** [comment] 2019-01-03 16:51
> This issue is clearly documented in https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.7.2 and is behaving as designed and as expected. I suggest
> 
> ```cs
>         var a5 = $"new[]{'{'}0x{hour:X4}{'}'}");
> ```

@gafter:
Thanks for reply. I know that this is totally not a big problem at all, but the designed working did killed the possibility to output desired result in previous example. The suggested code will generate a call to `string.Format("new[]{0}0x{1:X4}{2}", '{', hour, '}')` which increases the complexity of `formatString` and of course will bring additional cost. And yes it really is not a problem to most people but only obsessives. 😋

---

> This looks to me as though you're generating C# (or, at least, a closely related language), so why not write this instead?
> 
> ```cs
> var hour = DateTime.Now.Hour;
> var a1 = $"new[]{{ 0x{hour,8:X4} }}";
> var a2 = $"new[]{{ 0x{hour:X4} }}";
> var a3 = $"new[]{{ 0x{hour,8} }}";
> var a4 = $"new[]{{ 0x{hour} }}";
> ```
> 
> As a bonus, the additional whitespace will make the generated content easier to read for anyone needing to triage/diagnose issues.

@theunrepentantgeek 
Thanks for suggestion. I did use this code at first, but when the output includes hundreds code points the generated code will be too long to stay in one line, so I cutted the spaces since the output is not intented to be read by people 😄

**Comment by theunrepentantgeek** [comment] 2019-01-03 20:16
> when the output includes hundreds code points the generated code will be too long to stay in one line, so I cutted the spaces since the output is not intented to be read by people

I'm confused.

If the code isn't intended to be read by people, solving your problem by adding extra spaces can't make the line too long, because people won't care.

But if the line is too long to be read by people, taking out all the spaces just makes their life more difficult.

Regardless, I'd strongly recommend putting some effort into formatting your generated code so that it is readable.

_**Every**_ piece of generated code gets read by a human, eventually. Usually this happens when something critical and/or expensive is broken and needs to be fixed fast. Be kind to that person - it might be your future self.

**Comment by qaqz111** [comment] 2019-01-04 04:40
> _**Every**_ piece of generated code gets read by a human, eventually. Usually this happens when something critical and/or expensive is broken and needs to be fixed fast. Be kind to that person - it might be your future self.

The generated code is intented to be used via network and will be input to a program, no human intervention at all. So the readability is not the point but the size of the content.

The codes which will be reviewed by a human of course have to obey rules for code writings.

Anyway, thanks for your advice, you must be a good team leader 👍

**Comment by Happypig375** [comment] 2019-01-04 14:31
Be caution for code injection attacks if you are transmitting arbitrary code over the network though.
