### ISSUE TITLE
Union Support like c++ Union

### ISSUE THREAD

**Issue by andrevdl** [dotnet/csharplang#986] opened 2017-10-09 19:26 UTC
It would be great if c# supports Union.

Yes, you can create a struct with all types, like:
```
struct Example {
	int a;
	float b;
	...
}
```

And then do manual magic with struct layout Kind.
But this will only work for fix size elements and you must know the sizes of the objects.

**Comment by bondsbw** [comment] 2017-10-09 19:31
Dupe of #687.  See also #399.

**Closed** 2020-09-08 23:44 UTC
Labels: Discussion, Feature Request, Move to Discussion
