### ISSUE TITLE
[Proposal] Improve type inference for lambdas

### ISSUE THREAD

**Issue by leandromoh** [dotnet/csharplang#3483] opened 2020-05-21 17:26 UTC
currently, C# doest not offers any type inference about lambdas/delegates. It is always necessary to explict the type of variable, even when it could be easily inferred.

We have to define variable types,
```c#
Func<int, int> func1 = (int x) => x;
Func<int, string> func2 = (int x) => x.ToString();
```
when could be simplified to 
```c#
var func1 = (int x) => x;
var func2 = (int x) => x.ToString();
```

A workaround is define a helper function.

```c#
Func<T, R> GetFunc<T, R>(Func<T, R> x) => x;

var func1 = GetFunc((int x) => x);
var func2 = GetFunc((int x) => x.ToString());
```
Things get worse when currying functions, the helper function can no longer help us. The bellow code doest not compile, because compiler can not infer the return type, since it is a another lambda.

```c#
var func3 = GetFunc((int x) => (int y) => x + y);
```

Since, C# treat functions as [first-class citizens](https://en.wikipedia.org/wiki/First-class_citizen), and is getting more and more functional, should be nice to improve inferation, at least for cases without ambiguity.

**Comment by svick** [comment] 2020-05-21 17:54
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/150.

**Comment by HaloFour** [comment] 2020-05-21 18:06
> even when it could be easily inferred.

Except it can't.  The signature isn't enough to know the type of the delegate, and delegates are nominally typed even if they share the same signature.  `Func<int, bool>` and `Predicate<int>` are incompatible types, and "converting" from one to the other requires pointing one delegate to another and incurring twice the overhead on invocation.

**Comment by bbarry** [comment] 2020-05-21 18:22
Both of those could also be expression types:

```csharp
Expression<Func<int, int>> func1 = (int x) => x;
Expression<Func<int, string>> func2 = (int x) => x.ToString();
```

**Comment by leandromoh** [comment] 2020-05-21 18:34
@HaloFour  @bbarry , of course there is more than one possible type. 
But, as well we infer `0` to be an `int` at expression `var i = 0` (even we its a valid value for other types, like double, decimal, etc.), we can assume `Func<>` and `Action` as default

**Comment by leandromoh** [comment] 2020-05-21 18:40
Or even, infer the type based on the use of the variable.

**Comment by HaloFour** [comment] 2020-05-21 18:49
@leandromoh 

> But, as well we infer `0` to be an `int` at expression `var i = 0` (although its a valid value for other types, like double, decimal, etc.)

The expression `0` is an `int`.  The compiler will allow implicit conversion in some cases, and there is no penalty for doing so.

> we can assume `Func` and `Action` as default

It's not just that there is more than one type, it's that going with the wrong type adds overhead at runtime at every single invocation.  It's the same reason you can't implicitly cast from one delegate type to another, despite the signatures being the same.

> Or even, infer the type based on variable usage, which I image to be more complex.

https://github.com/dotnet/csharplang/issues/1694

**Comment by leandromoh** [comment] 2020-05-21 19:08
>  it's that going with the wrong type adds overhead at runtime at every single invocation. It's the same reason you can't implicitly cast from one delegate type to another, despite the signatures being the same.

I understand. In my experience as c# developer, other delegates are rarely used comparated to `Func` and `Action`. That is why i suggest these (an its 15 variants) as default. If the right type is  `Predicate<Foo>` instead of `Func<Foo, bool>`, developer can explict the right type in place of `var`, just as it is done today.

**Comment by DavidArno** [comment] 2020-05-27 08:26
Back before local functions were introduced, there was a big push by some of us here to have the compiler infer `Func` and `Action` delegates allowing the very syntax you propose:
```cs
var func1 = (int x) => x;
```
But then local functions came along and effectively offered the same thing with slightly different syntax:
```cs
int func1(int x) => x;
```
As a result, that push for `var` support for `Func` and `Action` fizzled out. It may one day happen, but it seems very unlikely these days as there's not really a compelling use case for it anymore.

**Comment by leandromoh** [comment] 2020-06-27 02:51
@DavidArno syntaxe is similar, but `fun1` in your last example is a method-identifier, not a variable-identifier. So `func1` is a method variable (delegate), but the method itself.

**Comment by YairHalberstadt** [comment] 2020-11-30 10:10
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/150

**Closed by YairHalberstadt** 2020-11-30 10:10 UTC
