### ISSUE TITLE
Proposal: Private top-level types

### ISSUE THREAD

**Issue by ryzngard** [dotnet/csharplang#2590] opened 2019-06-11 17:48 UTC
I propose we support private accessibility for top-level classes. The use case is to allow private types have reduced visibility within a program based on namespacing. 

For example: 

```C#
namespace My.Namespace.Serializer
{
	internal static class StringExtensions
	{ 
		public static string TrimAndReduce(this string value)
		{
			return string.IsNullOrEmpty(value)
        ? value 
        : ConvertWhitespacesToSingleSpaces(value).Trim();
		}

		public static string ConvertWhitespacesToSingleSpaces(this string value)
		{
			return Regex.Replace(value, @"\s+", " ");
		}
	}
}
```

```C#
namespace My.Namespace.Serializer.Simple
{
	public class SimpleSerializer
	{
        // My.Namespace.Serializer.StringExtensions is accessible here
		public string Serialize(object o) => o?.ToString().TrimAndReduce();
	}
}
```

```C#
using My.Namespace.Serializer;

namespace My.Namespace.Program
{
  public class Program 
  {
    public static void Main(string[] args)
    {
      // My.Namespace.Serializer.StringExtensions is innacessible
      Console.WriteLine(args.Select(s => s.TrimAndReduce()));
    }
  }
}
```

## Arguments 

1. This would allow domain specific extension methods to be written such as the string extension for serializers in example.
2. Reduce overhead of using partial classes as encapsulation for implementation details.

## Complications

1. How does the CLR support this? 
	a. One proposal would be to generate an unutterable name for private types so they cannot be used outside of the given program. This would complicate the debug scenario, but would allow the compiler to enforce this without changes to CLR

**Comment by HaloFour** [comment] 2019-06-11 19:49
So, this would be like `internal` except with namespace visibility?  This sounds like the default "package-private" visibility from Java.

**Comment by svick** [comment] 2019-06-11 19:50
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/1138.

**Comment by ryzngard** [comment] 2019-06-11 23:55
> This looks like a duplicate of #1138. 

Indeed, thanks for pointing that out. I think my concerns are mirrored well in that issue. Using internal + multiple assemblies works for this, but isn't perfect. 

I agree with the comment that [no IL changes are needed](https://github.com/dotnet/csharplang/issues/1138#issuecomment-353325181). 

[ChristopherHaws](https://github.com/dotnet/csharplang/issues/1138#issuecomment-353160797) enumerates similar use case expectations. 

The root issue is that current organizational means seem insufficient. Assemblies would the boundary here, but I wouldn't exactly say that ILMerge is a great solution. Assemblies are also not really something that the language is explicit about; there's no easy mapping to know what assemblies a given file gets compiled into. The benefit of having a language construct is that the intent is stated at type definition. This proposal is one solution for that.

**Comment by YairHalberstadt** [comment] 2020-10-28 10:15
Closing as duplicate of #1138 and https://github.com/dotnet/csharplang/issues/2497.

**Closed by YairHalberstadt** 2020-10-28 10:15 UTC
