### ISSUE TITLE
Proposal: Implicitly scoped lock statement

### ISSUE THREAD

**Issue by AustinWise** [dotnet/csharplang#3749] opened 2020-07-29 17:28 UTC
Basically its the same idea as "Implicitly scoped using statement" from C# 8 (see #1174 and the [spec](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/using.md) ), but for the `lock` statement.

# Example

Currently when you use the [`lock` statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/lock-statement) in C# you have to uses braces:

```csharp
void SomeFunction()
{
    lock (_lockObject)
    {
        // mutual-exclusion zone
    }
}
```

With this proposal you could instead write:

```csharp
void SomeFunction()
{
    lock _lockObject;
    // mutual-exclusion zone til the end of the current block
}
```

# Pros

* Lighter syntax for locks, avoiding extra scope
* Easier to acquire multiple locks

# Cons

* Harder to see if a method has the required locks
* By making it easier to acquire a lot of locks, it could encourage dead-lock prone code
* Locks don't play well with `await`, so to the extent that modern C# codebases uses `async` synchronization primitives this feature will not help.
* One more thing to complicate the language

**Comment by YairHalberstadt** [comment] 2020-07-29 17:50
For most disposable types it's less important when exactly they are disposed, and how quickly than that they eventually are disposed. Thus allowing implicitly scoped using statements is reasonable.

With lock statements this really isn't the case. Whether a lock includes or doesn't include a particular line of code can and does critically impact the behaviour of the lock. It is very important that their scope is explicit not implicit.

**Comment by AustinWise** [comment] 2020-07-29 21:01
@YairHalberstadt So your recommendation would be to use the old braces-form of when doing something is more like a lock statement:

```csharp
using (new MutexHolder(someMutex))
{
    // ...
}
```

I can see your argument for using the braces form of `using` selectively while using `lock` with braces would always be preferred to be explicit about the scope of the lock.

**Comment by YairHalberstadt** [comment] 2020-07-30 02:44
Exactly. Locks should be explicit about their scope.

**Comment by PathogenDavid** [comment] 2020-07-30 08:48
This is a duplicate of #2451

It's also similar to: #958/#892

**Comment by 333fred** [comment] 2020-07-30 14:41
Closing as a duplicate.

**Closed by 333fred** 2020-07-30 14:41 UTC

**Comment by AustinWise** [comment] 2020-07-30 15:07
Thanks for find the duplicate. I need to get better at searching.

**Comment by 333fred** [comment] 2020-07-30 15:23
I find it helpful to use Google to search a specific site, rather than issue search.

**Comment by PathogenDavid** [comment] 2020-07-30 18:12
I've also found that restricting the search to the titles of issues to be useful. IE: [`lock in:title`](https://github.com/dotnet/csharplang/issues?q=is%3Aissue+is%3Aopen+lock+in%3Atitle)
