### ISSUE TITLE
Using ?. and += together

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/csharplang#1737] opened 2018-07-25 13:10 UTC
In WPF, you write code like this a lot:
````
                if (__PART_ActionButton != null) {
                    __PART_ActionButton.Click -= this.PART_ActionButton_Click;
                }

                __PART_ActionButton = value;

                if (__PART_ActionButton != null) {
                    __PART_ActionButton.Click += this.PART_ActionButton_Click;
                }
````

It would be really nice if I could just do this:
````
__PART_ActionButton?.Click -= this.PART_ActionButton_Click;
__PART_ActionButton = value;
__PART_ActionButton?.Click += this.PART_ActionButton_Click;

````

**Comment by HaloFour** [comment] 2018-07-25 13:18
#1106

**Comment by YairHalberstadt** [comment] 2020-10-18 07:39
Closing as duplicate of #1106

**Closed by YairHalberstadt** 2020-10-18 07:39 UTC
