### ISSUE TITLE
[Proposal] Object Initializer support for events

### ISSUE THREAD

**Issue by CortiWins** [dotnet/csharplang#1552] opened 2018-05-22 14:24 UTC
I have it pretty often that my code would look a little bit simpler if it were possible to set events as part of the Object Initializer.

```c#
var instance = new SomeObject()
{
    Property = "StringValues",
    PropertyObj = new object(),
    OnChange += this.MyFunction, // <- THIS !
}
```

**Comment by HaloFour** [comment] 2018-05-22 14:26
#307

**Comment by masums** [comment] 2019-07-09 14:33
C# object property initialization is really a nice feature. And now I also feel the necessity of event initialization at object creation time. Then object creation will be more declarative.

**Comment by 333fred** [comment] 2024-12-03 22:44
Closing as a duplicate of https://github.com/dotnet/csharplang/discussions/307.

**Closed by 333fred** 2024-12-03 22:44 UTC
