### ISSUE TITLE
[Proposal] Unique generic constraint

### ISSUE THREAD

**Issue by petarpetrovt** [dotnet/csharplang#3822] opened 2020-08-25 19:30 UTC
Add support for **unique** generic constraint that ensures some or all generic type parameters are unique at compile time.

```csharp
public View<T1, T2> View<T1, T2>()
    // where T1 != T2
    // OR: where T1 is not T2
    // OR: where typeof(T1) != typeof(T2)
    // OR: where unique
{
    // Runtime checks are the only current alternative.
    Assert.NotSame<T1, T2>();
}
```

**Comment by ZacharyPatten** [comment] 2020-08-25 20:08
How would this work with polymorphism? Would generic types be considered equal if they are parts of the same branch in an inheritance tree?

If this feature would not respect polymorphism, it should never use the "`is`" keyword, because the current usage of "`is`" _does_ respect polymorphism.

```cs
using System;

public class Program
{
	public static void Main()
	{
		A a = new A();
		B b = new B();
		Method(a, b);
	}

	public static void Method<T1, T2>(T1 a, T2 b)
	{
		Console.WriteLine(a is T2);
		Console.WriteLine(b is T1);
	}
}

public class A { }
public class B : A { }
```

**Comment by svick** [comment] 2020-08-25 20:30
Why?

**Comment by petarpetrovt** [comment] 2020-08-25 20:32
@ZacharyPatten 
I don't really care about polymorphism support (my use case all types are value types with struct constraint). The proposed syntax is optional.

**Comment by PathogenDavid** [comment] 2020-08-26 06:19
Generic type constraints are encoded in CIL and are understood and enforced by the runtime, which means this request would most likely require a runtime change, which raises the bar significantly.

This is something you could/should pretty easily enforce with an analyzer.

Constraints are meant to enable you to use new capabilities with a generic type, not to enable your domain-specific usage restrictions.

**Comment by PathogenDavid** [comment] 2020-08-26 06:32
Also this is a duplicate of https://github.com/dotnet/csharplang/issues/1706 (which also presents a scenario where such a constraint enables you to do something new that an analyzer can't help with.)

Somewhat related: https://github.com/dotnet/csharplang/issues/707

**Comment by 333fred** [comment] 2020-08-26 15:04
Closing as a duplicate.

**Closed by 333fred** 2020-08-26 15:04 UTC
