### ISSUE TITLE
Allow get only properties to be initialised using object initialiser

### ISSUE THREAD

**Issue by rcmdh** [dotnet/csharplang#3120] opened 2020-01-22 10:14 UTC
For some objects, it is more pleasant to initialise them using object initialisers, however that means that you need to make the properties mutable.  Could we allow:

```
class MyClass
{
    public int MyProperty { get; }

    public static MyClass Make7()
    {
        return new MyClass { MyProperty = 7 };
    }
}
```

**Comment by canton7** [comment] 2020-01-22 12:28
Duplicate of https://github.com/dotnet/csharplang/issues/1684?

**Closed** 2020-01-22 12:34 UTC
