### ISSUE TITLE
Please allow omitting type of ref argument in lambda

### ISSUE THREAD

**Issue by Thaina** [dotnet/csharplang#1834] opened 2018-09-04 06:10 UTC
```C#
public delegate void RefAction<T>(ref T value);

RefAction<int> pow2 = (ref i) => i * i; // currently error
```

**Comment by svick** [comment] 2018-09-04 21:41
This is a duplicate of https://github.com/dotnet/csharplang/issues/338.

**Closed** 2018-09-05 01:14 UTC
