### ISSUE TITLE
[Proposal] For range loops

### ISSUE THREAD

**Issue by dynamiquel** [dotnet/csharplang#3540] opened 2020-06-06 23:25 UTC
I’ve recently been looking at the Swift language and noticed one amazing feature which I think would be great for C#, for range loops. It just makes writing for loops so much faster.

Instead of using:
`for (var i = 0; i < n; i++)`

We could use:
`for (var i in 0...n)`

Come on, look at how much shorter but obvious it is.

It should be a short hand way of doing:
`foreach (var i in Enumerable.Range(0, n))`

**Comment by bbarry** [comment] 2020-06-07 00:20
almost certain this is a duplicate but anyway...

it should not be a short hand way for ` foreach (var i in Enumerable.Range(0, n))`

it should be a short hand way for doing:

```csharp
 for (var temp = 0; temp < n; temp++)
{
    var i = temp;
    // ...
}
```

**Comment by CyrusNajmabadi** [comment] 2020-06-07 03:14
Your is simply solvable with extension GetEnumerator: https://github.com/dotnet/csharplang/issues/3194

**Comment by theunrepentantgeek** [comment] 2020-06-07 05:11
@dynamiquel - GitHub tells me this is your first issue here. Welcome!

The syntax `0..n` is already valid C# syntax for a Range - [introduced in C# 8](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#indices-and-ranges). 

What's missing is the ability to use **foreach** to iterate over it; the `Range` type doesn't include the requisite `GetEnumerator()` method.

Currently **foreach** requires the type to directly implement `GetEnumerator()`. The proposal in #3194 that @CyrusNajmabadi  linked would allow you to write your own extension method to provide `GetEnumerator()`, making iteration light up.

**Comment by dynamiquel** [comment] 2020-06-07 10:32
> almost certain this is a duplicate but anyway...
> 
> 
> 
> it should not be a short hand way for ` foreach (var i in Enumerable.Range(0, n))`
> 
> 
> 
> it should be a short hand way for doing:
> 
> 
> 
> ```csharp
> 
>  for (var temp = 0; temp < n; temp++)
> 
> {
> 
>     var i = temp;
> 
>     // ...
> 
> }
> 
> ```
> 
> 

Or that, I only mentioned the foreach loop because it already has something similar.

**Comment by AlgorithmsAreCool** [comment] 2020-06-17 16:02
If we got this feature I would really hope the compiler would lower it to a `for` loop not a `foreach` to keep it close to zero cost. If i am using an indexed loop (a `for` loop) in the first place it is almost certainly to avoid overhead from the enumerator for spans or arrays.

**Comment by CyrusNajmabadi** [comment] 2020-06-17 16:44
foreach is just as fast as for, provided your iterator is efficient (i.e. doesn't box, doesn't use virtual calls).

**Comment by jnm2** [comment] 2020-06-17 17:39
Duplicate of https://github.com/dotnet/csharplang/issues/2952?

**Comment by 333fred** [comment] 2020-06-17 21:45
There is an issue somewhere that this would be a duplicate of, but I don't think it's that one. In fact, I'm going to close that one because it's a library request, not a C# request.

**Comment by 333fred** [comment] 2020-06-17 21:53
Closing a duplicate of https://github.com/dotnet/csharplang/issues/2810.

**Closed by 333fred** 2020-06-17 21:53 UTC
