### ISSUE TITLE
out var (x, y) for tuples.

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/csharplang#956] opened 2017-10-02 23:08 UTC
allow tuple assignments in `out var` syntax too.

```
_pool = new Dictionary<int, (IBuffer, Stream)>();

if (_pool.TryGetValue(length, out var (buffer, stream)))
{
    // code
}
```

**Comment by jnm2** [comment] 2017-10-02 23:16
Dupe of https://github.com/dotnet/csharplang/issues/611

**Comment by DavesApps** [comment] 2017-10-05 14:21
I agree it's inconsistent if it doesn't handle it.  Though this is kind of ironic since part of the reason tuples were added was so that we could avoid using out variables :)  Should the language guide people towards avoiding out variables and using Tuple return's instead?

**Comment by jcouv** [comment] 2017-10-07 03:12
I'll go ahead and close this issue. It's indeed a duplicate. Thanks

**Closed by jcouv** 2017-10-07 03:12 UTC
Labels: Discussion, Feature Request
