### ISSUE TITLE
[Bug] Method extension overloading with generics fails to account for generic constraints

### ISSUE THREAD

**Issue by Expro** [dotnet/csharplang#1628] opened 2018-06-13 22:43 UTC
Not sure if this fits here, or in Roslyn repo.

Consider following code:
```
public static T Extension<T>(this T) where T : ISomeInterface<TypeOne>
{
   throw new NotImplementedException();
}

public static T Extension<T>(this T) where T : ISomeInterface<TypeTwo>
{
   throw new NotImplementedException();
}
```
Where TypeOne and TypeTwo inheritance tree meets only on root (object).

This will result in error: Type '...' already defines a member called 'Extension' with the same parameter types.

Expected result: both extension methods are being recognized as differend overloads.

**Comment by HaloFour** [comment] 2018-06-13 22:59
The CLR doesn't allow for overloading on generic type constraints.  They are not a part of the method signature, they're just metadata.

**Comment by benaadams** [comment] 2018-06-13 23:29
Could make a funny name for clr when name collisions are resolved via generic constraints
```csharp
public static T Extension<T>(this T) where T : class
{
   throw new NotImplementedException();
}

public static T Extension<T>(this T) where T : struct
{
   throw new NotImplementedException();
}
```

**Comment by gafter** [comment] 2018-06-13 23:38
[This works in C# 7.3 without any issues.](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwg4A2APgAIAMABCwIwDcAsACghPAGxcATBwAa3IQG8hHZVwDMXbuIAqHAKIAPMlRwB7CgB4tAPgAUMABY5kHHTACUHAO73yEFxxAOAEkAZRMAWwggijIEMCgMCEsATyIIAHkKCCslFUVBFUKHBBNPDiyygDkTGCDwogYISJiIABMDRKIYUwobNwEClQBfIRHhQTFJGQkFXOUWdUmdAyNcM0tbByd/dy8fJH9A0IiolriEpK1UiC1PExzB5XzClWLS8ogqmrqGpogW9r6TrdMx9AaFMZjIQ4M7xRLBMKRaKxOGXKwceQcMYsKRXNKZPyY7G4663EwYrEiKSItEBBEnZHkVEbClQiaLKQ8ADss0eag04hYABYNAAOPpzDGSwp4KAIDj6bgcAC8HzKNJS+Kytn60pUsvlAEcVQruAA6Fb/Na9XV8mVyhVSVUVDgavE3O468EvZQGrwm/QSC2GK09MGSyFAA)

Closing as fixed.

**Closed by gafter** 2018-06-13 23:38 UTC

**Comment by benaadams** [comment] 2018-06-13 23:44
@gafter ❤️

**Comment by HaloFour** [comment] 2018-06-14 00:05
@gafter 

The complaint seems to be about being able to define the extension methods in the same static class as overloads, which is a compiler error.

**Comment by gafter** [comment] 2018-06-14 00:19
@HaloFour Perhaps so, but in C# 7.3 there is a workaround.

**Comment by benaadams** [comment] 2018-06-14 01:12
And used as a suggested perf workaround... https://github.com/dotnet/corefxlab/pull/2358#issuecomment-397134747

**Comment by ufcpp** [comment] 2018-06-14 01:32
```cs
using System;

static class Ex
{
    public struct Struct { }
    public struct Class { }

    public static T Extension<T>(this T x, Class _ = default) where T : class
    {
        throw new NotImplementedException();
    }

    public static T Extension<T>(this T x, Struct _ = default) where T : struct
    {
        throw new NotImplementedException();
    }
}

class Program
{
    static void Main()
    {
        1.Extension();
        "".Extension();
    }
}
```

**Comment by Expro** [comment] 2018-06-14 06:37
Splitting extension versions into different classes is in fact acceptable workaround.

**Comment by dzmitry-lahoda** [comment] 2022-04-22 15:22
Not pleasant and not a self-evident workaround. So I will have to create a range of extensions suffixed 1,2,3. And have to move it into top-level class as extension require.

```csharp
using System;

Console.WriteLine();

record A();
record B();
record D();

record C() {
    public T To<T>() where T: A => throw new Exception();
    public T To<T>() where T: B => throw new Exception();
}

static class CE {
    static T To<T>(this C self) where T: D =>  throw new Exception();
}
```

**Comment by HaloFour** [comment] 2022-04-22 15:27
This is not a bug, the runtime does not consider generic type constraints as a part of the method signature and such does not permit overloading based on them.

**Comment by bernd5** [comment] 2022-04-22 19:51
As a workaround you can write:

```csharp
using System;

Console.WriteLine();

record A();
record B();
record D();

struct Dummy<T>{}

record C() {
    public T To<T>(Dummy<A> dummy = default) where T: A => throw new Exception();
    public T To<T>(Dummy<B> dummy = default) where T: B => throw new Exception();
    public T To<T>(Dummy<D> dummy = default) where T: B => throw new Exception();
}

static class CE {
    static T To<T>(this C self) where T: D =>  throw new Exception();
}
```

**Comment by dzmitry-lahoda** [comment] 2022-04-24 13:28
No need for a dummy. May end-use that for partial updates/merges (if value not set, take from `_`). Nice:
```csharp
record A();
record B();
record D();

record C() {
    public T To<T>(A _ = default) where T: A => throw new Exception();
    public T To<T>(B _ = default) where T: B => throw new Exception();
}

static class CE {
    static T To<T>(this C self) where T: D =>  throw new Exception();
}
```

**Comment by bernd5** [comment] 2022-04-24 14:37
I used an empty struct to reduce the overhead (the compiler may not eliminate the not used parameter...)

**Comment by dzmitry-lahoda** [comment] 2022-05-11 12:18
With default hack we get:

- `error CS0854: An expression tree may not contain a call or invocation that uses optional arguments` in LINQ expressions
- cannot use `x.To` for sure in delegate based LINQ as it is not good with optional parameters
