### ISSUE TITLE
Target-typed new can be passed in implicit-typed array

### ISSUE THREAD

**Issue by Sunnie-Shine** [dotnet/csharplang#3796] opened 2020-08-15 05:56 UTC
Consider the code in C# 9:
```csharp
public class C
{
    public void M()
    {
        A[] z1 = new[] { new() }; // CS0826.
        var z2 = new[] { new A() };
        var z3 = new A[] { new() };
        var z4 = new A[] { new A() };
    }
}

public readonly struct A
{
    public readonly int Prop => 3;
}
```

I think that all four cases should be okay, but in fact, Roslyn throws a syntax error CS0826 (**No best type found for implicitly-typed array**) for the new expression of `z1` . The reason why I think `z1` is okay is that `A` is a `struct`, so `new[]` means `new A[]` as the only possibility. Therefore, the inner expression `new()` should stand for `new A()`.

**Comment by CyrusNajmabadi** [comment] 2020-08-15 06:01
We could consider target-typing implicit arrays as a fallback if the type of it cannot be determined based on its elements.

**Comment by 333fred** [comment] 2020-08-15 17:05
Duplicate of https://github.com/dotnet/csharplang/issues/2701. I'm going to close this out.

**Closed by 333fred** 2020-08-15 17:05 UTC
