### ISSUE TITLE
Allow var in functions accepting lambdas

### ISSUE THREAD

**Issue by kofifus** [dotnet/csharplang#4280] opened 2020-12-27 23:02 UTC
A simplified version of restricted state access with side effects (locking):

```
public delegate void ActionRef<T>(ref T r1);
public delegate RES FuncRef<T, RES>(ref T r1);

public class LockedState<T>  {
  T Value;
  readonly object theLock = new object();

  public void Ref(ActionRef<T> f) { lock(theLock) f(ref Value);  }
  public TRES Ref<TRES>(FuncRef<T, TRES> f) { lock(theLock) return f(ref Value); }
}

public static void Main() {
  LockedState<SomeComplexType<DateTime, OtherComplexType<List<int>>>> State = new();

  // this is what I have to do ATM:	
  State.Ref((ref SomeComplexType<DateTime, OtherComplexType<List<int>>> v) => {  v = v.next();  }); 

  // but I would like to do this:
  State.Ref((ref var v) => { v = v.next();  }); // The contextual keyword 'var' may only appear within a local variable declaration or in script code	

  // or even better this:
  State.Ref(ref var v => { v = v.next();  });

  // or even better this:
  State.Ref((ref v) => {  v = v.next(); });

  // or best this:
  State.Ref(ref v => {  v = v.next(); });
}
```

I propose for some of the shorter forms I show above to be allowed Thanks!

**Comment by 333fred** [comment] 2020-12-27 23:05
Duplicate of https://github.com/dotnet/csharplang/issues/338.

**Closed by 333fred** 2020-12-27 23:05 UTC
