### ISSUE TITLE
{GET; SET;} CleanCode  -  Keyword "field"

### ISSUE THREAD

**Issue by srburton** [dotnet/csharplang#2647] opened 2019-07-10 20:24 UTC
Why declare a private `property` to have a` {get; set;}`?  We can have a `keyword` with the name I suggest from `field`  it would be that private property, leaving the code cleaner.

**Current**

```csharp
private int _property;
public  int Property {get => _property; set => _property = value;  };
```
**CleanCode**

Keyword suggestion:  `field`

```csharp
public  int Property {get => field; set => field = value;  };
```

**Comment by YairHalberstadt** [comment] 2019-07-10 20:28
In your example you could just use an auto property.

Can you give an example where an auto property wouldn't work?

By the way this is a duplicate of https://github.com/dotnet/csharplang/issues/140

**Comment by Joe4evr** [comment] 2019-07-10 20:38
Please search before opening new proposals.

**Comment by YairHalberstadt** [comment] 2019-07-10 20:41
@Joe4evr

I had to do a couple of Google searches before I found the original, and I knew it existed.

**Comment by srburton** [comment] 2019-07-10 20:49
@YairHalberstadt 

*Can you give an example where an auto property wouldn't work?*

```

  private Types _type { get; set; }

  public string Type
        {
            get => _types.Display<Types>(); 
            set
            {
                switch (value)
                {
                    case "recovery-payment":
                        _types = Types.RECOVERY_PAYMENT;
                    break;
                }
            }
        }

        public enum Types
        {
            [Display(Name = "recovery-payment")]
            RECOVERY_PAYMENT,
            ...            
        }

        //Extenssion 
        public string GetDisplay<T>(T value)
            => typeof(T)
                    .GetMember(value.ToString())
                    .First()
                    .GetCustomAttribute<DisplayAttribute>()
                    .Name;

```


**CleanCode**

Observation: 

The `field`, we can see that it behaves like a `var`, it is not necessarily the same type of parent, so we will have more possibilities and a cleaner code, merging the keyword is like checker gets a beautiful thing.

```
  public string Type
        {
            get => (field is Types)?  field.Display<Types>() :  default; 
            set
            {
                switch (value)
                {
                    case "recovery-payment":
                        field = Types.RECOVERY_PAYMENT;
                    break;
                }
            }
        }

        public enum Types
        {
            [Display(Name = "recovery-payment")]
            RECOVERY_PAYMENT,
            ...            
        }

        //Extenssion 
        public string GetDisplay<T>(T value)
            => typeof(T)
                    .GetMember(value.ToString())
                    .First()
                    .GetCustomAttribute<DisplayAttribute>()
                    .Name;

```

**Comment by Tom01098** [comment] 2019-07-10 21:43
I'm confused by what you mean when you say the backing store is *not* of the same type as the property, and how would this make the code cleaner?

**Comment by yaakov-h** [comment] 2019-07-10 22:39
Not being of the same type as the property is likely to be a non-starter.

It would either have to be the same type, `object`, or defined another way.

Using `object` has performance implications around boxing and type-casting.

If you define the backing field type another way, such as an attribute, then you may as well just declare a backing field instead.

**Comment by srburton** [comment] 2019-07-11 11:33
@Tom01098 


The `field` would be like a `var` that virtual, so for deserialization or conversions that most of the time
 `{get; set;}` is used, 99% of C # codes use `{get => ...; set => ...}` for the conversion of values with the file annihilate replicate value of the same patrimony repeated so that private, what is the current sense of having 2 properties a public and a _private?

**Comment by Tom01098** [comment] 2019-07-11 11:39
@srburton I have no idea what you mean here. Even so, `var` is only allow for local variables as it is not 'I don't know the type' it is 'the type is obvious from its use'. Your `field` keyword cannot be implicitly typed, just like how your backing store cannot be.

**Comment by HaloFour** [comment] 2019-07-11 11:52
"Cleaner code" does not mean less code, it means easier to read code.  Having the compiler (and the developer) have to guess at the actual type of the backing field and all of the performance/behavior characteristics that goes along with that is pretty much the opposite of clean.  If you want a backing field that is of a different type from the property it seems quite appropriate that you should have to manually declare that field.

**Comment by Unknown6656** [comment] 2019-07-11 12:02
Mentioned before / duplicates:
#1880
#1712
#1643
#1497
#1420
#1290
#1240
(#1059)
#626
#318
#140
#133

**Closed** 2019-07-11 13:48 UTC

**Comment by Unknown6656** [comment] 2020-04-04 10:50
Considered in https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-04-01.md
