### ISSUE TITLE
Conditional operators and definite assignment

### ISSUE THREAD

**Issue by AndreasHeisel** [dotnet/csharplang#3659] opened 2020-07-09 05:42 UTC
I first reported this at the [roslyn repository](https://github.com/dotnet/roslyn/issues/45776) , but was told that this is a language thing.

I purpose to refine the  [definite assignment specification](https://github.com/dotnet/csharplang/blob/master/spec/variables.md#definite-assignment) to cover the case described below:

I don't understand why I get an error if I use ?. but not if I use != null in the example below.

Version Used:

Visual Studio 16.6.3, .NET Core 3.1 Console Application

Steps to Reproduce:

```csharp
using System.Collections.Generic;

namespace RoslynTest
{
	class Program
	{
		class SomeClass
		{
			public Dictionary<string, string> SomeProperty { get; } = new Dictionary<string, string>();
		}

		static SomeClass? MyProperty { get; }

		static void Main(string[] args)
		{
			{
				// Doesn:t work
				if (MyProperty?.SomeProperty.TryGetValue("key", out var value) == true)
				{
					//Error CS0165  Use of unassigned local variable 'value'  RoslynTest C:\Users\h165\source\repos\RoslynTest\RoslynTest\Program.cs 21  Active
					value.ToString();
				}


				// Works
				if (MyProperty != null && MyProperty.SomeProperty.TryGetValue("key", out var value2))
				{
					//no error
					value.ToString();
				}
			}
		}
	}
}
```
Expected Behavior:

No errors

Actual Behavior:

CS0165

**Comment by yaakov-h** [comment] 2020-07-09 07:09
#3365 proposes to make this possible.

**Comment by jnm2** [comment] 2020-07-09 15:14
Direct duplicate of #3365

**Comment by 333fred** [comment] 2020-07-09 15:30
Closing as a duplicate m

**Closed by 333fred** 2020-07-09 15:30 UTC
