### ISSUE TITLE
Proposal Object and Collection initializer enhancement

### ISSUE THREAD

**Issue by NoofSaeidh** [dotnet/csharplang#1707] opened 2018-07-12 09:38 UTC
Now we have object and collection initializers for constructs:
```
var cls = new Class
{
  String = "string",
  Int = 5,
  InnerClass = { String = "innerString" }
};

var col = new List<string>{ "a", "b"};
```

But when you receive already initialized object and you need to fill properties of it (especially with inner complicated properties) you have to do it in the old style. It happens often with static initialization methods:
```
var cls = Class.New();
cls.String = "string";
cls.Int = 5;
cls.InnerClass.String = "innerString";

var col = GetList();
col.Add("a");
col.Add("b");
```

Propose is to add object and collection initializer into already initialized entities:
_first option (only for methods and properties):_
```
var cls = Class.New()
{
  String = "string",
  Int = 5,
  InnerClass = { String = "innerString" }
};

var col = var col = GetList(){ "a", "b"};
```
_second option (can be used anywhere in code):_
_but i'm not sure which syntax could be used_
```
var cls = Class.New();

// but in this case not so obvious that it isn't constructor here
// and intersection with array initialization

cls = {
  String = "string",
  Int = 5,
  InnerClass = { String = "innerString" }
}

// or without '-':
cls  {
  String = "string",
  Int = 5,
  InnerClass = { String = "innerString" }
}

// or perhaps with a new operator
cls := {
  String = "string",
  Int = 5,
  InnerClass = { String = "innerString" }
}
```

But i think the first approach will be enough.

**Comment by ufcpp** [comment] 2018-07-12 09:44
https://github.com/dotnet/csharplang/issues/803

**Comment by YairHalberstadt** [comment] 2020-10-18 06:39
Closing as duplicate of #803

**Closed by YairHalberstadt** 2020-10-18 06:39 UTC
