### ISSUE TITLE
Overload resolution chooses wrong overload for FormatableString

### ISSUE THREAD

**Issue by popcatalin81** [dotnet/csharplang#1417] opened 2018-03-27 17:30 UTC
**Version Used**: 7.1 

The following snippet shows how using a formattable string uses the wrong overload of write:

```CSharp
class Program {
	static void Main()
	{
		Write($"Hello there {DateTime.Now}");	
	}
	static void Write(string text)
	{
		Console.WriteLine("unformated");
	}
	
	static void Write(FormattableString text)
	{
		Console.WriteLine("formated");
	}
}
```

**Expected Behavior**:
`formatted`

**Actual Behavior**:
`unformatted`

As a note explicitly casting the formattable string to FormatableString produces the correct results:

```CSharp
Write((FormattableString)$"Hello there {DateTime.Now}");

Outputs: formatted
```

This is an unfortunate design and forbids the use of formattable string exactly in the place it would be most useful: Logging, and more specifically structured logging.

Yes, this feature has shipped and there's no way to fix overload resolution at this stage, however, there are some potential solutions:

  - Using an attribute to indicate a different overload preference:

```CSharp
	static void Write(string text)
	{
		Console.WriteLine("unformatted");
	}

	[FormattablePreffered]
	static void Write(IFormattable text)
	{
		Console.WriteLine("formatted");
	}
```
 - Using a more generic mechanism, that would allow choosing a generic overload over a method taking an object which happens presently :

```CSharp
class Program {
	static void Main()
	{
		Write(1);
	}
	
	static void Write(object value)
	{
		Console.WriteLine("object");
	}

	[PreferredOverload]
	static void WriteT<T>(T value)
			where T:ISpanFormattable
	{
		Console.WriteLine("ISpanFormattable");
	}

  // Current C# 7.1 outputs: object
  // Expected: ISpanFormattable
}
```

**Comment by jnm2** [comment] 2018-03-27 18:52
Duplicate of https://github.com/dotnet/csharplang/issues/675.

**Closed** 2018-03-28 00:25 UTC
