### ISSUE TITLE
Allow Null-conditional (?) operator for method parameters

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/csharplang#3802] opened 2020-08-17 07:20 UTC
Suggest to allow Null-conditional (?) operator for method parameters

The next code
```
var result  = Method(foo?, bar?);
```

will be compiled as next code
```
var result = (foo is not null && bar is not null) ? Method(foo, bar) : default;
```

Also allow Null-conditional (?) operator for loops and etc. see #2727

**Comment by theunrepentantgeek** [comment] 2020-08-17 07:37
I would expect this to be a fertile source of subtle bugs.

Think about what it would look like with non-trivial parameters being passed to the method, with the method call itself spread across several lines. 

One could easily miss the `?` that completely prevents the method from being called... but only _sometimes_. (Especially if it happened to be at the end of a line and out of view.)

**Comment by YairHalberstadt** [comment] 2020-08-17 07:49
On the one hand I would use this a lot - just today I was writing `if (item is not null) set = set.Add(item);` instead of `set = set.Add(item?) ?? set;`.

On the other hand, as @theunrepentantgeek said, it's quite subtle. 

It also introduces a kind of backwards control flow, where I have to read ahead to see if something earlier would be evaluated. Whilst this would already be the case if one of the parameters threw an exception, exceptions are not used as a primary means of controlling flow, and so I don't mind if the control flow is a bit confusing. I would be less enthusiastic about having this as part of the regular control flow.

Do you know of any other languages that have this sort of control flow construct? That would provide extremely useful data on whether people find this intuitive or confusing/a source of bugs.

**Comment by svick** [comment] 2020-08-17 19:17
This is a duplicate of https://github.com/dotnet/csharplang/issues/433, except with a different syntax: suffix `?` here vs. prefix `?` there.

**Comment by 333fred** [comment] 2020-08-17 21:35
Closing as a duplicate. Feel free to suggest this alternative syntax in that thread.

**Closed by 333fred** 2020-08-17 21:35 UTC
