### ISSUE TITLE
[Proposal]: Non-Compile Time Constant Default method parameter values

### ISSUE THREAD

**Issue by digitalcreature** [dotnet/csharplang#3947] opened 2020-09-27 12:17 UTC
# Non-Compile Time Constant Default method parameter values

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Right now, when declaring default values for method parameters, the expression must be a compile-time constant. Sometimes it would be nice to be able to declare a default value that is evaluated at call-time, such as instantiating a default object or struct.
```cs
// allowed
void Foo(Random rng = null) {
  // do something
}
// not allowed
void Bar(Random rng = new Random()) {
  // do something
}
```
## Motivation
[motivation]: #motivation

The current workaround for this is to use a method overload, or to check for a compile time default value such as null:
```cs
// check for null
void Foo(Random rng = null) {
  rng = rng ?? new Random();
 // do something
}

// overload
void Bar(Random rng) {
  // do something
}
void Bar() => Bar(new Random());
```
The former introduces a branch whose evaluation is known at compile time based on call site, but needs to be evaluated at every call. It also prevents passing the value null when it is desired as it will always be overwritten.
The latter is simple enough with one parameter, but it gets unwieldy with additional parameters, as well as 2^n overloads for a method with n parameters with non-comptime constant values. This is excessive boilerplate.
## Detailed design
[design]: #detailed-design

Implementation should be trivial with lowering. Simply generate the needed overloads when these such parameters are encountered.

**Comment by YairHalberstadt** [comment] 2020-09-27 12:36
> Implementation should be trivial with lowering. Simply generate the needed overloads when these such parameters are encountered.

Which overloads should be generated in the following case:

```csharp
M(List<int> a = new List<int>, List<int> b = new List<int>)
```

**Comment by HaloFour** [comment] 2020-09-27 12:49
@digitalcreature 

> Implementation should be trivial with lowering. Simply generate the needed overloads when these such parameters are encountered.

As @YairHalberstadt highlights overloads cannot be generated for methods with default parameter values due to the fact that they will create collisions where two such overloads will have the same signature.  Even if that was not the case it doesn't take too many optional parameters before you result in an explosion of overload methods.

**Comment by YairHalberstadt** [comment] 2020-09-27 13:01
A lowering method that could work would be this:

```csharp
void M(List<int> a = new List<int>(), List<int> b = new List<int>()) {...}
```
Is lowered to:

```cshahrp
void M([Optional, DefaultValueMethodCall("DefaultValue<>M<>List`1<>List`1<>0")] List<int> a, [Optional, DefaultValueMethodCall("DefaultValue<>M<>List`1<>List`1<>1")]] List<int> b) {...}

public DefaultValue<>M<>List`1<>List`1<>0 => new List<int>();
public DefaultValue<>M<>List`1<>List`1<>1 => new List<int>();
```

And then at the callsite generate: 

```csharp
M(DefaultValue<>M<>List`1<>List`1<>0, DefaultValue<>M<>List`1<>List`1<>1)
```

**Comment by HaloFour** [comment] 2020-09-27 13:03
Scala has an interesting way of enabling expressions for default values for optional parameters.  It emits another method on the type declaring the method which contains the expression.  When you omit the optional parameter at the call site the compiler automatically emits an invocation of that method to obtain the default parameter value which it then embeds into the call.  So you write something like this:

```cs
class Program
{
    void Foo(DateTime date = DateTime.Now) => Console.WriteLine(date);

    void Bar()
    {
        Foo();
    }
}
```

and the compiler emits (something like) this:

```cs
class Program
{
    void Foo([Opt("Foo_date")] DateTime date) => Console.WriteLine(date);

    DateTime Foo_date => DateTime.Now;

    void Bar()
    {
        Foo(Foo_date);
    }
}
```

While it does enable these expressions it is also brittle in a couple of ways.  It exposes the negotiation of the default parameter to the public surface of the type, and changes to the default values can break existing consumers.  That's currently not a problem as the default value is only negotiated by the compiler and embedded directly in the call.

**Comment by YairHalberstadt** [comment] 2020-09-27 13:03
Also duplicate of https://github.com/dotnet/csharplang/issues/1702

**Comment by digitalcreature** [comment] 2020-09-27 13:44
> > Implementation should be trivial with lowering. Simply generate the needed overloads when these such parameters are encountered.
> 
> Which overloads should be generated in the following case:
> 
> ```cs
> void M(List<int> a = new List<int>(), List<int> b = new List<int>()) {...}
> ```

```cs
void M(List<int> a) => M(a, new List<int>());
voic M() => M(new List<int>(), new List<int>());
```
Overload generation follows the current way method calls with default parameters are determined.
For example:
```cs
void Foo(int a = 0, int b = 1) {
  Console.WriteLine($"{a}, {b}");
}

Foo(4, 5); // 4, 5
Foo(4);    // 4, 1
Foo();      // 0, 1
```
Because we know that calling with one argument would always assign that value to the first of the two parameters with the same type, we'd generate only the overloads that follow this pattern.

**Comment by HaloFour** [comment] 2020-09-27 13:54
@digitalcreature 

That doesn't take into account named parameters and would make the following impossible:

```cs
Foo(b: 4);  // 0, 4
```

**Comment by digitalcreature** [comment] 2020-09-27 13:55
@HaloFour Good point. I suppose we could do some name mangling and do lowering at the callsite as well.... not as elegant, but possible.

**Comment by YairHalberstadt** [comment] 2020-09-27 14:44
@digitalcreature there are plenty of methods with 20 optional parameters. That would require generating over a million methods!

**Comment by digitalcreature** [comment] 2020-09-27 14:52
@YairHalberstadt we would only generate overloads for non-constant default parameters; I can't imagine many use cases that would require that many nonconst optionals. Also having 20 parameters in the first place seems like bad practice, I doubt there can really be that many of them.

**Comment by HaloFour** [comment] 2020-09-27 15:04
> we would only generate overloads for non-constant default parameters;

That could make changing the default value a breaking change.  There are a lot of cases where it's not obvious whether changing the expression would lead to such a break, such as `default(CancellationToken)` and `CancellationToken.None`.

> Also having 20 parameters in the first place seems like bad practice

The reason support for optional parameters was added to C# at all was to improve the story with Office interop, where it's normal for methods to have a large number of optional parameters.  From what I understand the teams originally tried to solve the problem with tooling that would generate overloads but that caused all of the problems listed above and was determined to be an untenable solution.  Adding optional parameters (and a few other language features) was a compromise.

**Closed** 2020-09-27 16:29 UTC
