### ISSUE TITLE
Implicitly scoped fixed statement

### ISSUE THREAD

**Issue by RUSshy** [dotnet/csharplang#3849] opened 2020-09-04 20:39 UTC
We have ``using var disposable = new Disposable()``

Can we please have the same for fixed? ``fixed byte* ptr = buffer``

**Comment by 333fred** [comment] 2020-09-04 21:15
Duplicate of https://github.com/dotnet/csharplang/issues/2186.

**Closed by 333fred** 2020-09-04 21:15 UTC

**Comment by RUSshy** [comment] 2020-09-04 22:28
Oops my bad, i made sure to search before posting, i couldn't find anything about it

Thanks!
