### ISSUE TITLE
[Proposal]: ignored directives

### ISSUE THREAD

**Issue by jcouv** [dotnet/csharplang#4745] opened 2021-05-12 19:23 UTC
# ignored directives

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

The feature is to allow some directives to be parsed and ignored by the language (like trivia), such as `#! ...` and `#r ...`.

## Motivation
[motivation]: #motivation

We'd like to allow scenarios like `dotnet run hello.cs`. This involves embedding some information which traditionally belonged in a project file into a C# file.
See [broader design proposal](https://github.com/dotnet/designs/pull/213).

## Design meetings

- LDM 5/12/2021

**Comment by 333fred** [comment] 2021-05-12 21:04
Closing as a duplicate of https://github.com/dotnet/csharplang/issues/3507.

**Closed by 333fred** 2021-05-12 21:04 UTC
Labels: Proposal, Proposal champion
