### ISSUE TITLE
using aliases broken for tuples

### ISSUE THREAD

**Issue by mqudsi** [dotnet/csharplang#1003] opened 2017-10-15 20:31 UTC
Not sure if this is by design, but while this works:

```csharp
using CustomType  = System.Collections.Generic.List<Object>
```

this doesn't:

```csharp
using CustomType = (int, int)
```

**Comment by svick** [comment] 2017-10-15 21:56
This looks like a duplicate of https://github.com/dotnet/csharplang/issues/423.

**Closed** 2020-09-08 23:45 UTC
Labels: Discussion, Feature Request, Move to Discussion
