### ISSUE TITLE
bool type &= should have a short-circuit-evaluating form.

### ISSUE THREAD

**Issue by Normanator** [dotnet/csharplang#5894] opened 2022-03-07 22:33 UTC
Our team was surprised to find bool operators `&=` and `|=` didn't behave as the expected expanded forms, a = a && b and c = c || d, would have done.  For integer types, the bit-wise behavior is expected, but for bool it was less clear this should be applicable.  

```cs
isGood = true;
isGood &= expensiveTest1();
isGood &= expensiveTest2();    // desired: not to evaluate right-hand-side 
```

Have short-circuiting operators `&&=` and `||=` for bool been considered?

**Comment by CyrusNajmabadi** [comment] 2022-03-07 22:35
Dupe of https://github.com/dotnet/csharplang/issues/397

**Closed by CyrusNajmabadi** 2022-03-07 22:35 UTC
