### ISSUE TITLE
Proposal: Type aliases / abbreviations / newtype

### ISSUE THREAD

**Issue by louthy** [dotnet/csharplang#410] opened 2017-04-05 16:06 UTC
F# [has a feature called type abbreviations](https://fsharpforfunandprofit.com/posts/type-abbreviations/) where a more complex type can have an easier to use alias.  I am finding more and more (especially as I use structs as wrapper types to avoid null) that creating sub-classes for more bespoke behaviour is either impossible or unnecessarily heavyweight.
```c#
    // Implicit alias
    public implicit alias IntMap<T> = Dictionary<int, T>;

    // Usage
    var x = new IntMap<string>();

    // Explicit alias
    public alias Month = int
        where value >= 1 && value =< 12;
```
> This is similar to the `using MyAlias = MyType`, but is parametric, generates a new type, and works across assemblies.

For further discussion is the notion of a predicate for the `value` that is run on construction and can be used to constrain the type further:
```c#
    public alias Year = int 
        where value > -5000 && value < 5000;

    public alias Month = int 
        where value >= 1 && value <= 12;

    public alias Day = int 
        where value >= 1 && value <= 31;

    public alias Username = string
        where value.Length > 0;

    public alias Password = string
        where value.Length > 6 && 
              value.Exists(Char.IsLetter) && 
              value.Exists(Char.IsDigit) &&
              value.Exists(Char.IsPunctuation);
```
The constraint would be injected into the constructor of the generated type alias (which would throw an `ArgumentOutOfRange` exception if it returns `false`).  And could also be used be tooling to do flow analysis on whether 'bad values' were likely to get into the type.

One technique that I have been using a lot recently is to embed validation into a type.  Although I think this is likely to be very niche (because it's bulky to use right now), I think it opens up a ton of useful functionality that is similar to dependently typed languages.  

Here's a simple example with a bespoke list implementation. This makes use of the concepts idea that has been previously investigated by the Roslyn team:
```c#
    public interface Pred<A>
    {
        bool IsTrue(A value);
    }

    public struct NonEmpty<A> : Pred<IReadOnlyList<A>>
    {
        public bool IsTrue(IReadOnlyList<A> list) => 
            list.Count > 0;
    }

    public struct Any<A> : Pred<IReadOnlyList<A>>
    {
        public bool IsTrue(IReadOnlyList<A> list) => 
            true;
    }

    public struct List<PRED, A> : IReadOnlyList<A>
        where PRED : struct, Pred<IReadOnlyList<A>>
    {
        A[] items;

        public List(IEnumerable<A> items)
        {
            // Initialise the list
            this.items = items.ToArray();

            // Runs the predicate validation
            if(!default(PRED).IsTrue(this)) throw new ArgumentOutOfRangeException(nameof(items));
        }

        // ... Implementation of the IReadOnlyList interface
    }
```
The `PRED` generic argument allows for validation behaviour to be injected into the _type_ and the _value_.  And therefore the compiler can do a ton of validation for free:
```c#
    public int Product(List<NonEmpty<int>, int> list)
    {
        var result = list.First();
        foreach(var item in list.Skip(1))
        {
            result = result * item;
        }
        return result;
    }
```
That means `Product` can't ever get a type that represents an empty list.  e.g.
```c#
    var x = new List<Any<int>, int>(new int [0]);
    var y = new List<NonEmpty<int>, int>(new int [0]);   // Compiles, but throws at run-time
    var z = new List<NonEmpty<int>, int>(new [] { 1, 2, 3, 4  });

    var res1 = Product(x);        // Invalid type, won't compile
    var res2 = Product(y);        // Won't ever get here because y can't be constructed
    var res3 = Product(z);        // Works
```

Clearly passing around `List<NonEmpty<int>, int>` is very annoying, and so a type-alias of:
```c#
    public alias NonEmptyList<A> = List<NonEmpty<A>, A>
```
Would be great, and would make `Product` much more declarative and easy to parse:
```c#
    public int Product(NonEmptyList<int> list)
    {
        var result = list.First();
        foreach(var item in list.Skip(1))
        {
            result = result * item;
        }
        return result;
    }
```
This is just one example of where this would be useful and lead to more explicit and declarative code (in my humble opinion).  Obviously with the constraints it would be possible to do this:
```c#
    public alias NonEmptyList<A> = List<A>
        where value.Count > 0;
```

I would prefer it to go much further than the F# version, and make the alias work more like Haskell's `newtype`.  That is it's essentially not implicitly convertible with the type it's aliasing.  That makes it trivial to represent lighterweight concepts like:
```c#
    public alias UserId = int where value > 0
    public alias FirstName = string where value.Length > 0
    public alias Surname = string where value.Length > 0
```
We could then have methods like:
```c#
     public User AddUser(UserId id, FirstName first, Surname last) => ...
```
Which would kill another common set of bugs in C#, namely that `int`, `string`, etc. are essentially 'untyped' (they have a type, but the type doesn't represent the data stored within it).

```c#
    public DateTime CreateDate(int year, int month, int day) => ...
```
Can anyone say they've never fallen over on something like this ^^^.

```c#
    public alias Year = int
    public alias Month = int
    public alias Day = int

    public DateTime CreateDate(Year year, Month month, Day day) => ...
```
I think calling `new` to instantiate an aliased type is fine, but I would prefer this:
```c#
    CreateDate(Year(2017), Month(4), Day(5));
```
To this:
```c#
    CreateDate(new Year(2017), new Month(4), new Day(5));
```
We should allow explicit conversions though:
```c#
    CreateDate((Year)2017, (Month)4, (Day)5);
```

I expect under-the-hood for the compiler to create a new type for this, which should be a lightweight struct:
```c#
    public struct NewType<A>
    {
        public readonly A Value;
        public NewType(A value) => Value = constraintExpr
             ? value
             : throw new ArgumentOutOfRangeException(nameof(value));
        public static explicit operator NewType<A>(A value) => new NewType<A>(value);
        public static implicit operator A(NewType<A> value) => value.Value;
    }
```
So `Year` would be:
```c#
    [AliasOf(typeof(int))]
    public struct Year
    {
        public readonly int Value;
        public Year(int value) => Value = constraintExpr
             ? value
             : throw new ArgumentOutOfRangeException(nameof(value));
        public static explicit operator Year(int value) => new Year(value);
        public static implicit operator int(Year value) => value.Value;
    }
```
And then the compiler can inject the `Value` indirection and re-wrap with the single argument constructor.  Obviously this comes with a run-time cost, but it is relatively small for such a powerful feature. 

The `AliasOf` attribute could be a hint for tooling.

I'm a strong believer that types should be the guidance to the programmer rather than variable names, because variable names don't persist from the input of a function to the output, whereas types do.

_(by the way I'm aware of the limitation of `new List<NonEmpty<A>, A>()` when the type is a `struct`, I want to raise that as a separate issue)_

**Comment by sirgru** [comment] 2017-04-05 16:30
If I understand correctly, part of what you'd like is already available, this code compiles.

``` C# 
namespace ConsoleApplication1 {
    using UserId = Int16;
    using FirstName = String;
    using SurName = String;
    using IntMapToString = Dictionary<int, string>;

    class Program {
        static void Main(string[] args) {
        }

        void Test(UserId userId, FirstName firstName, SurName surName) {
            // Do stuff here.
        }
    }
}
```
Using `using` with generics is not possible though,

**Comment by louthy** [comment] 2017-04-05 16:53
@sirgru That only works within a single compilation unit (a single source file).

**Comment by sirgru** [comment] 2017-04-05 17:00
Yes. I think there could be value in allowing it to be scoped the same way as the namespace and allowing this to compile:
```C#
 using IntMap<T> = Dictionary<int, T>;
```

**Comment by louthy** [comment] 2017-04-05 17:01
In reality it's just really annoying having to specify it for every source file, and has none of the constraints I listed.

**Comment by jnm2** [comment] 2017-04-05 17:23
This proposal adds on #259, improving it in a way that would be [extremely helpful for me](https://github.com/dotnet/csharplang/issues/259#issuecomment-286110157).

> Whatever we do here, I hope we don't block a future CLR improvement where I can declare a runtime type alias, enabling me to change the name of a type without breaking source or binary compatibility.

**Comment by scottdorman** [comment] 2017-04-06 00:04
@jnm2 What does this add to #259? I see these as being the same. What am I missing?

**Comment by fanoI** [comment] 2017-04-06 08:27
My preoccupations is they resembles too much C typedef, then when I'll use another library I find an IntMap<T> and how I should know that is a Dictionary with another name?

Calling and int "Year" seems yet more a typedef without any real value something as C "size_t" that in reality is simply an it :-(
It will be different if "Day" while being an int (with all operators working!) will have the added value of the validation (only a positive number between 1 and 31).

**Comment by sirgru** [comment] 2017-04-06 09:34
I think in addition to the desires of #259 proposal, this proposal brings a couple of functional programming habits into C#. For example, the desire to clearly carve out the limitations of a type and carry them explicitly in the type definition. 

IMHO this does not work in C# because all users have to construct that specific limited type for every argument of the methods they are calling. This brings a lot of extra work on the client's side and "over-specification" that does not necessarily bring further clarity. They aim to bring the "documentation of limitations with the type" but it ends up being a burden to bring it everywhere. The classic, dead-simple way to do it, check arguments and bail as soon as they are invalid:

``` C#
class DateTime {
    public DateTime(int year, int month, int day) {
        if(!IsValidDate(month, day)) throw new System.ArgumentOutOfRangeException("Unexpected value range for month / day.");

        // Do work
    }

    private bool IsValidDate(int month, int day) {
        // Do work
        return true;
    }
}

class User {
    void Operation() {
        var date = new DateTime(year: 2017, month: 4, day: 6);
    }
}
```
To me, this is 10x clearer because:
1) The `DateTime(year: 2017, month: 4, day: 6);` will always avoid the perceived error of mixing the arguments.
2) Throwing exceptions is the preferred signaling method that something unexpected is happening, with arguments and otherwise. As proposed, the exception is still thrown but the throwing point is in the predicate and not at the natural spot of checking for validity. This could bring less clarity when debugging.
3) In C#, this does not guard us from doing anything wrong, as mentioned:
```C# 
var y = new List<NonEmpty<int>, int>(new int [0]);   // Compiles, but throws at run-time 
```
so, the only purpose of carrying these properties within the type is to carry the documentation with the definition. The exception will be thrown at the call site either way, and no further compile time safety is gained.
4) If there is a lot of these constraints on a type, then in a general case some other abstraction can be made in an OOP way and the checks can be done there. 

I think this proposal sees the bulky-ness of the solutions, and tries to create additional language features to combat that.

**Comment by louthy** [comment] 2017-04-06 11:48
> Calling and int "Year" seems yet more a typedef without any real value something as C "size_t" that in reality is simply an int :-(

It isn't simply an `int`, it's a `Year` that happens to be backed by an `int`.  It stops programmers accidentally providing a `Day` where the `Year` should be.  

> It will be different if "Day" while being an int (with all operators working!) will have the added value of the validation (only a positive number between 1 and 31).

I agree, see [my comment on the Constrained Types](https://github.com/dotnet/csharplang/issues/413#issuecomment-292064891) proposal.  Extending this to contain a predicate of some sort would be great, but I already know there's value to strongly typing integers as I'm using it with the `NewType` feature I talk about in that comment.  It's also great for `Func` signatures to describe exactly what the expected parameters are.

I think a constrained type system should be part of a general type system improvement, rather than something specifically for alias types.

> To me, this is 10x clearer because:

You're taking one example, then using a technique that isn't enforced by the compiler and saying 'this works'.  Are you saying you've never been confused over a signature that takes ints, strings, bools, etc.?  Have you never had an `int` input variable get accidentally assigned to the wrong thing mid-method and because there's no compiler errors the value has propagated and caused issues later?

> so, the only purpose of carrying these properties within the type is to carry the documentation with the definition. 

No, it's to enforce type-safety for the life of the object.  The self documenting declarative nature of it is a very, very nice side-effect.

> The exception will be thrown at the call site either way, and no further compile time safety is gained.

Having an exception thrown at the source of the error is a most valuable feature.  Just like nullable references are walking time-bombs that need to be constantly checked, so are integer and string values, because they don't have a 'context'.  The example of a NonEmptyList, you want to know at the source of the instantiation that the type isn't going to work later when it's propagated through myriad functions.

**Comment by louthy** [comment] 2017-04-06 11:59
I have added some example syntax for how a possible constrained alias might work:
```c#
    public alias Year = int 
        where value > -5000 && value < 5000;

    public alias Month = int 
        where value >= 1 && value <= 12;

    public alias Day = int 
        where value >= 1 && value <= 31;
```
The idea would be that the `where` expression is injected into the constructor for the new type, and would throw an `ArgumentOutOfRange` error if the expression returns `false`.

**Comment by yaakov-h** [comment] 2017-04-06 12:13
That sounds an awful lot like the contracts proposal(s).

**Comment by sirgru** [comment] 2017-04-06 12:30
What I was trying to say is that for the vast majority of general cases this kind of overt argument specification isn't needed, in Visual Studio there's the popup which displays the name of the next argument so the chance of such error is really low in this day and age.

The non-null reference types are coming in the next versions of C#. I can understand the need to put these base types in context, but if the constraints are tied to the type then the new type can be created manually just like you've shown above. I believe most of the arguments in most APIs are user-defined types, and where the arguments are base types they can have specific constraints on the constructor, and all further work is not with base types but the "now properly constructed" type. I would find it superfluous to have a Year type whose only purpose is to be a type for the constructor at one place, I would rather have the checks inside the constructor and work with Date from there. Same general logic can apply in other cases.

Just my opinion though.

**Comment by louthy** [comment] 2017-04-06 12:42
@sirgru I think you're possibly thinking a bit too narrowly about short term usage of base types.  Of course we can do this validation manually every time a value is used, like we do with `null` reference checking.  But I'm thinking more about types that have a context (like `Month`), but once they're stored as an `int` that information is lost; the name of a variable can't enforce the rules of the type, no matter how obvious you think it is at the point of use.  A good example is the common error in javascript with zero indexed months.  That's an example of where an out-by-one error could propagate.

This is common thinking in functional languages, where the types are the 'point of truth' and not relying on imperatively injected validation throughout an app.  The type system validates much more at compile time rather than relying purely on runtime checks (which may be missing, and is therefore impossible for the compiler to reason about).

**Comment by jnm2** [comment] 2017-04-06 12:59
@scottdorman #259 is explicitly asking for aliases internal to an assembly; my only need is for aliases that act externally.

**Comment by DerpMcDerp** [comment] 2017-04-07 21:35
One major problem with this proposal is that sometimes type predicates are dependent on others, e.g. `Day` should be dependent on `Month` and `Year` in the example given in this proposal.

A more common example is `Index`:

```C#
public alias NonNegative = int where value >= 0;
public alias Index<T>(ICollection<T> collection) = NonNegative
    where value <= collection.Count;

void Foo(IList<T> list, Index(list) index) { ... }
```

Where you want it to use the collection `Count` rather than just being non-negative.

**Comment by ufcpp** [comment] 2017-04-08 02:53
I really like this feature but it could be achieved by [Source Code Generator](https://github.com/dotnet/csharplang/issues/107) as I listed in [Code Generator Catalog](https://github.com/dotnet/csharplang/issues/341).

On the other hand, if you want constraints on types, [ "defaultability" checking](https://github.com/dotnet/csharplang/issues/146) might be also needed.

**Comment by jnm2** [comment] 2017-04-08 13:01
@ufcpp Source generators don't help when what you're doing is using type aliases to rename an existing type without breaking binary compatibility of assemblies built against that type.

**Comment by louthy** [comment] 2017-04-10 16:08
@DerpMcDerp 

> One major problem with this proposal is that sometimes type predicates are dependent on others, e.g. Day should be dependent on Month and Year in the example given in this proposal.

That isn't a problem with this proposal, it's a problem with the example in this proposal.  What you're suggesting is a much more complicated proposal which is more akin to dependently types languages.  I'm not saying that's not desired (I'd love it), but it's out of the scope of this relatively simple proposal.

**Comment by jmagaram** [comment] 2017-04-27 04:48
I see the value of creating new "primitive" types with built-in validation that match the real-world domain. Although you can validate method parameters and throw before stuffing invalid data into a string or int we lose meaning. `EmailAddress` is so much easier to grok than `string`. Custom primitives could help solve the "primitive obsession" code smell. Enums feel really good to use because they specifically model whatever we're trying to represent and limit our choices to valid ones, but we don’t get this same experience working with numbers and strings. With custom primitives there would be less chance of mixing up incompatible domains like UserId and ProductId where both are represented by Guid. Func and Action delegates are easier to understand without having to add parameter names. Tuples become easier to understand too without component names.

A very basic implementation like `public alias Month = int` that disallowed implicit conversion could make code a bit more self-documenting and maybe a little more safe. But the alias type doesn’t mean very much. An int is NOT a month unless it is limited to a particular range.

One step up is adding basic validation like `public alias Month = int where value >= 1 && value <= 12;` This could be useful. You’d need some way to ensure a valid default.

My biggest concern is that this proposal doesn’t go far enough. For example, it is helpful to have data validation rules defined in one place and use them in the data persistence layer, business layer, and UI. In the UI you need to generate validation errors of various types. So an EmailAddress type could benefit from static members like `IEnumerable ValidationErrors(string email)`. Just having a single Func<bool> is not enough. I’d want to do `public alias Month = int where MonthUtilitiesClass.IsValid`. You might want additional static constructor methods like Month.FromDateTime(DateTime d). Maybe you also want some instance methods, like a ToString that generates the English month name and though you could do this with extension methods right now it is more convenient to build it into the class.

In other words I think we really want to build full-blown classes AND structs to represent the small stuff and not just aliases.

Here is one implementation that uses classes. The biggest problems with this are (1) can’t stop null, and (2) performance – using reference type to often wrap a tiny value type. But otherwise it is totally flexible and customizable. It doesn’t take much effort to create a new tiny type.

    public abstract class Constrained<T>
    {
        private readonly T _value;

        public Constrained(T value, Func<T, bool> isValid)
        {
            if (!isValid(value)) throw new ArgumentOutOfRangeException(nameof(value));
            _value = value;
        }

        public static implicit operator T(Constrained<T> value) => value._value;

        public T Value => _value;

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            Constrained<T> other = (Constrained<T>)obj;
            return _value.Equals(other._value);
        }

        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public static bool operator ==(Constrained<T> a, Constrained<T> b) =>
            EqualityComparer<T>.Default.Equals(a._value, b._value);

        public static bool operator !=(Constrained<T> a, Constrained<T> b) =>
            !(a == b);

        public override string ToString() => _value?.ToString();
    }

    public class SurveyScaleRating : Constrained<uint>
    {
        public SurveyScaleRating(uint value) : base(value, IsValid) { }

        public static uint MinValue = 1;

        public static uint MaxValue = 10;

        public static IEnumerable<string> ValidationErrors(uint v)
        {
            if (v < MinValue) yield return "Too small.";
            else if (v > MaxValue) yield return "Too big.";
        }

        public static bool IsValid(uint v) => !ValidationErrors(v).Cast<object>().Any();
    }

    public class UserId : Constrained<Guid>
    {
        public UserId(Guid value) : base(value, v => v != Guid.Empty) { }
    }

But it is really unworkable to build this kind of thing using Struct. Without inheritance you have to custom build every tiny type and there is too much boilerplate. If there was some kind of inherit-only-once or code-generation for Struct that matched what you could do with Class, I think you'd be set.

**Comment by hardhub** [comment] 2017-05-17 23:42
Hopefully it will help to solve this spaghetti: Task<Output<ICollection<IUser>>>

**Comment by schotime** [comment] 2017-05-21 22:11
+100 for type alias'. Especially for string/int type types.

**Comment by hardhub** [comment] 2017-05-22 05:33
If somebody means global type aliases.. then it is important to allow them to be nested in class to narrow scope.

**Comment by gulshan** [comment] 2017-05-26 14:33
I think the simple aliasing (without constrains) can come first. And it should be discussed by language design team meeting as a simple but meaningful feature. Constrained types can be discussed later along with method contracts.

**Comment by orthoxerox** [comment] 2017-09-13 06:49
I agree with @gulshan, a more restricted feature for aliasing should come first. I imagine it could even avoid creating new types at all, something like this:

```c#
public newtype Email : string

public void SendEmail(Email to, IEnumerable<Email> cc, string subject, string body) { ... }
```

This is equivalent to:

```c#
public void SendEmail(
[NewType("Email")] string to, 
[NewType("IEnumerable<Email>")] IEnumerable<string> cc, 
string subject, 
string body)
{ ... }
```

This way programs compiled by older C# versions will be able to consume the API as is, using strings, but more modern programs will get an error when they try to pass a different newtype (say, Phone) instead of `Email`.

**Comment by svick** [comment] 2017-09-13 08:04
@orthoxerox With that approach, if I upgrade to a new compiler, my code suddenly stops compiling? I think that's not considered acceptable.

**Comment by orthoxerox** [comment] 2017-09-13 09:52
@svick that's what will happen if you upgrade to the compiler version supporting nullable reference types, too.

**Comment by svick** [comment] 2017-09-13 10:15
@orthoxerox It won't. Nullable reference types only cause warnings, not errors. And even then, it will be opt-in, based on the current proposal. From https://github.com/dotnet/csharplang/issues/790:

> A number of the features described would lead to breaking of existing code in the form of new warnings. The simplest "solution" to this is to simply put all the warnings under a big switch. […]

**Comment by orthoxerox** [comment] 2017-09-13 11:10
@svick you got me confused there for a moment and I gave a hasty incorrect reply. There won't be a compiler error in most cases, "original type to newtype" and "newtype to original type" conversions should be implicit. The only error would be a conversion from newtype X to newtype Y, which is only possible to get when upgrading your compiler when you either use an external assembly with newtypes incorrectly (so it's a real bug that you've caught) or when you use two external assemblies and pass a newtype from one of them into another expecting a different newtype (now that's a potential issue).

I'll think about the second pitfall some more.

**Comment by svick** [comment] 2017-09-13 11:34
@orthoxerox Ok, now that I understand what you meant, that does sound fairly reasonable.

**Comment by Johnny-Bee** [comment] 2018-05-11 13:29
@louthy IMO, we must have a more declarative way to create primitive types with constraints to be in phase with the swagger specification data types: https://swagger.io/docs/specification/data-models/data-types/
In our side we had to develop our own primitive abstract class to manage this kind of constraints in our custom code generation.

Please see below the abstract class we have created to fulfill our needs.

```


    public interface IPrimitiveType : IComparable
    {
        object Value { get; }
        Type GenericType { get; }
    }

    public interface IPrimitiveType<T> : IPrimitiveType, IEquatable<T>, IComparable<T>
    {
        new T Value { get; }
    }

    [DataContract]
    [Serializable]
    [TypeDescriptionProvider(typeof(PrimitiveTypeTypeDescriptionProvider))]
    [JsonConverter(typeof(PrimitiveTypeJsonConverter))]
    public abstract class PrimitiveType<TMySelf, T> : IPrimitiveType<T>, IFormattable, IValidatableObject
        where TMySelf : PrimitiveType<TMySelf, T>
        where T : IComparable
    {
        static PrimitiveType()
        {
            var valueType = typeof(T);
            if (!valueType.IsSimpleType())
            {
                throw new ArgumentException("The T parameter must be a simple type.");
            }

            if (valueType != typeof(string) && valueType != typeof(bool) && !typeof(IFormattable).IsAssignableFrom(typeof(T)))
            {
                throw new InvalidOperationException($"Cannot create PrimitiveType<{typeof(T).Name}> because it's not implementing {nameof(IFormattable)}.");
            }
        }

        /// <summary>
        /// Override this constructor with [JsonConstructor] attribute
        /// to allow deserialisation of PrimitiveTypes with values
        /// that are no longer possible throught normal constructor validation
        /// </summary>
        protected PrimitiveType() { }

        protected PrimitiveType(T value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            if ((value is Guid || value is DateTime) && value.IsNullOrDefault()) throw new ArgumentNullException(nameof(value));

            Value = value;

            var validationResults = Validate(null).ToArray();

            if (validationResults.Length == 0) return;
            if (validationResults.Length == 1) throw new ValidationException(validationResults[0].ErrorMessage);
            else throw new AggregateException(validationResults.Select(r => new ValidationException(r.ErrorMessage)));
        }

        public virtual IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }

        /// <summary>
        /// Return the validation context display name or name of the type.
        /// </summary>
        protected string SayMyName(ValidationContext validationContext) => validationContext.SayMyName(this);

        [NotNull]
        [DataMember]
        public T Value { get; private set; }

        #region IPrimitiveType Members

        object IPrimitiveType.Value => Value;

        [SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Justification = "F.Y.")]
        Type IPrimitiveType.GenericType => typeof(T);

        #endregion

        public override bool Equals(object other)
        {
            if (other == null)
            {
                return false;
            }
            if (other is T)
            {
                return this.Value.Equals(other);
            }
            if (!(other is TMySelf))
            {
                return false;
            }
            if (this.Value == null)
            {
                return (other == null);
            }
            return this.Value.Equals(((TMySelf)other).Value);
        }

        public override int GetHashCode()
        {
            return this.Value.GetHashCode();
        }

        public override string ToString() => Value.ToString();

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return (Value as IFormattable)?.ToString(format, formatProvider) ?? ToString();
        }

        public int CompareTo(object obj)
        {
            var implementation = obj as TMySelf;
            if (implementation != null)
            {
                return this.Value.CompareTo(implementation.Value);
            }
            else
            {
                return this.Value.CompareTo(obj);
            }
        }

        public virtual bool Equals(T other)
        {
            return this.Equals((object)other);
        }

        public virtual int CompareTo(T other)
        {
            return this.Value.CompareTo(other);
        }

        public static bool operator !=(PrimitiveType<TMySelf, T> a, PrimitiveType<TMySelf, T> b)
        {
            return !(a == b);
        }
        public static bool operator ==(PrimitiveType<TMySelf, T> a, PrimitiveType<TMySelf, T> b)
        {
            // If both are null, or both are same instance, return true.
            if (ReferenceEquals(a, b))
            {
                return true;
            }

            // If one is null, but not both, return false.
            if (((object)a == null) || ((object)b == null))
            {
                return false;
            }

            return a.Equals(b);
        }

        public static bool operator !=(PrimitiveType<TMySelf, T> a, T b)
        {
            return !(a == b);
        }
        public static bool operator ==(PrimitiveType<TMySelf, T> a, T b)
        {
            // If both are null, or both are same instance, return true.
            if (ReferenceEquals(a, b))
            {
                return true;
            }
            if (a == null
                 && (b is Guid && ((Guid)(object)b) == default(Guid)))
            {
                return true;
            }

            // If one is null, but not both, return false.
            if (((object)a == null) || ((object)b == null))
            {
                return false;
            }


            return a.Equals(b);
        }

        #region DO NOT USE IMPLICT OR YOU ARE GOING TO A WORLD OF PAIN!

        public static explicit operator T(PrimitiveType<TMySelf, T> PrimitiveType)
        {
            return PrimitiveType.Value;
        }

        public static explicit operator PrimitiveType<TMySelf, T>(T primitive)
        {
            if (primitive == null || (primitive is Guid && ((Guid)(object)primitive) == default(Guid)))
            {
                return null;
            }

            var ths = (TMySelf)Activator.CreateInstance(typeof(TMySelf), primitive);
            return ths;
        }

        #endregion
    }


```

We use it like this:

```

  [Serializable]
    [DataContract]
    public class UserId : PrimitveType<UserId, Guid>
    {
        public UserId(Guid value) : base(value)
        {
        }
    }

```



```

 [DataContract]
    [Serializable]
    public class Percent : PrimitveType<Percent, decimal>
    {
        public Percent(decimal value) : base(value)
        {
        }

        public override IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Value < 0 || Value > 100)
                yield return new ValidationResult($"{SayMyName(validationContext)} is not a valid percentage.");
        }
    }

```

As you can see we had some trouble in the json serialization, we apply the validation after the deserialization is done to avoid error management during the deserialization and response the list of errors in case of bad request.

Of course this code is incomplete, if you need more info don't hesitate to ask me.

**Comment by chrisrollins** [comment] 2018-08-31 20:34
I have run into a problem which reminded me of this. I am working on a library which exposed some delegate types meant to be passed by application code. The problem I found is that delegate don't seem to be compatible with methods. You can pass lambda expressions but if you want to pass a method you are out of luck. This was fixed by switching from delegates to Func and Action types. Now this is a bit awkward because either I have to explicitly define the types in each parameter or have using statements in each file. Of course I opted for using statements, but that meant I had to go through each file which needed them and add them separately. This is a case where better aliasing mechanics would be useful. Alternatively it would be nice to see some improvements to delegate type resolution and things like that.

**Comment by HaloFour** [comment] 2018-09-01 01:53
@chrisrollins 

> The problem I found is that delegates don't seem to be compatible with methods. You can pass lambda expressions but if you want to pass a method you are out of luck.

What do you mean by this?  Delegates can certainly be pointed to methods as long as the signatures match.  `Func<...>` and `Action<...>` are just standard delegates.

Can you post a short repro?

**Comment by chrisrollins** [comment] 2018-09-01 02:00
@HaloFour Looks like you're right. The culprit is an implicit operator which I'm using to convert tuples to structs. It seems that the implicit operator cannot take a tuple with a method if the type it's looking for in the tuple is a delegate, but it works if I use a Func or Action type instead.

**Comment by pongba** [comment] 2018-11-03 20:04
I have to say that I'm truly surprised (to say the least) by the fact that typedef equivalence is still not supported in C# in 2018(!). 

Not long ago I had the need to rename an existing type to a new name without breaking client code on binary & source-code level, and coming from a C++ background, I naturally searched for ways to do that in C#, and what I found out instead is an utterly utterly broken "using alias" that nobody actually uses (pardon the pun) and everybody complains about (I don't even bother to paste the links it's everywhere).

The current status of C# "using alias" suffers from two major issues:

1. composability
2. scope

that basically rendered it unusable for serious purpose.

And don't start suggesting inheritence... It's semantically evil to peg everything square into the OO round hole. (I don't dislike OO BTW)

And I don't really know what the debate is about and why the delay, it's not some rocket science langauge feature, it exists in so many mature and modern language, and proven to be useful in so many scenarios. C++ even has a using that supports tempates. Why oh why..

**Comment by theunrepentantgeek** [comment] 2018-11-03 20:37
@pongba For a start, convention based libraries would still fail

For example, a seralization library might expect there to be supporting classes with the suffixes `Reader` and `Writer` to support the serialization of a class:

``` csharp
public class Customer { ... }
public class CustomerReader { ... }
public class CustomerWriter { ... }
```

A user of that library would expect to be able to write this

``` csharp
public typedef Vendor : Customer
public class VendorReader { ... }
public class VendorWriter { ... }
```

But, those classes wouldn't be used. In fact, if the classes `CustomerReader` and `CustomerWriter` already existed elsewhere, they'd be used instead, with very surprising results.

Even a simple **typedef** where you're just defining a different name for an existing type runs into difficulties like this very quickly. 

I think the key here is a fundamental difference between C++ and C#. In my (admittedly limited) understanding of C++, type names are largely or entirely elided from the compiled binary, having little or not use at runtime. This contrasts with C# where the name of a type is a fundamental thing that's used heavily at runtime for type identification, loading, and so on.

**Comment by pongba** [comment] 2018-11-03 21:00
@theunrepentantgeek Thanks! That cleared things up quite a bit! :)

**Comment by VBAndCs** [comment] 2020-03-25 13:56
This will be more powerful if also allows generic aliases #3309.

**Comment by svdHero** [comment] 2023-01-13 09:38
Any update on this?

This is a crucial feature when it come to Domain Driven Design and modelling a domain. It's so easy in F# to assign domain specific aliases to existing types.
In C#, however, it is a pain, because one has to build wrapper types which (from a domain point of view) just don't make sense. Since we have to name both the wrapper and the wrappee, we end up with having two named things in code while only one of them exists in the business domain.
That is awful domain modelling whose sole reason is a technical one, namely the lack of proper global type aliases in C#.

And no, the `using` directive does not solve the problem, because our domain model is used by multiple assemblies and the ubiquitous language should be used in the whole codebase.

This feature proposal should really be pushed by anyone who is serious about DDD.

**Comment by orosbogdan** [comment] 2024-04-14 21:22
Any ypdates on this, it'd would help with strongly typed ids a lot.

**Comment by CyrusNajmabadi** [comment] 2024-04-14 23:09
@orosbogdan Explicit extensions seems to subsume these use cases.

**Comment by KennethHoff** [comment] 2024-04-15 05:14
> @orosbogdan Explicit extensions seems to subsume these use cases.  

Last time implementation strategy (lowering) were mentioned it was stated that you couldn't overload on extensions; has that changed since then to allow them to?

**Comment by CyrusNajmabadi** [comment] 2024-04-15 05:35
Whatever strategy we'd go with would likely be the same as what we'd do for any strongly-typed-id scenario.  :)

**Comment by KennethHoff** [comment] 2024-04-15 05:40
> Whatever strategy we'd go with would likely be the same as what we'd do for any strongly-typed-id scenario.  :)

.. fair enough 😅

**Comment by 333fred** [comment] 2024-12-03 22:02
Closing as a duplicate of https://github.com/dotnet/csharplang/issues/1239.

**Closed by 333fred** 2024-12-03 22:02 UTC
Labels: Discussion, Feature Request
