### ISSUE TITLE
Proposal: Type parameter inference by where constraint

### ISSUE THREAD

**Issue by HexJacaranda** [dotnet/csharplang#3271] opened 2020-03-17 07:27 UTC
Sometimes where constraint can infer the type parameter like this：
```
interface I<T>{}
class Some : I<string>{}
class Inference<T, TKey> where T : I<TKey>
```
if I put **Some** to Inference<>，then the **TKey** can be inferred to **System.String**. Therefore, we don't need to fill the second parameter because **Inference&lt;Some&gt;** is **Inference&lt;Some,string&gt;**.

**Comment by Richiban** [comment] 2020-03-17 14:58
@HexJacaranda There's already an issue https://github.com/dotnet/csharplang/issues/1349 that champions partial type inference. I'm not sure if it it covers your scenario or not so it might be worth dropping over there and mentioning this.

**Comment by HexJacaranda** [comment] 2020-03-18 01:16
@Richiban  Issue #1349 mainly discusses the partial type inference when calling generic method. This one requires inference when I directly use the type to do something like declaring a local variable or whatever. What's more, if this feature/syntax can be implemented, some compile-time type operations will be possible because inferred type can be used within the whole class rather than a single method.

There is some suggestions on the form:
1. Necessary types always go first.
2. Types that can be inferred potientially must be placed after necessary types.

So the form will be like this:
```
class Some<NecessaryT, ... ,Infer> where //some constraint that can be use to infer type
```
When it's used, all the types to infer can be omitted, no comma, no placeholder is needed.

```
var some = new Some<Necessary0,Necessary1, ... ,NecessaryN>();
```
A more general policy can be used here (Named type argument: issue #1349) but is not so natural and neat in this scenario.

**Comment by YairHalberstadt** [comment] 2020-11-23 12:00
Closing as duplicate of https://github.com/dotnet/csharplang/discussions/741

**Closed by YairHalberstadt** 2020-11-23 12:00 UTC
