### ISSUE TITLE
Proposal: Allow return statement in null-coalescing operator

### ISSUE THREAD

**Issue by thargol1** [dotnet/csharplang#1841] opened 2018-09-07 10:11 UTC
# Allow return statement in null-coalescing operator

Currently the null-coalescing operator allows either a new value on the right side of the operator or a throw statement.

For example:
```csharp
string x = y ?? "";
string name = parameter ?? throw new ArgumentNullException("parameter");
```

In some cases it's preferable to return default values instead of exceptions.

```csharp
string name = parameter ?? return "";
```

Some real code from one of my projects:
``` csharp
public static BeheerRecht GetRecht_UnCached(int idFormulier, string username)
{
	if (idFormulier == 0 || string.IsNullOrEmpty(username)) return new BeheerRecht();
	var cache = new AccountCache();
	var account = cache.GetByUsername(username);
	if (account == null) return new BeheerRecht { Pcn = username };
	var userkey = DBUser.GetUserKey(username, account);
	if (userkey == null) return new BeheerRecht { Pcn = username };
	var con = DAL.OpenFormBouwerConnection();
	var user = DBUser.ReadByKey(con, userkey);
	if (user == null) return new BeheerRecht(account);
	if (user.IsAdmin) return new BeheerRecht(account, isAdmin:true);
	var recht = DBFormulierUserRecht.ByIdFormulierEnIdUser(con, idFormulier, user.IdUser).FirstOrDefault();
	if (recht == null) return new BeheerRecht(account);
	return new BeheerRecht(recht, cache, user);
}
```

If the return statement would be allowed in the null-coalescing operator this code could be shortened to:

``` csharp
public static BeheerRecht GetRecht_UnCached(int idFormulier, string username)
{
	if (idFormulier == 0 || string.IsNullOrEmpty(username)) return new BeheerRecht();
	var cache = new AccountCache();
	var account = cache.GetByUsername(username) ?? return new BeheerRecht { Pcn = username };
	var userkey = DBUser.GetUserKey(username, account) ?? return new BeheerRecht { Pcn = username };
	var con = DAL.OpenFormBouwerConnection();
	var user = DBUser.ReadByKey(con, userkey) ?? return new BeheerRecht(account);
	if (user.IsAdmin) return new BeheerRecht(account, isAdmin:true);
	var recht = DBFormulierUserRecht.ByIdFormulierEnIdUser(con, idFormulier, user.IdUser).FirstOrDefault() ?? return new BeheerRecht(account);
	return new BeheerRecht(recht, cache, user);
}
```

**Comment by DavidArno** [comment] 2018-09-07 12:01
This is a duplicate of #176

**Comment by thargol1** [comment] 2018-09-07 12:11
You're right, my proposal is subset of #176. Did not find it because I searched for 'coalesce' in the issues.

**Comment by DavidArno** [comment] 2018-09-07 12:29
Github's search abilities aren't that great. And having prior knowledge of existing issues helps too! 😄  

I found it by going to google and searching for `site:github.com/dotnet/csharplang ternary return`  (because I knew it had been discussed previously with regard to the ternary operator).

Would you mind closing this issue therefore as it's already covered?

**Closed** 2018-09-07 13:26 UTC
