### ISSUE TITLE
Nullable reassignment Syntax sugar

### ISSUE THREAD

**Issue by kfird214** [dotnet/csharplang#2072] opened 2018-12-13 21:06 UTC
It will be nice to have a syntax for assign a nullable variable only when it null

now it can be like that
```C#
int OptionalSumTen(int num1, int? num2 = null) {
  num2 = num2 == null ? 10 : num;
  return num1 + num2;
}
```
the new syntax can look like this:
```C#
int OptionalSumTen(int num1, int? num2 = null) {
  num2 ?= 10;
  return num1 + num2;
}
```
or as optional parameter
the new syntax can look like this:
```C#
int OptionalSumTen(int num1, int? num2 ?= 10) {
  return num1 + num2;
}
```

kind of weird example but you get the idea

Thanks

**Comment by cpplearner** [comment] 2018-12-13 21:31
Duplicate of #34.

**Comment by YairHalberstadt** [comment] 2018-12-13 21:57
And even today, you could write this far more simply as 
```csharp
num2 = num2 ?? 10;
```

**Comment by ufcpp** [comment] 2018-12-13 22:43
VS 2019 Preview 1 has already implemented the null-coalescing assignment:

```cs
num2 ??= 10;
```

**Comment by DavidArno** [comment] 2018-12-14 08:56
Whilst `??=` will be supported in C# 8, the OP's example neatly highlights why folk should think twice before using it. Rather than mangling parameters as their examples do, it could already have just been written as:
```cs
int OptionalSumTen(int num1, int? num2 = null) => num1 + num2 ?? 10;
```

Whilst such "operator assignments" (not sure if they have a proper name) can be useful very occasionally, they all too often are a sign of poorly thought out code in my view.

**Comment by CyrusNajmabadi** [comment] 2018-12-14 09:10
> Whilst such "operator assignments" (not sure if they have a proper name) can be useful very occasionally, 

I found about 8500 usages of them in roslyn alone :)  

> they all too often are a sign of poorly thought out code in my experience.

Your experience seems pretty far off of the norm.  The idea of having a value that accumulates data, which you read, update, write, is super common in programming, especially in the realm of languages that C# participates in.

**Comment by dsaf** [comment] 2018-12-14 09:42
> I guess i don't get the point. Roslyn is a real world example...

But can you explain to someone completely unfamiliar with the project why would you want bare ```null```s to "travel" farther than some impure integration points like input/transport?

**Comment by DavidArno** [comment] 2018-12-14 10:03
> I guess i don't get the point. Roslyn is a real world example

To my mind, Roslyn is never a good real world example to use. We all demand a lot of it: we want it to be super fast and to have very low resource impact at the same time. Therefore there is a demand on the developers that they maximise efficiency, optimising the code to within an inch of its life. "Good practice" is often a necessary casualty of such code basis. 

Of course, the folk working on Roslyn are all very clever developers and they definitely achieve that efficiency without creating an unreadable mess as others might do with such a code base. But I'd still not consider it a good choice for real world examples of C# good practice without careful thought first.

**Comment by CyrusNajmabadi** [comment] 2018-12-14 20:23
> But can you explain to someone completely unfamiliar with the project why would you want bare nulls to "travel" farther than some impure integration points like input/transport?

Because nulls are still useful, and being able to compose over them with an operator, just as compose over other values with operators happens as well.

> To my mind, Roslyn is never a good real world example to use. We all demand a lot of it: we want it to be super fast and to have very low resource impact at the same time. Therefore there is a demand on the developers that they maximise efficiency, optimising the code to within an inch of its life. "Good practice" is often a necessary casualty of such code basis.

There are large swaths of roslyn not under these sorts of constraints.  Much of Roslyn is about having a clean and maintainable design that can be adapted on demand to the needs of customers and the market.

>  But I'd still not consider it a good choice for real world examples of C# good practice without careful thought first.

I literally see nothing wrong with "operator assignments".  They're a staple of tons of languages and are a concise and reasonable way to express a unbelievably common pattern.  I would say the onus is on you to provide a reasonable argument for why they're as bad as you're making them out to be.  Because, from real-world use cases, they appear to be totally fine and not at all a problem.

**Comment by YairHalberstadt** [comment] 2020-10-20 11:39
Closing as implemented in C# 8 with `??=` used as the syntac

**Closed by YairHalberstadt** 2020-10-20 11:39 UTC
