### ISSUE TITLE
Allow adding setters to overridden virtual getters

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/csharplang#3130] opened 2020-01-29 06:47 UTC
Sorry if this isn't the right way to word this, its a bit hard to explain but I run into it a lot.

In an interface, you can specify that you want a property with a getter, like so. 

```
public interface IC {
    int Thing {get;}
}
```

This generates the following IL signatures in the interface.

```
    // Methods
    .method public hidebysig specialname newslot abstract virtual 
        instance int32 get_Thing () cil managed 
    {
    } // end of method IC::get_Thing

    // Properties
    .property instance int32 Thing()
    {
        .get instance int32 IC::get_Thing()
    }
```

I can make a abstract getter in an abstract class as well.

```
public abstract class C {
    public abstract int Thing {get;}
}
```

Which generates the following IL

```
    // Methods
    .method public hidebysig specialname newslot abstract virtual 
        instance int32 get_Thing () cil managed 
    {
    } // end of method C::get_Thing

    // Properties
    .property instance int32 Thing()
    {
        .get instance int32 C::get_Thing()
    }
```

Notice how the generated IL is 100% identical. 

If I were to implement the interface, I could implement the getter, and add a setter. This works fine.

```
public class D : IC {
    public int Thing {get; set;}
}
```

However, I cannot implement the getter and add a setter from the abstract class, even though I'm overriding the same base signature.

```
public class D : C {
    public override int Thing {get; set;}
}
error CS0546: 'D.Thing.set': cannot override because 'C.Thing' does not have an overridable set accessor
```

I can do this from IL with no problem, and I've ran into this countless times over the years.

Doing this seems to be trivially possible and allowed at the IL level through all the testing I have done.

There are a few ways this could be done I think, I'm going to propose the easiest.

On the new property, allow `new` to be added to the definition.

```
public override int Thing {get; new set;}
```

If you want it to be virtual, use `new virtual`

```
public override int Thing {get; new virtual set;}
```

I'm sure there are a few other ways to do this as well, but this was an easy one using existing keywords that wouldn't break existing code that I could come up with.

This issue would affect setter only properties as well, its just that getter only is much more common.

This would work identically on non auto properties as well, and would work the same way.

**Comment by ber-sma** [comment] 2020-01-29 10:39
Yes please. I would prefer this to work without adding any keywords. The compiler could figure out that only 'get' is overridable and therefore generate a non-overriding setter as well.

Is there a use-case for an overridden, virtual getter with a non-virtual setter? I think the new setter should be virtual as well (as long as the property is not sealed, in which case the new setter would neither be overriding nor virtual).

**Comment by quinmars** [comment] 2020-01-29 11:16
This was already discussed in #1568 and #2288.

**Comment by YairHalberstadt** [comment] 2020-11-17 12:17
Closing as duplicate of https://github.com/dotnet/csharplang/issues/1568

**Closed by YairHalberstadt** 2020-11-17 12:17 UTC
