### ISSUE TITLE
[Proposal]: Emojis in internal/private Variable, member, and method names.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/csharplang#4402] opened 2021-02-08 21:05 UTC
# Unicode based Emojis in variable and method names.

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

People long for a feature in programming: the use of unicode based characters, like emojis since they are always custom and unique. Example emojis include the [sob](https://emojipedia.org/loudly-crying-face/) emoji and others. I would like all of the emojis currently supported by unicode (which was then become part of some emoji version stuff).

## Motivation
[motivation]: #motivation

Well users currently get to choose their variable or method names, however there are limitations to this, for starters c# code files use UTF-8 BOM by default which supports using emojis in the files, yet the language would not compile the code if emojis was used for variable names, method names, etc of private or internal symbols (as long as they use english based method names for their public api).

This would allow programmers to not only write working and great code, but also have fun too by being able to use emojis for local variables, in using blocks or statements, etc that does not get exposed to public api.

The expected outcome is code like below:
![image](https://user-images.githubusercontent.com/15173749/107277328-35dc6280-6a22-11eb-9702-32539c9fc758.png)
Except that it would be able to compile.

## Detailed design
[design]: #detailed-design

```cs
public class Example
{
    // example internal method with emojis.
    internal void EmojiTime😂😂😂😂()
    {
        // example local variable with emojis.
        var 😂😂😂 = string.Empty;
        // use it later.
    }

    // example private method using emojis.
    private void AnotherEmoji😂😂😂😂😂()
    {
        // example using block using emojis.
        using (var 😂😂😂😂 = new MemoryStream()
        {
            // do stuff to the stream.
        }

        // example using statement using emojis.
        using var 😂😂😂 = new MemoryStream();
        // do stuff to the stream.
    }

    // example internal property using emojis.
    internal byte[] 😂😂😂😂😂😂 { get; set; }

    // example private property using emojis.
    private byte[] 😂😂 { get; set; }

    // anything else that can make internal or private variables or members of any
    // type using emojis that I have not thought of above.
}
```

The entire variable [spec](https://github.com/dotnet/csharplang/blob/master/spec/variables.md), class [spec](https://github.com/dotnet/csharplang/blob/master/spec/classes.md) (people would probably want to use emojis for class names too on internal/private only classes), enum [spec](https://github.com/dotnet/csharplang/blob/master/spec/enums.md) (for internal or private enumeration members), struct [spec](https://github.com/dotnet/csharplang/blob/master/spec/structs.md) (for internal/private structures) for variables(or class/enum/struct members) as this very well could apply to the whole thing. However I would like emojis only usable on non-public members (internal or private) to avoid issues with users who cannot type emojis.

## Drawbacks
[drawbacks]: #drawbacks

I do not see any drawbacks with allowing usage of emojis in variable, member, or method names as long as they are not allowed to be an public member name for fear of someone unable to type the emojis from having issues.

## Alternatives
[alternatives]: #alternatives

I have not considered any other ones that would allow using emojis for variable names, member, or method names.

I think the impact of not doing this is limited to the people who want to use emojis for variable, member, and method names of internal symbols.

## Unresolved questions
[unresolved]: #unresolved-questions

None so far, this is a new proposal.

## Design meetings

None so far, this is a new proposal.

**Comment by AraHaan** [comment] 2021-02-08 21:12
cc @CyrusNajmabadi

**Comment by 333fred** [comment] 2021-02-08 21:14
Duplicate of https://github.com/dotnet/csharplang/discussions/3490.

**Closed by 333fred** 2021-02-08 21:14 UTC
