### ISSUE TITLE
Nullable struct inference in the conditional operator 

### ISSUE THREAD

**Issue by savahmel** [dotnet/csharplang#1073] opened 2017-11-03 08:21 UTC
The following code fails to compile 

`static int? GetLength(string[] args)
{
      return (args == null) ? null : args.Length;
}`

the following passes

`static int? GetLength(string[] args)
{
       return args?.Length;
}`

wouldn't it be safe to infer nullability in the first more general case?

**Comment by MkazemAkhgary** [comment] 2017-11-03 08:27
this will compile too

    static int? GetLength(string[] args) { return (args == null) ? default(int?) : args.Length; }

operands of ternary operator `:` must be implicitly assignable. `null` and `int` are not assignable together, but `int?` and `int` are.

**Comment by Joe4evr** [comment] 2017-11-03 09:33
This is something that will [get improved in the near future](https://github.com/dotnet/csharplang/blob/master/proposals/nullable-enhanced-common-type.md).

**Comment by svick** [comment] 2017-11-03 17:08
And since the proposal mentioned by @Joe4evr has its own issue at https://github.com/dotnet/csharplang/issues/33, I think this issue should be closed as a duplicate of that one.

**Comment by jcouv** [comment] 2017-11-05 22:40
This is indeed a duplicate and is a candidate for 8.0 (fits well with other nullability work there).
I'll go ahead and close. Thanks

**Closed by jcouv** 2017-11-05 22:40 UTC
